{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdldocument\/administrativenumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdldocument\/administrativenumber"]}],"sections":[],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"MdlHolder"}],"externalID":"c:@M@MdlHolder@objc(cs)XTMdlDocument(py)administrativeNumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"administrativeNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"administrativeNumber","navigatorTitle":[{"kind":"identifier","text":"administrativeNumber"}]},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"administrativeNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/administrativeNumber","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"An audit control number assignet by the issuing authority."}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"kind":"symbol","role":"collection","url":"\/documentation\/mdlholder","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/administrativeNumber":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"administrativeNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"administrativeNumber","navigatorTitle":[{"kind":"identifier","text":"administrativeNumber"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/administrativeNumber","abstract":[{"type":"text","text":"An audit control number assignet by the issuing authority."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdldocument\/administrativenumber","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument":{"url":"\/documentation\/mdlholder\/mdldocument","abstract":[{"type":"text","text":"Representation of mDL document"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"title":"MdlDocument","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"administrativeNumber","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"administrativeNumber"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"administrativeNumber"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"administrativeNumber","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1administrativeNumber\/title"},{"op":"replace","value":[{"kind":"identifier","text":"administrativeNumber"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1administrativeNumber\/fragments"},{"op":"replace","value":"XTMdlDocument","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}