{"abstract":[{"type":"text","text":"Age attestation: Nearest “true” attestation above request."}],"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/ageOverNn","interfaceLanguage":"swift"},"metadata":{"title":"ageOverNn","navigatorTitle":[{"kind":"identifier","text":"ageOverNn"}],"modules":[{"name":"MdlHolder"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ageOverNn","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AgeOverNnEntry","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTAgeOverNnEntry"},{"text":"]?","kind":"text"}],"externalID":"c:@M@MdlHolder@objc(cs)XTMdlDocument(py)ageOverNn","roleHeading":"Instance Property","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ageOverNn","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AgeOverNnEntry","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTAgeOverNnEntry"},{"text":"]?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mdlholder\/mdldocument\/ageovernn"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdldocument\/ageovernn"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument"]]},"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/AgeOverNnEntry":{"type":"topic","title":"AgeOverNnEntry","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgeOverNnEntry","kind":"identifier"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"AgeOverNnEntry","kind":"identifier"}],"url":"\/documentation\/mdlholder\/ageovernnentry","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument":{"title":"MdlDocument","abstract":[{"type":"text","text":"Representation of mDL document"}],"url":"\/documentation\/mdlholder\/mdldocument","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","role":"symbol","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/ageOverNn":{"abstract":[{"type":"text","text":"Age attestation: Nearest “true” attestation above request."}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/ageOverNn","title":"ageOverNn","role":"symbol","navigatorTitle":[{"text":"ageOverNn","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ageOverNn","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTAgeOverNnEntry","text":"AgeOverNnEntry","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"url":"\/documentation\/mdlholder\/mdldocument\/ageovernn","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"ageOverNn","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ageOverNn"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<XTAgeOverNnEntry *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"ageOverNn"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/title","value":"XTAgeOverNnEntry","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/fragments","value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/navigatorTitle","value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/title","value":"XTMdlDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/fragments","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/navigatorTitle","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1ageOverNn\/title","value":"ageOverNn"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1ageOverNn\/fragments","value":[{"text":"ageOverNn","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}