{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/biometricTemplateXx"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdldocument\/biometrictemplatexx"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdldocument\/biometrictemplatexx"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"biometricTemplateXx","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlBiometricTemplate","text":"MdlBiometricTemplate","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate"},{"text":"]?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","externalID":"c:@M@MdlHolder@objc(cs)XTMdlDocument(py)biometricTemplateXx","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"MdlHolder"}],"title":"biometricTemplateXx","navigatorTitle":[{"text":"biometricTemplateXx","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlBiometricTemplate","text":"MdlBiometricTemplate"},{"kind":"text","text":"]?"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/biometricTemplateXx":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/biometricTemplateXx","title":"biometricTemplateXx","abstract":[],"role":"symbol","url":"\/documentation\/mdlholder\/mdldocument\/biometrictemplatexx","kind":"symbol","navigatorTitle":[{"text":"biometricTemplateXx","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"biometricTemplateXx","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MdlBiometricTemplate","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlBiometricTemplate","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlBiometricTemplate":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate","title":"MdlBiometricTemplate","abstract":[],"role":"symbol","url":"\/documentation\/mdlholder\/mdlbiometrictemplate","kind":"symbol","navigatorTitle":[{"text":"MdlBiometricTemplate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlBiometricTemplate"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","title":"MdlDocument","abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","url":"\/documentation\/mdlholder\/mdldocument","kind":"symbol","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MdlDocument","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"biometricTemplateXx"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"biometricTemplateXx","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<XTMdlBiometricTemplate *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"biometricTemplateXx","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1biometricTemplateXx\/title","value":"biometricTemplateXx","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1biometricTemplateXx\/fragments","value":[{"text":"biometricTemplateXx","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate\/title","value":"XTMdlBiometricTemplate","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate\/fragments","value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate\/navigatorTitle","value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/title","value":"XTMdlDocument","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/fragments","value":[{"text":"XTMdlDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/navigatorTitle","value":[{"text":"XTMdlDocument","kind":"identifier"}],"op":"replace"}]}]}