{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiryDate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument"]]},"variants":[{"paths":["\/documentation\/mdlholder\/mdldocument\/expirydate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdldocument\/expirydate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"navigatorTitle":[{"kind":"identifier","text":"expiryDate"}],"title":"expiryDate","modules":[{"name":"MdlHolder"}],"symbolKind":"property","externalID":"c:@M@MdlHolder@objc(cs)XTMdlDocument(py)expiryDate","role":"symbol","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/expiryDate","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Date when mDL expires."}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/expiryDate":{"url":"\/documentation\/mdlholder\/mdldocument\/expirydate","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"expiryDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/expiryDate","navigatorTitle":[{"text":"expiryDate","kind":"identifier"}],"title":"expiryDate","abstract":[{"type":"text","text":"Date when mDL expires."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","title":"MdlHolder","type":"topic","url":"\/documentation\/mdlholder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","type":"topic","url":"\/documentation\/mdlholder\/mdldocument","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"title":"MdlDocument","abstract":[{"type":"text","text":"Representation of mDL document"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"expiryDate","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"expiryDate"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"text":" * ","kind":"text"},{"text":"expiryDate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"expiryDate","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1expiryDate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1expiryDate\/fragments","value":[{"text":"expiryDate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/title","value":"XTMdlDocument","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}