{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenNameNationalCharacter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument"]]},"variants":[{"paths":["\/documentation\/mdlholder\/mdldocument\/givennamenationalcharacter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdldocument\/givennamenationalcharacter"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"givenNameNationalCharacter","navigatorTitle":[{"kind":"identifier","text":"givenNameNationalCharacter"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"givenNameNationalCharacter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"externalID":"c:@M@MdlHolder@objc(cs)XTMdlDocument(py)givenNameNationalCharacter","modules":[{"name":"MdlHolder"}],"symbolKind":"property","role":"symbol"},"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/givenNameNationalCharacter","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The given name of the mDL holder using full UTF-8 character set."}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","title":"MdlHolder","type":"topic","url":"\/documentation\/mdlholder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","type":"topic","url":"\/documentation\/mdlholder\/mdldocument","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"title":"MdlDocument","abstract":[{"type":"text","text":"Representation of mDL document"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/givenNameNationalCharacter":{"url":"\/documentation\/mdlholder\/mdldocument\/givennamenationalcharacter","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenNameNationalCharacter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/givenNameNationalCharacter","navigatorTitle":[{"kind":"identifier","text":"givenNameNationalCharacter"}],"title":"givenNameNationalCharacter","abstract":[{"type":"text","text":"The given name of the mDL holder using full UTF-8 character set."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"givenNameNationalCharacter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"givenNameNationalCharacter"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"givenNameNationalCharacter"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/title","value":"XTMdlDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/fragments","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1givenNameNationalCharacter\/title","value":"givenNameNationalCharacter"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1givenNameNationalCharacter\/fragments","value":[{"kind":"identifier","text":"givenNameNationalCharacter"}]}]}]}