{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"familyName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"givenName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"birthDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issueDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingCountry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingAuthority"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"portrait"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingPrivileges"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivileges","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges","kind":"typeIdentifier","text":"MdlDrivingPrivileges"},{"kind":"text","text":", "},{"kind":"externalParam","text":"unDistinguishingSign"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"holderIdNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bloodGroup"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlIssueDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlExpiryDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingRestrictions"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"administrativeNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@E@XTMdlGender","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender","kind":"typeIdentifier","text":"MdlGender"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"eyeColour"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"hairColour"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"birthPlace"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"residentAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"portraitCaptureDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"ageInYears"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"ageBirthYear"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"ageOverNn"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTAgeOverNnEntry","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry","kind":"typeIdentifier","text":"AgeOverNnEntry"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"issuingJurisdiction"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"nationality"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"residentCity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"residentState","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"residentPostalCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"residentCountry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlBiometricTemplate","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate","kind":"typeIdentifier","text":"MdlBiometricTemplate"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"familyNameNationalCharacter"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"givenNameNationalCharacter"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureUsualMark"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdldocument\/init(familyname:givenname:birthdate:issuedate:expirydate:issuingcountry:issuingauthority:documentnumber:portrait:drivingprivileges:undistinguishingsign:holderidnumber:bloodgroup:dlissuedate:dlexpirydate:drivingrestrictions:administrativenum-1g6bl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdldocument\/init(familyname:givenname:birthdate:issuedate:expirydate:issuingcountry:issuingauthority:documentnumber:portrait:drivingprivileges:undistinguishingsign:holderidnumber:bloodgroup:dlissuedate:dlexpirydate:drivingrestrictions:administrativenum-1g6bl"]}],"metadata":{"role":"symbol","title":"init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"MdlHolder"}],"externalID":"c:@M@MdlHolder@objc(cs)XTMdlDocument(im)initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","navigatorTitle":[{"text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"familyName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"givenName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"birthDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"text":", ","kind":"text"},{"text":"issueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issuingCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issuingAuthority","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"portrait","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"drivingPrivileges","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlDrivingPrivileges","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivileges","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"unDistinguishingSign","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"holderIdNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bloodGroup","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"dlIssueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"dlExpiryDate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingRestrictions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"administrativeNumber"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"sex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlGender","preciseIdentifier":"c:@M@MdlHolder@E@XTMdlGender","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"height","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"weight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eyeColour"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"hairColour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"birthPlace","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"residentAddress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"portraitCaptureDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"ageInYears","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"ageBirthYear","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"ageOverNn","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AgeOverNnEntry","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTAgeOverNnEntry"},{"text":"]?, ","kind":"text"},{"text":"issuingJurisdiction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"nationality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"residentCity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"residentState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"residentPostalCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"residentCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"biometricTemplateXx","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MdlBiometricTemplate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlBiometricTemplate"},{"text":"]?, ","kind":"text"},{"text":"familyNameNationalCharacter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"givenNameNationalCharacter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"signatureUsualMark","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?)","kind":"text"}]},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlBiometricTemplate":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate","title":"MdlBiometricTemplate","abstract":[],"role":"symbol","url":"\/documentation\/mdlholder\/mdlbiometrictemplate","kind":"symbol","navigatorTitle":[{"text":"MdlBiometricTemplate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlBiometricTemplate"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/AgeOverNnEntry":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgeOverNnEntry"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholder\/ageovernnentry","title":"AgeOverNnEntry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AgeOverNnEntry"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry","abstract":[]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","title":"init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","abstract":[],"role":"symbol","url":"\/documentation\/mdlholder\/mdldocument\/init(familyname:givenname:birthdate:issuedate:expirydate:issuingcountry:issuingauthority:documentnumber:portrait:drivingprivileges:undistinguishingsign:holderidnumber:bloodgroup:dlissuedate:dlexpirydate:drivingrestrictions:administrativenum-1g6bl","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"familyName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"givenName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"birthDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"issuingCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"issuingAuthority","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"portrait"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingPrivileges"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivileges","kind":"typeIdentifier","text":"MdlDrivingPrivileges"},{"kind":"text","text":", "},{"kind":"externalParam","text":"unDistinguishingSign"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"holderIdNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bloodGroup"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlIssueDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlExpiryDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingRestrictions"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"administrativeNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@E@XTMdlGender","kind":"typeIdentifier","text":"MdlGender"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eyeColour"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hairColour"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"birthPlace"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentAddress"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"portraitCaptureDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageInYears"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageBirthYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageOverNn"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgeOverNnEntry","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTAgeOverNnEntry"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"issuingJurisdiction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nationality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentCity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"residentPostalCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"residentCountry"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlBiometricTemplate","kind":"typeIdentifier","text":"MdlBiometricTemplate"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"familyNameNationalCharacter"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"givenNameNationalCharacter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureUsualMark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","title":"MdlDocument","abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","url":"\/documentation\/mdlholder\/mdldocument","kind":"symbol","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MdlDocument","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivileges":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges","abstract":[{"type":"text","text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL)."}],"title":"MdlDrivingPrivileges","role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdldrivingprivileges","navigatorTitle":[{"text":"MdlDrivingPrivileges","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivileges"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender","title":"MdlGender","abstract":[],"role":"symbol","url":"\/documentation\/mdlholder\/mdlgender","kind":"symbol","navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFamilyName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"familyName"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"givenName"},{"text":" ","kind":"text"},{"kind":"identifier","text":"birthDate:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"birthDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"issueDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiryDate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier","text":"NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"expiryDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingCountry:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"issuingCountry"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingAuthority:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"issuingAuthority"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentNumber"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"portrait"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingPrivileges:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivileges","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges","text":"XTMdlDrivingPrivileges"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"drivingPrivileges"},{"kind":"text","text":" "},{"kind":"identifier","text":"unDistinguishingSign:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"unDistinguishingSign"},{"text":" ","kind":"text"},{"kind":"identifier","text":"holderIdNumber:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"holderIdNumber","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"bloodGroup:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bloodGroup"},{"kind":"text","text":" "},{"kind":"identifier","text":"dlIssueDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dlIssueDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"dlExpiryDate:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dlExpiryDate"},{"text":" ","kind":"text"},{"text":"drivingRestrictions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"drivingRestrictions","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"administrativeNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"administrativeNumber"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@E@XTMdlGender","text":"XTMdlGender","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sex"},{"kind":"text","text":" "},{"kind":"identifier","text":"height:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"height"},{"kind":"text","text":" "},{"kind":"identifier","text":"weight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"weight"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeColour:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"eyeColour","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"hairColour:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"hairColour","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"birthPlace:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"birthPlace","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"residentAddress:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"residentAddress","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"portraitCaptureDate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"},{"text":" *) ","kind":"text"},{"text":"portraitCaptureDate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ageInYears:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"text":"ageInYears","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ageBirthYear:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"ageBirthYear","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ageOverNn:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<XTAgeOverNnEntry *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"ageOverNn","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuingJurisdiction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"issuingJurisdiction","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"nationality:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nationality"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentCity:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"residentCity"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"residentState"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentPostalCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"residentPostalCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentCountry:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"residentCountry"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricTemplateXx:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<XTMdlBiometricTemplate *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"biometricTemplateXx"},{"kind":"text","text":" "},{"kind":"identifier","text":"familyNameNationalCharacter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"familyNameNationalCharacter"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenNameNationalCharacter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"givenNameNationalCharacter"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureUsualMark:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"signatureUsualMark"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate\/title","value":"XTMdlBiometricTemplate","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate\/fragments","value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate\/navigatorTitle","value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/title","value":"XTAgeOverNnEntry","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/fragments","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/navigatorTitle","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/title","value":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/title","value":"XTMdlDocument","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/fragments","value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges\/title","value":"XTMdlDrivingPrivileges","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/title","value":"XTMdlGender","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/fragments","value":[{"kind":"identifier","text":"XTMdlGender"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/navigatorTitle","op":"replace","value":[{"text":"XTMdlGender","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}