{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdldocument\/issuingauthority"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdldocument\/issuingauthority"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument"]]},"abstract":[{"text":"Issuing authority name.","type":"text"}],"sections":[],"metadata":{"role":"symbol","title":"issuingAuthority","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"MdlHolder"}],"externalID":"c:@M@MdlHolder@objc(cs)XTMdlDocument(py)issuingAuthority","navigatorTitle":[{"text":"issuingAuthority","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingAuthority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingAuthority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issuingAuthority"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/issuingAuthority":{"url":"\/documentation\/mdlholder\/mdldocument\/issuingauthority","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingAuthority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"text":"Issuing authority name.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"issuingAuthority"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issuingAuthority","role":"symbol","title":"issuingAuthority"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","title":"MdlDocument","abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","url":"\/documentation\/mdlholder\/mdldocument","kind":"symbol","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MdlDocument","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"issuingAuthority"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"issuingAuthority"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"issuingAuthority"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1issuingAuthority\/title","value":"issuingAuthority"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1issuingAuthority\/fragments","value":[{"kind":"identifier","text":"issuingAuthority"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/title","value":"XTMdlDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/fragments","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocument"}]}]}]}