{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentCity"},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"residentCity","kind":"identifier"}],"externalID":"c:@M@MdlHolder@objc(cs)XTMdlDocument(py)residentCity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentCity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property","role":"symbol","title":"residentCity","modules":[{"name":"MdlHolder"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentCity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/mdlholder\/mdldocument\/residentcity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdldocument\/residentcity"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The city where the mDL holder lives.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument"]]},"sections":[],"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/residentCity":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentCity","navigatorTitle":[{"text":"residentCity","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentCity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"residentCity","role":"symbol","abstract":[{"text":"The city where the mDL holder lives.","type":"text"}],"type":"topic","url":"\/documentation\/mdlholder\/mdldocument\/residentcity","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument":{"title":"MdlDocument","abstract":[{"type":"text","text":"Representation of mDL document"}],"url":"\/documentation\/mdlholder\/mdldocument","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","role":"symbol","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"residentCity"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"residentCity"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"residentCity","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1residentCity\/title","value":"residentCity"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1residentCity\/fragments","value":[{"kind":"identifier","text":"residentCity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/title","value":"XTMdlDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/fragments","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocument"}]}]}]}