{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTHolderErrorCode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HolderErrorCode","kind":"identifier"}]}]}],"topicSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleDenied","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleRestricted","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleUnauthorized","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleUnsupported","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/cryptographicError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/initializationError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/internalError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocExpired","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocLostOrStolen","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocNotFound","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocRequestError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocRevoked","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocValidationError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/networkError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/notInitialized","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/pinIsEmpty","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/pinIsWrong","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/requestNotFound","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/rootCaCertificateMissing","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/sessionDataError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/sessionNotFound","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/startSharingError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/success","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/unknown"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/Equatable-Implementations","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"abstract":[{"type":"text","text":"Possible error codes in SDK"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH","doc:\/\/com.xinfotech.mdlholder\/SY"],"type":"conformsTo","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode"},"metadata":{"navigatorTitle":[{"text":"HolderErrorCode","kind":"identifier"}],"title":"HolderErrorCode","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HolderErrorCode"}],"modules":[{"name":"MdlHolder"}],"externalID":"c:@M@MdlHolder@E@XTHolderErrorCode","roleHeading":"Enumeration","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder"]]},"sections":[],"variants":[{"paths":["\/documentation\/mdlholder\/holdererrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/holdererrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.xinfotech.mdlholder/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SH","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/networkError":{"title":"HolderErrorCode.networkError","kind":"symbol","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/networkerror","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/networkError","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkError","kind":"identifier"}],"navigatorTitle":[{"text":"XTHolderErrorCodeNetworkError","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/cryptographicError":{"title":"HolderErrorCode.cryptographicError","kind":"symbol","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/cryptographicerror","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/cryptographicError","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cryptographicError","kind":"identifier"}],"navigatorTitle":[{"text":"XTHolderErrorCodeCryptographicError","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/mDocLostOrStolen":{"title":"HolderErrorCode.mDocLostOrStolen","kind":"symbol","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/mdoclostorstolen","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocLostOrStolen","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocLostOrStolen"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeMDocLostOrStolen"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/mDocExpired":{"title":"HolderErrorCode.mDocExpired","kind":"symbol","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/mdocexpired","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocExpired","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mDocExpired"}],"navigatorTitle":[{"text":"XTHolderErrorCodeMDocExpired","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/mDocRevoked":{"title":"HolderErrorCode.mDocRevoked","kind":"symbol","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/mdocrevoked","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocRevoked","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocRevoked","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeMDocRevoked"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/startSharingError":{"title":"HolderErrorCode.startSharingError","kind":"symbol","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/startsharingerror","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/startSharingError","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSharingError"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeStartSharingError"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/bleUnsupported":{"kind":"symbol","title":"HolderErrorCode.bleUnsupported","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/bleunsupported","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleUnsupported","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleUnsupported"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeBleUnsupported"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/init(rawvalue:)","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/requestNotFound":{"kind":"symbol","title":"HolderErrorCode.requestNotFound","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/requestnotfound","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/requestNotFound","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestNotFound"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeRequestNotFound"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/success":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/success","navigatorTitle":[{"text":"XTHolderErrorCodeSuccess","kind":"identifier"}],"url":"\/documentation\/mdlholder\/holdererrorcode\/success","type":"topic","title":"HolderErrorCode.success","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/notInitialized":{"title":"HolderErrorCode.notInitialized","navigatorTitle":[{"text":"XTHolderErrorCodeNotInitialized","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mdlholder\/holdererrorcode\/notinitialized","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notInitialized","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/notInitialized"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/mDocError":{"kind":"symbol","title":"HolderErrorCode.mDocError","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/mdocerror","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocError","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocError"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeMDocError"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/mDocValidationError":{"kind":"symbol","title":"HolderErrorCode.mDocValidationError","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/mdocvalidationerror","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocValidationError","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocValidationError"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeMDocValidationError"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/bleDenied":{"kind":"symbol","title":"HolderErrorCode.bleDenied","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/bledenied","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleDenied","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleDenied"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeBleDenied"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/initializationError":{"kind":"symbol","title":"HolderErrorCode.initializationError","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/initializationerror","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/initializationError","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializationError"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeInitializationError"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/internalError":{"kind":"symbol","title":"HolderErrorCode.internalError","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/internalerror","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/internalError","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeInternalError"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/sessionDataError":{"kind":"symbol","title":"HolderErrorCode.sessionDataError","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/sessiondataerror","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/sessionDataError","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDataError"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeSessionDataError"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode","navigatorTitle":[{"text":"HolderErrorCode","kind":"identifier"}],"url":"\/documentation\/mdlholder\/holdererrorcode","type":"topic","title":"HolderErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HolderErrorCode","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"role":"symbol"},"doc://com.xinfotech.mdlholder/SY":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SY","title":"Swift.RawRepresentable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/mDocNotFound":{"title":"HolderErrorCode.mDocNotFound","kind":"symbol","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/mdocnotfound","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocNotFound","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mDocNotFound","kind":"identifier"}],"navigatorTitle":[{"text":"XTHolderErrorCodeMDocNotFound","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/bleUnauthorized":{"kind":"symbol","title":"HolderErrorCode.bleUnauthorized","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/bleunauthorized","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleUnauthorized","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleUnauthorized"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeBleUnauthorized"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/pinIsWrong":{"kind":"symbol","title":"HolderErrorCode.pinIsWrong","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/piniswrong","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/pinIsWrong","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinIsWrong"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodePinIsWrong"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/bleRestricted":{"kind":"symbol","title":"HolderErrorCode.bleRestricted","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/blerestricted","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleRestricted","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleRestricted"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeBleRestricted"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/equatable-implementations","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/Equatable-Implementations","role":"collectionGroup"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/pinIsEmpty":{"title":"HolderErrorCode.pinIsEmpty","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodePinIsEmpty"}],"role":"symbol","url":"\/documentation\/mdlholder\/holdererrorcode\/pinisempty","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinIsEmpty"}],"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/pinIsEmpty"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/mdlholder\/holdererrorcode\/rawrepresentable-implementations","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/RawRepresentable-Implementations"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/rootCaCertificateMissing":{"title":"HolderErrorCode.rootCaCertificateMissing","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeRootCaCertificateMissing"}],"role":"symbol","url":"\/documentation\/mdlholder\/holdererrorcode\/rootcacertificatemissing","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootCaCertificateMissing"}],"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/rootCaCertificateMissing"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/mDocRequestError":{"title":"HolderErrorCode.mDocRequestError","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeMDocRequestError"}],"role":"symbol","url":"\/documentation\/mdlholder\/holdererrorcode\/mdocrequesterror","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocRequestError"}],"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocRequestError"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/unknown":{"title":"HolderErrorCode.unknown","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeUnknown"}],"role":"symbol","url":"\/documentation\/mdlholder\/holdererrorcode\/unknown","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/unknown"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/sessionNotFound":{"title":"HolderErrorCode.sessionNotFound","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeSessionNotFound"}],"role":"symbol","url":"\/documentation\/mdlholder\/holdererrorcode\/sessionnotfound","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionNotFound"}],"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/sessionNotFound"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"XTHolderErrorCode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"XTHolderErrorCode","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"XTHolderErrorCode","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleDenied","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleRestricted","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleUnauthorized","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleUnsupported","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/cryptographicError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/initializationError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/internalError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocExpired","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocLostOrStolen","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocNotFound","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocRequestError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocRevoked","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocValidationError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/networkError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/notInitialized","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/pinIsEmpty","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/pinIsWrong","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/requestNotFound","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/rootCaCertificateMissing","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/sessionDataError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/sessionNotFound","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/startSharingError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/success","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/unknown"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XTHolderErrorCode","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1networkError\/title","op":"replace","value":"XTHolderErrorCodeNetworkError"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1networkError\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeNetworkError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1cryptographicError\/title","op":"replace","value":"XTHolderErrorCodeCryptographicError"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1cryptographicError\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeCryptographicError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocLostOrStolen\/title","op":"replace","value":"XTHolderErrorCodeMDocLostOrStolen"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocLostOrStolen\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeMDocLostOrStolen","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocExpired\/title","op":"replace","value":"XTHolderErrorCodeMDocExpired"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocExpired\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeMDocExpired","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocRevoked\/title","op":"replace","value":"XTHolderErrorCodeMDocRevoked"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocRevoked\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeMDocRevoked","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1startSharingError\/title","op":"replace","value":"XTHolderErrorCodeStartSharingError"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1startSharingError\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeStartSharingError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1bleUnsupported\/title","op":"replace","value":"XTHolderErrorCodeBleUnsupported"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1bleUnsupported\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeBleUnsupported","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1requestNotFound\/title","op":"replace","value":"XTHolderErrorCodeRequestNotFound"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1requestNotFound\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeRequestNotFound","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1success\/title","op":"replace","value":"XTHolderErrorCodeSuccess"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1success\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeSuccess","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1notInitialized\/title","op":"replace","value":"XTHolderErrorCodeNotInitialized"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1notInitialized\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeNotInitialized","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocError\/title","op":"replace","value":"XTHolderErrorCodeMDocError"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocError\/fragments","value":[{"text":"XTHolderErrorCodeMDocError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocValidationError\/title","value":"XTHolderErrorCodeMDocValidationError"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocValidationError\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCodeMDocValidationError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1bleDenied\/title","value":"XTHolderErrorCodeBleDenied"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1bleDenied\/fragments","value":[{"text":"XTHolderErrorCodeBleDenied","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1initializationError\/title","value":"XTHolderErrorCodeInitializationError"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1initializationError\/fragments","value":[{"text":"XTHolderErrorCodeInitializationError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1internalError\/title","value":"XTHolderErrorCodeInternalError"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1internalError\/fragments","value":[{"text":"XTHolderErrorCodeInternalError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1sessionDataError\/title","value":"XTHolderErrorCodeSessionDataError"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1sessionDataError\/fragments","value":[{"text":"XTHolderErrorCodeSessionDataError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/title","value":"XTHolderErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/fragments","value":[{"text":"XTHolderErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/navigatorTitle","value":[{"text":"XTHolderErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocNotFound\/title","value":"XTHolderErrorCodeMDocNotFound"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocNotFound\/fragments","value":[{"text":"XTHolderErrorCodeMDocNotFound","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1bleUnauthorized\/title","value":"XTHolderErrorCodeBleUnauthorized"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1bleUnauthorized\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCodeBleUnauthorized"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1pinIsWrong\/title","value":"XTHolderErrorCodePinIsWrong"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1pinIsWrong\/fragments","value":[{"text":"XTHolderErrorCodePinIsWrong","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1bleRestricted\/title","value":"XTHolderErrorCodeBleRestricted"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1bleRestricted\/fragments","value":[{"text":"XTHolderErrorCodeBleRestricted","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1pinIsEmpty\/title","value":"XTHolderErrorCodePinIsEmpty"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1pinIsEmpty\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCodePinIsEmpty"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1rootCaCertificateMissing\/title","value":"XTHolderErrorCodeRootCaCertificateMissing"},{"value":[{"text":"XTHolderErrorCodeRootCaCertificateMissing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1rootCaCertificateMissing\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocRequestError\/title","value":"XTHolderErrorCodeMDocRequestError"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocRequestError\/fragments","value":[{"text":"XTHolderErrorCodeMDocRequestError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1unknown\/title","op":"replace","value":"XTHolderErrorCodeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1unknown\/fragments","value":[{"text":"XTHolderErrorCodeUnknown","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1sessionNotFound\/title","value":"XTHolderErrorCodeSessionNotFound"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1sessionNotFound\/fragments","value":[{"text":"XTHolderErrorCodeSessionNotFound","kind":"identifier"}]}]}]}