{"topicSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField\/description","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField\/identifier","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField\/value"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdldocumentfield"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdldocumentfield"]}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(XTMdlDocumentField) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocumentField"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The "},{"code":"MdlDocumentField","type":"codeVoice"},{"type":"text","text":" class encapsulates a key-value pair, where "},{"code":"identifier","type":"codeVoice"},{"type":"text","text":" defines the type of the field"},{"type":"text","text":" "},{"type":"text","text":"(e.g., name, date of birth, etc.), and "},{"code":"value","type":"codeVoice"},{"type":"text","text":" holds the actual data for that field."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This class is used in representing mDL data both on the Holder and Reader sides."}],"type":"paragraph"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"value"},{"type":"text","text":" can be of any type depending on the context."}]}],"type":"aside","name":"Note"}]}],"abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder"]]},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocumentField"}],"navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"modules":[{"name":"MdlHolder"}],"title":"MdlDocumentField","symbolKind":"class","externalID":"c:@M@MdlHolder@objc(cs)XTMdlDocumentField","role":"symbol","roleHeading":"Class"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"],"generated":true,"anchor":"Main-Classes","title":"Main Classes"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.xinfotech.mdlholder/SQ":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.xinfotech.mdlholder/SH":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocumentField/identifier":{"url":"\/documentation\/mdlholder\/mdldocumentfield\/identifier","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField\/identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"title":"identifier","abstract":[{"type":"text","text":"The field identifier that defines its type within the document structure."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","title":"MdlHolder","type":"topic","url":"\/documentation\/mdlholder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/s7CVarArgP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.xinfotech.mdlholder/objc(cs)NSObject":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.xinfotech.mdlholder/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.xinfotech.mdlholder/objc(pl)NSObject":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate":{"url":"\/documentation\/mdlholder\/mdlholderdelegate","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolderDelegate"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"title":"MdlHolderDelegate","abstract":[{"type":"text","text":"Delivers events from the "},{"type":"reference","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","isActive":true},{"type":"text","text":" during the mDL document sharing lifecycle."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","type":"topic","url":"\/documentation\/mdlholder\/mdldocument","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"title":"MdlDocument","abstract":[{"type":"text","text":"Representation of mDL document"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocumentField/value":{"url":"\/documentation\/mdlholder\/mdldocumentfield\/value","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField\/value","navigatorTitle":[{"text":"value","kind":"identifier"}],"title":"value","abstract":[{"text":"The value of the field. The type depends on the context in which it is used.","type":"text"}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocumentField/description":{"url":"\/documentation\/mdlholder\/mdldocumentfield\/description","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","abstract":[{"text":"A string representation of the field in the format ","type":"text"},{"code":"(identifier = value)","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocumentField":{"url":"\/documentation\/mdlholder\/mdldocumentfield","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlDocumentField"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"title":"MdlDocumentField","abstract":[{"type":"text","text":"Represents an mDL document field containing an identifier and a corresponding value."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"abstract":[{"text":"Main class of the SDK","type":"text"}],"title":"MdlHolder","navigatorTitle":[{"text":"MdlHolder","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolder"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlholder"},"doc://com.xinfotech.mdlholder/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"XTMdlDocumentField"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"XTMdlDocumentField"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocumentField"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField\/description","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField\/identifier","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField\/value"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"],"anchor":"Main-Classes","generated":true,"title":"Main Classes"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlDocumentField"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField~1identifier\/title","value":"identifier"},{"value":[{"kind":"identifier","text":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField~1identifier\/fragments","op":"replace"},{"value":"XTMdlHolderDelegate","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/title","value":"XTMdlDocument","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/navigatorTitle","op":"replace"},{"value":"value","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField~1value\/title","op":"replace"},{"value":[{"kind":"identifier","text":"value"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField~1value\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"op":"replace","value":"XTMdlDocumentField","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocumentField"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocumentField"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title","value":"XTMdlHolder","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments","value":[{"kind":"identifier","text":"XTMdlHolder"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlHolder"}],"op":"replace"}]}]}