{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocumentField\/value"},"kind":"symbol","metadata":{"roleHeading":"Instance Property","modules":[{"name":"MdlHolderSdk"}],"externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlDocumentField(py)value","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"}],"symbolKind":"property","role":"symbol","platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false}],"navigatorTitle":[{"text":"value","kind":"identifier"}],"title":"value"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocumentField"]]},"abstract":[{"type":"text","text":"The value of the field. The type depends on the context in which it is used."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdldocumentfield\/value"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdldocumentfield\/value"]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocumentField":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocumentField","kind":"identifier"}],"abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}],"title":"MdlDocumentField","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocumentField","url":"\/documentation\/mdlholdersdk\/mdldocumentfield"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocumentField/value":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocumentField\/value","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdldocumentfield\/value","role":"symbol","navigatorTitle":[{"text":"value","kind":"identifier"}],"abstract":[{"text":"The value of the field. The type depends on the context in which it is used.","type":"text"}],"title":"value"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/platforms","value":[{"introducedAt":"14.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"introducedAt":"14.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"14.0","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"value"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"value","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField\/title","op":"replace","value":"XTMdlDocumentField"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocumentField"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDocumentField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField~1value\/title","op":"replace","value":"value"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField~1value\/fragments","op":"replace","value":[{"text":"value","kind":"identifier"}]}]}]}