{"abstract":[{"text":"The year when the mDL holder was born.  Age attestation: In what year where you born?","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ageBirthYear"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/ageBirthYear","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageBirthYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"modules":[{"name":"MdlHolderSdk"}],"role":"symbol","title":"ageBirthYear","externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlDocument(py)ageBirthYear","navigatorTitle":[{"kind":"identifier","text":"ageBirthYear"}],"platforms":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"14.0"},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"14.0"},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"14.0"}],"symbolKind":"property"},"variants":[{"paths":["\/documentation\/mdlholdersdk\/mdldocument\/agebirthyear"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholdersdk\/mdldocument\/agebirthyear"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/ageBirthYear":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ageBirthYear","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The year when the mDL holder was born.  Age attestation: In what year where you born?"}],"title":"ageBirthYear","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ageBirthYear"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/ageBirthYear","url":"\/documentation\/mdlholdersdk\/mdldocument\/agebirthyear"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","title":"MdlDocument","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdldocument"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"14.0","beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"14.0","beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"14.0","beta":false}]},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ageBirthYear","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ageBirthYear","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"ageBirthYear","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ageBirthYear","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1ageBirthYear\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1ageBirthYear\/fragments","value":[{"text":"ageBirthYear","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/title","value":"XTMdlDocument"},{"value":[{"text":"XTMdlDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocument"}]}]}]}