{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlBiometricTemplate","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate","kind":"typeIdentifier","text":"MdlBiometricTemplate"},{"kind":"text","text":"]?"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","modules":[{"name":"MdlHolderSdk"}],"externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlDocument(py)biometricTemplateXx","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"biometricTemplateXx","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MdlBiometricTemplate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlBiometricTemplate"},{"text":"]?","kind":"text"}],"symbolKind":"property","platforms":[{"introducedAt":"14.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"introducedAt":"14.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"14.0","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"biometricTemplateXx"}],"title":"biometricTemplateXx"},"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/biometricTemplateXx","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdldocument\/biometrictemplatexx"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdldocument\/biometrictemplatexx"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument"]]},"sections":[],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","title":"MdlDocument","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdldocument"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlBiometricTemplate":{"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlBiometricTemplate"}],"type":"topic","title":"MdlBiometricTemplate","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate","navigatorTitle":[{"kind":"identifier","text":"MdlBiometricTemplate"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdlbiometrictemplate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/biometricTemplateXx":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/biometricTemplateXx","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlBiometricTemplate","kind":"typeIdentifier","text":"MdlBiometricTemplate"},{"kind":"text","text":"]?"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdldocument\/biometrictemplatexx","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"biometricTemplateXx"}],"abstract":[],"title":"biometricTemplateXx"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"replace","value":[{"deprecated":false,"introducedAt":"14.0","unavailable":false,"name":"iOS","beta":false},{"introducedAt":"14.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"biometricTemplateXx"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"biometricTemplateXx"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<XTMdlBiometricTemplate *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"biometricTemplateXx"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/title","op":"replace","value":"XTMdlDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/fragments","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/navigatorTitle","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate\/title","value":"XTMdlBiometricTemplate"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate\/fragments","value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate\/navigatorTitle","op":"replace","value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}]},{"value":"biometricTemplateXx","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1biometricTemplateXx\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1biometricTemplateXx\/fragments","op":"replace","value":[{"text":"biometricTemplateXx","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}