{"abstract":[{"type":"text","text":"Date when mDL expires."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"expiryDate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/expiryDate","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MdlHolderSdk"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"title":"expiryDate","externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlDocument(py)expiryDate","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"expiryDate"}],"roleHeading":"Instance Property","platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"14.0","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"14.0","beta":false},{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdldocument\/expirydate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdldocument\/expirydate"]}],"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/expiryDate":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"expiryDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"abstract":[{"text":"Date when mDL expires.","type":"text"}],"title":"expiryDate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"expiryDate"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/expiryDate","url":"\/documentation\/mdlholdersdk\/mdldocument\/expirydate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","title":"MdlDocument","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdldocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","deprecated":false},{"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false}],"path":"\/metadata\/platforms","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"expiryDate"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"expiryDate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"expiryDate"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1expiryDate\/title","op":"replace","value":"expiryDate"},{"value":[{"text":"expiryDate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1expiryDate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/title","op":"replace","value":"XTMdlDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/fragments","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/navigatorTitle","value":[{"text":"XTMdlDocument","kind":"identifier"}]}]}]}