{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument"]]},"sections":[],"metadata":{"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"familyName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"givenName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"birthDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"text":"issuingCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issuingAuthority","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"portrait","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"drivingPrivileges","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivileges","text":"MdlDrivingPrivileges","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"unDistinguishingSign","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"holderIdNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bloodGroup","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dlIssueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dlExpiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"drivingRestrictions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"administrativeNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"sex","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolderSdk@E@XTMdlGender","text":"MdlGender","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"weight","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"eyeColour","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"hairColour","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"birthPlace","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"residentAddress","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"portraitCaptureDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"ageInYears","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"ageBirthYear","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"ageOverNn","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTAgeOverNnEntry","text":"AgeOverNnEntry","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"issuingJurisdiction","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"nationality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"residentCity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"residentState","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"residentPostalCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"residentCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"biometricTemplateXx","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlBiometricTemplate","text":"MdlBiometricTemplate","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"familyNameNationalCharacter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"givenNameNationalCharacter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"signatureUsualMark","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"MdlHolderSdk"}],"title":"init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlDocument(im)initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","role":"symbol","navigatorTitle":[{"text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","kind":"identifier"}],"platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0","beta":false},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"name":"Mac Catalyst","beta":false}],"symbolKind":"init"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdldocument\/init(familyname:givenname:birthdate:issuedate:expirydate:issuingcountry:issuingauthority:documentnumber:portrait:drivingprivileges:undistinguishingsign:holderidnumber:bloodgroup:dlissuedate:dlexpirydate:drivingrestrictions:administrativenum-1g6bl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdldocument\/init(familyname:givenname:birthdate:issuedate:expirydate:issuingcountry:issuingauthority:documentnumber:portrait:drivingprivileges:undistinguishingsign:holderidnumber:bloodgroup:dlissuedate:dlexpirydate:drivingrestrictions:administrativenum-1g6bl"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"familyName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"givenName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"birthDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issuingCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issuingAuthority","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"portrait","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"drivingPrivileges","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlDrivingPrivileges","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivileges","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivileges","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"unDistinguishingSign","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"holderIdNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bloodGroup","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dlIssueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dlExpiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"drivingRestrictions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"administrativeNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"sex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlGender","preciseIdentifier":"c:@M@MdlHolderSdk@E@XTMdlGender","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlGender","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"weight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"eyeColour","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"hairColour","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"birthPlace","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"residentAddress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"portraitCaptureDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"ageInYears","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"ageBirthYear","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"ageOverNn","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AgeOverNnEntry","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTAgeOverNnEntry","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/AgeOverNnEntry","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"text":"issuingJurisdiction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"nationality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"residentCity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"residentState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"residentPostalCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"residentCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"biometricTemplateXx","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MdlBiometricTemplate","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlBiometricTemplate","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"text":"familyNameNationalCharacter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"givenNameNationalCharacter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"signatureUsualMark","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlBiometricTemplate":{"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlBiometricTemplate"}],"type":"topic","title":"MdlBiometricTemplate","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate","navigatorTitle":[{"kind":"identifier","text":"MdlBiometricTemplate"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdlbiometrictemplate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","title":"MdlDocument","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdldocument"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"familyName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"givenName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"birthDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issueDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingCountry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingAuthority"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"portrait"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingPrivileges"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivileges","kind":"typeIdentifier","text":"MdlDrivingPrivileges"},{"kind":"text","text":", "},{"kind":"externalParam","text":"unDistinguishingSign"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"holderIdNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bloodGroup"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlIssueDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlExpiryDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingRestrictions"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"administrativeNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolderSdk@E@XTMdlGender","kind":"typeIdentifier","text":"MdlGender"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eyeColour"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hairColour"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"birthPlace"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"portraitCaptureDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageInYears"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageBirthYear"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageOverNn"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTAgeOverNnEntry","kind":"typeIdentifier","text":"AgeOverNnEntry"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"issuingJurisdiction"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nationality"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentCity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentState"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentPostalCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentCountry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlBiometricTemplate","kind":"typeIdentifier","text":"MdlBiometricTemplate"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"familyNameNationalCharacter"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"givenNameNationalCharacter"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureUsualMark"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"}],"url":"\/documentation\/mdlholdersdk\/mdldocument\/init(familyname:givenname:birthdate:issuedate:expirydate:issuingcountry:issuingauthority:documentnumber:portrait:drivingprivileges:undistinguishingsign:holderidnumber:bloodgroup:dlissuedate:dlexpirydate:drivingrestrictions:administrativenum-1g6bl","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","title":"init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/AgeOverNnEntry":{"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgeOverNnEntry","kind":"identifier"}],"title":"AgeOverNnEntry","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/AgeOverNnEntry","navigatorTitle":[{"text":"AgeOverNnEntry","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/ageovernnentry"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivileges":{"abstract":[{"text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL).","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MdlDrivingPrivileges","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivileges","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivileges","url":"\/documentation\/mdlholdersdk\/mdldrivingprivileges","title":"MdlDrivingPrivileges"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlGender":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}],"abstract":[],"title":"MdlGender","role":"symbol","navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlGender","url":"\/documentation\/mdlholdersdk\/mdlgender"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"introducedAt":"14.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"introducedAt":"14.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"14.0","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFamilyName:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"familyName"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenName:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"givenName"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier","text":"NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"birthDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueDate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier","text":"NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"issueDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiryDate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier","text":"NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"expiryDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingCountry:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"issuingCountry"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingAuthority:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"issuingAuthority"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentNumber"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"portrait"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingPrivileges:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivileges","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivileges","kind":"typeIdentifier","text":"XTMdlDrivingPrivileges"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"drivingPrivileges"},{"kind":"text","text":" "},{"kind":"identifier","text":"unDistinguishingSign:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"unDistinguishingSign"},{"kind":"text","text":" "},{"kind":"identifier","text":"holderIdNumber:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"holderIdNumber"},{"kind":"text","text":" "},{"kind":"identifier","text":"bloodGroup:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bloodGroup"},{"kind":"text","text":" "},{"kind":"identifier","text":"dlIssueDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dlIssueDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"dlExpiryDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dlExpiryDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingRestrictions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"drivingRestrictions"},{"kind":"text","text":" "},{"kind":"identifier","text":"administrativeNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"administrativeNumber"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@E@XTMdlGender","text":"XTMdlGender","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlGender"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sex"},{"kind":"text","text":" "},{"kind":"identifier","text":"height:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"text":"height","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"weight:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"text":"weight","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeColour:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"eyeColour"},{"kind":"text","text":" "},{"kind":"identifier","text":"hairColour:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"hairColour"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthPlace:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"birthPlace"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentAddress:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"residentAddress","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"portraitCaptureDate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"},{"text":" *) ","kind":"text"},{"text":"portraitCaptureDate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ageInYears:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"text":"ageInYears","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ageBirthYear:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"text":"ageBirthYear","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ageOverNn:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<XTAgeOverNnEntry *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"ageOverNn","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"issuingJurisdiction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"issuingJurisdiction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nationality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"nationality","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"residentCity:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"residentCity","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"residentState:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"residentState"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentPostalCode:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"residentPostalCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentCountry:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"residentCountry"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricTemplateXx:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<XTMdlBiometricTemplate *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"biometricTemplateXx"},{"kind":"text","text":" "},{"kind":"identifier","text":"familyNameNationalCharacter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"familyNameNationalCharacter"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenNameNationalCharacter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"givenNameNationalCharacter"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureUsualMark:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"signatureUsualMark"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate\/title","value":"XTMdlBiometricTemplate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlBiometricTemplate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlBiometricTemplate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/title","op":"replace","value":"XTMdlDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/title","op":"replace","value":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/fragments"},{"value":"XTAgeOverNnEntry","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1AgeOverNnEntry\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1AgeOverNnEntry\/fragments","op":"replace","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1AgeOverNnEntry\/navigatorTitle","op":"replace","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivileges\/title","op":"replace","value":"XTMdlDrivingPrivileges"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivileges\/fragments","value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}]},{"value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivileges\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlGender\/title","op":"replace","value":"XTMdlGender"},{"value":[{"kind":"identifier","text":"XTMdlGender"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlGender\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlGender"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlGender\/navigatorTitle","op":"replace"}]}]}