{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/portrait"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument"]]},"abstract":[{"type":"text","text":"A reproduction of the mDL holder’s portrait."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdldocument\/portrait"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdldocument\/portrait"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"portrait"}],"roleHeading":"Instance Property","platforms":[{"introducedAt":"14.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"introducedAt":"14.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"14.0","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false}],"externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlDocument(py)portrait","symbolKind":"property","title":"portrait","modules":[{"name":"MdlHolderSdk"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/portrait":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"portrait","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"abstract":[{"text":"A reproduction of the mDL holder’s portrait.","type":"text"}],"title":"portrait","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"portrait"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/portrait","url":"\/documentation\/mdlholdersdk\/mdldocument\/portrait"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","title":"MdlDocument","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdldocument"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"introducedAt":"14.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"introducedAt":"14.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"14.0","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"portrait","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"portrait"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" * "},{"kind":"identifier","text":"portrait"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1portrait\/title","value":"portrait","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1portrait\/fragments","value":[{"kind":"identifier","text":"portrait"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/title","value":"XTMdlDocument","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/fragments","value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace"}]}]}