{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portraitCaptureDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/portraitCaptureDate","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"MdlHolderSdk"}],"externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlDocument(py)portraitCaptureDate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portraitCaptureDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"symbolKind":"property","role":"symbol","platforms":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}],"navigatorTitle":[{"text":"portraitCaptureDate","kind":"identifier"}],"title":"portraitCaptureDate"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument"]]},"abstract":[{"type":"text","text":"Date when portrait was taken."}],"variants":[{"paths":["\/documentation\/mdlholdersdk\/mdldocument\/portraitcapturedate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholdersdk\/mdldocument\/portraitcapturedate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","title":"MdlDocument","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdldocument"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/portraitCaptureDate":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/portraitCaptureDate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portraitCaptureDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdldocument\/portraitcapturedate","role":"symbol","navigatorTitle":[{"text":"portraitCaptureDate","kind":"identifier"}],"abstract":[{"type":"text","text":"Date when portrait was taken."}],"title":"portraitCaptureDate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"portraitCaptureDate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"portraitCaptureDate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"portraitCaptureDate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/title","op":"replace","value":"XTMdlDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/fragments","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1portraitCaptureDate\/title","op":"replace","value":"portraitCaptureDate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1portraitCaptureDate\/fragments","op":"replace","value":[{"text":"portraitCaptureDate","kind":"identifier"}]}]}]}