{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdldrivingprivilege\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdldrivingprivilege\/description"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"description","platforms":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilege(py)description","modules":[{"name":"MdlReader"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege\/description","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilege/description":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege\/description","abstract":[],"url":"\/documentation\/mdlreader\/mdldrivingprivilege\/description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilege":{"abstract":[{"type":"text","text":"A data model representing a single driving privilege entry from a Mobile Driving Licence (mDL)."}],"url":"\/documentation\/mdlreader\/mdldrivingprivilege","title":"MdlDrivingPrivilege","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"identifier"}],"navigatorTitle":[{"text":"MdlDrivingPrivilege","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"description","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege~1description\/fragments","op":"replace"},{"value":"XTMdlDrivingPrivilege","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/navigatorTitle","op":"replace"}]}]}