{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege"]]},"kind":"symbol","metadata":{"platforms":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}],"role":"symbol","roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"vehicleCategoryCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"issueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"codes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCodes","text":"MdlDrivingPrivilegeCodes"},{"kind":"text","text":"?)"}],"modules":[{"name":"MdlReader"}],"navigatorTitle":[{"text":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:","kind":"identifier"}],"title":"init(vehicleCategoryCode:issueDate:expiryDate:codes:)","externalID":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilege(im)initWithVehicleCategoryCode:issueDate:expiryDate:codes:"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"vehicleCategoryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"codes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCodes","text":"MdlDrivingPrivilegeCodes","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The category of the vehicle permitted to drive."}]}],"name":"vehicleCategoryCode"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The date the privilege was issued."}]}],"name":"issueDate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The date the privilege expires."}]}],"name":"expiryDate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Driving privilege codes"}]}],"name":"codes"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Initializes a new instance of "},{"code":"MdlDrivingPrivilege","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdldrivingprivilege\/init(vehiclecategorycode:issuedate:expirydate:codes:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdldrivingprivilege\/init(vehiclecategorycode:issuedate:expirydate:codes:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege\/init(vehicleCategoryCode:issueDate:expiryDate:codes:)"},"sections":[],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCodes":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes","abstract":[],"navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"url":"\/documentation\/mdlreader\/mdldrivingprivilegecodes","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"type":"topic","kind":"symbol","title":"MdlDrivingPrivilegeCodes","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilege/init(vehicleCategoryCode:issueDate:expiryDate:codes:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege\/init(vehicleCategoryCode:issueDate:expiryDate:codes:)","abstract":[{"type":"text","text":"Initializes a new instance of "},{"type":"codeVoice","code":"MdlDrivingPrivilege"},{"type":"text","text":"."}],"url":"\/documentation\/mdlreader\/mdldrivingprivilege\/init(vehiclecategorycode:issuedate:expirydate:codes:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vehicleCategoryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"expiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"codes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCodes","text":"MdlDrivingPrivilegeCodes"},{"text":"?)","kind":"text"}],"title":"init(vehicleCategoryCode:issueDate:expiryDate:codes:)","navigatorTitle":[{"kind":"identifier","text":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilege":{"abstract":[{"type":"text","text":"A data model representing a single driving privilege entry from a Mobile Driving Licence (mDL)."}],"url":"\/documentation\/mdlreader\/mdldrivingprivilege","title":"MdlDrivingPrivilege","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"identifier"}],"navigatorTitle":[{"text":"MdlDrivingPrivilege","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false,"beta":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithVehicleCategoryCode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"vehicleCategoryCode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"issueDate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"issueDate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"expiryDate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"expiryDate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"codes:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCodes","text":"XTMdlDrivingPrivilegeCodes","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"codes","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The category of the vehicle permitted to drive."}]}],"name":"vehicleCategoryCode"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The date the privilege was issued."}]}],"name":"issueDate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The date the privilege expires."}]}],"name":"expiryDate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Driving privilege codes"}]}],"name":"codes"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/title","value":"XTMdlDrivingPrivilegeCodes","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege~1init(vehicleCategoryCode:issueDate:expiryDate:codes:)\/title","value":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege~1init(vehicleCategoryCode:issueDate:expiryDate:codes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/title","value":"XTMdlDrivingPrivilege","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}],"op":"replace"}]}]}