{"metadata":{"navigatorTitle":[{"text":"drivingRestrictions","kind":"identifier"}],"roleHeading":"Type Property","platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"14.0","deprecated":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}],"externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier(cpy)drivingRestrictions","symbolKind":"property","title":"drivingRestrictions","modules":[{"name":"MdlHolderSdk"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"drivingRestrictions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier"]]},"abstract":[{"text":"Driver’s restrictions","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/mdlholdersdk\/mdlfieldidentifier\/drivingrestrictions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdlfieldidentifier\/drivingrestrictions"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier\/drivingRestrictions"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drivingRestrictions","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Value type: "},{"code":"String","type":"codeVoice"}]}]}],"type":"unorderedList"}]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlFieldIdentifier":{"abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","url":"\/documentation\/mdlholdersdk\/mdlfieldidentifier"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlFieldIdentifier/drivingRestrictions":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drivingRestrictions","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"drivingRestrictions"}],"url":"\/documentation\/mdlholdersdk\/mdlfieldidentifier\/drivingrestrictions","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier\/drivingRestrictions","abstract":[{"type":"text","text":"Driver’s restrictions"}],"kind":"symbol","title":"drivingRestrictions","type":"topic","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"replace","value":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"14.0","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"drivingRestrictions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"drivingRestrictions","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier","text":"XTMdlFieldIdentifier","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"drivingRestrictions","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/fragments","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]},{"value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/navigatorTitle"},{"value":"drivingRestrictions","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier~1drivingRestrictions\/title"},{"value":[{"text":"drivingRestrictions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier~1drivingRestrictions\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}