{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The eye colour of the document holder."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeColour","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Value type: "},{"code":"String","type":"codeVoice"}]}]}],"type":"unorderedList"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"eyeColour"}],"role":"symbol","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeColour"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier(cpy)eyeColour","platforms":[{"deprecated":false,"introducedAt":"14.0","unavailable":false,"name":"iOS","beta":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}],"title":"eyeColour","symbolKind":"property","modules":[{"name":"MdlHolderSdk"}]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier\/eyeColour","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdlfieldidentifier\/eyecolour"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdlfieldidentifier\/eyecolour"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier"]]},"sections":[],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlFieldIdentifier/eyeColour":{"abstract":[{"type":"text","text":"The eye colour of the document holder."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"eyeColour"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeColour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier\/eyeColour","url":"\/documentation\/mdlholdersdk\/mdlfieldidentifier\/eyecolour","title":"eyeColour"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlFieldIdentifier":{"abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","url":"\/documentation\/mdlholdersdk\/mdlfieldidentifier"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"14.0","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"14.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0","beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"eyeColour"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"eyeColour","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier","kind":"typeIdentifier","text":"XTMdlFieldIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"eyeColour"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier~1eyeColour\/title","op":"replace","value":"eyeColour"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier~1eyeColour\/fragments","op":"replace","value":[{"text":"eyeColour","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/title","op":"replace","value":"XTMdlFieldIdentifier"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/fragments","op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/navigatorTitle","op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}