{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"familyNameNationalCharacter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier"}],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Value type: "},{"code":"String","type":"codeVoice"}],"type":"paragraph"}]}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier\/familyNameNationalCharacter","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier"]]},"abstract":[{"type":"text","text":"The family name in national characters."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdlfieldidentifier\/familynamenationalcharacter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdlfieldidentifier\/familynamenationalcharacter"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"familyNameNationalCharacter"}],"roleHeading":"Type Property","platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}],"externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier(cpy)familyNameNationalCharacter","symbolKind":"property","title":"familyNameNationalCharacter","modules":[{"name":"MdlHolderSdk"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"familyNameNationalCharacter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlFieldIdentifier":{"abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","url":"\/documentation\/mdlholdersdk\/mdlfieldidentifier"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlFieldIdentifier/familyNameNationalCharacter":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"familyNameNationalCharacter","kind":"identifier"},{"kind":"text","text":": "},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier"}],"abstract":[{"type":"text","text":"The family name in national characters."}],"title":"familyNameNationalCharacter","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"familyNameNationalCharacter"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier\/familyNameNationalCharacter","url":"\/documentation\/mdlholdersdk\/mdlfieldidentifier\/familynamenationalcharacter"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"familyNameNationalCharacter"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"familyNameNationalCharacter","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier","text":"XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"familyNameNationalCharacter"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/title","op":"replace","value":"XTMdlFieldIdentifier"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/fragments","op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/navigatorTitle","op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier~1familyNameNationalCharacter\/title","op":"replace","value":"familyNameNationalCharacter"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier~1familyNameNationalCharacter\/fragments","op":"replace","value":[{"text":"familyNameNationalCharacter","kind":"identifier"}]}]}]}