{"metadata":{"roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"holderIdNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"modules":[{"name":"MdlHolderSdk"}],"title":"holderIdNumber","role":"symbol","externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier(cpy)holderIdNumber","navigatorTitle":[{"text":"holderIdNumber","kind":"identifier"}],"platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"14.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0","beta":false}],"symbolKind":"property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier"]]},"abstract":[{"text":"mDL holder’s national ID or alien ID, or diplomatic ID","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdlfieldidentifier\/holderidnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdlfieldidentifier\/holderidnumber"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier\/holderIdNumber","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"holderIdNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Value type: ","type":"text"},{"type":"codeVoice","code":"String"}],"type":"paragraph"}]}]}],"kind":"content"}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlFieldIdentifier/holderIdNumber":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"holderIdNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier"}],"abstract":[{"type":"text","text":"mDL holder’s national ID or alien ID, or diplomatic ID"}],"title":"holderIdNumber","role":"symbol","navigatorTitle":[{"text":"holderIdNumber","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier\/holderIdNumber","url":"\/documentation\/mdlholdersdk\/mdlfieldidentifier\/holderidnumber"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlFieldIdentifier":{"abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","url":"\/documentation\/mdlholdersdk\/mdlfieldidentifier"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"introducedAt":"14.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"14.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"holderIdNumber"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"holderIdNumber"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier","kind":"typeIdentifier","text":"XTMdlFieldIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"holderIdNumber"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier~1holderIdNumber\/title","op":"replace","value":"holderIdNumber"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier~1holderIdNumber\/fragments","op":"replace","value":[{"kind":"identifier","text":"holderIdNumber"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/title","op":"replace","value":"XTMdlFieldIdentifier"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]}]}]}