{"abstract":[{"text":"The issue date of the document.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issueDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Value type: ","type":"text"},{"code":"Date","type":"codeVoice"}]}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier\/issueDate","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MdlHolderSdk"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issueDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier"}],"title":"issueDate","externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier(cpy)issueDate","symbolKind":"property","navigatorTitle":[{"text":"issueDate","kind":"identifier"}],"roleHeading":"Type Property","platforms":[{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false}]},"variants":[{"paths":["\/documentation\/mdlholdersdk\/mdlfieldidentifier\/issuedate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholdersdk\/mdlfieldidentifier\/issuedate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlFieldIdentifier/issueDate":{"abstract":[{"text":"The issue date of the document.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueDate"},{"kind":"text","text":": "},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier"}],"title":"issueDate","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier\/issueDate","navigatorTitle":[{"text":"issueDate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdlfieldidentifier\/issuedate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlFieldIdentifier":{"abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","url":"\/documentation\/mdlholdersdk\/mdlfieldidentifier"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"issueDate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"issueDate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"XTMdlFieldIdentifier","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier"},{"text":" * ","kind":"text"},{"text":"issueDate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier~1issueDate\/title","op":"replace","value":"issueDate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier~1issueDate\/fragments","op":"replace","value":[{"text":"issueDate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/title","op":"replace","value":"XTMdlFieldIdentifier"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/fragments","op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlFieldIdentifier\/navigatorTitle","op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}