{"topicSections":[{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/AgeOverNnEntry\/init(age:isOverAge:)"],"title":"Initializers"},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/AgeOverNnEntry\/age","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/AgeOverNnEntry\/isOverAge"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTAgeOverNnEntry) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AgeOverNnEntry","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/AgeOverNnEntry","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MdlHolderSdk"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgeOverNnEntry"}],"title":"AgeOverNnEntry","externalID":"c:@M@MdlHolderSdk@objc(cs)XTAgeOverNnEntry","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"AgeOverNnEntry"}],"roleHeading":"Class","platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","deprecated":false},{"introducedAt":"14.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false}]},"variants":[{"paths":["\/documentation\/mdlholdersdk\/ageovernnentry"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholdersdk\/ageovernnentry"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH"],"title":"Conforms To"}],"references":{"doc://com.xinfotech.mdlholder/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP"},"doc://com.xinfotech.mdlholder/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/AgeOverNnEntry/age":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"age"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"title":"age","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"age"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/AgeOverNnEntry\/age","url":"\/documentation\/mdlholdersdk\/ageovernnentry\/age"},"doc://com.xinfotech.mdlholder/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SH"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/objc(pl)NSObject":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/AgeOverNnEntry":{"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgeOverNnEntry","kind":"identifier"}],"title":"AgeOverNnEntry","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/AgeOverNnEntry","navigatorTitle":[{"text":"AgeOverNnEntry","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/ageovernnentry"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/AgeOverNnEntry/init(age:isOverAge:)":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithAge:isOverAge:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"age"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isOverAge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/AgeOverNnEntry\/init(age:isOverAge:)","title":"init(age:isOverAge:)","url":"\/documentation\/mdlholdersdk\/ageovernnentry\/init(age:isoverage:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/AgeOverNnEntry/isOverAge":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"isOverAge","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isOverAge","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/AgeOverNnEntry\/isOverAge","title":"isOverAge","url":"\/documentation\/mdlholdersdk\/ageovernnentry\/isoverage"},"doc://com.xinfotech.mdlholder/SQ":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.xinfotech.mdlholder/objc(cs)NSObject":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.xinfotech.mdlholder/s7CVarArgP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"deprecated":false,"introducedAt":"14.0","unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"XTAgeOverNnEntry"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/AgeOverNnEntry\/age","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/AgeOverNnEntry\/isOverAge"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/AgeOverNnEntry\/init(age:isOverAge:)"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"XTAgeOverNnEntry","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1AgeOverNnEntry~1age\/title","value":"age"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1AgeOverNnEntry~1age\/fragments","value":[{"kind":"identifier","text":"age"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1AgeOverNnEntry\/title","value":"XTAgeOverNnEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1AgeOverNnEntry\/fragments","value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1AgeOverNnEntry\/navigatorTitle","value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1AgeOverNnEntry~1init(age:isOverAge:)\/title","value":"initWithAge:isOverAge:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1AgeOverNnEntry~1init(age:isOverAge:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAge:isOverAge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1AgeOverNnEntry~1isOverAge\/title","value":"isOverAge"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1AgeOverNnEntry~1isOverAge\/fragments","value":[{"kind":"identifier","text":"isOverAge"}]}]}]}