{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Possible error codes in SDK","type":"text"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/bleDenied","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/bleRestricted","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/bleUnauthorized","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/bleUnsupported","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/cryptographicError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/initializationError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/internalError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocExpired","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocLostOrStolen","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocNotFound","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocRequestError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocRevoked","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocValidationError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/networkError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/notInitialized","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/pinIsEmpty","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/pinIsWrong","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/requestNotFound","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/rootCaCertificateMissing","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/sessionDataError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/sessionNotFound","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/startSharingError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/success","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/unknown"],"anchor":"Enumeration-Cases","generated":true},{"title":"Initializers","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/Equatable-Implementations","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTHolderErrorCode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HolderErrorCode","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"HolderErrorCode","kind":"identifier"}],"role":"symbol","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HolderErrorCode"}],"externalID":"c:@M@MdlHolderSdk@E@XTHolderErrorCode","title":"HolderErrorCode","symbolKind":"enum","modules":[{"name":"MdlHolderSdk"}]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/holdererrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/holdererrorcode"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk"]]},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH","doc:\/\/com.xinfotech.mdlholder\/SY"],"type":"conformsTo"}],"sections":[],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/pinIsEmpty":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodePinIsEmpty"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinIsEmpty"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/pinIsEmpty","title":"HolderErrorCode.pinIsEmpty","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/pinisempty"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/bleUnsupported":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeBleUnsupported"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleUnsupported"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/bleUnsupported","title":"HolderErrorCode.bleUnsupported","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/bleunsupported"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/mDocNotFound":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeMDocNotFound"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocNotFound"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocNotFound","title":"HolderErrorCode.mDocNotFound","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/mdocnotfound"},"doc://com.xinfotech.mdlholder/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SY"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/RawRepresentable-Implementations":{"type":"topic","abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/RawRepresentable-Implementations","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/rawrepresentable-implementations"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/networkError":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeNetworkError"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"networkError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/networkError","title":"HolderErrorCode.networkError","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/networkerror"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/Equatable-Implementations":{"abstract":[],"type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/equatable-implementations"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/mDocValidationError":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocValidationError"}],"abstract":[],"title":"HolderErrorCode.mDocValidationError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeMDocValidationError"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocValidationError","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/mdocvalidationerror"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/bleRestricted":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeBleRestricted"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"bleRestricted","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/bleRestricted","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/blerestricted","title":"HolderErrorCode.bleRestricted"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/unknown":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[],"title":"HolderErrorCode.unknown","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeUnknown","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/unknown","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/unknown"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/mDocExpired":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mDocExpired","kind":"identifier"}],"abstract":[],"title":"HolderErrorCode.mDocExpired","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeMDocExpired","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocExpired","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/mdocexpired"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/mDocRevoked":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocRevoked"}],"abstract":[],"title":"HolderErrorCode.mDocRevoked","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeMDocRevoked","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocRevoked","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/mdocrevoked"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/sessionNotFound":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeSessionNotFound","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionNotFound","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/sessionNotFound","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/sessionnotfound","title":"HolderErrorCode.sessionNotFound"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/startSharingError":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSharingError"}],"abstract":[],"title":"HolderErrorCode.startSharingError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeStartSharingError"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/startSharingError","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/startsharingerror"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/requestNotFound":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeRequestNotFound","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestNotFound","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/requestNotFound","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/requestnotfound","title":"HolderErrorCode.requestNotFound"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/bleUnauthorized":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeBleUnauthorized"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleUnauthorized"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/bleUnauthorized","title":"HolderErrorCode.bleUnauthorized","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/bleunauthorized"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/bleDenied":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeBleDenied","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bleDenied","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/bleDenied","title":"HolderErrorCode.bleDenied","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/bledenied"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/rootCaCertificateMissing":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeRootCaCertificateMissing","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootCaCertificateMissing","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/rootCaCertificateMissing","title":"HolderErrorCode.rootCaCertificateMissing","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/rootcacertificatemissing"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/success":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeSuccess","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/success","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/success","title":"HolderErrorCode.success"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HolderErrorCode","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/holdererrorcode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HolderErrorCode"}],"abstract":[{"type":"text","text":"Possible error codes in SDK"}],"title":"HolderErrorCode"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/pinIsWrong":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodePinIsWrong","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pinIsWrong","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/pinIsWrong","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/piniswrong","title":"HolderErrorCode.pinIsWrong"},"doc://com.xinfotech.mdlholder/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SH"},"doc://com.xinfotech.mdlholder/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ","title":"Swift.Equatable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/init(rawValue:)":{"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/init(rawValue:)","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/init(rawvalue:)","title":"init(rawValue:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/mDocLostOrStolen":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeMDocLostOrStolen","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocLostOrStolen","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocLostOrStolen","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/mdoclostorstolen","title":"HolderErrorCode.mDocLostOrStolen"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/sessionDataError":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeSessionDataError"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionDataError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/sessionDataError","title":"HolderErrorCode.sessionDataError","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/sessiondataerror"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/initializationError":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeInitializationError","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initializationError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/initializationError","title":"HolderErrorCode.initializationError","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/initializationerror"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/mDocError":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocError","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/mdocerror","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeMDocError","kind":"identifier"}],"abstract":[],"title":"HolderErrorCode.mDocError"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/cryptographicError":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/cryptographicError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cryptographicError","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/cryptographicerror","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeCryptographicError","kind":"identifier"}],"abstract":[],"title":"HolderErrorCode.cryptographicError"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/internalError":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/internalError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/internalerror","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeInternalError"}],"abstract":[],"title":"HolderErrorCode.internalError"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/mDocRequestError":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocRequestError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocRequestError","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/mdocrequesterror","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeMDocRequestError","kind":"identifier"}],"abstract":[],"title":"HolderErrorCode.mDocRequestError"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/notInitialized":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/notInitialized","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notInitialized","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/notinitialized","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeNotInitialized","kind":"identifier"}],"abstract":[],"title":"HolderErrorCode.notInitialized"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"XTHolderErrorCode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","value":[{"text":"XTHolderErrorCode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"XTHolderErrorCode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/bleDenied","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/bleRestricted","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/bleUnauthorized","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/bleUnsupported","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/cryptographicError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/initializationError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/internalError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocExpired","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocLostOrStolen","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocNotFound","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocRequestError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocRevoked","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocValidationError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/networkError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/notInitialized","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/pinIsEmpty","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/pinIsWrong","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/requestNotFound","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/rootCaCertificateMissing","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/sessionDataError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/sessionNotFound","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/startSharingError","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/success","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/unknown"],"generated":true,"anchor":"Enumeration-Cases"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"XTHolderErrorCode","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1pinIsEmpty\/title","value":"XTHolderErrorCodePinIsEmpty"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1pinIsEmpty\/fragments","value":[{"text":"XTHolderErrorCodePinIsEmpty","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1bleUnsupported\/title","value":"XTHolderErrorCodeBleUnsupported"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1bleUnsupported\/fragments","value":[{"text":"XTHolderErrorCodeBleUnsupported","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocNotFound\/title","value":"XTHolderErrorCodeMDocNotFound"},{"op":"replace","value":[{"text":"XTHolderErrorCodeMDocNotFound","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocNotFound\/fragments"},{"op":"replace","value":"XTHolderErrorCodeNetworkError","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1networkError\/title"},{"op":"replace","value":[{"text":"XTHolderErrorCodeNetworkError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1networkError\/fragments"},{"op":"replace","value":"XTHolderErrorCodeMDocValidationError","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocValidationError\/title"},{"op":"replace","value":[{"text":"XTHolderErrorCodeMDocValidationError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocValidationError\/fragments"},{"op":"replace","value":"XTHolderErrorCodeBleRestricted","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1bleRestricted\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1bleRestricted\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTHolderErrorCodeBleRestricted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1unknown\/title","value":"XTHolderErrorCodeUnknown"},{"op":"replace","value":[{"text":"XTHolderErrorCodeUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1unknown\/fragments"},{"op":"replace","value":"XTHolderErrorCodeMDocExpired","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocExpired\/title"},{"op":"replace","value":[{"text":"XTHolderErrorCodeMDocExpired","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocExpired\/fragments"},{"op":"replace","value":"XTHolderErrorCodeMDocRevoked","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocRevoked\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocRevoked\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeMDocRevoked","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1sessionNotFound\/title","op":"replace","value":"XTHolderErrorCodeSessionNotFound"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1sessionNotFound\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTHolderErrorCodeSessionNotFound"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1startSharingError\/title","op":"replace","value":"XTHolderErrorCodeStartSharingError"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1startSharingError\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTHolderErrorCodeStartSharingError"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1requestNotFound\/title","op":"replace","value":"XTHolderErrorCodeRequestNotFound"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1requestNotFound\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTHolderErrorCodeRequestNotFound"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1bleUnauthorized\/title","op":"replace","value":"XTHolderErrorCodeBleUnauthorized"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1bleUnauthorized\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTHolderErrorCodeBleUnauthorized"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1bleDenied\/title","op":"replace","value":"XTHolderErrorCodeBleDenied"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1bleDenied\/fragments","value":[{"text":"XTHolderErrorCodeBleDenied","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1rootCaCertificateMissing\/title","value":"XTHolderErrorCodeRootCaCertificateMissing","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1rootCaCertificateMissing\/fragments","value":[{"text":"XTHolderErrorCodeRootCaCertificateMissing","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1success\/title","value":"XTHolderErrorCodeSuccess","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1success\/fragments","value":[{"text":"XTHolderErrorCodeSuccess","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/title","value":"XTHolderErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTHolderErrorCode"}]},{"op":"replace","value":[{"text":"XTHolderErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1pinIsWrong\/title","value":"XTHolderErrorCodePinIsWrong","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1pinIsWrong\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCodePinIsWrong"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocLostOrStolen\/title","value":"XTHolderErrorCodeMDocLostOrStolen"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocLostOrStolen\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCodeMDocLostOrStolen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1sessionDataError\/title","value":"XTHolderErrorCodeSessionDataError"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1sessionDataError\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCodeSessionDataError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1initializationError\/title","value":"XTHolderErrorCodeInitializationError"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1initializationError\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeInitializationError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocError\/title","op":"replace","value":"XTHolderErrorCodeMDocError"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocError\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeMDocError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1cryptographicError\/title","op":"replace","value":"XTHolderErrorCodeCryptographicError"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1cryptographicError\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeCryptographicError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1internalError\/title","op":"replace","value":"XTHolderErrorCodeInternalError"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1internalError\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeInternalError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocRequestError\/title","op":"replace","value":"XTHolderErrorCodeMDocRequestError"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocRequestError\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeMDocRequestError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1notInitialized\/title","op":"replace","value":"XTHolderErrorCodeNotInitialized"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1notInitialized\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeNotInitialized","kind":"identifier"}]}]}]}