{"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTMdlBiometricTemplate) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlBiometricTemplate","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Class","modules":[{"name":"MdlHolderSdk"}],"externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlBiometricTemplate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlBiometricTemplate"}],"symbolKind":"class","platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","deprecated":false},{"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlBiometricTemplate"}],"title":"MdlBiometricTemplate"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate\/init(templateName:content:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate\/content","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate\/templateName"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdlbiometrictemplate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdlbiometrictemplate"]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlBiometricTemplate/init(templateName:content:)":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate\/init(templateName:content:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"templateName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdlbiometrictemplate\/init(templatename:content:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithTemplateName:content:"}],"abstract":[],"title":"init(templateName:content:)"},"doc://com.xinfotech.mdlholder/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.xinfotech.mdlholder/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlBiometricTemplate/content":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate\/content","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdlbiometrictemplate\/content","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"content"}],"abstract":[],"title":"content"},"doc://com.xinfotech.mdlholder/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SH"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlBiometricTemplate/templateName":{"abstract":[{"text":"Template name. It replaces ‘xx’ in ‘biometric_template_xx’.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"templateName","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate\/templateName","navigatorTitle":[{"kind":"identifier","text":"templateName"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdlbiometrictemplate\/templatename"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP"},"doc://com.xinfotech.mdlholder/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject"},"doc://com.xinfotech.mdlholder/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ"},"doc://com.xinfotech.mdlholder/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlBiometricTemplate":{"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlBiometricTemplate"}],"type":"topic","title":"MdlBiometricTemplate","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate","navigatorTitle":[{"kind":"identifier","text":"MdlBiometricTemplate"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdlbiometrictemplate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"14.0"},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"14.0"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"14.0","deprecated":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"XTMdlBiometricTemplate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate\/content","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate\/templateName"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlBiometricTemplate\/init(templateName:content:)"],"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlBiometricTemplate"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate~1init(templateName:content:)\/title","op":"replace","value":"initWithTemplateName:content:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate~1init(templateName:content:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithTemplateName:content:","kind":"identifier"}]},{"value":"content","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate~1content\/title","op":"replace"},{"value":[{"text":"content","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate~1content\/fragments","op":"replace"},{"value":"templateName","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate~1templateName\/title","op":"replace"},{"value":[{"text":"templateName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate~1templateName\/fragments","op":"replace"},{"value":"XTMdlBiometricTemplate","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlBiometricTemplate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate\/fragments","op":"replace"},{"value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlBiometricTemplate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}