{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk"]]},"sections":[],"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"modules":[{"name":"MdlHolderSdk"}],"role":"symbol","externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivilegeCode","title":"MdlDrivingPrivilegeCode","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilegeCode"}],"platforms":[{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"introducedAt":"14.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false}],"symbolKind":"class"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdldrivingprivilegecode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdldrivingprivilegecode"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/init(code:sign:value:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/code","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/sign","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/value"],"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(XTMdlDrivingPrivilegeCode) "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"references":{"doc://com.xinfotech.mdlholder/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","type":"unresolvable"},"doc://com.xinfotech.mdlholder/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivilegeCode":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdldrivingprivilegecode","role":"symbol","navigatorTitle":[{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"abstract":[],"title":"MdlDrivingPrivilegeCode"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivilegeCode/init(code:sign:value:)":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/init(code:sign:value:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sign","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdldrivingprivilegecode\/init(code:sign:value:)","role":"symbol","navigatorTitle":[{"text":"initWithCode:sign:value:","kind":"identifier"}],"abstract":[],"title":"init(code:sign:value:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivilegeCode/sign":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sign","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"Sign as per ISO\/IEC 18013-2 Annex A","type":"text"}],"title":"sign","role":"symbol","navigatorTitle":[{"text":"sign","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/sign","url":"\/documentation\/mdlholdersdk\/mdldrivingprivilegecode\/sign"},"doc://com.xinfotech.mdlholder/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivilegeCode/code":{"abstract":[{"text":"Code as per ISO\/IEC 18013-2 Annex A.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"code","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/code","url":"\/documentation\/mdlholdersdk\/mdldrivingprivilegecode\/code","title":"code"},"doc://com.xinfotech.mdlholder/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.xinfotech.mdlholder/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SH","type":"unresolvable"},"doc://com.xinfotech.mdlholder/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivilegeCode/value":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"Value as per ISO\/IEC 18013-2 Annex A","type":"text"}],"title":"value","role":"symbol","navigatorTitle":[{"text":"value","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/value","url":"\/documentation\/mdlholdersdk\/mdldrivingprivilegecode\/value"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0","beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"XTMdlDrivingPrivilegeCode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/code","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/sign","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/value"],"generated":true},{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/init(code:sign:value:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode\/title","op":"replace","value":"XTMdlDrivingPrivilegeCode"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode~1init(code:sign:value:)\/title","value":"initWithCode:sign:value:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode~1init(code:sign:value:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCode:sign:value:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode~1sign\/title","op":"replace","value":"sign"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode~1sign\/fragments","op":"replace","value":[{"text":"sign","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode~1code\/title","op":"replace","value":"code"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode~1code\/fragments","op":"replace","value":[{"kind":"identifier","text":"code"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode~1value\/title","value":"value","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode~1value\/fragments","op":"replace","value":[{"text":"value","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}