{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdldocument"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdldocument"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTMdlDocument) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk"]]},"abstract":[{"text":"Representation of mDL document","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/administrativeNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/ageBirthYear","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/ageInYears","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/ageOverNn","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/biometricTemplateXx","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/birthDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/birthPlace","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/bloodGroup","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/dlExpiryDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/dlIssueDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/documentNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/drivingPrivileges","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/drivingRestrictions","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/expiryDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/eyeColour","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/familyName","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/familyNameNationalCharacter","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/givenName","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/givenNameNationalCharacter","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/hairColour","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/height","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/holderIdNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/issueDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/issuingAuthority","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/issuingCountry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/issuingJurisdiction","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/nationality","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/portrait","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/portraitCaptureDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentAddress","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentCity","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentCountry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentPostalCode","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentState","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/sex","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/signatureUsualMark","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/unDistinguishingSign","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/weight"],"title":"Instance Properties"}],"kind":"symbol","seeAlsoSections":[{"anchor":"Main-Classes","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocumentField","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate"],"title":"Main Classes"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"metadata":{"modules":[{"name":"MdlHolderSdk"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"title":"MdlDocument","externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlDocument","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"roleHeading":"Class","platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0","beta":false},{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/issuingJurisdiction":{"abstract":[{"type":"text","text":"Country subdivision code of the jurisdiction that issued the mDL. The first part of the code shall be the same as the value for issuing country."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"issuingJurisdiction"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuingJurisdiction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/issuingJurisdiction","url":"\/documentation\/mdlholdersdk\/mdldocument\/issuingjurisdiction","title":"issuingJurisdiction"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/givenNameNationalCharacter":{"abstract":[{"text":"The given name of the mDL holder using full UTF-8 character set.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenNameNationalCharacter"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","title":"givenNameNationalCharacter","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/givenNameNationalCharacter","navigatorTitle":[{"text":"givenNameNationalCharacter","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdldocument\/givennamenationalcharacter"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/height":{"abstract":[{"text":"mDL holder’s height in centimeters.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"height"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/height","url":"\/documentation\/mdlholdersdk\/mdldocument\/height","title":"height"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/sex":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolderSdk@E@XTMdlGender","kind":"typeIdentifier","text":"MdlGender"}],"navigatorTitle":[{"kind":"identifier","text":"sex"}],"url":"\/documentation\/mdlholdersdk\/mdldocument\/sex","abstract":[{"text":"mDL holder’s sex.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/sex","title":"sex","kind":"symbol","type":"topic","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/ageOverNn":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageOverNn"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTAgeOverNnEntry","kind":"typeIdentifier","text":"AgeOverNnEntry"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"ageOverNn"}],"url":"\/documentation\/mdlholdersdk\/mdldocument\/ageovernn","abstract":[{"text":"Age attestation: Nearest “true” attestation above request.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/ageOverNn","title":"ageOverNn","kind":"symbol","type":"topic","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/issueDate":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"}],"navigatorTitle":[{"kind":"identifier","text":"issueDate"}],"url":"\/documentation\/mdlholdersdk\/mdldocument\/issuedate","abstract":[{"text":"Date when mDL was issued.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/issueDate","title":"issueDate","kind":"symbol","type":"topic","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"familyName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"givenName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"birthDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issueDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingCountry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingAuthority"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"portrait"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingPrivileges"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivileges","kind":"typeIdentifier","text":"MdlDrivingPrivileges"},{"kind":"text","text":", "},{"kind":"externalParam","text":"unDistinguishingSign"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"holderIdNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bloodGroup"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlIssueDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlExpiryDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingRestrictions"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"administrativeNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolderSdk@E@XTMdlGender","kind":"typeIdentifier","text":"MdlGender"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eyeColour"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hairColour"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"birthPlace"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"portraitCaptureDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageInYears"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageBirthYear"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageOverNn"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTAgeOverNnEntry","kind":"typeIdentifier","text":"AgeOverNnEntry"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"issuingJurisdiction"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nationality"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentCity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentState"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentPostalCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentCountry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlBiometricTemplate","kind":"typeIdentifier","text":"MdlBiometricTemplate"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"familyNameNationalCharacter"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"givenNameNationalCharacter"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureUsualMark"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"}],"url":"\/documentation\/mdlholdersdk\/mdldocument\/init(familyname:givenname:birthdate:issuedate:expirydate:issuingcountry:issuingauthority:documentnumber:portrait:drivingprivileges:undistinguishingsign:holderidnumber:bloodgroup:dlissuedate:dlexpirydate:drivingrestrictions:administrativenum-1g6bl","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","title":"init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/portraitCaptureDate":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/portraitCaptureDate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portraitCaptureDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdldocument\/portraitcapturedate","role":"symbol","navigatorTitle":[{"text":"portraitCaptureDate","kind":"identifier"}],"abstract":[{"type":"text","text":"Date when portrait was taken."}],"title":"portraitCaptureDate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/givenName":{"abstract":[{"type":"text","text":"First name(s), other name(s), or secondary identifier, of the mDL holder."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"givenName"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"givenName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/givenName","title":"givenName","url":"\/documentation\/mdlholdersdk\/mdldocument\/givenname"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/familyNameNationalCharacter":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"familyNameNationalCharacter"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"familyNameNationalCharacter"}],"url":"\/documentation\/mdlholdersdk\/mdldocument\/familynamenationalcharacter","abstract":[{"text":"The family name of the mDL holder using full UTF-8 character set.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/familyNameNationalCharacter","title":"familyNameNationalCharacter","kind":"symbol","type":"topic","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/documentNumber":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":"The number assigned or calculated by the issuing authority."}],"title":"documentNumber","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentNumber"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/documentNumber","url":"\/documentation\/mdlholdersdk\/mdldocument\/documentnumber"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/residentPostalCode":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentPostalCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentPostalCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdldocument\/residentpostalcode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"residentPostalCode"}],"abstract":[{"type":"text","text":"The postal code of the mDL holder."}],"title":"residentPostalCode"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/holderIdNumber":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"holderIdNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"text":"mDL holder’s national ID or alien ID, or diplomatic ID","type":"text"}],"title":"holderIdNumber","role":"symbol","navigatorTitle":[{"text":"holderIdNumber","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/holderIdNumber","url":"\/documentation\/mdlholdersdk\/mdldocument\/holderidnumber"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/signatureUsualMark":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/signatureUsualMark","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureUsualMark"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdldocument\/signatureusualmark","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"signatureUsualMark"}],"abstract":[{"type":"text","text":"Image of the signature or usual mark of the mDL holder."}],"title":"signatureUsualMark"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/birthPlace":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"birthPlace","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"Country and municipality or state\/province where the mDL holder was born.","type":"text"}],"title":"birthPlace","role":"symbol","navigatorTitle":[{"text":"birthPlace","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/birthPlace","url":"\/documentation\/mdlholdersdk\/mdldocument\/birthplace"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/bloodGroup":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bloodGroup","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"mDL holder’s blood group"}],"title":"bloodGroup","role":"symbol","navigatorTitle":[{"text":"bloodGroup","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/bloodGroup","url":"\/documentation\/mdlholdersdk\/mdldocument\/bloodgroup"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/weight":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/weight","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"weight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdldocument\/weight","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"weight"}],"abstract":[{"type":"text","text":"mDL holder’s weigth in kilograms."}],"title":"weight"},"doc://com.xinfotech.mdlholder/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder":{"abstract":[{"type":"text","text":"Main class of the SDK"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlHolder"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolder"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder","url":"\/documentation\/mdlholdersdk\/mdlholder","title":"MdlHolder"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/dlIssueDate":{"abstract":[{"text":"Date of issue of eDL (physical document) issued to mDL holder","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dlIssueDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"type":"topic","title":"dlIssueDate","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/dlIssueDate","navigatorTitle":[{"text":"dlIssueDate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdldocument\/dlissuedate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/residentAddress":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Permanent place of residence. The place where the mDL holder resides and\/or may be contacted (street\/house number, municipality etc.)."}],"title":"residentAddress","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"residentAddress"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentAddress","url":"\/documentation\/mdlholdersdk\/mdldocument\/residentaddress"},"doc://com.xinfotech.mdlholder/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ"},"doc://com.xinfotech.mdlholder/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/nationality":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"nationality","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"text":"Nationality of the mDL holder as two letter country code.","type":"text"}],"title":"nationality","role":"symbol","navigatorTitle":[{"text":"nationality","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/nationality","url":"\/documentation\/mdlholdersdk\/mdldocument\/nationality"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/ageBirthYear":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ageBirthYear","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The year when the mDL holder was born.  Age attestation: In what year where you born?"}],"title":"ageBirthYear","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ageBirthYear"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/ageBirthYear","url":"\/documentation\/mdlholdersdk\/mdldocument\/agebirthyear"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/biometricTemplateXx":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/biometricTemplateXx","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlBiometricTemplate","kind":"typeIdentifier","text":"MdlBiometricTemplate"},{"kind":"text","text":"]?"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdldocument\/biometrictemplatexx","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"biometricTemplateXx"}],"abstract":[],"title":"biometricTemplateXx"},"doc://com.xinfotech.mdlholder/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/dlExpiryDate":{"abstract":[{"text":"Date of expiry of eDL (physical document) issued to mDL holder","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"dlExpiryDate","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dlExpiryDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/dlExpiryDate","title":"dlExpiryDate","url":"\/documentation\/mdlholdersdk\/mdldocument\/dlexpirydate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/eyeColour":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeColour","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"mDL holder’s eye colour. The value shall be one of the following: “black”, “blue”, “brown”, “dichromatic”, “grey”, “green”, “hazel”, “maroon”, “pink”, “unknown”."}],"title":"eyeColour","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"eyeColour"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/eyeColour","url":"\/documentation\/mdlholdersdk\/mdldocument\/eyecolour"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/residentState":{"abstract":[{"type":"text","text":"The state\/province\/district where the mDL holder lives."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"residentState"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"type":"topic","title":"residentState","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentState","navigatorTitle":[{"text":"residentState","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdldocument\/residentstate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/issuingAuthority":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingAuthority","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"Issuing authority name.","type":"text"}],"title":"issuingAuthority","role":"symbol","navigatorTitle":[{"text":"issuingAuthority","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/issuingAuthority","url":"\/documentation\/mdlholdersdk\/mdldocument\/issuingauthority"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/unDistinguishingSign":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unDistinguishingSign","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"UN Distinguishing sign.","type":"text"}],"title":"unDistinguishingSign","role":"symbol","navigatorTitle":[{"text":"unDistinguishingSign","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/unDistinguishingSign","url":"\/documentation\/mdlholdersdk\/mdldocument\/undistinguishingsign"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/residentCity":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentCity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"The city where the mDL holder lives.","type":"text"}],"title":"residentCity","role":"symbol","navigatorTitle":[{"text":"residentCity","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentCity","url":"\/documentation\/mdlholdersdk\/mdldocument\/residentcity"},"doc://com.xinfotech.mdlholder/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/drivingRestrictions":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drivingRestrictions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Driver’s restrictions"}],"title":"drivingRestrictions","role":"symbol","navigatorTitle":[{"text":"drivingRestrictions","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/drivingRestrictions","url":"\/documentation\/mdlholdersdk\/mdldocument\/drivingrestrictions"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/residentCountry":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentCountry","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The country where the mDL holder lives as the two letter country code."}],"title":"residentCountry","role":"symbol","navigatorTitle":[{"text":"residentCountry","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentCountry","url":"\/documentation\/mdlholdersdk\/mdldocument\/residentcountry"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/birthDate":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"}],"abstract":[{"type":"text","text":"Day, month and year on which the mDL holder was born. If unknown, approximate date of birth."}],"title":"birthDate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"birthDate"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/birthDate","url":"\/documentation\/mdlholdersdk\/mdldocument\/birthdate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/drivingPrivileges":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drivingPrivileges","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivileges","text":"MdlDrivingPrivileges","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Driving privileges of the mDL holder. Categories of vehicles\/restrictions\/conditions. (zero or more)"}],"title":"drivingPrivileges","role":"symbol","navigatorTitle":[{"text":"drivingPrivileges","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/drivingPrivileges","url":"\/documentation\/mdlholdersdk\/mdldocument\/drivingprivileges"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/ageInYears":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/ageInYears","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageInYears"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdldocument\/ageinyears","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ageInYears"}],"abstract":[{"text":"The age of the mDL holder.  Age attestation: How old are you (in years)?","type":"text"}],"title":"ageInYears"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/hairColour":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hairColour","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"hairColour","kind":"identifier"}],"url":"\/documentation\/mdlholdersdk\/mdldocument\/haircolour","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/hairColour","abstract":[{"type":"text","text":"mDL holder’s hair colour. One of these values: “bald”, “black”, “blond”, “brown”, “grey”, “red”, “auburn”, “sandy”, “white”, “unknown”."}],"kind":"symbol","title":"hairColour","type":"topic","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","title":"MdlDocument","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdldocument"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/portrait":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"portrait","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"abstract":[{"text":"A reproduction of the mDL holder’s portrait.","type":"text"}],"title":"portrait","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"portrait"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/portrait","url":"\/documentation\/mdlholdersdk\/mdldocument\/portrait"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/administrativeNumber":{"abstract":[{"type":"text","text":"An audit control number assignet by the issuing authority."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"administrativeNumber","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"administrativeNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/administrativeNumber","url":"\/documentation\/mdlholdersdk\/mdldocument\/administrativenumber","title":"administrativeNumber"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolderDelegate"}],"abstract":[{"text":"Delivers events from the ","type":"text"},{"type":"codeVoice","code":"MdlHolder"},{"type":"text","text":" during the mDL document sharing lifecycle."}],"title":"MdlHolderDelegate","role":"symbol","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocumentField":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocumentField","kind":"identifier"}],"abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}],"title":"MdlDocumentField","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocumentField","url":"\/documentation\/mdlholdersdk\/mdldocumentfield"},"doc://com.xinfotech.mdlholder/SH":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/issuingCountry":{"abstract":[{"type":"text","text":"Alpha-2 country code of the issuing authority’s country or territory."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"issuingCountry","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingCountry","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/issuingCountry","url":"\/documentation\/mdlholdersdk\/mdldocument\/issuingcountry","title":"issuingCountry"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/expiryDate":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"expiryDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"abstract":[{"text":"Date when mDL expires.","type":"text"}],"title":"expiryDate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"expiryDate"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/expiryDate","url":"\/documentation\/mdlholdersdk\/mdldocument\/expirydate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument/familyName":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"familyName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Last name, surname or primary identifier, of the mDL holder."}],"title":"familyName","role":"symbol","navigatorTitle":[{"text":"familyName","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/familyName","url":"\/documentation\/mdlholdersdk\/mdldocument\/familyname"},"doc://com.xinfotech.mdlholder/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"introducedAt":"14.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false},{"introducedAt":"14.0","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"XTMdlDocument"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/administrativeNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/ageBirthYear","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/ageInYears","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/ageOverNn","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/biometricTemplateXx","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/birthDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/birthPlace","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/bloodGroup","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/dlExpiryDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/dlIssueDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/documentNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/drivingPrivileges","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/drivingRestrictions","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/expiryDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/eyeColour","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/familyName","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/familyNameNationalCharacter","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/givenName","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/givenNameNationalCharacter","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/hairColour","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/height","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/holderIdNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/issueDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/issuingAuthority","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/issuingCountry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/issuingJurisdiction","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/nationality","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/portrait","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/portraitCaptureDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentAddress","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentCity","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentCountry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentPostalCode","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/residentState","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/sex","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/signatureUsualMark","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/unDistinguishingSign","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/weight"],"generated":true,"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Main-Classes","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocumentField","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate"],"title":"Main Classes"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlDocument"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1issuingJurisdiction\/title","value":"issuingJurisdiction"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1issuingJurisdiction\/fragments","op":"replace","value":[{"text":"issuingJurisdiction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1givenNameNationalCharacter\/title","op":"replace","value":"givenNameNationalCharacter"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1givenNameNationalCharacter\/fragments","op":"replace","value":[{"text":"givenNameNationalCharacter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1height\/title","op":"replace","value":"height"},{"value":[{"kind":"identifier","text":"height"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1height\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1sex\/title","op":"replace","value":"sex"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1sex\/fragments","op":"replace","value":[{"kind":"identifier","text":"sex"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1ageOverNn\/title","op":"replace","value":"ageOverNn"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1ageOverNn\/fragments","op":"replace","value":[{"text":"ageOverNn","kind":"identifier"}]},{"op":"replace","value":"issueDate","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1issueDate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1issueDate\/fragments","value":[{"kind":"identifier","text":"issueDate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/title","value":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","kind":"identifier"}],"op":"replace"},{"value":"portraitCaptureDate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1portraitCaptureDate\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1portraitCaptureDate\/fragments","value":[{"kind":"identifier","text":"portraitCaptureDate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1givenName\/title","value":"givenName","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1givenName\/fragments","value":[{"kind":"identifier","text":"givenName"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1familyNameNationalCharacter\/title","value":"familyNameNationalCharacter","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1familyNameNationalCharacter\/fragments","value":[{"kind":"identifier","text":"familyNameNationalCharacter"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1documentNumber\/title","value":"documentNumber","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1documentNumber\/fragments","value":[{"kind":"identifier","text":"documentNumber"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1residentPostalCode\/title","value":"residentPostalCode","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1residentPostalCode\/fragments","value":[{"kind":"identifier","text":"residentPostalCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1holderIdNumber\/title","value":"holderIdNumber","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1holderIdNumber\/fragments","value":[{"text":"holderIdNumber","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1signatureUsualMark\/title","value":"signatureUsualMark","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1signatureUsualMark\/fragments","value":[{"kind":"identifier","text":"signatureUsualMark"}]},{"op":"replace","value":"birthPlace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1birthPlace\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1birthPlace\/fragments","value":[{"kind":"identifier","text":"birthPlace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1bloodGroup\/title","value":"bloodGroup"},{"op":"replace","value":[{"text":"bloodGroup","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1bloodGroup\/fragments"},{"op":"replace","value":"weight","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1weight\/title"},{"op":"replace","value":[{"kind":"identifier","text":"weight"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1weight\/fragments"},{"op":"replace","value":"XTMdlHolder","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/title"},{"op":"replace","value":[{"text":"XTMdlHolder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/navigatorTitle","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1dlIssueDate\/title","value":"dlIssueDate"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1dlIssueDate\/fragments","value":[{"text":"dlIssueDate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1residentAddress\/title","value":"residentAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1residentAddress\/fragments","value":[{"kind":"identifier","text":"residentAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1nationality\/title","value":"nationality"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1nationality\/fragments","op":"replace","value":[{"text":"nationality","kind":"identifier"}]},{"value":"ageBirthYear","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1ageBirthYear\/title"},{"value":[{"text":"ageBirthYear","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1ageBirthYear\/fragments"},{"value":"biometricTemplateXx","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1biometricTemplateXx\/title"},{"value":[{"text":"biometricTemplateXx","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1biometricTemplateXx\/fragments"},{"value":"dlExpiryDate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1dlExpiryDate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1dlExpiryDate\/fragments","value":[{"kind":"identifier","text":"dlExpiryDate"}]},{"value":"eyeColour","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1eyeColour\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1eyeColour\/fragments","value":[{"text":"eyeColour","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1residentState\/title","value":"residentState"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1residentState\/fragments","op":"replace","value":[{"kind":"identifier","text":"residentState"}]},{"value":"issuingAuthority","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1issuingAuthority\/title"},{"value":[{"text":"issuingAuthority","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1issuingAuthority\/fragments"},{"value":"unDistinguishingSign","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1unDistinguishingSign\/title"},{"value":[{"kind":"identifier","text":"unDistinguishingSign"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1unDistinguishingSign\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1residentCity\/title","value":"residentCity"},{"value":[{"text":"residentCity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1residentCity\/fragments"},{"value":"drivingRestrictions","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1drivingRestrictions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"drivingRestrictions"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1drivingRestrictions\/fragments"},{"op":"replace","value":"residentCountry","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1residentCountry\/title"},{"op":"replace","value":[{"kind":"identifier","text":"residentCountry"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1residentCountry\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1birthDate\/title","value":"birthDate"},{"op":"replace","value":[{"kind":"identifier","text":"birthDate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1birthDate\/fragments"},{"op":"replace","value":"drivingPrivileges","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1drivingPrivileges\/title"},{"value":[{"kind":"identifier","text":"drivingPrivileges"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1drivingPrivileges\/fragments","op":"replace"},{"value":"ageInYears","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1ageInYears\/title","op":"replace"},{"value":[{"text":"ageInYears","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1ageInYears\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1hairColour\/title","op":"replace","value":"hairColour"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1hairColour\/fragments","op":"replace","value":[{"text":"hairColour","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/title","op":"replace","value":"XTMdlDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/fragments","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1portrait\/title","op":"replace","value":"portrait"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1portrait\/fragments","op":"replace","value":[{"text":"portrait","kind":"identifier"}]},{"value":"administrativeNumber","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1administrativeNumber\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1administrativeNumber\/fragments","op":"replace","value":[{"kind":"identifier","text":"administrativeNumber"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/title","op":"replace","value":"XTMdlHolderDelegate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField\/title","op":"replace","value":"XTMdlDocumentField"},{"value":[{"text":"XTMdlDocumentField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocumentField"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField\/navigatorTitle"},{"value":"issuingCountry","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1issuingCountry\/title","op":"replace"},{"op":"replace","value":[{"text":"issuingCountry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1issuingCountry\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1expiryDate\/title","value":"expiryDate"},{"op":"replace","value":[{"text":"expiryDate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1expiryDate\/fragments"},{"value":"familyName","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1familyName\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"familyName"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument~1familyName\/fragments"}]}]}