{"abstract":[{"text":"Delivers events from the ","type":"text"},{"code":"MdlHolder","type":"codeVoice"},{"type":"text","text":" during the mDL document sharing lifecycle."}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDataTransferProgress(transfered:total:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDidReceiveError(_:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDocumentDidSent()"],"anchor":"Instance-Methods","title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(XTMdlHolderDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolderDelegate"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"inlineContent":[{"text":"Methods in this protocol notify your app about incoming field requests, errors, connection status changes,","type":"text"},{"text":" ","type":"text"},{"text":"transfer progress, and completion of document transmission.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate"},"metadata":{"modules":[{"name":"MdlHolderSdk"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolderDelegate","kind":"identifier"}],"title":"MdlHolderDelegate","externalID":"c:@M@MdlHolderSdk@objc(pl)XTMdlHolderDelegate","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"MdlHolderDelegate"}],"roleHeading":"Protocol","platforms":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"14.0","deprecated":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"14.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"14.0","deprecated":false}]},"seeAlsoSections":[{"title":"Main Classes","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocumentField"],"anchor":"Main-Classes","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdlholderdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdlholderdelegate"]}],"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolderDelegate"}],"abstract":[{"text":"Delivers events from the ","type":"text"},{"type":"codeVoice","code":"MdlHolder"},{"type":"text","text":" during the mDL document sharing lifecycle."}],"title":"MdlHolderDelegate","role":"symbol","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder":{"abstract":[{"type":"text","text":"Main class of the SDK"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlHolder"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolder"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder","url":"\/documentation\/mdlholdersdk\/mdlholder","title":"MdlHolder"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","title":"MdlDocument","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdldocument"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate/mdlHolderDidReceiveRequestedFields(_:)":{"abstract":[{"type":"text","text":"Called when the Reader requests specific document fields."}],"type":"topic","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDidReceiveRequestedFields","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"},{"kind":"text","text":"])"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderdidreceiverequestedfields(_:)","title":"mdlHolderDidReceiveRequestedFields(_:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocumentField":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocumentField","kind":"identifier"}],"abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}],"title":"MdlDocumentField","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocumentField","url":"\/documentation\/mdlholdersdk\/mdldocumentfield"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate/mdlHolderDocumentDidSent()":{"abstract":[{"type":"emphasis","inlineContent":[{"type":"text","text":"(Optional)"}]},{"type":"text","text":" Indicates that the document has been fully sent to the Reader."}],"required":true,"defaultImplementations":1,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDocumentDidSent","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","title":"mdlHolderDocumentDidSent()","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDocumentDidSent()","navigatorTitle":[{"text":"mdlHolderDocumentDidSent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderdocumentdidsent()"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate/mdlHolderDidReceiveError(_:)":{"required":true,"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDidReceiveError(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mdlHolderDidReceiveError"},{"text":"(","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderdidreceiveerror(_:)","role":"symbol","navigatorTitle":[{"text":"mdlHolderDidReceiveError:","kind":"identifier"}],"abstract":[{"text":"Called when an error occurs in the sharing workflow.","type":"text"}],"title":"mdlHolderDidReceiveError(_:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate/mdlHolderConnectionStatusChanged(isReaderConnected:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isReaderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:","kind":"identifier"}],"url":"\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)","abstract":[{"inlineContent":[{"text":"(Optional)","type":"text"}],"type":"emphasis"},{"text":" Notifies about a change in the connection status to the Reader.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)","title":"mdlHolderConnectionStatusChanged(isReaderConnected:)","kind":"symbol","required":true,"defaultImplementations":1,"type":"topic","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate/mdlHolderDataTransferProgress(transfered:total:)":{"abstract":[{"type":"emphasis","inlineContent":[{"text":"(Optional)","type":"text"}]},{"type":"text","text":" Reports the progress of data transfer to the Reader."}],"type":"topic","required":true,"role":"symbol","navigatorTitle":[{"text":"mdlHolderDataTransferProgressWithTransfered:total:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDataTransferProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"transfered","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"total","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDataTransferProgress(transfered:total:)","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderdatatransferprogress(transfered:total:)","title":"mdlHolderDataTransferProgress(transfered:total:)","defaultImplementations":1}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false}]},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"XTMdlHolderDelegate"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDataTransferProgress(transfered:total:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDidReceiveError(_:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDocumentDidSent()"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Main Classes","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocumentField"],"anchor":"Main-Classes","generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"XTMdlHolderDelegate","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","value":"XTMdlHolderDelegate","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/fragments","op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/navigatorTitle","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/title","value":"XTMdlHolder"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/fragments","value":[{"text":"XTMdlHolder","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlHolder"}]},{"op":"replace","value":"XTMdlDocument","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/fragments","value":[{"text":"XTMdlDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/navigatorTitle","value":[{"text":"XTMdlDocument","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/title","value":"mdlHolderDidReceiveRequestedFields:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField\/title","value":"XTMdlDocumentField"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField\/fragments","value":[{"text":"XTMdlDocumentField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField\/navigatorTitle","value":[{"text":"XTMdlDocumentField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderDocumentDidSent()\/title","value":"mdlHolderDocumentDidSent"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderDocumentDidSent()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mdlHolderDocumentDidSent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderDidReceiveError(_:)\/title","value":"mdlHolderDidReceiveError:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderDidReceiveError(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mdlHolderDidReceiveError:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderConnectionStatusChanged(isReaderConnected:)\/title","value":"mdlHolderConnectionStatusChangedWithIsReaderConnected:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderConnectionStatusChanged(isReaderConnected:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderDataTransferProgress(transfered:total:)\/title","value":"mdlHolderDataTransferProgressWithTransfered:total:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderDataTransferProgress(transfered:total:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mdlHolderDataTransferProgressWithTransfered:total:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}