{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Main class of the SDK","type":"text"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/mdlDocument"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/approveDocumentSharing()","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/initialize()","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/initialize(completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/loadDocumentWith(token:pin:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/loadDocumentWith(token:pin:completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/rejectDocumentSharing()","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/removeDocument()","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/startDocumentSharing(withPin:delegate:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/startDocumentSharing(withPin:delegate:completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/updateRootCertificates()","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/updateRootCertificates(completion:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/sdkVersion","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/shared"],"anchor":"Type-Properties","title":"Type Properties"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocumentField","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate"],"anchor":"Main-Classes","title":"Main Classes"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(XTMdlHolder) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolder"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"MdlHolder","kind":"identifier"}],"role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolder","kind":"identifier"}],"externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlHolder","platforms":[{"deprecated":false,"introducedAt":"14.0","unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"name":"Mac Catalyst","beta":false}],"title":"MdlHolder","symbolKind":"class","modules":[{"name":"MdlHolderSdk"}]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdlholder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdlholder"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH"],"type":"conformsTo","title":"Conforms To"}],"sections":[],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/updateRootCertificates(completion:)":{"abstract":[{"type":"text","text":"Downloads CA Root certificates and updates them in the local SDK storage"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"updateRootCertificatesWithCompletion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateRootCertificates","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/updateRootCertificates(completion:)","title":"updateRootCertificates(completion:)","url":"\/documentation\/mdlholdersdk\/mdlholder\/updaterootcertificates(completion:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/approveDocumentSharing()":{"abstract":[{"text":"This method sends the requested document fields to the reader.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"approveDocumentSharing","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"approveDocumentSharing"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/approveDocumentSharing()","url":"\/documentation\/mdlholdersdk\/mdlholder\/approvedocumentsharing()","title":"approveDocumentSharing()"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/shared":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlHolder","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlHolder"}],"abstract":[{"text":"The shared framework instance","type":"text"}],"title":"shared","role":"symbol","navigatorTitle":[{"text":"shared","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/shared","url":"\/documentation\/mdlholdersdk\/mdlholder\/shared"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder":{"abstract":[{"type":"text","text":"Main class of the SDK"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlHolder"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolder"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder","url":"\/documentation\/mdlholdersdk\/mdlholder","title":"MdlHolder"},"doc://com.xinfotech.mdlholder/objc(pl)NSObject":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.xinfotech.mdlholder/objc(cs)NSObject":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.xinfotech.mdlholder/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/initialize(completion:)":{"abstract":[{"type":"text","text":"SDK initialization"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"initializeWithCompletion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/initialize(completion:)","url":"\/documentation\/mdlholdersdk\/mdlholder\/initialize(completion:)","title":"initialize(completion:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/startDocumentSharing(withPin:delegate:completion:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDocumentSharing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPin"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(pl)XTMdlHolderDelegate","kind":"typeIdentifier","text":"MdlHolderDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"qrString"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Starts the mDL document sharing session initiated via QR engagement."}],"title":"startDocumentSharing(withPin:delegate:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startDocumentSharingWithPin:delegate:completion:"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/startDocumentSharing(withPin:delegate:completion:)","url":"\/documentation\/mdlholdersdk\/mdlholder\/startdocumentsharing(withpin:delegate:completion:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/XTMdlHolder/init":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"abstract":[],"title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/XTMdlHolder\/init","url":"\/documentation\/mdlholdersdk\/xtmdlholder\/init"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolderDelegate"}],"abstract":[{"text":"Delivers events from the ","type":"text"},{"type":"codeVoice","code":"MdlHolder"},{"type":"text","text":" during the mDL document sharing lifecycle."}],"title":"MdlHolderDelegate","role":"symbol","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/loadDocumentWith(token:pin:completion:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadDocumentWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"text":"Loads the mDL document to the SDK’s secure storage.","type":"text"}],"title":"loadDocumentWith(token:pin:completion:)","role":"symbol","navigatorTitle":[{"text":"loadDocumentWithToken:pin:completion:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/loadDocumentWith(token:pin:completion:)","url":"\/documentation\/mdlholdersdk\/mdlholder\/loaddocumentwith(token:pin:completion:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/loadDocumentWith(token:pin:)":{"abstract":[{"type":"text","text":"Loads the mDL document to the SDK’s secure storage."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadDocumentWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"loadDocumentWith(token:pin:)","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/loadDocumentWith(token:pin:)","kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdlholder\/loaddocumentwith(token:pin:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/sdkVersion":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"Framework version"}],"title":"sdkVersion","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sdkVersion"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/sdkVersion","url":"\/documentation\/mdlholdersdk\/mdlholder\/sdkversion"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/rejectDocumentSharing()":{"abstract":[{"text":"This method rejects the document request.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rejectDocumentSharing"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rejectDocumentSharing"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/rejectDocumentSharing()","title":"rejectDocumentSharing()","url":"\/documentation\/mdlholdersdk\/mdlholder\/rejectdocumentsharing()"},"doc://com.xinfotech.mdlholder/SQ":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/mdlDocument":{"abstract":[{"text":"Returns the entire mDL document from the local  SDK storage or nil if document missing","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"mdlDocument","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlDocument","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDocument"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/mdlDocument","url":"\/documentation\/mdlholdersdk\/mdlholder\/mdldocument","title":"mdlDocument"},"doc://com.xinfotech.mdlholder/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.xinfotech.mdlholder/SH":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.xinfotech.mdlholder/s7CVarArgP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/initialize()":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"SDK initialization"}],"title":"initialize()","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/initialize()","url":"\/documentation\/mdlholdersdk\/mdlholder\/initialize()"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","title":"MdlDocument","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdldocument"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDocumentField":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocumentField","kind":"identifier"}],"abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}],"title":"MdlDocumentField","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocumentField","url":"\/documentation\/mdlholdersdk\/mdldocumentfield"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/startDocumentSharing(withPin:delegate:)":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/startDocumentSharing(withPin:delegate:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDocumentSharing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPin","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(pl)XTMdlHolderDelegate","text":"MdlHolderDelegate"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdlholder\/startdocumentsharing(withpin:delegate:)","role":"symbol","abstract":[{"text":"Starts the mDL document sharing session initiated via QR engagement.","type":"text"}],"title":"startDocumentSharing(withPin:delegate:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/updateRootCertificates()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateRootCertificates","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Downloads CA Root certificates and updates them in the local SDK storage."}],"title":"updateRootCertificates()","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/updateRootCertificates()","url":"\/documentation\/mdlholdersdk\/mdlholder\/updaterootcertificates()"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/removeDocument()":{"abstract":[{"type":"text","text":"Deletes a document and all associated data from the local SDK storage."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeDocument","kind":"identifier"},{"text":"()","kind":"text"}],"title":"removeDocument()","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/removeDocument()","navigatorTitle":[{"kind":"identifier","text":"removeDocument"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdlholder\/removedocument()"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"replace","value":[{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"introducedAt":"14.0","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"XTMdlHolder"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/mdlDocument"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/approveDocumentSharing()","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/initialize(completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/loadDocumentWith(token:pin:completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/rejectDocumentSharing()","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/removeDocument()","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/startDocumentSharing(withPin:delegate:completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/updateRootCertificates(completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/XTMdlHolder\/init"],"generated":true},{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/sdkVersion","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/shared"],"anchor":"Type-Properties","generated":true,"title":"Type Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocument","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDocumentField","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate"],"anchor":"Main-Classes","generated":true,"title":"Main Classes"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"XTMdlHolder","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1updateRootCertificates(completion:)\/title","op":"replace","value":"updateRootCertificatesWithCompletion:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1updateRootCertificates(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateRootCertificatesWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1approveDocumentSharing()\/title","value":"approveDocumentSharing"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1approveDocumentSharing()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"approveDocumentSharing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/title","value":"XTMdlHolder"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/fragments","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/navigatorTitle","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1initialize(completion:)\/title","value":"initializeWithCompletion:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1initialize(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initializeWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1startDocumentSharing(withPin:delegate:completion:)\/title","value":"startDocumentSharingWithPin:delegate:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1startDocumentSharing(withPin:delegate:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"startDocumentSharingWithPin:delegate:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/title","value":"XTMdlHolderDelegate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/fragments","op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/navigatorTitle","op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1loadDocumentWith(token:pin:completion:)\/title","op":"replace","value":"loadDocumentWithToken:pin:completion:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1loadDocumentWith(token:pin:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loadDocumentWithToken:pin:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1sdkVersion\/title","value":"sdkVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1sdkVersion\/fragments","value":[{"kind":"identifier","text":"sdkVersion"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1rejectDocumentSharing()\/title","value":"rejectDocumentSharing","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1rejectDocumentSharing()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rejectDocumentSharing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1mdlDocument\/title","value":"mdlDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1mdlDocument\/fragments","value":[{"text":"mdlDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/title","op":"replace","value":"XTMdlDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/fragments","value":[{"text":"XTMdlDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField\/title","op":"replace","value":"XTMdlDocumentField"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField\/fragments","op":"replace","value":[{"text":"XTMdlDocumentField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDocumentField\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocumentField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1removeDocument()\/title","value":"removeDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1removeDocument()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"removeDocument","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}