{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivileges\/init(drivingPrivileges:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"drivingPrivileges"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilege","text":"MdlDrivingPrivilege","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilege"},{"text":"])","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An array of "},{"code":"MdlDrivingPrivilege","type":"codeVoice"},{"type":"text","text":" instances."}],"type":"paragraph"}],"name":"drivingPrivileges"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivileges"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"init(drivingPrivileges:)","navigatorTitle":[{"text":"initWithDrivingPrivileges:","kind":"identifier"}],"modules":[{"name":"MdlReaderSdk"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"drivingPrivileges","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilege","kind":"typeIdentifier","text":"MdlDrivingPrivilege"},{"text":"])","kind":"text"}],"platforms":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"14.0","name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"14.0","name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivileges(im)initWithDrivingPrivileges:","roleHeading":"Initializer"},"abstract":[{"text":"Initializes the container with the provided list of driving privileges.","type":"text"}],"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdldrivingprivileges\/init(drivingprivileges:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdldrivingprivileges\/init(drivingprivileges:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivileges":{"kind":"symbol","title":"MdlDrivingPrivileges","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivileges"}],"abstract":[{"type":"text","text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL)."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivileges","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivileges","url":"\/documentation\/mdlreadersdk\/mdldrivingprivileges"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilege":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilege","title":"MdlDrivingPrivilege","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilege"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"identifier"}],"abstract":[{"type":"text","text":"A data model representing a single driving privilege entry from a Mobile Driving Licence (mDL)."}],"url":"\/documentation\/mdlreadersdk\/mdldrivingprivilege","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivileges/init(drivingPrivileges:)":{"navigatorTitle":[{"text":"initWithDrivingPrivileges:","kind":"identifier"}],"kind":"symbol","title":"init(drivingPrivileges:)","url":"\/documentation\/mdlreadersdk\/mdldrivingprivileges\/init(drivingprivileges:)","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivileges\/init(drivingPrivileges:)","abstract":[{"text":"Initializes the container with the provided list of driving privileges.","type":"text"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"drivingPrivileges","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilege"},{"text":"])","kind":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"name":"iPadOS","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false}]},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithDrivingPrivileges:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDrivingPrivileges:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"text":"initWithDrivingPrivileges:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<XTMdlDrivingPrivilege *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"drivingPrivileges"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"drivingPrivileges","content":[{"inlineContent":[{"type":"text","text":"An array of "},{"code":"MdlDrivingPrivilege","type":"codeVoice"},{"type":"text","text":" instances."}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"XTMdlDrivingPrivileges","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege\/title","value":"XTMdlDrivingPrivilege"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges~1init(drivingPrivileges:)\/title","value":"initWithDrivingPrivileges:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges~1init(drivingPrivileges:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDrivingPrivileges:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}