{"sections":[],"variants":[{"paths":["\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)-9sx7"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"extendedModule":"MdlHolder","title":"mdlHolderConnectionStatusChanged(isReaderConnected:)","externalID":"s:9MdlHolder0aB8DelegatePAAE03mdlB23ConnectionStatusChanged17isReaderConnectedySb_tF","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"MdlHolder"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isReaderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isReaderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"]]},"abstract":[{"type":"text","text":"Optional. Default no-op implementation."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)-9sx7"},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","abstract":[{"text":"Main class of the SDK","type":"text"}],"kind":"symbol","url":"\/documentation\/mdlholder\/mdlholder","navigatorTitle":[{"text":"MdlHolder","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolder","kind":"identifier"}],"role":"symbol","title":"MdlHolder","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","abstract":[{"text":"Delivers events from the ","type":"text"},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","type":"reference","isActive":true},{"text":" during the mDL document sharing lifecycle.","type":"text"}],"kind":"symbol","url":"\/documentation\/mdlholder\/mdlholderdelegate","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolderDelegate","kind":"identifier"}],"role":"symbol","title":"MdlHolderDelegate","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderConnectionStatusChanged(isReaderConnected:)-9sx7":{"title":"mdlHolderConnectionStatusChanged(isReaderConnected:)","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)-9sx7","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isReaderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Optional. Default no-op implementation.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)-9sx7"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"}},"variantOverrides":[{"patch":[{"value":"XTMdlHolder","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"value":[{"text":"XTMdlHolder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle"},{"value":"XTMdlHolderDelegate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/title"},{"value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/fragments"},{"value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}