{"abstract":[{"inlineContent":[{"type":"text","text":"(Optional)"}],"type":"emphasis"},{"text":" Reports the progress of data transfer to the Reader.","type":"text"}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDataTransferProgress(transfered:total:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdatatransferprogress(transfered:total:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdatatransferprogress(transfered:total:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderDataTransferProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transfered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"total"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"transfered","content":[{"type":"paragraph","inlineContent":[{"text":"The number of bytes already sent.","type":"text"}]}]},{"name":"total","content":[{"type":"paragraph","inlineContent":[{"text":"The total number of bytes to be sent.","type":"text"}]}]}]}],"metadata":{"externalID":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate(im)mdlHolderDataTransferProgressWithTransfered:total:","symbolKind":"method","required":true,"navigatorTitle":[{"text":"mdlHolderDataTransferProgressWithTransfered:total:","kind":"identifier"}],"title":"mdlHolderDataTransferProgress(transfered:total:)","platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDataTransferProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"transfered","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"total","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"MdlHolder"}],"roleHeading":"Instance Method"},"defaultImplementationsSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDataTransferProgress(transfered:total:)-6luhs"],"title":"MdlHolderDelegate Implementations","anchor":"MdlHolderDelegate-Implementations"}],"sections":[],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","type":"topic","title":"MdlHolder","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderDataTransferProgress(transfered:total:)-6luhs":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDataTransferProgress(transfered:total:)-6luhs","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderDataTransferProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transfered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"total"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"mdlHolderDataTransferProgress(transfered:total:)","url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdatatransferprogress(transfered:total:)-6luhs","abstract":[{"type":"text","text":"Optional. Default no-op implementation."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate":{"abstract":[{"type":"text","text":"Delivers events from the "},{"type":"codeVoice","code":"MdlHolder"},{"type":"text","text":" during the mDL document sharing lifecycle."}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolderDelegate"}],"url":"\/documentation\/mdlholder\/mdlholderdelegate","title":"MdlHolderDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlHolderDelegate"}],"type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderDataTransferProgress(transfered:total:)":{"abstract":[{"inlineContent":[{"type":"text","text":"(Optional)"}],"type":"emphasis"},{"type":"text","text":" Reports the progress of data transfer to the Reader."}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDataTransferProgress(transfered:total:)","defaultImplementations":1,"type":"topic","required":true,"kind":"symbol","title":"mdlHolderDataTransferProgress(transfered:total:)","navigatorTitle":[{"kind":"identifier","text":"mdlHolderDataTransferProgressWithTransfered:total:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderDataTransferProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transfered"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"total"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdatatransferprogress(transfered:total:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"mdlHolderDataTransferProgressWithTransfered:total:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlHolderDataTransferProgressWithTransfered:total:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"mdlHolderDataTransferProgressWithTransfered:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"transfered","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"total:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"total","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"transfered","content":[{"inlineContent":[{"text":"The number of bytes already sent.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The total number of bytes to be sent.","type":"text"}]}],"name":"total"}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/title","op":"replace","value":"XTMdlHolderDelegate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/fragments","op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/navigatorTitle","op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDataTransferProgress(transfered:total:)\/title","op":"replace","value":"mdlHolderDataTransferProgressWithTransfered:total:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlHolderDataTransferProgressWithTransfered:total:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDataTransferProgress(transfered:total:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}