{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDidReceiveRequestedFields","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"fieldsRequest","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","kind":"typeIdentifier"},{"text":"])","kind":"text"}]}]},{"parameters":[{"name":"fieldsRequest","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of field identifiers requested by the Reader."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Handle this callback by deciding whether to approve or reject the request based on the fields being requested."},{"text":" ","type":"text"},{"text":"Use the appropriate APIs (e.g., ","type":"text"},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/approveDocumentSharing(completion:)","type":"reference","isActive":true},{"text":" or ","type":"text"},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/rejectDocumentSharing(completion:)","type":"reference","isActive":true},{"text":")","type":"text"},{"text":" ","type":"text"},{"text":"to respond to the Reader.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"Called when the Reader requests specific document fields.","type":"text"}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","interfaceLanguage":"swift"},"metadata":{"title":"mdlHolderDidReceiveRequestedFields(_:)","required":true,"roleHeading":"Instance Method","modules":[{"name":"MdlHolder"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDidReceiveRequestedFields","kind":"identifier"},{"text":"([","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"mdlHolderDidReceiveRequestedFields:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate(im)mdlHolderDidReceiveRequestedFields:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdidreceiverequestedfields(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdidreceiverequestedfields(_:)"]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/approveDocumentSharing(completion:)":{"title":"approveDocumentSharing(completion:)","kind":"symbol","abstract":[{"text":"This method sends the requested document fields to the reader.","type":"text"}],"url":"\/documentation\/mdlholder\/mdlholder\/approvedocumentsharing(completion:)","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/approveDocumentSharing(completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"approveDocumentSharing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"approveDocumentSharingWithCompletion:","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","abstract":[{"text":"Main class of the SDK","type":"text"}],"kind":"symbol","url":"\/documentation\/mdlholder\/mdlholder","navigatorTitle":[{"text":"MdlHolder","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolder","kind":"identifier"}],"role":"symbol","title":"MdlHolder","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/rejectDocumentSharing(completion:)":{"title":"rejectDocumentSharing(completion:)","kind":"symbol","abstract":[{"text":"This method rejects the document request.","type":"text"}],"url":"\/documentation\/mdlholder\/mdlholder\/rejectdocumentsharing(completion:)","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/rejectDocumentSharing(completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rejectDocumentSharing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"rejectDocumentSharingWithCompletion:","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"url":"\/documentation\/mdlholder\/mdlfieldidentifier","type":"topic","title":"MdlFieldIdentifier","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderDidReceiveRequestedFields(_:)":{"title":"mdlHolderDidReceiveRequestedFields(_:)","kind":"symbol","required":true,"abstract":[{"text":"Called when the Reader requests specific document fields.","type":"text"}],"url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdidreceiverequestedfields(_:)","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDidReceiveRequestedFields","kind":"identifier"},{"text":"([","kind":"text"},{"text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"mdlHolderDidReceiveRequestedFields:","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","abstract":[{"text":"Delivers events from the ","type":"text"},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","type":"reference","isActive":true},{"text":" during the mDL document sharing lifecycle.","type":"text"}],"kind":"symbol","url":"\/documentation\/mdlholder\/mdlholderdelegate","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolderDelegate","kind":"identifier"}],"role":"symbol","title":"MdlHolderDelegate","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mdlHolderDidReceiveRequestedFields:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mdlHolderDidReceiveRequestedFields:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mdlHolderDidReceiveRequestedFields:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<XTMdlFieldIdentifier *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fieldsRequest","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"fieldsRequest","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of field identifiers requested by the Reader."}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1approveDocumentSharing(completion:)\/title","op":"replace","value":"approveDocumentSharingWithCompletion:"},{"value":[{"text":"- ","kind":"text"},{"text":"approveDocumentSharingWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1approveDocumentSharing(completion:)\/fragments"},{"value":"XTMdlHolder","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title"},{"value":[{"text":"XTMdlHolder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle","op":"replace","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1rejectDocumentSharing(completion:)\/title","op":"replace","value":"rejectDocumentSharingWithCompletion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rejectDocumentSharingWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1rejectDocumentSharing(completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier"},{"op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/navigatorTitle","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/title","value":"mdlHolderDidReceiveRequestedFields:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mdlHolderDidReceiveRequestedFields:","kind":"identifier"}]},{"value":"XTMdlHolderDelegate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/title"},{"value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/fragments"},{"op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}