{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isReaderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"isReaderConnected","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the Reader is currently connected; otherwise, "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]}]}],"kind":"parameters"}],"abstract":[{"type":"emphasis","inlineContent":[{"text":"(Optional)","type":"text"}]},{"text":" Notifies about a change in the connection status to the Reader.","type":"text"}],"metadata":{"title":"mdlHolderConnectionStatusChanged(isReaderConnected:)","required":true,"modules":[{"name":"MdlHolder"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isReaderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate(im)mdlHolderConnectionStatusChangedWithIsReaderConnected:"},"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)"]}],"defaultImplementationsSections":[{"anchor":"MdlHolderDelegate-Implementations","title":"MdlHolderDelegate Implementations","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)-9sx7"]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderConnectionStatusChanged(isReaderConnected:)":{"kind":"symbol","title":"mdlHolderConnectionStatusChanged(isReaderConnected:)","required":true,"abstract":[{"type":"emphasis","inlineContent":[{"text":"(Optional)","type":"text"}]},{"text":" Notifies about a change in the connection status to the Reader.","type":"text"}],"url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isReaderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:","kind":"identifier"}],"defaultImplementations":1},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","abstract":[{"text":"Delivers events from the ","type":"text"},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","type":"reference","isActive":true},{"text":" during the mDL document sharing lifecycle.","type":"text"}],"kind":"symbol","url":"\/documentation\/mdlholder\/mdlholderdelegate","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolderDelegate","kind":"identifier"}],"role":"symbol","title":"MdlHolderDelegate","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","abstract":[{"text":"Main class of the SDK","type":"text"}],"kind":"symbol","url":"\/documentation\/mdlholder\/mdlholder","navigatorTitle":[{"text":"MdlHolder","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolder","kind":"identifier"}],"role":"symbol","title":"MdlHolder","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderConnectionStatusChanged(isReaderConnected:)-9sx7":{"title":"mdlHolderConnectionStatusChanged(isReaderConnected:)","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)-9sx7","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isReaderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Optional. Default no-op implementation.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)-9sx7"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mdlHolderConnectionStatusChangedWithIsReaderConnected:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isReaderConnected","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"true","type":"codeVoice"},{"type":"text","text":" if the Reader is currently connected; otherwise, "},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"isReaderConnected"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderConnectionStatusChanged(isReaderConnected:)\/title","value":"mdlHolderConnectionStatusChangedWithIsReaderConnected:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderConnectionStatusChanged(isReaderConnected:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/title","value":"XTMdlHolderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/fragments","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/navigatorTitle","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}],"op":"replace"},{"value":"XTMdlHolder","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments","op":"replace","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle","op":"replace","value":[{"text":"XTMdlHolder","kind":"identifier"}]}]}]}