{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"]]},"defaultImplementationsSections":[{"title":"MdlHolderDelegate Implementations","anchor":"MdlHolderDelegate-Implementations","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDocumentDidSent()-7yfdf"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDocumentDidSent","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdocumentdidsent()"]},{"paths":["\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdocumentdidsent()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"mdlHolderDocumentDidSent()","required":true,"roleHeading":"Instance Method","modules":[{"name":"MdlHolder"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mdlHolderDocumentDidSent"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mdlHolderDocumentDidSent"}],"symbolKind":"method","externalID":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate(im)mdlHolderDocumentDidSent"},"abstract":[{"inlineContent":[{"type":"text","text":"(Optional)"}],"type":"emphasis"},{"text":" Indicates that the document has been fully sent to the Reader.","type":"text"}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDocumentDidSent()","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","abstract":[{"text":"Delivers events from the ","type":"text"},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","type":"reference","isActive":true},{"text":" during the mDL document sharing lifecycle.","type":"text"}],"kind":"symbol","url":"\/documentation\/mdlholder\/mdlholderdelegate","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolderDelegate","kind":"identifier"}],"role":"symbol","title":"MdlHolderDelegate","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","abstract":[{"text":"Main class of the SDK","type":"text"}],"kind":"symbol","url":"\/documentation\/mdlholder\/mdlholder","navigatorTitle":[{"text":"MdlHolder","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolder","kind":"identifier"}],"role":"symbol","title":"MdlHolder","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderDocumentDidSent()-7yfdf":{"title":"mdlHolderDocumentDidSent()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDocumentDidSent","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Optional. Default no-op implementation."}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDocumentDidSent()-7yfdf","url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdocumentdidsent()-7yfdf","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderDocumentDidSent()":{"title":"mdlHolderDocumentDidSent()","navigatorTitle":[{"text":"mdlHolderDocumentDidSent","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdocumentdidsent()","type":"topic","kind":"symbol","defaultImplementations":1,"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDocumentDidSent","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"inlineContent":[{"type":"text","text":"(Optional)"}],"type":"emphasis"},{"text":" Indicates that the document has been fully sent to the Reader.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDocumentDidSent()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"mdlHolderDocumentDidSent"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"mdlHolderDocumentDidSent","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"mdlHolderDocumentDidSent","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/title","value":"XTMdlHolderDelegate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/navigatorTitle","op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title","op":"replace","value":"XTMdlHolder"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments","op":"replace","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle","op":"replace","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDocumentDidSent()\/title","op":"replace","value":"mdlHolderDocumentDidSent"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDocumentDidSent()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mdlHolderDocumentDidSent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}