{"metadata":{"title":"init(vehicleCategoryCode:issueDate:expiryDate:codes:)","navigatorTitle":[{"text":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:","kind":"identifier"}],"modules":[{"name":"MdlHolder"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"vehicleCategoryCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"issueDate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"codes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlDrivingPrivilegeCodes","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilegeCodes"},{"kind":"text","text":"?)"}],"externalID":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilege(im)initWithVehicleCategoryCode:issueDate:expiryDate:codes:","roleHeading":"Initializer","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilege"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vehicleCategoryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"expiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"codes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlDrivingPrivilegeCodes","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilegeCodes"},{"kind":"text","text":"? = nil)"}]}]},{"kind":"parameters","parameters":[{"name":"issueDate","content":[{"inlineContent":[{"type":"text","text":"The date the privilege was issued."}],"type":"paragraph"}]},{"name":"expiryDate","content":[{"inlineContent":[{"type":"text","text":"The date the privilege expires."}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilege\/init(vehicleCategoryCode:issueDate:expiryDate:codes:)"},"abstract":[{"text":"Initializes a new instance of ","type":"text"},{"code":"MdlDrivingPrivilege","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/mdlholder\/mdldrivingprivilege\/init(vehiclecategorycode:issuedate:expirydate:codes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdldrivingprivilege\/init(vehiclecategorycode:issuedate:expirydate:codes:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilegeCodes":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes","navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"title":"MdlDrivingPrivilegeCodes","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/mdlholder\/mdldrivingprivilegecodes","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilege/init(vehicleCategoryCode:issueDate:expiryDate:codes:)":{"abstract":[{"text":"Initializes a new instance of ","type":"text"},{"code":"MdlDrivingPrivilege","type":"codeVoice"},{"text":".","type":"text"}],"title":"init(vehicleCategoryCode:issueDate:expiryDate:codes:)","type":"topic","url":"\/documentation\/mdlholder\/mdldrivingprivilege\/init(vehiclecategorycode:issuedate:expirydate:codes:)","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilege\/init(vehicleCategoryCode:issueDate:expiryDate:codes:)","role":"symbol","navigatorTitle":[{"text":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vehicleCategoryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"codes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilegeCodes"},{"text":"?)","kind":"text"}],"kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilege":{"abstract":[{"text":"A data model representing a single driving privilege entry from a Mobile Driving Licence (mDL).","type":"text"}],"kind":"symbol","url":"\/documentation\/mdlholder\/mdldrivingprivilege","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilege","role":"symbol","navigatorTitle":[{"text":"MdlDrivingPrivilege","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"identifier"}],"title":"MdlDrivingPrivilege"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithVehicleCategoryCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"vehicleCategoryCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueDate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier","text":"NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"issueDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiryDate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier","text":"NSDate"},{"text":" *) ","kind":"text"},{"text":"expiryDate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"codes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"XTMdlDrivingPrivilegeCodes","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilegeCodes","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"codes","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The date the privilege was issued."}]}],"name":"issueDate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The date the privilege expires."}]}],"name":"expiryDate"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes\/title","value":"XTMdlDrivingPrivilegeCodes"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilege~1init(vehicleCategoryCode:issueDate:expiryDate:codes:)\/title","value":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilege~1init(vehicleCategoryCode:issueDate:expiryDate:codes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilege\/title","value":"XTMdlDrivingPrivilege"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilege\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilege\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}]}]}]}