{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Optional. Default no-op implementation.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderConnectionStatusChanged"},{"kind":"text","text":"("},{"text":"isReaderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isReaderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"externalID":"s:12MdlHolderSdk0aB8DelegatePAAE03mdlB23ConnectionStatusChanged17isReaderConnectedySb_tF","title":"mdlHolderConnectionStatusChanged(isReaderConnected:)","symbolKind":"method","extendedModule":"MdlHolderSdk","modules":[{"name":"MdlHolderSdk"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)-4x8k"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)-4x8k"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate"]]},"sections":[],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolderDelegate"}],"abstract":[{"text":"Delivers events from the ","type":"text"},{"type":"codeVoice","code":"MdlHolder"},{"type":"text","text":" during the mDL document sharing lifecycle."}],"title":"MdlHolderDelegate","role":"symbol","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate/mdlHolderConnectionStatusChanged(isReaderConnected:)-4x8k":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)-4x8k","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderConnectionStatusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isReaderConnected"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)-4x8k","role":"symbol","abstract":[{"type":"text","text":"Optional. Default no-op implementation."}],"title":"mdlHolderConnectionStatusChanged(isReaderConnected:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"XTMdlHolderDelegate","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/navigatorTitle"}]}]}