{"abstract":[{"inlineContent":[{"type":"text","text":"(Optional)"}],"type":"emphasis"},{"type":"text","text":" Notifies about a change in the connection status to the Reader."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderConnectionStatusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isReaderConnected"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"isReaderConnected","content":[{"inlineContent":[{"type":"text","text":""},{"code":"true","type":"codeVoice"},{"type":"text","text":" if the Reader is currently connected; otherwise, "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)"},"metadata":{"required":true,"platforms":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"14.0","deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"14.0","deprecated":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"14.0","deprecated":false}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isReaderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"mdlHolderConnectionStatusChanged(isReaderConnected:)","externalID":"c:@M@MdlHolderSdk@objc(pl)XTMdlHolderDelegate(im)mdlHolderConnectionStatusChangedWithIsReaderConnected:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:"}],"roleHeading":"Instance Method","modules":[{"name":"MdlHolderSdk"}]},"variants":[{"paths":["\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)"],"traits":[{"interfaceLanguage":"occ"}]}],"defaultImplementationsSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)-4x8k"],"title":"MdlHolderDelegate Implementations","anchor":"MdlHolderDelegate-Implementations"}],"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate/mdlHolderConnectionStatusChanged(isReaderConnected:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isReaderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:","kind":"identifier"}],"url":"\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)","abstract":[{"inlineContent":[{"text":"(Optional)","type":"text"}],"type":"emphasis"},{"text":" Notifies about a change in the connection status to the Reader.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)","title":"mdlHolderConnectionStatusChanged(isReaderConnected:)","kind":"symbol","required":true,"defaultImplementations":1,"type":"topic","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate/mdlHolderConnectionStatusChanged(isReaderConnected:)-4x8k":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)-4x8k","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderConnectionStatusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isReaderConnected"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)-4x8k","role":"symbol","abstract":[{"type":"text","text":"Optional. Default no-op implementation."}],"title":"mdlHolderConnectionStatusChanged(isReaderConnected:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolderDelegate"}],"abstract":[{"text":"Delivers events from the ","type":"text"},{"type":"codeVoice","code":"MdlHolder"},{"type":"text","text":" during the mDL document sharing lifecycle."}],"title":"MdlHolderDelegate","role":"symbol","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","deprecated":false},{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"mdlHolderConnectionStatusChangedWithIsReaderConnected:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isReaderConnected","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"isReaderConnected","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"true"},{"text":" if the Reader is currently connected; otherwise, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]}]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderConnectionStatusChanged(isReaderConnected:)\/title","op":"replace","value":"mdlHolderConnectionStatusChangedWithIsReaderConnected:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderConnectionStatusChanged(isReaderConnected:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/title","op":"replace","value":"XTMdlHolderDelegate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/fragments","op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/navigatorTitle","op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]}]}]}