{"abstract":[{"type":"emphasis","inlineContent":[{"type":"text","text":"(Optional)"}]},{"text":" Indicates that the document has been fully sent to the Reader.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDocumentDidSent","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDocumentDidSent()"},"metadata":{"platforms":[{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false}],"modules":[{"name":"MdlHolderSdk"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDocumentDidSent","kind":"identifier"},{"text":"()","kind":"text"}],"title":"mdlHolderDocumentDidSent()","externalID":"c:@M@MdlHolderSdk@objc(pl)XTMdlHolderDelegate(im)mdlHolderDocumentDidSent","symbolKind":"method","navigatorTitle":[{"text":"mdlHolderDocumentDidSent","kind":"identifier"}],"required":true,"roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderdocumentdidsent()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderdocumentdidsent()"]}],"defaultImplementationsSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDocumentDidSent()-395y3"],"title":"MdlHolderDelegate Implementations","anchor":"MdlHolderDelegate-Implementations"}],"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate/mdlHolderDocumentDidSent()":{"abstract":[{"type":"emphasis","inlineContent":[{"type":"text","text":"(Optional)"}]},{"type":"text","text":" Indicates that the document has been fully sent to the Reader."}],"required":true,"defaultImplementations":1,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDocumentDidSent","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","title":"mdlHolderDocumentDidSent()","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDocumentDidSent()","navigatorTitle":[{"text":"mdlHolderDocumentDidSent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderdocumentdidsent()"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate/mdlHolderDocumentDidSent()-395y3":{"abstract":[{"type":"text","text":"Optional. Default no-op implementation."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDocumentDidSent","kind":"identifier"},{"text":"()","kind":"text"}],"title":"mdlHolderDocumentDidSent()","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDocumentDidSent()-395y3","kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderdocumentdidsent()-395y3"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolderDelegate"}],"abstract":[{"text":"Delivers events from the ","type":"text"},{"type":"codeVoice","code":"MdlHolder"},{"type":"text","text":" during the mDL document sharing lifecycle."}],"title":"MdlHolderDelegate","role":"symbol","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"14.0"},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"14.0"},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"14.0"}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"mdlHolderDocumentDidSent","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"mdlHolderDocumentDidSent","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"mdlHolderDocumentDidSent","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderDocumentDidSent()\/title","value":"mdlHolderDocumentDidSent"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderDocumentDidSent()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mdlHolderDocumentDidSent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/title","op":"replace","value":"XTMdlHolderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/fragments","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/navigatorTitle","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]}]}]}