{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codes"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivilegeCode","kind":"typeIdentifier","text":"MdlDrivingPrivilegeCode"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCodes"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCodes\/init(codes:)"},"metadata":{"platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"codes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivilegeCode"},{"text":"])","kind":"text"}],"title":"init(codes:)","externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivilegeCodes(im)initWithCodes:","symbolKind":"init","navigatorTitle":[{"text":"initWithCodes:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"MdlHolderSdk"}]},"variants":[{"paths":["\/documentation\/mdlholdersdk\/mdldrivingprivilegecodes\/init(codes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholdersdk\/mdldrivingprivilegecodes\/init(codes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivilegeCodes/init(codes:)":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithCodes:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"codes","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivilegeCode","text":"MdlDrivingPrivilegeCode","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCodes\/init(codes:)","title":"init(codes:)","url":"\/documentation\/mdlholdersdk\/mdldrivingprivilegecodes\/init(codes:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivilegeCodes":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCodes","title":"MdlDrivingPrivilegeCodes","url":"\/documentation\/mdlholdersdk\/mdldrivingprivilegecodes"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivilegeCode":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdldrivingprivilegecode","role":"symbol","navigatorTitle":[{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"abstract":[],"title":"MdlDrivingPrivilegeCode"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"14.0"},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"14.0"},{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithCodes:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCodes:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCodes:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<XTMdlDrivingPrivilegeCode *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"codes","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCodes~1init(codes:)\/title","op":"replace","value":"initWithCodes:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCodes~1init(codes:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCodes:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCodes\/title","op":"replace","value":"XTMdlDrivingPrivilegeCodes"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCodes\/fragments","op":"replace","value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}]},{"value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCodes\/navigatorTitle","op":"replace"},{"value":"XTMdlDrivingPrivilegeCode","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}]}]}]}