{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","title":"value","modules":[{"name":"MdlReaderSdk"}],"platforms":[{"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"14.0"}],"externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocumentField(py)value","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"value","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdldocumentfield\/value"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/mdldocumentfield\/value"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocumentField"]]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocumentField\/value","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"The value of the field. The type depends on the context in which it is used.","type":"text"}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocumentField/value":{"navigatorTitle":[{"text":"value","kind":"identifier"}],"url":"\/documentation\/mdlreadersdk\/mdldocumentfield\/value","title":"value","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocumentField\/value","kind":"symbol","abstract":[{"text":"The value of the field. The type depends on the context in which it is used.","type":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocumentField":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/mdldocumentfield","abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MdlDocumentField","kind":"identifier"}],"title":"MdlDocumentField","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocumentField","navigatorTitle":[{"text":"MdlDocumentField","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst"}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"value","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"value"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"id"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"value","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField~1value\/title"},{"value":[{"kind":"identifier","text":"value"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField~1value\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField\/title","value":"XTMdlDocumentField","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField\/fragments","value":[{"kind":"identifier","text":"XTMdlDocumentField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField\/navigatorTitle","value":[{"text":"XTMdlDocumentField","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}