{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingPrivileges"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilege","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilege","text":"MdlDrivingPrivilege"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mdlholder\/mdldrivingprivileges\/drivingprivileges"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdldrivingprivileges\/drivingprivileges"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges\/drivingPrivileges","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges"]]},"abstract":[{"type":"text","text":"An array of "},{"code":"MdlDrivingPrivilege","type":"codeVoice"},{"type":"text","text":" objects representing individual driving privileges."}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"drivingPrivileges","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MdlDrivingPrivilege","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilege"},{"kind":"text","text":"]"}],"roleHeading":"Instance Property","externalID":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivileges(py)drivingPrivileges","modules":[{"name":"MdlHolder"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"drivingPrivileges"}],"title":"drivingPrivileges","symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivileges":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges","abstract":[{"type":"text","text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL)."}],"title":"MdlDrivingPrivileges","role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdldrivingprivileges","navigatorTitle":[{"text":"MdlDrivingPrivileges","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivileges"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlholder","title":"MdlHolder","role":"collection","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilege":{"title":"MdlDrivingPrivilege","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilege"}],"url":"\/documentation\/mdlholder\/mdldrivingprivilege","abstract":[{"text":"A data model representing a single driving privilege entry from a Mobile Driving Licence (mDL).","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivilege"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilege","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivileges/drivingPrivileges":{"url":"\/documentation\/mdlholder\/mdldrivingprivileges\/drivingprivileges","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drivingPrivileges","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilege"},{"text":"]","kind":"text"}],"abstract":[{"text":"An array of ","type":"text"},{"code":"MdlDrivingPrivilege","type":"codeVoice"},{"text":" objects representing individual driving privileges.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"drivingPrivileges","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges\/drivingPrivileges","role":"symbol","title":"drivingPrivileges"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"drivingPrivileges","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"drivingPrivileges","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"text":"NSArray<XTMdlDrivingPrivilege *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"drivingPrivileges","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges\/title","value":"XTMdlDrivingPrivileges","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilege\/title","value":"XTMdlDrivingPrivilege","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilege\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilege\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges~1drivingPrivileges\/title","value":"drivingPrivileges","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges~1drivingPrivileges\/fragments","value":[{"text":"drivingPrivileges","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}