{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField\/description"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"A string representation of the field in the format ","type":"text"},{"type":"codeVoice","code":"(identifier = value)"},{"text":".","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"modules":[{"name":"MdlHolder"}],"title":"description","symbolKind":"property","externalID":"c:@M@MdlHolder@objc(cs)XTMdlDocumentField(py)description","role":"symbol","roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/mdlholder\/mdldocumentfield\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdldocumentfield\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","title":"MdlHolder","type":"topic","url":"\/documentation\/mdlholder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocumentField":{"url":"\/documentation\/mdlholder\/mdldocumentfield","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlDocumentField"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"title":"MdlDocumentField","abstract":[{"type":"text","text":"Represents an mDL document field containing an identifier and a corresponding value."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocumentField/description":{"url":"\/documentation\/mdlholder\/mdldocumentfield\/description","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","abstract":[{"text":"A string representation of the field in the format ","type":"text"},{"code":"(identifier = value)","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"description","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"XTMdlDocumentField","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocumentField"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocumentField"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/navigatorTitle"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField~1description\/title"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField~1description\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}