{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField\/value","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mdlholder\/mdldocumentfield\/value"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdldocumentfield\/value"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"MdlHolder"}],"platforms":[{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"iOS"},{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"Mac Catalyst"}],"symbolKind":"property","externalID":"c:@M@MdlHolder@objc(cs)XTMdlDocumentField(py)value","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"}],"roleHeading":"Instance Property","title":"value","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"value"}]},"abstract":[{"type":"text","text":"The value of the field. The type depends on the context in which it is used."}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","type":"topic","title":"MdlHolder","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocumentField/value":{"abstract":[{"type":"text","text":"The value of the field. The type depends on the context in which it is used."}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField\/value","type":"topic","navigatorTitle":[{"kind":"identifier","text":"value"}],"title":"value","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"}],"url":"\/documentation\/mdlholder\/mdldocumentfield\/value"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocumentField":{"url":"\/documentation\/mdlholder\/mdldocumentfield","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MdlDocumentField","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"type":"topic","title":"MdlDocumentField","abstract":[{"type":"text","text":"Represents an mDL document field containing an identifier and a corresponding value."}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"iOS"},{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"Mac Catalyst"}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"value"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"value","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField~1value\/title","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField~1value\/fragments","value":[{"text":"value","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/title","value":"XTMdlDocumentField"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/fragments","value":[{"text":"XTMdlDocumentField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/navigatorTitle","value":[{"text":"XTMdlDocumentField","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}