{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"init","title":"init(rawValue:)","modules":[{"name":"MdlReaderSdk"}],"platforms":[{"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false,"beta":false}],"externalID":"s:12MdlReaderSdk0A6GenderO8rawValueACSgSi_tcfc","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer"},"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdlgender\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender"]]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/init(rawValue:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlGender/init(rawValue:)":{"url":"\/documentation\/mdlreadersdk\/mdlgender\/init(rawvalue:)","title":"init(rawValue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/init(rawValue:)","kind":"symbol","abstract":[]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlGender":{"navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"url":"\/documentation\/mdlreadersdk\/mdlgender","title":"MdlGender","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"XTMdlGender","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/title","op":"replace"},{"value":[{"text":"XTMdlGender","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/fragments","op":"replace"},{"value":[{"text":"XTMdlGender","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}