{"abstract":[{"type":"text","text":"Initializes a new instance of "},{"code":"MdlDrivingPrivilege","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"vehicleCategoryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"issueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"? = nil, ","kind":"text"},{"text":"codes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivilegeCodes","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCodes","text":"MdlDrivingPrivilegeCodes","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"vehicleCategoryCode","content":[{"inlineContent":[{"text":"The category of the vehicle permitted to drive.","type":"text"}],"type":"paragraph"}]},{"name":"issueDate","content":[{"type":"paragraph","inlineContent":[{"text":"The date the privilege was issued.","type":"text"}]}]},{"name":"expiryDate","content":[{"type":"paragraph","inlineContent":[{"text":"The date the privilege expires.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Driving privilege codes"}],"type":"paragraph"}],"name":"codes"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilege"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilege\/init(vehicleCategoryCode:issueDate:expiryDate:codes:)","interfaceLanguage":"swift"},"metadata":{"platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"introducedAt":"14.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"name":"Mac Catalyst","beta":false}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"vehicleCategoryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"codes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivilegeCodes"},{"text":"?)","kind":"text"}],"title":"init(vehicleCategoryCode:issueDate:expiryDate:codes:)","externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivilege(im)initWithVehicleCategoryCode:issueDate:expiryDate:codes:","symbolKind":"init","navigatorTitle":[{"text":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"MdlHolderSdk"}]},"variants":[{"paths":["\/documentation\/mdlholdersdk\/mdldrivingprivilege\/init(vehiclecategorycode:issuedate:expirydate:codes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholdersdk\/mdldrivingprivilege\/init(vehiclecategorycode:issuedate:expirydate:codes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivilege":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivilege"}],"abstract":[{"type":"text","text":"A data model representing a single driving privilege entry from a Mobile Driving Licence (mDL)."}],"title":"MdlDrivingPrivilege","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilege"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilege","url":"\/documentation\/mdlholdersdk\/mdldrivingprivilege"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivilege/init(vehicleCategoryCode:issueDate:expiryDate:codes:)":{"abstract":[{"text":"Initializes a new instance of ","type":"text"},{"code":"MdlDrivingPrivilege","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"vehicleCategoryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"codes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivilegeCodes","text":"MdlDrivingPrivilegeCodes","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(vehicleCategoryCode:issueDate:expiryDate:codes:)","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilege\/init(vehicleCategoryCode:issueDate:expiryDate:codes:)","navigatorTitle":[{"text":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlholdersdk\/mdldrivingprivilege\/init(vehiclecategorycode:issuedate:expirydate:codes:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivilegeCodes":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCodes","title":"MdlDrivingPrivilegeCodes","url":"\/documentation\/mdlholdersdk\/mdldrivingprivilegecodes"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"14.0","deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"14.0","deprecated":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"14.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithVehicleCategoryCode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"vehicleCategoryCode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"issueDate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"},{"text":" *) ","kind":"text"},{"text":"issueDate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"expiryDate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"},{"text":" *) ","kind":"text"},{"text":"expiryDate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"codes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"XTMdlDrivingPrivilegeCodes","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCodes","preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivilegeCodes"},{"text":" *) ","kind":"text"},{"text":"codes","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"vehicleCategoryCode","content":[{"inlineContent":[{"text":"The category of the vehicle permitted to drive.","type":"text"}],"type":"paragraph"}]},{"name":"issueDate","content":[{"inlineContent":[{"text":"The date the privilege was issued.","type":"text"}],"type":"paragraph"}]},{"name":"expiryDate","content":[{"inlineContent":[{"text":"The date the privilege expires.","type":"text"}],"type":"paragraph"}]},{"name":"codes","content":[{"inlineContent":[{"text":"Driving privilege codes","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilege\/title","value":"XTMdlDrivingPrivilege"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilege\/fragments","value":[{"text":"XTMdlDrivingPrivilege","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilege\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivilege","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilege~1init(vehicleCategoryCode:issueDate:expiryDate:codes:)\/title","value":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilege~1init(vehicleCategoryCode:issueDate:expiryDate:codes:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithVehicleCategoryCode:issueDate:expiryDate:codes:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCodes\/title","value":"XTMdlDrivingPrivilegeCodes"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCodes\/fragments","value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCodes\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}