{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MdlDrivingPrivilegeCode","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCode","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilegeCode"},{"kind":"text","text":"]"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"MdlHolder"}],"symbolKind":"property","title":"codes","externalID":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilegeCodes(py)codes","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"codes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilegeCode","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilegeCode","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"codes","kind":"identifier"}]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdldrivingprivilegecodes\/codes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdldrivingprivilegecodes\/codes"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes"]]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes\/codes","interfaceLanguage":"swift"},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilegeCodes":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes","navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"title":"MdlDrivingPrivilegeCodes","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/mdlholder\/mdldrivingprivilegecodes","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilegeCodes/codes":{"abstract":[],"title":"codes","type":"topic","url":"\/documentation\/mdlholder\/mdldrivingprivilegecodes\/codes","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes\/codes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"codes"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MdlDrivingPrivilegeCode","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilegeCode"},{"kind":"text","text":"]"}],"kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilegeCode":{"type":"topic","title":"MdlDrivingPrivilegeCode","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"url":"\/documentation\/mdlholder\/mdldrivingprivilegecode","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"codes","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"codes","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<XTMdlDrivingPrivilegeCode *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"codes","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes\/title","value":"XTMdlDrivingPrivilegeCodes"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes\/fragments","value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes~1codes\/title","value":"codes"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes~1codes\/fragments","value":[{"text":"codes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode\/title","value":"XTMdlDrivingPrivilegeCode"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode\/fragments","value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}]}]}]}