{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate"]]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDidReceiveDocumentFields(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderDidReceiveDocumentFields"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MdlDocumentField","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDocumentField"},{"kind":"text","text":"])"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderdidreceivedocumentfields(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderdidreceivedocumentfields(_:)"]}],"metadata":{"externalID":"c:@M@MdlReader@objc(pl)XTMdlReaderDelegate(im)mdlReaderDidReceiveDocumentFields:","navigatorTitle":[{"kind":"identifier","text":"mdlReaderDidReceiveDocumentFields:"}],"title":"mdlReaderDidReceiveDocumentFields(_:)","modules":[{"name":"MdlReader"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderDidReceiveDocumentFields"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDocumentField","kind":"typeIdentifier","text":"MdlDocumentField"},{"kind":"text","text":"])"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate/mdlReaderDidReceiveDocumentFields(_:)":{"abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"mdlReaderDidReceiveDocumentFields:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDidReceiveDocumentFields(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderDidReceiveDocumentFields","kind":"identifier"},{"text":"([","kind":"text"},{"text":"MdlDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDocumentField"},{"text":"])","kind":"text"}],"url":"\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderdidreceivedocumentfields(_:)","title":"mdlReaderDidReceiveDocumentFields(_:)","required":true},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocumentField":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocumentfield","title":"MdlDocumentField","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocumentField"}],"navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate":{"navigatorTitle":[{"kind":"identifier","text":"MdlReaderDelegate"}],"title":"MdlReaderDelegate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlReaderDelegate"}],"url":"\/documentation\/mdlreader\/mdlreaderdelegate"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"mdlReaderDidReceiveDocumentFields:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"mdlReaderDidReceiveDocumentFields:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"mdlReaderDidReceiveDocumentFields:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<XTMdlDocumentField *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"fields","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"mdlReaderDidReceiveDocumentFields:","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderDidReceiveDocumentFields(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlReaderDidReceiveDocumentFields:"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderDidReceiveDocumentFields(_:)\/fragments"},{"value":"XTMdlDocumentField","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/title"},{"value":[{"text":"XTMdlDocumentField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocumentField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/title","value":"XTMdlReaderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/fragments","value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}