{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate"]]},"metadata":{"title":"mdlReaderConnectionStatusChanged(isHolderConnected:)","externalID":"c:@M@MdlReader@objc(pl)XTMdlReaderDelegate(im)mdlReaderConnectionStatusChangedWithIsHolderConnected:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mdlReaderConnectionStatusChanged"},{"kind":"text","text":"("},{"text":"isHolderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"mdlReaderConnectionStatusChangedWithIsHolderConnected:"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"MdlReader"}],"required":true,"role":"symbol"},"defaultImplementationsSections":[{"anchor":"MdlReaderDelegate-Implementations","title":"MdlReaderDelegate Implementations","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)-3k5an"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderConnectionStatusChanged"},{"kind":"text","text":"("},{"text":"isHolderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderconnectionstatuschanged(isholderconnected:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderconnectionstatuschanged(isholderconnected:)"]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate/mdlReaderConnectionStatusChanged(isHolderConnected:)-3k5an":{"role":"symbol","title":"mdlReaderConnectionStatusChanged(isHolderConnected:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderConnectionStatusChanged"},{"kind":"text","text":"("},{"text":"isHolderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)-3k5an","abstract":[],"url":"\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderconnectionstatuschanged(isholderconnected:)-3k5an"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate/mdlReaderConnectionStatusChanged(isHolderConnected:)":{"defaultImplementations":1,"navigatorTitle":[{"text":"mdlReaderConnectionStatusChangedWithIsHolderConnected:","kind":"identifier"}],"title":"mdlReaderConnectionStatusChanged(isHolderConnected:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderConnectionStatusChanged"},{"text":"(","kind":"text"},{"text":"isHolderConnected","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"url":"\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderconnectionstatuschanged(isholderconnected:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate":{"navigatorTitle":[{"kind":"identifier","text":"MdlReaderDelegate"}],"title":"MdlReaderDelegate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlReaderDelegate"}],"url":"\/documentation\/mdlreader\/mdlreaderdelegate"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"mdlReaderConnectionStatusChangedWithIsHolderConnected:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mdlReaderConnectionStatusChangedWithIsHolderConnected:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mdlReaderConnectionStatusChangedWithIsHolderConnected:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isHolderConnected"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"mdlReaderConnectionStatusChangedWithIsHolderConnected:","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderConnectionStatusChanged(isHolderConnected:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlReaderConnectionStatusChangedWithIsHolderConnected:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderConnectionStatusChanged(isHolderConnected:)\/fragments"},{"value":"XTMdlReaderDelegate","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/fragments","op":"replace"},{"value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/navigatorTitle","op":"replace"}]}]}