{"kind":"symbol","abstract":[{"type":"text","text":"Optional. Default no-op implementation."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)-3k5an","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"s:9MdlReader0aB8DelegatePAAE03mdlB23ConnectionStatusChanged17isHolderConnectedySb_tF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isHolderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"mdlReaderConnectionStatusChanged(isHolderConnected:)","extendedModule":"MdlReader","modules":[{"name":"MdlReader"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isHolderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderconnectionstatuschanged(isholderconnected:)-3k5an"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate/mdlReaderConnectionStatusChanged(isHolderConnected:)-3k5an":{"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)-3k5an","type":"topic","abstract":[{"text":"Optional. Default no-op implementation.","type":"text"}],"url":"\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderconnectionstatuschanged(isholderconnected:)-3k5an","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isHolderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"mdlReaderConnectionStatusChanged(isHolderConnected:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate":{"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","type":"topic","abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"type":"codeVoice","code":"MdlReader"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"url":"\/documentation\/mdlreader\/mdlreaderdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReaderDelegate","kind":"identifier"}],"title":"MdlReaderDelegate","navigatorTitle":[{"text":"MdlReaderDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"XTMdlReaderDelegate","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/title","op":"replace"},{"value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/fragments"},{"value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}