{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderDataTransferProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transfered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"total"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"transfered","content":[{"inlineContent":[{"type":"text","text":"The number of bytes already received."}],"type":"paragraph"}]},{"name":"total","content":[{"inlineContent":[{"type":"text","text":"The total number of bytes expected to be received."}],"type":"paragraph"}]}],"kind":"parameters"}],"abstract":[{"inlineContent":[{"text":"(Optional)","type":"text"}],"type":"emphasis"},{"text":" Reports the progress of data transfer from the Holder.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderdatatransferprogress(transfered:total:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderdatatransferprogress(transfered:total:)"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)"},"sections":[],"defaultImplementationsSections":[{"anchor":"MdlReaderDelegate-Implementations","title":"MdlReaderDelegate Implementations","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)-710n0"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mdlReaderDataTransferProgress","kind":"identifier"},{"kind":"text","text":"("},{"text":"transfered","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"total","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mdlReaderDataTransferProgressWithTransfered:total:","kind":"identifier"}],"title":"mdlReaderDataTransferProgress(transfered:total:)","role":"symbol","platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"iOS","beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}],"roleHeading":"Instance Method","externalID":"c:@M@MdlReader@objc(pl)XTMdlReaderDelegate(im)mdlReaderDataTransferProgressWithTransfered:total:","modules":[{"name":"MdlReader"}],"required":true,"symbolKind":"method"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate":{"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","type":"topic","abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"type":"codeVoice","code":"MdlReader"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"url":"\/documentation\/mdlreader\/mdlreaderdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReaderDelegate","kind":"identifier"}],"title":"MdlReaderDelegate","navigatorTitle":[{"text":"MdlReaderDelegate","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate/mdlReaderDataTransferProgress(transfered:total:)-710n0":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mdlReaderDataTransferProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transfered"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"total","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"mdlReaderDataTransferProgress(transfered:total:)","role":"symbol","type":"topic","url":"\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderdatatransferprogress(transfered:total:)-710n0","abstract":[{"text":"Optional. Default no-op implementation.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)-710n0","kind":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate/mdlReaderDataTransferProgress(transfered:total:)":{"title":"mdlReaderDataTransferProgress(transfered:total:)","navigatorTitle":[{"text":"mdlReaderDataTransferProgressWithTransfered:total:","kind":"identifier"}],"required":true,"kind":"symbol","abstract":[{"type":"emphasis","inlineContent":[{"type":"text","text":"(Optional)"}]},{"type":"text","text":" Reports the progress of data transfer from the Holder."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderDataTransferProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"transfered","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"total","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)","role":"symbol","defaultImplementations":1,"url":"\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderdatatransferprogress(transfered:total:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"mdlReaderDataTransferProgressWithTransfered:total:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mdlReaderDataTransferProgressWithTransfered:total:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"mdlReaderDataTransferProgressWithTransfered:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"transfered","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"total:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"total","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"transfered","content":[{"inlineContent":[{"text":"The number of bytes already received.","type":"text"}],"type":"paragraph"}]},{"name":"total","content":[{"inlineContent":[{"text":"The total number of bytes expected to be received.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/title","op":"replace","value":"XTMdlReaderDelegate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/fragments","op":"replace","value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/navigatorTitle","op":"replace","value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderDataTransferProgress(transfered:total:)\/title","op":"replace","value":"mdlReaderDataTransferProgressWithTransfered:total:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderDataTransferProgress(transfered:total:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mdlReaderDataTransferProgressWithTransfered:total:","kind":"identifier"}]}]}]}