{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate"]]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)-710n0","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderDataTransferProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transfered"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"text":"total","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderdatatransferprogress(transfered:total:)-710n0"]}],"metadata":{"role":"symbol","extendedModule":"MdlReader","externalID":"s:9MdlReader0aB8DelegatePAAE03mdlB20DataTransferProgress10transfered5totalySi_SitF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderDataTransferProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transfered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"total"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"modules":[{"name":"MdlReader"}],"title":"mdlReaderDataTransferProgress(transfered:total:)","symbolKind":"method","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate":{"navigatorTitle":[{"kind":"identifier","text":"MdlReaderDelegate"}],"title":"MdlReaderDelegate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlReaderDelegate"}],"url":"\/documentation\/mdlreader\/mdlreaderdelegate"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate/mdlReaderDataTransferProgress(transfered:total:)-710n0":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)-710n0","url":"\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderdatatransferprogress(transfered:total:)-710n0","kind":"symbol","title":"mdlReaderDataTransferProgress(transfered:total:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderDataTransferProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transfered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"total"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/title","value":"XTMdlReaderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/fragments","value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/navigatorTitle","value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}]}]}]}