{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate"]]},"abstract":[{"text":"Optional. Default no-op implementation.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isHolderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Method","externalID":"s:12MdlReaderSdk0aB8DelegatePAAE03mdlB23ConnectionStatusChanged17isHolderConnectedySb_tF","modules":[{"name":"MdlReaderSdk"}],"extendedModule":"MdlReaderSdk","title":"mdlReaderConnectionStatusChanged(isHolderConnected:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isHolderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderconnectionstatuschanged(isholderconnected:)-64b8x"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)-64b8x","interfaceLanguage":"swift"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate/mdlReaderConnectionStatusChanged(isHolderConnected:)-64b8x":{"url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderconnectionstatuschanged(isholderconnected:)-64b8x","title":"mdlReaderConnectionStatusChanged(isHolderConnected:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderConnectionStatusChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"isHolderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)-64b8x","kind":"symbol","abstract":[{"text":"Optional. Default no-op implementation.","type":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate","abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"type":"codeVoice","code":"MdlReader"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReaderDelegate","kind":"identifier"}],"title":"MdlReaderDelegate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","navigatorTitle":[{"text":"MdlReaderDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"XTMdlReaderDelegate","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/title","op":"replace"},{"value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/fragments","op":"replace"},{"value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}