{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderDataTransferProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"transfered","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"total","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderdatatransferprogress(transfered:total:)-uzzh"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate"]]},"abstract":[{"text":"Optional. Default no-op implementation.","type":"text"}],"metadata":{"extendedModule":"MdlReaderSdk","role":"symbol","modules":[{"name":"MdlReaderSdk"}],"symbolKind":"method","title":"mdlReaderDataTransferProgress(transfered:total:)","roleHeading":"Instance Method","externalID":"s:12MdlReaderSdk0aB8DelegatePAAE03mdlB20DataTransferProgress10transfered5totalySi_SitF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderDataTransferProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"transfered","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"total","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)-uzzh"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate/mdlReaderDataTransferProgress(transfered:total:)-uzzh":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderDataTransferProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"transfered","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"total","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","abstract":[{"text":"Optional. Default no-op implementation.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderdatatransferprogress(transfered:total:)-uzzh","title":"mdlReaderDataTransferProgress(transfered:total:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)-uzzh","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate","abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"type":"codeVoice","code":"MdlReader"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReaderDelegate","kind":"identifier"}],"title":"MdlReaderDelegate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","navigatorTitle":[{"text":"MdlReaderDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/title","value":"XTMdlReaderDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/fragments","value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/navigatorTitle","value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}