{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate"]]},"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderdidreceivedocumentfields(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderdidreceivedocumentfields(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Called when the Reader successfully receives document fields from the Holder.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderDidReceiveDocumentFields","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocumentField","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocumentField","text":"MdlDocumentField"},{"kind":"text","text":"])"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The array of document fields received from the Holder.","type":"text"}]}],"name":"fields"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderDidReceiveDocumentFields(_:)"},"metadata":{"modules":[{"name":"MdlReaderSdk"}],"required":true,"title":"mdlReaderDidReceiveDocumentFields(_:)","platforms":[{"name":"iOS","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false}],"navigatorTitle":[{"text":"mdlReaderDidReceiveDocumentFields:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(pl)XTMdlReaderDelegate(im)mdlReaderDidReceiveDocumentFields:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderDidReceiveDocumentFields"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocumentField","text":"MdlDocumentField"},{"text":"])","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate":{"kind":"symbol","title":"MdlReaderDelegate","navigatorTitle":[{"kind":"identifier","text":"MdlReaderDelegate"}],"abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"code":"MdlReader","type":"codeVoice"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlReaderDelegate"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocumentField":{"kind":"symbol","title":"MdlDocumentField","navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocumentField"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocumentField","url":"\/documentation\/mdlreadersdk\/mdldocumentfield"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate/mdlReaderDidReceiveDocumentFields(_:)":{"kind":"symbol","required":true,"title":"mdlReaderDidReceiveDocumentFields(_:)","navigatorTitle":[{"text":"mdlReaderDidReceiveDocumentFields:","kind":"identifier"}],"abstract":[{"text":"Called when the Reader successfully receives document fields from the Holder.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderDidReceiveDocumentFields","kind":"identifier"},{"text":"([","kind":"text"},{"text":"MdlDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocumentField"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderDidReceiveDocumentFields(_:)","url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderdidreceivedocumentfields(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"replace","value":[{"name":"iOS","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"mdlReaderDidReceiveDocumentFields:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlReaderDidReceiveDocumentFields:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"mdlReaderDidReceiveDocumentFields:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<XTMdlDocumentField *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fields"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The array of document fields received from the Holder."}]}],"name":"fields"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/title","op":"replace","value":"XTMdlReaderDelegate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField\/title","op":"replace","value":"XTMdlDocumentField"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocumentField"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocumentField"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate~1mdlReaderDidReceiveDocumentFields(_:)\/title","op":"replace","value":"mdlReaderDidReceiveDocumentFields:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate~1mdlReaderDidReceiveDocumentFields(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlReaderDidReceiveDocumentFields:"}]}]}]}