{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"emphasis","inlineContent":[{"text":"(Optional)","type":"text"}]},{"type":"text","text":" Reports the progress of data transfer from the Holder."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderDataTransferProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transfered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"total"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The number of bytes already received.","type":"text"}],"type":"paragraph"}],"name":"transfered"},{"content":[{"inlineContent":[{"text":"The total number of bytes expected to be received.","type":"text"}],"type":"paragraph"}],"name":"total"}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"MdlReaderSdk"}],"platforms":[{"name":"iOS","introducedAt":"14.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"14.0","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"14.0","beta":false,"deprecated":false,"unavailable":false}],"externalID":"c:@M@MdlReaderSdk@objc(pl)XTMdlReaderDelegate(im)mdlReaderDataTransferProgressWithTransfered:total:","navigatorTitle":[{"text":"mdlReaderDataTransferProgressWithTransfered:total:","kind":"identifier"}],"title":"mdlReaderDataTransferProgress(transfered:total:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderDataTransferProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"transfered","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"total","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"symbolKind":"method","role":"symbol"},"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderdatatransferprogress(transfered:total:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderdatatransferprogress(transfered:total:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","defaultImplementationsSections":[{"anchor":"MdlReaderDelegate-Implementations","title":"MdlReaderDelegate Implementations","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)-uzzh"]}],"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)","interfaceLanguage":"swift"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate/mdlReaderDataTransferProgress(transfered:total:)-uzzh":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderDataTransferProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"transfered","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"total","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","abstract":[{"text":"Optional. Default no-op implementation.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderdatatransferprogress(transfered:total:)-uzzh","title":"mdlReaderDataTransferProgress(transfered:total:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)-uzzh","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate","abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"type":"codeVoice","code":"MdlReader"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReaderDelegate","kind":"identifier"}],"title":"MdlReaderDelegate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","navigatorTitle":[{"text":"MdlReaderDelegate","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate/mdlReaderDataTransferProgress(transfered:total:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderDataTransferProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"transfered","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"total","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"mdlReaderDataTransferProgressWithTransfered:total:","kind":"identifier"}],"abstract":[{"inlineContent":[{"text":"(Optional)","type":"text"}],"type":"emphasis"},{"text":" Reports the progress of data transfer from the Holder.","type":"text"}],"required":true,"url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderdatatransferprogress(transfered:total:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)","title":"mdlReaderDataTransferProgress(transfered:total:)","defaultImplementations":1,"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"name":"iOS","introducedAt":"14.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"14.0","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"14.0","beta":false,"deprecated":false,"unavailable":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"mdlReaderDataTransferProgressWithTransfered:total:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlReaderDataTransferProgressWithTransfered:total:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mdlReaderDataTransferProgressWithTransfered:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"transfered","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"total:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"total","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The number of bytes already received.","type":"text"}]}],"name":"transfered"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The total number of bytes expected to be received.","type":"text"}]}],"name":"total"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/title","op":"replace","value":"XTMdlReaderDelegate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate~1mdlReaderDataTransferProgress(transfered:total:)\/title","op":"replace","value":"mdlReaderDataTransferProgressWithTransfered:total:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate~1mdlReaderDataTransferProgress(transfered:total:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlReaderDataTransferProgressWithTransfered:total:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}