{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate"]]},"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderconnectionstatuschanged(isholderconnected:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderconnectionstatuschanged(isholderconnected:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"emphasis","inlineContent":[{"type":"text","text":"(Optional)"}]},{"text":" Notifies about a change in connection status with the Holder.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderConnectionStatusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isHolderConnected"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the Holder is currently connected, otherwise ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"isHolderConnected"}],"kind":"parameters"}],"defaultImplementationsSections":[{"title":"MdlReaderDelegate Implementations","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)-64b8x"],"anchor":"MdlReaderDelegate-Implementations"}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)","interfaceLanguage":"swift"},"metadata":{"platforms":[{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false}],"required":true,"title":"mdlReaderConnectionStatusChanged(isHolderConnected:)","modules":[{"name":"MdlReaderSdk"}],"navigatorTitle":[{"text":"mdlReaderConnectionStatusChangedWithIsHolderConnected:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(pl)XTMdlReaderDelegate(im)mdlReaderConnectionStatusChangedWithIsHolderConnected:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isHolderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate":{"kind":"symbol","title":"MdlReaderDelegate","navigatorTitle":[{"kind":"identifier","text":"MdlReaderDelegate"}],"abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"code":"MdlReader","type":"codeVoice"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlReaderDelegate"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate/mdlReaderConnectionStatusChanged(isHolderConnected:)-64b8x":{"kind":"symbol","title":"mdlReaderConnectionStatusChanged(isHolderConnected:)","abstract":[{"text":"Optional. Default no-op implementation.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderConnectionStatusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isHolderConnected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)-64b8x","url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderconnectionstatuschanged(isholderconnected:)-64b8x"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate/mdlReaderConnectionStatusChanged(isHolderConnected:)":{"kind":"symbol","required":true,"title":"mdlReaderConnectionStatusChanged(isHolderConnected:)","navigatorTitle":[{"kind":"identifier","text":"mdlReaderConnectionStatusChangedWithIsHolderConnected:"}],"abstract":[{"type":"emphasis","inlineContent":[{"type":"text","text":"(Optional)"}]},{"text":" Notifies about a change in connection status with the Holder.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlReaderConnectionStatusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isHolderConnected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"defaultImplementations":1,"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)","url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate\/mdlreaderconnectionstatuschanged(isholderconnected:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mdlReaderConnectionStatusChangedWithIsHolderConnected:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlReaderConnectionStatusChangedWithIsHolderConnected:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"mdlReaderConnectionStatusChangedWithIsHolderConnected:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isHolderConnected","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the Holder is currently connected, otherwise "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"isHolderConnected"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/title","value":"XTMdlReaderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/fragments","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate~1mdlReaderConnectionStatusChanged(isHolderConnected:)\/title","value":"mdlReaderConnectionStatusChangedWithIsHolderConnected:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate~1mdlReaderConnectionStatusChanged(isHolderConnected:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlReaderConnectionStatusChangedWithIsHolderConnected:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}