{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"biometricTemplateXx","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MdlBiometricTemplate","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlBiometricTemplate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate"},{"kind":"text","text":"]?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/biometricTemplateXx","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@MdlReader@objc(cs)XTMdlDocument(py)biometricTemplateXx","navigatorTitle":[{"kind":"identifier","text":"biometricTemplateXx"}],"title":"biometricTemplateXx","modules":[{"name":"MdlReader"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlBiometricTemplate","text":"MdlBiometricTemplate","kind":"typeIdentifier"},{"kind":"text","text":"]?"}]},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument"]]},"variants":[{"paths":["\/documentation\/mdlreader\/mdldocument\/biometrictemplatexx"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdldocument\/biometrictemplatexx"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlBiometricTemplate":{"role":"symbol","title":"MdlBiometricTemplate","navigatorTitle":[{"kind":"identifier","text":"MdlBiometricTemplate"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlBiometricTemplate"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate","abstract":[],"url":"\/documentation\/mdlreader\/mdlbiometrictemplate"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument":{"type":"topic","url":"\/documentation\/mdlreader\/mdldocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol","title":"MdlDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument","abstract":[{"type":"text","text":"Representation of mDL document"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/biometricTemplateXx":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/biometricTemplateXx","title":"biometricTemplateXx","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/biometrictemplatexx","navigatorTitle":[{"kind":"identifier","text":"biometricTemplateXx"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MdlBiometricTemplate","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlBiometricTemplate"},{"kind":"text","text":"]?"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"biometricTemplateXx","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"biometricTemplateXx","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<XTMdlBiometricTemplate *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"biometricTemplateXx","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate\/title","op":"replace","value":"XTMdlBiometricTemplate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlBiometricTemplate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlBiometricTemplate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/title","op":"replace","value":"XTMdlDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1biometricTemplateXx\/title","op":"replace","value":"biometricTemplateXx"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1biometricTemplateXx\/fragments","op":"replace","value":[{"kind":"identifier","text":"biometricTemplateXx"}]}]}]}