{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/bloodGroup","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@MdlReader@objc(cs)XTMdlDocument(py)bloodGroup","modules":[{"name":"MdlReader"}],"symbolKind":"property","title":"bloodGroup","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bloodGroup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"bloodGroup","kind":"identifier"}],"platforms":[{"introducedAt":"14.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"beta":false,"unavailable":false,"introducedAt":"14.0","deprecated":false,"name":"iPadOS"},{"beta":false,"unavailable":false,"introducedAt":"14.0","deprecated":false,"name":"Mac Catalyst"}]},"variants":[{"paths":["\/documentation\/mdlreader\/mdldocument\/bloodgroup"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdldocument\/bloodgroup"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bloodGroup","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument"]]},"abstract":[{"type":"text","text":"mDL holder’s blood group"}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument":{"kind":"symbol","abstract":[{"type":"text","text":"Representation of mDL document"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument","url":"\/documentation\/mdlreader\/mdldocument","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"title":"MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/bloodGroup":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bloodGroup","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"bloodGroup","navigatorTitle":[{"text":"bloodGroup","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mdlreader\/mdldocument\/bloodgroup","abstract":[{"type":"text","text":"mDL holder’s blood group"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/bloodGroup","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"unavailable":false,"introducedAt":"14.0","deprecated":false,"name":"iOS"},{"beta":false,"unavailable":false,"introducedAt":"14.0","deprecated":false,"name":"iPadOS"},{"beta":false,"unavailable":false,"introducedAt":"14.0","deprecated":false,"name":"Mac Catalyst"}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"bloodGroup","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"bloodGroup","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bloodGroup"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"XTMdlDocument","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/title","op":"replace"},{"value":[{"text":"XTMdlDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/fragments","op":"replace"},{"value":[{"text":"XTMdlDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/navigatorTitle","op":"replace"},{"value":"bloodGroup","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1bloodGroup\/title","op":"replace"},{"value":[{"text":"bloodGroup","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1bloodGroup\/fragments","op":"replace"}]}]}