{"kind":"symbol","abstract":[{"text":"Country subdivision code of the jurisdiction that issued the mDL. The first part of the code shall be the same as the value for issuing country.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument"]]},"metadata":{"title":"issuingJurisdiction","externalID":"c:@M@MdlReader@objc(cs)XTMdlDocument(py)issuingJurisdiction","modules":[{"name":"MdlReader"}],"roleHeading":"Instance Property","platforms":[{"introducedAt":"14.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"14.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingJurisdiction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"issuingJurisdiction"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issuingJurisdiction"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingJurisdiction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdldocument\/issuingjurisdiction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdldocument\/issuingjurisdiction"]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/issuingJurisdiction":{"title":"issuingJurisdiction","navigatorTitle":[{"text":"issuingJurisdiction","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Country subdivision code of the jurisdiction that issued the mDL. The first part of the code shall be the same as the value for issuing country.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingJurisdiction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issuingJurisdiction","role":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/issuingjurisdiction"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument":{"kind":"symbol","abstract":[{"type":"text","text":"Representation of mDL document"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument","url":"\/documentation\/mdlreader\/mdldocument","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"title":"MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"introducedAt":"14.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"14.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"issuingJurisdiction","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"issuingJurisdiction","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"issuingJurisdiction","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1issuingJurisdiction\/title","value":"issuingJurisdiction","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1issuingJurisdiction\/fragments","value":[{"text":"issuingJurisdiction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/title","value":"XTMdlDocument","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/fragments","value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}