{"abstract":[{"type":"text","text":"Permanent place of residence. The place where the mDL holder resides and\/or may be contacted (street\/house number, municipality etc.)."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdldocument\/residentaddress"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdldocument\/residentaddress"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentAddress"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"residentAddress"}],"title":"residentAddress","role":"symbol","platforms":[{"beta":false,"introducedAt":"14.0","name":"iOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}],"externalID":"c:@M@MdlReader@objc(cs)XTMdlDocument(py)residentAddress","roleHeading":"Instance Property","modules":[{"name":"MdlReader"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"residentAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/residentAddress":{"abstract":[{"text":"Permanent place of residence. The place where the mDL holder resides and\/or may be contacted (street\/house number, municipality etc.).","type":"text"}],"url":"\/documentation\/mdlreader\/mdldocument\/residentaddress","title":"residentAddress","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentAddress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"residentAddress"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument":{"kind":"symbol","abstract":[{"type":"text","text":"Representation of mDL document"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument","url":"\/documentation\/mdlreader\/mdldocument","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"title":"MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"introducedAt":"14.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"14.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"residentAddress"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"residentAddress","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"residentAddress"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1residentAddress\/title","op":"replace","value":"residentAddress"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1residentAddress\/fragments","op":"replace","value":[{"text":"residentAddress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/title","op":"replace","value":"XTMdlDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/fragments","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]}]}]}