{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"sex","externalID":"c:@M@MdlReader@objc(cs)XTMdlDocument(py)sex","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlReader@E@XTMdlGender","text":"MdlGender","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"sex"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"MdlReader"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender","text":"MdlGender","preciseIdentifier":"c:@M@MdlReader@E@XTMdlGender"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/sex","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdldocument\/sex"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdldocument\/sex"]}],"abstract":[{"type":"text","text":"mDL holder’s sex."}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument":{"type":"topic","url":"\/documentation\/mdlreader\/mdldocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol","title":"MdlDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument","abstract":[{"type":"text","text":"Representation of mDL document"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/sex":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/sex","title":"sex","url":"\/documentation\/mdlreader\/mdldocument\/sex","kind":"symbol","navigatorTitle":[{"text":"sex","kind":"identifier"}],"abstract":[{"type":"text","text":"mDL holder’s sex."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlGender","preciseIdentifier":"c:@M@MdlReader@E@XTMdlGender","kind":"typeIdentifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlGender":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender","kind":"symbol","title":"MdlGender","url":"\/documentation\/mdlreader\/mdlgender","navigatorTitle":[{"kind":"identifier","text":"MdlGender"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlGender"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"sex"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"sex","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"XTMdlGender","preciseIdentifier":"c:@M@MdlReader@E@XTMdlGender","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/title","value":"XTMdlDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/fragments","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1sex\/title","value":"sex"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1sex\/fragments","value":[{"text":"sex","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender\/title","op":"replace","value":"XTMdlGender"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlGender"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlGender"}]}]}]}