{"abstract":[{"text":"UN Distinguishing sign.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdldocument\/undistinguishingsign"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdldocument\/undistinguishingsign"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/unDistinguishingSign"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unDistinguishingSign","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"unDistinguishingSign","kind":"identifier"}],"title":"unDistinguishingSign","role":"symbol","platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}],"roleHeading":"Instance Property","externalID":"c:@M@MdlReader@objc(cs)XTMdlDocument(py)unDistinguishingSign","modules":[{"name":"MdlReader"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unDistinguishingSign","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/unDistinguishingSign":{"abstract":[{"text":"UN Distinguishing sign.","type":"text"}],"url":"\/documentation\/mdlreader\/mdldocument\/undistinguishingsign","title":"unDistinguishingSign","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/unDistinguishingSign","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unDistinguishingSign"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"unDistinguishingSign"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument":{"kind":"symbol","abstract":[{"type":"text","text":"Representation of mDL document"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument","url":"\/documentation\/mdlreader\/mdldocument","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"title":"MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"unDistinguishingSign","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"unDistinguishingSign","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"unDistinguishingSign","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"unDistinguishingSign","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1unDistinguishingSign\/title"},{"op":"replace","value":[{"kind":"identifier","text":"unDistinguishingSign"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1unDistinguishingSign\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/title","op":"replace","value":"XTMdlDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}]}]}]}