{"kind":"symbol","hierarchy":{"paths":[[]]},"variants":[{"paths":["\/documentation\/mdlreadersdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Supported platform: iOS 14.0+"}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"MdlReaderSdk"},{"type":"text","text":" provides a high-level API to enable iOS applications to act as mDL Readers that can securely request and retrieve data from mDL Holders. The framework implements BLE as the primary communication channel and uses QR codes to initiate the engagement process, following the ISO\/IEC 18013-5 standard."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The framework handles the full reader-side workflow, including engagement, connection establishment, document request generation, and verification of received data."}]},{"text":"Features","level":2,"type":"heading","anchor":"Features"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"QR-based engagement for establishing secure sessions"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"BLE transport for data exchange with the Holder"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Support for online and offline (device-to-device) verification modes"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Automatic generation and validation of server tokens"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"High-level delegate interface for receiving updates and data"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Built-in validation of document authenticity and signature verification"}]}]}],"type":"unorderedList"},{"text":"Getting Started","level":2,"type":"heading","anchor":"Getting-Started"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Import the "},{"code":"MdlReaderSdk","type":"codeVoice"},{"type":"text","text":" framework into your iOS project."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add required dependencies to your project:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Include the "},{"type":"codeVoice","code":"CoreSdk.xcframework"},{"type":"text","text":" which is shipped together with the "},{"type":"codeVoice","code":"MdReaderSdk"},{"type":"text","text":" distribution."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add "},{"type":"reference","identifier":"https:\/\/github.com\/krzyzanowskim\/OpenSSL.git","isActive":true},{"type":"text","text":" library to your project."}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Access all framework functionality through the shared singleton instance "},{"code":"MdlReader.shared","type":"codeVoice"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Before using the framework, initialize it by calling the "},{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/initialize(completion:)","isActive":true,"type":"reference"},{"type":"text","text":" method."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If not yet, you need to personalize the Reader by calling "},{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/personalizeWith(token:pin:completion:)","isActive":true,"type":"reference"},{"type":"text","text":" method that downloads the necessary certificates and creates private keys."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Start the engagement process by calling "},{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)","isActive":true,"type":"reference"},{"type":"text","text":" with the QR engagement data, the required fields and a delegate conforming to "},{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","isActive":true,"type":"reference"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle delegate callbacks to process received data or errors."}]}]}],"type":"orderedList"},{"text":"Architecture","level":2,"type":"heading","anchor":"Architecture"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader","isActive":true,"type":"reference"},{"type":"text","text":" — Main class responsible for initiating and managing document requests."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","isActive":true,"type":"reference"},{"type":"text","text":" — Protocol that delivers updates about connection, transfer progress, and received data."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","isActive":true,"type":"reference"},{"type":"text","text":" — Describes data fields that can be requested from the mDL."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocumentField","isActive":true,"type":"reference"},{"type":"text","text":" — Represents a single field received from the mDL."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode","isActive":true,"type":"reference"},{"type":"text","text":" — Contains possible error codes that may occur during document request and validation."}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"All errors are returned as instances of "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":". The "},{"type":"codeVoice","code":"code"},{"type":"text","text":" property corresponds to a value from the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode"},{"type":"text","text":" enumeration, allowing for easy identification of failure causes."}]},{"text":"Security Considerations","level":2,"type":"heading","anchor":"Security-Considerations"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Communication between Reader and Holder is encrypted and authenticated."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"All tokens and documents are signed and verified according to ISO\/IEC 18013-5."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Data minimization principles are enforced—only requested fields are transmitted."}]}]}],"type":"unorderedList"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk"},"topicSections":[{"title":"Main Classes","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocumentField","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode"],"anchor":"Main-Classes"},{"title":"Classes","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilege","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivileges"],"generated":true,"anchor":"Classes"},{"title":"Variables","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/XTReaderErrorDomain"],"generated":true,"anchor":"Variables"},{"title":"Enumerations","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender"],"generated":true,"anchor":"Enumerations"}],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["https:\/\/www.iso.org\/standard\/69084.html"],"anchor":"Related-Documentation"}],"metadata":{"title":"MdlReaderSdk","role":"collection","modules":[{"name":"MdlReaderSdk"}],"roleHeading":"Framework","symbolKind":"module","externalID":"MdlReaderSdk"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader/startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)":{"kind":"symbol","title":"startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)","navigatorTitle":[{"text":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:","kind":"identifier"}],"abstract":[{"text":"This method initializes the document request process and sends the request to the holder.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startRequestDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fields","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"isOnline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"engagement","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlReaderDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(pl)XTMdlReaderDelegate"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)","url":"\/documentation\/mdlreadersdk\/mdlreader\/startrequestdocument(fields:isonline:engagement:pin:delegate:completion:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"title":"MdlDocument","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","url":"\/documentation\/mdlreadersdk\/mdldocument"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader/initialize(completion:)":{"kind":"symbol","title":"initialize(completion:)","navigatorTitle":[{"text":"initializeWithCompletion:","kind":"identifier"}],"abstract":[{"type":"text","text":"SDK initialization"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/initialize(completion:)","url":"\/documentation\/mdlreadersdk\/mdlreader\/initialize(completion:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate":{"kind":"symbol","title":"MdlReaderDelegate","navigatorTitle":[{"kind":"identifier","text":"MdlReaderDelegate"}],"abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"code":"MdlReader","type":"codeVoice"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlReaderDelegate"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader","title":"MdlReader","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MdlReader","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlReader"}],"abstract":[{"type":"text","text":"Main class of the SDK"}],"url":"\/documentation\/mdlreadersdk\/mdlreader","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/AgeOverNnEntry":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry","kind":"symbol","type":"topic","title":"AgeOverNnEntry","navigatorTitle":[{"text":"AgeOverNnEntry","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgeOverNnEntry","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/ageovernnentry","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlBiometricTemplate":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate","title":"MdlBiometricTemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MdlBiometricTemplate"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlBiometricTemplate"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/mdlbiometrictemplate","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCode":{"kind":"symbol","title":"MdlDrivingPrivilegeCode","navigatorTitle":[{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode","url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecode"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocumentField":{"kind":"symbol","title":"MdlDocumentField","navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocumentField"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocumentField","url":"\/documentation\/mdlreadersdk\/mdldocumentfield"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilege":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilege","title":"MdlDrivingPrivilege","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilege"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"identifier"}],"abstract":[{"type":"text","text":"A data model representing a single driving privilege entry from a Mobile Driving Licence (mDL)."}],"url":"\/documentation\/mdlreadersdk\/mdldrivingprivilege","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlGender":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender","kind":"symbol","type":"topic","title":"MdlGender","navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/mdlgender","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode":{"navigatorTitle":[{"text":"ReaderErrorCode","kind":"identifier"}],"kind":"symbol","title":"ReaderErrorCode","url":"\/documentation\/mdlreadersdk\/readererrorcode","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderErrorCode","kind":"identifier"}]},"https://github.com/krzyzanowskim/OpenSSL.git":{"titleInlineContent":[{"type":"text","text":"OpenSSL"}],"title":"OpenSSL","identifier":"https:\/\/github.com\/krzyzanowskim\/OpenSSL.git","type":"link","url":"https:\/\/github.com\/krzyzanowskim\/OpenSSL.git"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlFieldIdentifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlFieldIdentifier"}],"abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/XTReaderErrorDomain":{"kind":"symbol","title":"XTReaderErrorDomain","abstract":[{"text":"SDK error domain: “com.xinfotech.mdlreader”","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XTReaderErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/XTReaderErrorDomain","url":"\/documentation\/mdlreadersdk\/xtreadererrordomain"},"https://www.iso.org/standard/69084.html":{"type":"link","titleInlineContent":[{"type":"text","text":"ISO\/IEC 18013-5 Standard"}],"url":"https:\/\/www.iso.org\/standard\/69084.html","title":"ISO\/IEC 18013-5 Standard","identifier":"https:\/\/www.iso.org\/standard\/69084.html"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivileges":{"kind":"symbol","title":"MdlDrivingPrivileges","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivileges"}],"abstract":[{"type":"text","text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL)."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivileges","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivileges","url":"\/documentation\/mdlreadersdk\/mdldrivingprivileges"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader/personalizeWith(token:pin:completion:)":{"kind":"symbol","title":"personalizeWith(token:pin:completion:)","navigatorTitle":[{"kind":"identifier","text":"personalizeWithToken:pin:completion:"}],"abstract":[{"type":"text","text":"This method personalizes the Reader App, downloads the necessary certificates and saves them in the secure SDK storage"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"personalizeWith","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pin"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/personalizeWith(token:pin:completion:)","url":"\/documentation\/mdlreadersdk\/mdlreader\/personalizewith(token:pin:completion:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCodes":{"kind":"symbol","title":"MdlDrivingPrivilegeCodes","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilegeCodes"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivilegeCodes"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes","url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecodes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":[{"title":"Main Classes","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocumentField","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode"],"anchor":"Main-Classes"},{"anchor":"Classes","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilege","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivileges"],"title":"Classes","generated":true},{"anchor":"Enumerations","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender"],"title":"Enumerations","generated":true}],"op":"replace"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"Related-Documentation","identifiers":["https:\/\/www.iso.org\/standard\/69084.html"],"title":"Related Documentation"}],"path":"\/seeAlsoSections"},{"op":"replace","value":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)\/fragments"},{"op":"replace","value":"XTMdlDocument","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/fragments","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/navigatorTitle","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1initialize(completion:)\/title","value":"initializeWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1initialize(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initializeWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/title","value":"XTMdlReaderDelegate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/title","op":"replace","value":"XTMdlReader"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlReader"}]},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlReader"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/navigatorTitle"},{"op":"replace","value":"XTAgeOverNnEntry","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/fragments","op":"replace","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/navigatorTitle","op":"replace","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}]},{"value":"XTMdlBiometricTemplate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate\/title"},{"value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate\/fragments"},{"value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate\/navigatorTitle"},{"value":"XTMdlDrivingPrivilegeCode","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode\/title"},{"value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode\/fragments"},{"value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField\/title","op":"replace","value":"XTMdlDocumentField"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField\/fragments","op":"replace","value":[{"text":"XTMdlDocumentField","kind":"identifier"}]},{"value":[{"text":"XTMdlDocumentField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField\/navigatorTitle"},{"value":"XTMdlDrivingPrivilege","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege\/title"},{"value":[{"text":"XTMdlDrivingPrivilege","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege\/fragments"},{"value":[{"text":"XTMdlDrivingPrivilege","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege\/navigatorTitle"},{"value":"XTMdlGender","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/title"},{"value":[{"text":"XTMdlGender","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/fragments"},{"value":[{"text":"XTMdlGender","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/navigatorTitle"},{"value":"XTReaderErrorCode","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/title"},{"value":[{"text":"XTReaderErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"XTReaderErrorCode"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/fragments","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges\/title","value":"XTMdlDrivingPrivileges"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}]},{"value":"personalizeWithToken:pin:completion:","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1personalizeWith(token:pin:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1personalizeWith(token:pin:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"personalizeWithToken:pin:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes\/title","value":"XTMdlDrivingPrivilegeCodes"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes\/fragments","value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}]}]}]}