{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"topicSections":[{"title":"Main Classes","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"],"anchor":"Main-Classes"},{"title":"Classes","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/AgeOverNnEntry","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges"],"anchor":"Classes"},{"title":"Variables","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/XTReaderErrorDomain"],"anchor":"Variables"},{"title":"Enumerations","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender"],"anchor":"Enumerations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader"]}],"sections":[],"primaryContentSections":[{"content":[{"anchor":"Overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Supported platform: iOS 14.0+"}]},{"type":"paragraph","inlineContent":[{"code":"MdlReader","type":"codeVoice"},{"type":"text","text":" provides a high-level API to enable iOS applications to act as mDL Readers that can securely request and retrieve data from mDL Holders. The framework implements BLE as the primary communication channel and uses QR codes to initiate the engagement process, following the ISO\/IEC 18013-5 standard."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The framework handles the full reader-side workflow, including engagement, connection establishment, document request generation, and verification of received data."}]},{"anchor":"Features","type":"heading","level":2,"text":"Features"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"QR-based engagement for establishing secure sessions"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"BLE transport for data exchange with the Holder"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Support for online and offline (device-to-device) verification modes"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Automatic generation and validation of server tokens"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"High-level delegate interface for receiving updates and data"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Built-in validation of document authenticity and signature verification"}],"type":"paragraph"}]}]},{"anchor":"Getting-Started","type":"heading","level":2,"text":"Getting Started"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Import the "},{"code":"MdlReader","type":"codeVoice"},{"type":"text","text":" framework into your iOS project."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Access all framework functionality through the shared singleton instance "},{"code":"MdlReader.shared","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Before using the framework, initialize it by calling the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/initialize(completion:)"},{"type":"text","text":" method."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"If not yet, you need to personalize the Reader by calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/personalizeWith(token:pin:completion:)"},{"type":"text","text":" method that downloads the necessary certificates and creates private keys."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Start the engagement process by calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)"},{"type":"text","text":" with the QR engagement data, the required fields and a delegate conforming to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Handle delegate callbacks to process received data or errors.","type":"text"}],"type":"paragraph"}]}]},{"anchor":"Architecture","type":"heading","level":2,"text":"Architecture"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader"},{"text":" — Main class responsible for initiating and managing document requests.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate"},{"type":"text","text":" — Protocol that delivers updates about connection, transfer progress, and received data."}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier"},{"type":"text","text":" — Describes data fields that can be requested from the mDL."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField"},{"text":" — Represents a single field received from the mDL.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"},{"text":" — Contains possible error codes that may occur during document request and validation.","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"All errors are returned as instances of "},{"type":"codeVoice","code":"NSError"},{"text":". The ","type":"text"},{"type":"codeVoice","code":"code"},{"text":" property corresponds to a value from the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"},{"text":" enumeration, allowing for easy identification of failure causes.","type":"text"}]},{"anchor":"Security-Considerations","type":"heading","level":2,"text":"Security Considerations"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Communication between Reader and Holder is encrypted and authenticated."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"All tokens and documents are signed and verified according to ISO\/IEC 18013-5."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Data minimization principles are enforced—only requested fields are transmitted."}]}]}]}],"kind":"content"}],"metadata":{"roleHeading":"Framework","symbolKind":"module","externalID":"MdlReader","title":"MdlReader","role":"collection","modules":[{"name":"MdlReader"}]},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["https:\/\/www.iso.org\/standard\/69084.html"],"anchor":"Related-Documentation"}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivileges":{"abstract":[{"type":"text","text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL)."}],"url":"\/documentation\/mdlreader\/mdldrivingprivileges","title":"MdlDrivingPrivileges","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivileges","kind":"identifier"}],"navigatorTitle":[{"text":"MdlDrivingPrivileges","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlGender":{"url":"\/documentation\/mdlreader\/mdlgender","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender","role":"symbol","navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MdlGender","kind":"identifier"}],"title":"MdlGender"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocumentField":{"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField","url":"\/documentation\/mdlreader\/mdldocumentfield","kind":"symbol","title":"MdlDocumentField","type":"topic","abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocumentField","kind":"identifier"}],"navigatorTitle":[{"text":"MdlDocumentField","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/XTReaderErrorDomain":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTReaderErrorDomain"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"SDK error domain: “com.xinfotech.mdlreader”","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/XTReaderErrorDomain","title":"XTReaderErrorDomain","url":"\/documentation\/mdlreader\/xtreadererrordomain"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ReaderErrorCode"}],"url":"\/documentation\/mdlreader\/readererrorcode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReaderErrorCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ReaderErrorCode","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument":{"kind":"symbol","abstract":[{"type":"text","text":"Representation of mDL document"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument","url":"\/documentation\/mdlreader\/mdldocument","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"title":"MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)":{"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)","url":"\/documentation\/mdlreader\/mdlreader\/startrequestdocument(fields:isonline:engagement:pin:delegate:completion:)","kind":"symbol","title":"startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)","type":"topic","abstract":[{"text":"This method initializes the document request process and sends the request to the holder.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startRequestDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fields","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"isOnline","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"engagement","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlReaderDelegate","preciseIdentifier":"c:@M@MdlReader@objc(pl)XTMdlReaderDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCode":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode","abstract":[],"navigatorTitle":[{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"url":"\/documentation\/mdlreader\/mdldrivingprivilegecode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"MdlDrivingPrivilegeCode","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/personalizeWith(token:pin:completion:)":{"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/personalizeWith(token:pin:completion:)","url":"\/documentation\/mdlreader\/mdlreader\/personalizewith(token:pin:completion:)","kind":"symbol","title":"personalizeWith(token:pin:completion:)","type":"topic","abstract":[{"text":"This method personalizes the Reader App, downloads the necessary certificates and saves them in the secure SDK storage","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"personalizeWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"personalizeWithToken:pin:completion:","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/initialize(completion:)":{"abstract":[{"text":"SDK initialization","type":"text"}],"url":"\/documentation\/mdlreader\/mdlreader\/initialize(completion:)","title":"initialize(completion:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/initialize(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initializeWithCompletion:","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader":{"kind":"symbol","abstract":[{"text":"Main class of the SDK","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader","type":"topic","url":"\/documentation\/mdlreader\/mdlreader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReader","kind":"identifier"}],"title":"MdlReader","navigatorTitle":[{"text":"MdlReader","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate":{"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","type":"topic","abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"type":"codeVoice","code":"MdlReader"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"url":"\/documentation\/mdlreader\/mdlreaderdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReaderDelegate","kind":"identifier"}],"title":"MdlReaderDelegate","navigatorTitle":[{"text":"MdlReaderDelegate","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCodes":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes","abstract":[],"navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"url":"\/documentation\/mdlreader\/mdldrivingprivilegecodes","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"type":"topic","kind":"symbol","title":"MdlDrivingPrivilegeCodes","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlFieldIdentifier":{"url":"\/documentation\/mdlreader\/mdlfieldidentifier","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"abstract":[{"text":"Provides predefined field identifiers used in mDL documents.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","title":"MdlFieldIdentifier","type":"topic"},"https://www.iso.org/standard/69084.html":{"url":"https:\/\/www.iso.org\/standard\/69084.html","title":"ISO\/IEC 18013-5 Standard","identifier":"https:\/\/www.iso.org\/standard\/69084.html","type":"link","titleInlineContent":[{"text":"ISO\/IEC 18013-5 Standard","type":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/AgeOverNnEntry":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgeOverNnEntry","kind":"identifier"}],"title":"AgeOverNnEntry","navigatorTitle":[{"text":"AgeOverNnEntry","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mdlreader\/ageovernnentry","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/AgeOverNnEntry","kind":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlBiometricTemplate":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate","abstract":[],"navigatorTitle":[{"text":"MdlBiometricTemplate","kind":"identifier"}],"url":"\/documentation\/mdlreader\/mdlbiometrictemplate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlBiometricTemplate","kind":"identifier"}],"type":"topic","kind":"symbol","title":"MdlBiometricTemplate","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilege":{"abstract":[{"type":"text","text":"A data model representing a single driving privilege entry from a Mobile Driving Licence (mDL)."}],"url":"\/documentation\/mdlreader\/mdldrivingprivilege","title":"MdlDrivingPrivilege","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"identifier"}],"navigatorTitle":[{"text":"MdlDrivingPrivilege","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"],"title":"Main Classes","anchor":"Main-Classes"},{"title":"Classes","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/AgeOverNnEntry","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges"],"generated":true,"anchor":"Classes"},{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender"],"title":"Enumerations","generated":true,"anchor":"Enumerations"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"identifiers":["https:\/\/www.iso.org\/standard\/69084.html"],"title":"Related Documentation","anchor":"Related-Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"value":"XTMdlDrivingPrivileges","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges\/fragments","value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}],"op":"replace"},{"value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender\/title","op":"replace","value":"XTMdlGender"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender\/fragments","op":"replace","value":[{"text":"XTMdlGender","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender\/navigatorTitle","value":[{"text":"XTMdlGender","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/title","op":"replace","value":"XTMdlDocumentField"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/fragments","value":[{"text":"XTMdlDocumentField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDocumentField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/title","value":"XTReaderErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/fragments","value":[{"text":"XTReaderErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTReaderErrorCode"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/title","op":"replace","value":"XTMdlDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)\/title","op":"replace","value":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode\/title","op":"replace","value":"XTMdlDrivingPrivilegeCode"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode\/fragments","op":"replace","value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1personalizeWith(token:pin:completion:)\/title","op":"replace","value":"personalizeWithToken:pin:completion:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1personalizeWith(token:pin:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"personalizeWithToken:pin:completion:"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1initialize(completion:)\/title","op":"replace","value":"initializeWithCompletion:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1initialize(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithCompletion:"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/title","op":"replace","value":"XTMdlReader"},{"value":[{"text":"XTMdlReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/fragments"},{"value":[{"text":"XTMdlReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/navigatorTitle"},{"value":"XTMdlReaderDelegate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/fragments","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/title","value":"XTMdlDrivingPrivilegeCodes","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/fragments","op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1AgeOverNnEntry\/title","value":"XTAgeOverNnEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1AgeOverNnEntry\/fragments","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1AgeOverNnEntry\/navigatorTitle","op":"replace","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate\/title","op":"replace","value":"XTMdlBiometricTemplate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate\/fragments","op":"replace","value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate\/navigatorTitle","op":"replace","value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/title","op":"replace","value":"XTMdlDrivingPrivilege"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/fragments","op":"replace","value":[{"text":"XTMdlDrivingPrivilege","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDrivingPrivilege","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}