{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder"},"abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"code":"MdlHolder","type":"codeVoice"},{"text":" provides a high-level API to enable iOS applications to act as mobile Driving Licence (mDL) holders. It facilitates secure, privacy-respecting document sharing with mDL Readers using BLE as the data transport channel and QR codes for initial engagement, in accordance with ISO\/IEC 18013-5.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"The framework manages the document sharing lifecycle, including engagement, document request handling, and user consent. It abstracts lower-level cryptographic and transport details, offering a convenient interface for integrating mDL functionality into your app.","type":"text"}],"type":"paragraph"},{"anchor":"Features","level":2,"text":"Features","type":"heading"},{"items":[{"content":[{"inlineContent":[{"text":"QR-based engagement initialization","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"BLE-based data exchange with Readers"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Support for both online (Issuer Authority) and offline (device-to-device) modes","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"High-level delegate callbacks for user consent flow"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Token and document structure validation for debugging","type":"text"}]}]}],"type":"unorderedList"},{"anchor":"Getting-Started","level":2,"text":"Getting Started","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Import the ","type":"text"},{"code":"MdlHolder","type":"codeVoice"},{"text":" framework into your iOS project.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Access all framework functionality through the shared singleton instance "},{"code":"MdlHolder.shared","type":"codeVoice"},{"type":"text","text":". Before using the framework, you must initialize it by calling the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/initialize(completion:)"},{"type":"text","text":" method. If the mDL has not yet been downloaded from the Issuer Authority, call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/loadDocumentWith(token:pin:completion:)"},{"type":"text","text":" to download the mDL and place it into secure storage before starting document sharing."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Call ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/startDocumentSharing(withPin:delegate:completion:)"},{"text":" with a delegate conforming to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle delegate callbacks to approve or reject field requests."}]}]}],"type":"orderedList"},{"anchor":"Architecture","level":2,"text":"Architecture","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","isActive":true,"type":"reference"},{"text":" — The main class responsible for document management and sharing session.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","type":"reference","isActive":true},{"text":" — Represents mDL document with all fields.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","type":"reference","isActive":true},{"text":" — Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}]}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"},{"text":" — The protocol that delivers events to the application layer, such as when requested fields are received or errors occur.","type":"text"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"All errors within the framework are returned as instances of "},{"code":"NSError","type":"codeVoice"},{"type":"text","text":". The "},{"code":"code","type":"codeVoice"},{"type":"text","text":" property of each error corresponds to a value from the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode"},{"text":" enumeration, allowing you to identify and handle specific failure scenarios programmatically.","type":"text"}]},{"level":2,"text":"Security Considerations","anchor":"Security-Considerations","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Data is signed using keys bound to the mDL","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Field-level consent is always required from the user"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"BLE sessions are encrypted and authenticated per standard","type":"text"}]}]}],"type":"unorderedList"}]}],"hierarchy":{"paths":[[]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder"]}],"metadata":{"roleHeading":"Framework","role":"collection","symbolKind":"module","modules":[{"name":"MdlHolder"}],"title":"MdlHolder","externalID":"MdlHolder"},"topicSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"],"title":"Main Classes","anchor":"Main-Classes"},{"anchor":"Classes","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilege","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCode","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier"],"generated":true,"title":"Classes"},{"title":"Variables","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/XTHolderErrorDomain"],"generated":true,"anchor":"Variables"},{"anchor":"Enumerations","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender"],"generated":true,"title":"Enumerations"}],"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["https:\/\/www.iso.org\/standard\/69084.html"]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier":{"url":"\/documentation\/mdlholder\/mdlfieldidentifier","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlFieldIdentifier"}],"abstract":[{"text":"Provides predefined field identifiers used in mDL documents.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","role":"symbol","title":"MdlFieldIdentifier"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender","title":"MdlGender","abstract":[],"role":"symbol","url":"\/documentation\/mdlholder\/mdlgender","kind":"symbol","navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilegeCodes":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes","title":"MdlDrivingPrivilegeCodes","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdldrivingprivilegecodes","navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlDrivingPrivilegeCodes"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivileges":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges","abstract":[{"type":"text","text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL)."}],"title":"MdlDrivingPrivileges","role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdldrivingprivileges","navigatorTitle":[{"text":"MdlDrivingPrivileges","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivileges"}]},"https://www.iso.org/standard/69084.html":{"identifier":"https:\/\/www.iso.org\/standard\/69084.html","titleInlineContent":[{"type":"text","text":"ISO\/IEC 18013-5 Standard"}],"url":"https:\/\/www.iso.org\/standard\/69084.html","type":"link","title":"ISO\/IEC 18013-5 Standard"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate":{"url":"\/documentation\/mdlholder\/mdlholderdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlHolderDelegate"}],"abstract":[{"text":"Delivers events from the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","type":"reference"},{"type":"text","text":" during the mDL document sharing lifecycle."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlHolderDelegate"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","role":"symbol","title":"MdlHolderDelegate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilege":{"title":"MdlDrivingPrivilege","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilege"}],"url":"\/documentation\/mdlholder\/mdldrivingprivilege","abstract":[{"text":"A data model representing a single driving privilege entry from a Mobile Driving Licence (mDL).","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivilege"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilege","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","title":"MdlDocument","abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","url":"\/documentation\/mdlholder\/mdldocument","kind":"symbol","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MdlDocument","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlBiometricTemplate":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate","title":"MdlBiometricTemplate","abstract":[],"role":"symbol","url":"\/documentation\/mdlholder\/mdlbiometrictemplate","kind":"symbol","navigatorTitle":[{"text":"MdlBiometricTemplate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlBiometricTemplate"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HolderErrorCode"}],"kind":"symbol","type":"topic","title":"HolderErrorCode","url":"\/documentation\/mdlholder\/holdererrorcode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HolderErrorCode"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/XTHolderErrorDomain":{"title":"XTHolderErrorDomain","kind":"symbol","url":"\/documentation\/mdlholder\/xtholdererrordomain","abstract":[{"type":"text","text":"SDK error domain: “com.xinfotech.mdlholder”"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTHolderErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/XTHolderErrorDomain","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocumentField":{"type":"topic","abstract":[{"type":"text","text":"Represents an mDL document field containing an identifier and a corresponding value."}],"title":"MdlDocumentField","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","role":"symbol","url":"\/documentation\/mdlholder\/mdldocumentfield","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocumentField"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilegeCode":{"title":"MdlDrivingPrivilegeCode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilegeCode"}],"url":"\/documentation\/mdlholder\/mdldrivingprivilegecode","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCode","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/loadDocumentWith(token:pin:completion:)":{"type":"topic","abstract":[{"type":"text","text":"The asynchronous method that loads a document into the SDK"}],"title":"loadDocumentWith(token:pin:completion:)","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/loadDocumentWith(token:pin:completion:)","role":"symbol","url":"\/documentation\/mdlholder\/mdlholder\/loaddocumentwith(token:pin:completion:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadDocumentWithToken:pin:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadDocumentWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"url":"\/documentation\/mdlholder\/mdlholder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolder","kind":"identifier"}],"abstract":[{"text":"Main class of the SDK","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MdlHolder","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","role":"symbol","title":"MdlHolder"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/startDocumentSharing(withPin:delegate:completion:)":{"type":"topic","title":"startDocumentSharing(withPin:delegate:completion:)","abstract":[{"text":"Starts the mDL document sharing session initiated via QR engagement.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/startDocumentSharing(withPin:delegate:completion:)","role":"symbol","url":"\/documentation\/mdlholder\/mdlholder\/startdocumentsharing(withpin:delegate:completion:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"startDocumentSharingWithPin:delegate:completion:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDocumentSharing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlHolderDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, ("},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/initialize(completion:)":{"url":"\/documentation\/mdlholder\/mdlholder\/initialize(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"text":"SDK initialization","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initializeWithCompletion:"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/initialize(completion:)","role":"symbol","title":"initialize(completion:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/AgeOverNnEntry":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgeOverNnEntry"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholder\/ageovernnentry","title":"AgeOverNnEntry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AgeOverNnEntry"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Main Classes","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"],"anchor":"Main-Classes"},{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilege","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCode","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier"],"title":"Classes","anchor":"Classes","generated":true},{"title":"Enumerations","generated":true,"anchor":"Enumerations","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["https:\/\/www.iso.org\/standard\/69084.html"]}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/title","value":"XTMdlGender"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/fragments","value":[{"text":"XTMdlGender","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/navigatorTitle","value":[{"text":"XTMdlGender","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes\/title","value":"XTMdlDrivingPrivilegeCodes"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges\/title","value":"XTMdlDrivingPrivileges"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/title","value":"XTMdlHolderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/fragments","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/navigatorTitle","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilege\/title","value":"XTMdlDrivingPrivilege"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilege\/fragments","value":[{"text":"XTMdlDrivingPrivilege","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilege\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDrivingPrivilege","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/title","op":"replace","value":"XTMdlDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/fragments","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate\/title","op":"replace","value":"XTMdlBiometricTemplate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate\/fragments","op":"replace","value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate\/navigatorTitle","value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/title","value":"XTHolderErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCode"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/navigatorTitle","value":[{"text":"XTHolderErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/title","value":"XTMdlDocumentField","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/fragments","value":[{"kind":"identifier","text":"XTMdlDocumentField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocumentField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode\/title","value":"XTMdlDrivingPrivilegeCode"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1loadDocumentWith(token:pin:completion:)\/title","op":"replace","value":"loadDocumentWithToken:pin:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1loadDocumentWith(token:pin:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadDocumentWithToken:pin:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title","value":"XTMdlHolder"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1startDocumentSharing(withPin:delegate:completion:)\/title","op":"replace","value":"startDocumentSharingWithPin:delegate:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1startDocumentSharing(withPin:delegate:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startDocumentSharingWithPin:delegate:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1initialize(completion:)\/title","value":"initializeWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1initialize(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/title","value":"XTAgeOverNnEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/fragments","value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}]},{"value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/navigatorTitle","op":"replace"}]}]}