{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH"],"type":"conformsTo","title":"Conforms To"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader"]]},"topicSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate\/init(templateName:content:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate\/content","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate\/templateName"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdlbiometrictemplate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdlbiometrictemplate"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTMdlBiometricTemplate) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlBiometricTemplate","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"MdlBiometricTemplate","externalID":"c:@M@MdlReader@objc(cs)XTMdlBiometricTemplate","roleHeading":"Class","modules":[{"name":"MdlReader"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"14.0"},{"beta":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlBiometricTemplate","kind":"identifier"}],"symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlBiometricTemplate"}]},"references":{"doc://com.xinfotech.mdlreader/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.xinfotech.mdlreader/s7CVarArgP":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.xinfotech.mdlreader/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","type":"unresolvable"},"doc://com.xinfotech.mdlreader/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlBiometricTemplate/templateName":{"title":"templateName","navigatorTitle":[{"text":"templateName","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Template name. It replaces ‘xx’ in ‘biometric_template_xx’.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templateName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate\/templateName","role":"symbol","url":"\/documentation\/mdlreader\/mdlbiometrictemplate\/templatename"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlBiometricTemplate":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate","abstract":[],"navigatorTitle":[{"text":"MdlBiometricTemplate","kind":"identifier"}],"url":"\/documentation\/mdlreader\/mdlbiometrictemplate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlBiometricTemplate","kind":"identifier"}],"type":"topic","kind":"symbol","title":"MdlBiometricTemplate","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlBiometricTemplate/content":{"url":"\/documentation\/mdlreader\/mdlbiometrictemplate\/content","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"content"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"content","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate\/content","title":"content","type":"topic"},"doc://com.xinfotech.mdlreader/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlBiometricTemplate/init(templateName:content:)":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate\/init(templateName:content:)","type":"topic","url":"\/documentation\/mdlreader\/mdlbiometrictemplate\/init(templatename:content:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"templateName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(templateName:content:)","navigatorTitle":[{"text":"initWithTemplateName:content:","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/SH":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SH","title":"Swift.Hashable"},"doc://com.xinfotech.mdlreader/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"XTMdlBiometricTemplate","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate\/content","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate\/templateName"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlBiometricTemplate\/init(templateName:content:)"]}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlBiometricTemplate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"templateName","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate~1templateName\/title","op":"replace"},{"value":[{"text":"templateName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate~1templateName\/fragments","op":"replace"},{"value":"XTMdlBiometricTemplate","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate\/title","op":"replace"},{"value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate\/fragments","op":"replace"},{"value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate\/navigatorTitle","op":"replace"},{"value":"content","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate~1content\/title","op":"replace"},{"value":[{"text":"content","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate~1content\/fragments","op":"replace"},{"value":"initWithTemplateName:content:","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate~1init(templateName:content:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTemplateName:content:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlBiometricTemplate~1init(templateName:content:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}