{"metadata":{"title":"MdlDrivingPrivileges","externalID":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivileges","roleHeading":"Class","modules":[{"name":"MdlReader"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"14.0","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivileges"}],"symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivileges"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader"]]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTMdlDrivingPrivileges) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivileges","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each element in the "},{"code":"drivingPrivileges","type":"codeVoice"},{"type":"text","text":" array describes a specific privilege the license holder has,"},{"type":"text","text":" "},{"type":"text","text":"such as vehicle categories or conditions."}]},{"type":"aside","style":"note","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"MdlDrivingPrivilege"}]}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL)."}],"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges\/init(drivingPrivileges:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges\/description","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges\/drivingPrivileges"],"generated":true}],"variants":[{"paths":["\/documentation\/mdlreader\/mdldrivingprivileges"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreader\/mdldrivingprivileges"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges"},"sections":[],"references":{"doc://com.xinfotech.mdlreader/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.xinfotech.mdlreader/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivileges":{"abstract":[{"type":"text","text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL)."}],"url":"\/documentation\/mdlreader\/mdldrivingprivileges","title":"MdlDrivingPrivileges","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivileges","kind":"identifier"}],"navigatorTitle":[{"text":"MdlDrivingPrivileges","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivileges/drivingPrivileges":{"title":"drivingPrivileges","navigatorTitle":[{"text":"drivingPrivileges","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"An array of "},{"code":"MdlDrivingPrivilege","type":"codeVoice"},{"type":"text","text":" objects representing individual driving privileges."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drivingPrivileges","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilege"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges\/drivingPrivileges","role":"symbol","url":"\/documentation\/mdlreader\/mdldrivingprivileges\/drivingprivileges"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivileges/description":{"role":"symbol","url":"\/documentation\/mdlreader\/mdldrivingprivileges\/description","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges\/description","title":"description","type":"topic"},"doc://com.xinfotech.mdlreader/SQ":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SH"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivileges/init(drivingPrivileges:)":{"abstract":[{"type":"text","text":"Initializes the container with the provided list of driving privileges."}],"url":"\/documentation\/mdlreader\/mdldrivingprivileges\/init(drivingprivileges:)","title":"init(drivingPrivileges:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges\/init(drivingPrivileges:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"drivingPrivileges"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilege"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"initWithDrivingPrivileges:","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/objc(pl)NSObject":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.xinfotech.mdlreader/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP"},"doc://com.xinfotech.mdlreader/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"beta":false,"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"XTMdlDrivingPrivileges","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges\/description","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges\/drivingPrivileges"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges\/init(drivingPrivileges:)"],"generated":true,"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XTMdlDrivingPrivileges","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges\/title","value":"XTMdlDrivingPrivileges","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges\/fragments","value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges~1drivingPrivileges\/title","value":"drivingPrivileges","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges~1drivingPrivileges\/fragments","value":[{"text":"drivingPrivileges","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges~1init(drivingPrivileges:)\/title","value":"initWithDrivingPrivileges:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges~1init(drivingPrivileges:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDrivingPrivileges:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}