{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader"]]},"metadata":{"title":"MdlDrivingPrivilegeCodes","navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCodes","symbolKind":"class","modules":[{"name":"MdlReader"}]},"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes\/init(codes:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes\/codes"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTMdlDrivingPrivilegeCodes) ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivilegeCodes"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes"},"variants":[{"paths":["\/documentation\/mdlreader\/mdldrivingprivilegecodes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdldrivingprivilegecodes"]}],"references":{"doc://com.xinfotech.mdlreader/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"},"doc://com.xinfotech.mdlreader/SQ":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.xinfotech.mdlreader/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject"},"doc://com.xinfotech.mdlreader/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCodes/init(codes:)":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes\/init(codes:)","kind":"symbol","title":"init(codes:)","url":"\/documentation\/mdlreader\/mdldrivingprivilegecodes\/init(codes:)","navigatorTitle":[{"kind":"identifier","text":"initWithCodes:"}],"abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCode","kind":"typeIdentifier","text":"MdlDrivingPrivilegeCode"},{"kind":"text","text":"])"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCodes/codes":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes\/codes","kind":"symbol","url":"\/documentation\/mdlreader\/mdldrivingprivilegecodes\/codes","title":"codes","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCode","kind":"typeIdentifier","text":"MdlDrivingPrivilegeCode"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"codes"}],"abstract":[]},"doc://com.xinfotech.mdlreader/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"},"doc://com.xinfotech.mdlreader/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCodes":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes","url":"\/documentation\/mdlreader\/mdldrivingprivilegecodes","title":"MdlDrivingPrivilegeCodes","kind":"symbol","navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"XTMdlDrivingPrivilegeCodes","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes\/codes"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes\/init(codes:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithCodes:","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes~1init(codes:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCodes:"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes~1init(codes:)\/fragments"},{"value":"codes","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes~1codes\/title"},{"value":[{"kind":"identifier","text":"codes"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes~1codes\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/title","op":"replace","value":"XTMdlDrivingPrivilegeCodes"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/fragments","op":"replace","value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}]}]}]}