{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(XTMdlDocument) "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"abstract":[{"text":"Representation of mDL document","type":"text"}],"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/administrativeNumber","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/ageBirthYear","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/ageInYears","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/ageOverNn","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/biometricTemplateXx","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/birthDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/birthPlace","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/bloodGroup","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/dlExpiryDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/dlIssueDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/documentNumber","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/drivingPrivileges","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/drivingRestrictions","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/expiryDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/eyeColour","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/familyName","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/familyNameNationalCharacter","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/givenName","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/givenNameNationalCharacter","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/hairColour","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/height","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/holderIdNumber","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issueDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issuingAuthority","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issuingCountry","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issuingJurisdiction","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/nationality","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/portrait","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/portraitCaptureDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentAddress","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentCity","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentCountry","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentPostalCode","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentState","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/sex","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/signatureUsualMark","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/unDistinguishingSign","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/weight"]}],"metadata":{"title":"MdlDocument","externalID":"c:@M@MdlReader@objc(cs)XTMdlDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"symbolKind":"class","roleHeading":"Class","modules":[{"name":"MdlReader"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdldocument"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdldocument"]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/sex":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/sex","title":"sex","url":"\/documentation\/mdlreader\/mdldocument\/sex","kind":"symbol","navigatorTitle":[{"text":"sex","kind":"identifier"}],"abstract":[{"type":"text","text":"mDL holder’s sex."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlGender","preciseIdentifier":"c:@M@MdlReader@E@XTMdlGender","kind":"typeIdentifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/height":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/height","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/height","title":"height","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"height"}],"abstract":[{"text":"mDL holder’s height in centimeters.","type":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/holderIdNumber":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/holderIdNumber","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/holderidnumber","title":"holderIdNumber","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"holderIdNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"holderIdNumber","kind":"identifier"}],"abstract":[{"text":"mDL holder’s national ID or alien ID, or diplomatic ID","type":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/dlExpiryDate":{"abstract":[{"text":"Date of expiry of eDL (physical document) issued to mDL holder","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dlExpiryDate"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/dlExpiryDate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dlExpiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"title":"dlExpiryDate","url":"\/documentation\/mdlreader\/mdldocument\/dlexpirydate","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/unDistinguishingSign":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/unDistinguishingSign","url":"\/documentation\/mdlreader\/mdldocument\/undistinguishingsign","title":"unDistinguishingSign","kind":"symbol","navigatorTitle":[{"text":"unDistinguishingSign","kind":"identifier"}],"abstract":[{"type":"text","text":"UN Distinguishing sign."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unDistinguishingSign","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/givenNameNationalCharacter":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/givenNameNationalCharacter","kind":"symbol","title":"givenNameNationalCharacter","url":"\/documentation\/mdlreader\/mdldocument\/givennamenationalcharacter","navigatorTitle":[{"kind":"identifier","text":"givenNameNationalCharacter"}],"abstract":[{"text":"The given name of the mDL holder using full UTF-8 character set.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenNameNationalCharacter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/portraitCaptureDate":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/portraitCaptureDate","kind":"symbol","title":"portraitCaptureDate","url":"\/documentation\/mdlreader\/mdldocument\/portraitcapturedate","navigatorTitle":[{"text":"portraitCaptureDate","kind":"identifier"}],"abstract":[{"type":"text","text":"Date when portrait was taken."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portraitCaptureDate","kind":"identifier"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/givenName":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/givenName","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/givenname","title":"givenName","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"givenName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"givenName","kind":"identifier"}],"abstract":[{"text":"First name(s), other name(s), or secondary identifier, of the mDL holder.","type":"text"}]},"doc://com.xinfotech.mdlreader/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP"},"doc://com.xinfotech.mdlreader/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ","title":"Swift.Equatable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/drivingPrivileges":{"url":"\/documentation\/mdlreader\/mdldocument\/drivingprivileges","title":"drivingPrivileges","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/drivingPrivileges","navigatorTitle":[{"text":"drivingPrivileges","kind":"identifier"}],"abstract":[{"type":"text","text":"Driving privileges of the mDL holder. Categories of vehicles\/restrictions\/conditions. (zero or more)"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drivingPrivileges","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivileges","text":"MdlDrivingPrivileges","kind":"typeIdentifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/drivingRestrictions":{"url":"\/documentation\/mdlreader\/mdldocument\/drivingrestrictions","title":"drivingRestrictions","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/drivingRestrictions","kind":"symbol","navigatorTitle":[{"text":"drivingRestrictions","kind":"identifier"}],"abstract":[{"type":"text","text":"Driver’s restrictions"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drivingRestrictions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/issuingJurisdiction":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issuingJurisdiction","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/issuingjurisdiction","title":"issuingJurisdiction","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingJurisdiction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"issuingJurisdiction","kind":"identifier"}],"abstract":[{"type":"text","text":"Country subdivision code of the jurisdiction that issued the mDL. The first part of the code shall be the same as the value for issuing country."}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)":{"url":"\/documentation\/mdlreader\/mdldocument\/init(familyname:givenname:birthdate:issuedate:expirydate:issuingcountry:issuingauthority:documentnumber:portrait:drivingprivileges:undistinguishingsign:holderidnumber:bloodgroup:dlissuedate:dlexpirydate:drivingrestrictions:administrativenum-1g6bl","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","title":"init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","navigatorTitle":[{"text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"familyName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"givenName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"birthDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"issueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"issuingCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"issuingAuthority","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"portrait"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingPrivileges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlDrivingPrivileges","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivileges"},{"kind":"text","text":", "},{"kind":"externalParam","text":"unDistinguishingSign"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"holderIdNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bloodGroup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlIssueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlExpiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingRestrictions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"administrativeNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@E@XTMdlGender","text":"MdlGender"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eyeColour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hairColour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"birthPlace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"portraitCaptureDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageInYears"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageBirthYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageOverNn"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTAgeOverNnEntry","text":"AgeOverNnEntry"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"issuingJurisdiction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nationality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentCity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentPostalCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlBiometricTemplate","text":"MdlBiometricTemplate"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"familyNameNationalCharacter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"givenNameNationalCharacter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"signatureUsualMark","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/bloodGroup":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/bloodGroup","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/bloodgroup","title":"bloodGroup","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bloodGroup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"bloodGroup"}],"abstract":[{"type":"text","text":"mDL holder’s blood group"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/residentCountry":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentCountry","url":"\/documentation\/mdlreader\/mdldocument\/residentcountry","title":"residentCountry","kind":"symbol","navigatorTitle":[{"text":"residentCountry","kind":"identifier"}],"abstract":[{"type":"text","text":"The country where the mDL holder lives as the two letter country code."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentCountry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/residentState":{"url":"\/documentation\/mdlreader\/mdldocument\/residentstate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentState","title":"residentState","kind":"symbol","navigatorTitle":[{"text":"residentState","kind":"identifier"}],"abstract":[{"text":"The state\/province\/district where the mDL holder lives.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentState","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/ageBirthYear":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/ageBirthYear","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/agebirthyear","title":"ageBirthYear","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageBirthYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"ageBirthYear"}],"abstract":[{"type":"text","text":"The year when the mDL holder was born.  Age attestation: In what year where you born?"}]},"doc://com.xinfotech.mdlreader/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/birthPlace":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/birthPlace","url":"\/documentation\/mdlreader\/mdldocument\/birthplace","title":"birthPlace","kind":"symbol","navigatorTitle":[{"text":"birthPlace","kind":"identifier"}],"abstract":[{"text":"Country and municipality or state\/province where the mDL holder was born.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"birthPlace","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/familyNameNationalCharacter":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/familyNameNationalCharacter","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/familynamenationalcharacter","title":"familyNameNationalCharacter","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"familyNameNationalCharacter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"familyNameNationalCharacter","kind":"identifier"}],"abstract":[{"type":"text","text":"The family name of the mDL holder using full UTF-8 character set."}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/signatureUsualMark":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/signatureUsualMark","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/signatureusualmark","title":"signatureUsualMark","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureUsualMark"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"signatureUsualMark"}],"abstract":[{"text":"Image of the signature or usual mark of the mDL holder.","type":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/biometricTemplateXx":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/biometricTemplateXx","title":"biometricTemplateXx","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/biometrictemplatexx","navigatorTitle":[{"kind":"identifier","text":"biometricTemplateXx"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MdlBiometricTemplate","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlBiometricTemplate"},{"kind":"text","text":"]?"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/administrativeNumber":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/administrativeNumber","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/administrativenumber","title":"administrativeNumber","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"administrativeNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"administrativeNumber"}],"abstract":[{"text":"An audit control number assignet by the issuing authority.","type":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/nationality":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/nationality","title":"nationality","url":"\/documentation\/mdlreader\/mdldocument\/nationality","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nationality"}],"abstract":[{"type":"text","text":"Nationality of the mDL holder as two letter country code."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nationality"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/birthDate":{"role":"symbol","title":"birthDate","navigatorTitle":[{"text":"birthDate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"birthDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/birthDate","abstract":[{"type":"text","text":"Day, month and year on which the mDL holder was born. If unknown, approximate date of birth."}],"url":"\/documentation\/mdlreader\/mdldocument\/birthdate"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/portrait":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/portrait","title":"portrait","url":"\/documentation\/mdlreader\/mdldocument\/portrait","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"portrait"}],"abstract":[{"type":"text","text":"A reproduction of the mDL holder’s portrait."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"type":"topic"},"doc://com.xinfotech.mdlreader/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/ageOverNn":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/ageOverNn","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/ageovernn","title":"ageOverNn","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageOverNn"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgeOverNnEntry","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTAgeOverNnEntry"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"ageOverNn"}],"abstract":[{"text":"Age attestation: Nearest “true” attestation above request.","type":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/familyName":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/familyName","url":"\/documentation\/mdlreader\/mdldocument\/familyname","title":"familyName","kind":"symbol","navigatorTitle":[{"text":"familyName","kind":"identifier"}],"abstract":[{"type":"text","text":"Last name, surname or primary identifier, of the mDL holder."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"familyName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/residentPostalCode":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentPostalCode","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/residentpostalcode","title":"residentPostalCode","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentPostalCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"residentPostalCode","kind":"identifier"}],"abstract":[{"type":"text","text":"The postal code of the mDL holder."}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/issuingCountry":{"role":"symbol","title":"issuingCountry","navigatorTitle":[{"kind":"identifier","text":"issuingCountry"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issuingCountry","abstract":[{"type":"text","text":"Alpha-2 country code of the issuing authority’s country or territory."}],"url":"\/documentation\/mdlreader\/mdldocument\/issuingcountry"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/issueDate":{"abstract":[{"type":"text","text":"Date when mDL was issued."}],"navigatorTitle":[{"kind":"identifier","text":"issueDate"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issueDate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"title":"issueDate","url":"\/documentation\/mdlreader\/mdldocument\/issuedate","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/residentCity":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentCity","title":"residentCity","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/residentcity","navigatorTitle":[{"kind":"identifier","text":"residentCity"}],"abstract":[{"type":"text","text":"The city where the mDL holder lives."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentCity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/eyeColour":{"role":"symbol","title":"eyeColour","navigatorTitle":[{"text":"eyeColour","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeColour","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/eyeColour","abstract":[{"text":"mDL holder’s eye colour. The value shall be one of the following: “black”, “blue”, “brown”, “dichromatic”, “grey”, “green”, “hazel”, “maroon”, “pink”, “unknown”.","type":"text"}],"url":"\/documentation\/mdlreader\/mdldocument\/eyecolour"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/ageInYears":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/ageInYears","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/ageinyears","title":"ageInYears","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageInYears"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"ageInYears"}],"abstract":[{"text":"The age of the mDL holder.  Age attestation: How old are you (in years)?","type":"text"}]},"doc://com.xinfotech.mdlreader/s7CVarArgP":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/residentAddress":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentAddress","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/residentaddress","title":"residentAddress","navigatorTitle":[{"text":"residentAddress","kind":"identifier"}],"abstract":[{"type":"text","text":"Permanent place of residence. The place where the mDL holder resides and\/or may be contacted (street\/house number, municipality etc.)."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentAddress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://com.xinfotech.mdlreader/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SH","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/hairColour":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/hairColour","kind":"symbol","title":"hairColour","url":"\/documentation\/mdlreader\/mdldocument\/haircolour","navigatorTitle":[{"kind":"identifier","text":"hairColour"}],"abstract":[{"text":"mDL holder’s hair colour. One of these values: “bald”, “black”, “blond”, “brown”, “grey”, “red”, “auburn”, “sandy”, “white”, “unknown”.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hairColour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/dlIssueDate":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/dlIssueDate","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/dlissuedate","title":"dlIssueDate","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dlIssueDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"navigatorTitle":[{"text":"dlIssueDate","kind":"identifier"}],"abstract":[{"text":"Date of issue of eDL (physical document) issued to mDL holder","type":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/documentNumber":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/documentNumber","kind":"symbol","title":"documentNumber","url":"\/documentation\/mdlreader\/mdldocument\/documentnumber","navigatorTitle":[{"text":"documentNumber","kind":"identifier"}],"abstract":[{"type":"text","text":"The number assigned or calculated by the issuing authority."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"documentNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/issuingAuthority":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issuingAuthority","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/issuingauthority","title":"issuingAuthority","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuingAuthority"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"issuingAuthority"}],"abstract":[{"text":"Issuing authority name.","type":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/expiryDate":{"role":"symbol","title":"expiryDate","navigatorTitle":[{"kind":"identifier","text":"expiryDate"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/expiryDate","abstract":[{"text":"Date when mDL expires.","type":"text"}],"url":"\/documentation\/mdlreader\/mdldocument\/expirydate"},"doc://com.xinfotech.mdlreader/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject","title":"NSObject"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument":{"type":"topic","url":"\/documentation\/mdlreader\/mdldocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"kind":"symbol","title":"MdlDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument","abstract":[{"type":"text","text":"Representation of mDL document"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocument/weight":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mdlreader\/mdldocument\/weight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"weight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"text":"mDL holder’s weigth in kilograms.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/weight","navigatorTitle":[{"kind":"identifier","text":"weight"}],"title":"weight"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"XTMdlDocument"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/administrativeNumber","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/ageBirthYear","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/ageInYears","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/ageOverNn","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/biometricTemplateXx","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/birthDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/birthPlace","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/bloodGroup","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/dlExpiryDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/dlIssueDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/documentNumber","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/drivingPrivileges","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/drivingRestrictions","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/expiryDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/eyeColour","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/familyName","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/familyNameNationalCharacter","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/givenName","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/givenNameNationalCharacter","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/hairColour","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/height","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/holderIdNumber","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issueDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issuingAuthority","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issuingCountry","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/issuingJurisdiction","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/nationality","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/portrait","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/portraitCaptureDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentAddress","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentCity","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentCountry","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentPostalCode","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/residentState","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/sex","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/signatureUsualMark","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/unDistinguishingSign","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/weight"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlDocument"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"sex","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1sex\/title"},{"op":"replace","value":[{"text":"sex","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1sex\/fragments"},{"op":"replace","value":"height","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1height\/title"},{"op":"replace","value":[{"kind":"identifier","text":"height"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1height\/fragments"},{"op":"replace","value":"holderIdNumber","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1holderIdNumber\/title"},{"value":[{"text":"holderIdNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1holderIdNumber\/fragments","op":"replace"},{"value":"dlExpiryDate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1dlExpiryDate\/title"},{"op":"replace","value":[{"text":"dlExpiryDate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1dlExpiryDate\/fragments"},{"value":"unDistinguishingSign","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1unDistinguishingSign\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1unDistinguishingSign\/fragments","value":[{"text":"unDistinguishingSign","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1givenNameNationalCharacter\/title","value":"givenNameNationalCharacter"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1givenNameNationalCharacter\/fragments","value":[{"kind":"identifier","text":"givenNameNationalCharacter"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1portraitCaptureDate\/title","value":"portraitCaptureDate","op":"replace"},{"value":[{"text":"portraitCaptureDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1portraitCaptureDate\/fragments"},{"value":"givenName","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1givenName\/title"},{"value":[{"kind":"identifier","text":"givenName"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1givenName\/fragments"},{"value":"drivingPrivileges","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1drivingPrivileges\/title"},{"value":[{"text":"drivingPrivileges","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1drivingPrivileges\/fragments"},{"value":"drivingRestrictions","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1drivingRestrictions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"drivingRestrictions"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1drivingRestrictions\/fragments"},{"op":"replace","value":"issuingJurisdiction","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1issuingJurisdiction\/title"},{"op":"replace","value":[{"text":"issuingJurisdiction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1issuingJurisdiction\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/title","value":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1bloodGroup\/title","value":"bloodGroup"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1bloodGroup\/fragments","value":[{"text":"bloodGroup","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1residentCountry\/title","value":"residentCountry"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1residentCountry\/fragments","value":[{"kind":"identifier","text":"residentCountry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1residentState\/title","value":"residentState"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1residentState\/fragments","value":[{"text":"residentState","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1ageBirthYear\/title","value":"ageBirthYear"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1ageBirthYear\/fragments","value":[{"kind":"identifier","text":"ageBirthYear"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1birthPlace\/title","value":"birthPlace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1birthPlace\/fragments","value":[{"text":"birthPlace","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1familyNameNationalCharacter\/title","value":"familyNameNationalCharacter"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1familyNameNationalCharacter\/fragments","value":[{"text":"familyNameNationalCharacter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1signatureUsualMark\/title","op":"replace","value":"signatureUsualMark"},{"value":[{"text":"signatureUsualMark","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1signatureUsualMark\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1biometricTemplateXx\/title","value":"biometricTemplateXx"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1biometricTemplateXx\/fragments","value":[{"kind":"identifier","text":"biometricTemplateXx"}]},{"value":"administrativeNumber","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1administrativeNumber\/title"},{"value":[{"text":"administrativeNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1administrativeNumber\/fragments","op":"replace"},{"value":"nationality","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1nationality\/title","op":"replace"},{"value":[{"text":"nationality","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1nationality\/fragments","op":"replace"},{"value":"birthDate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1birthDate\/title"},{"value":[{"text":"birthDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1birthDate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1portrait\/title","value":"portrait"},{"value":[{"kind":"identifier","text":"portrait"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1portrait\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1ageOverNn\/title","value":"ageOverNn"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1ageOverNn\/fragments","value":[{"kind":"identifier","text":"ageOverNn"}]},{"value":"familyName","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1familyName\/title","op":"replace"},{"value":[{"text":"familyName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1familyName\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1residentPostalCode\/title","value":"residentPostalCode"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1residentPostalCode\/fragments","value":[{"kind":"identifier","text":"residentPostalCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1issuingCountry\/title","value":"issuingCountry"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1issuingCountry\/fragments","value":[{"kind":"identifier","text":"issuingCountry"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1issueDate\/title","op":"replace","value":"issueDate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1issueDate\/fragments","op":"replace","value":[{"kind":"identifier","text":"issueDate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1residentCity\/title","op":"replace","value":"residentCity"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1residentCity\/fragments","op":"replace","value":[{"kind":"identifier","text":"residentCity"}]},{"value":"eyeColour","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1eyeColour\/title"},{"value":[{"text":"eyeColour","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1eyeColour\/fragments"},{"value":"ageInYears","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1ageInYears\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ageInYears"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1ageInYears\/fragments","op":"replace"},{"value":"residentAddress","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1residentAddress\/title","op":"replace"},{"value":[{"text":"residentAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1residentAddress\/fragments","op":"replace"},{"value":"hairColour","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1hairColour\/title","op":"replace"},{"value":[{"text":"hairColour","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1hairColour\/fragments","op":"replace"},{"op":"replace","value":"dlIssueDate","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1dlIssueDate\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1dlIssueDate\/fragments","op":"replace","value":[{"text":"dlIssueDate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1documentNumber\/title","value":"documentNumber"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1documentNumber\/fragments","value":[{"kind":"identifier","text":"documentNumber"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1issuingAuthority\/title","value":"issuingAuthority","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1issuingAuthority\/fragments","value":[{"text":"issuingAuthority","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1expiryDate\/title","value":"expiryDate","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1expiryDate\/fragments","value":[{"kind":"identifier","text":"expiryDate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/title","value":"XTMdlDocument","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/fragments","value":[{"text":"XTMdlDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument\/navigatorTitle","value":[{"text":"XTMdlDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1weight\/title","value":"weight","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"weight"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocument~1weight\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}