{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader"]]},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCode","platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilegeCode"}],"roleHeading":"Class","title":"MdlDrivingPrivilegeCode","modules":[{"name":"MdlReader"}],"symbolKind":"class"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTMdlDrivingPrivilegeCode) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode\/init(code:sign:value:)"]},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode\/code","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode\/sign","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode\/value"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdldrivingprivilegecode"]},{"paths":["\/documentation\/mdlreader\/mdldrivingprivilegecode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode"},"sections":[],"references":{"doc://com.xinfotech.mdlreader/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.xinfotech.mdlreader/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCode/init(code:sign:value:)":{"title":"init(code:sign:value:)","navigatorTitle":[{"kind":"identifier","text":"initWithCode:sign:value:"}],"kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"sign","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode\/init(code:sign:value:)","role":"symbol","url":"\/documentation\/mdlreader\/mdldrivingprivilegecode\/init(code:sign:value:)"},"doc://com.xinfotech.mdlreader/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCode/sign":{"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode\/sign","url":"\/documentation\/mdlreader\/mdldrivingprivilegecode\/sign","kind":"symbol","title":"sign","type":"topic","abstract":[{"type":"text","text":"Sign as per ISO\/IEC 18013-2 Annex A"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sign","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"sign","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCode":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode","abstract":[],"navigatorTitle":[{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"url":"\/documentation\/mdlreader\/mdldrivingprivilegecode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"MdlDrivingPrivilegeCode","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCode/value":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"value","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Value as per ISO\/IEC 18013-2 Annex A","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode\/value","title":"value","url":"\/documentation\/mdlreader\/mdldrivingprivilegecode\/value"},"doc://com.xinfotech.mdlreader/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ","title":"Swift.Equatable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCode/code":{"role":"symbol","url":"\/documentation\/mdlreader\/mdldrivingprivilegecode\/code","abstract":[{"text":"Code as per ISO\/IEC 18013-2 Annex A.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"code","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode\/code","title":"code","type":"topic"},"doc://com.xinfotech.mdlreader/SH":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"14.0","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"14.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0","beta":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"XTMdlDrivingPrivilegeCode","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode\/code","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode\/sign","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode\/value"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode\/init(code:sign:value:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode~1init(code:sign:value:)\/title","value":"initWithCode:sign:value:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode~1init(code:sign:value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCode:sign:value:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode~1sign\/title","value":"sign","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode~1sign\/fragments","value":[{"kind":"identifier","text":"sign"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode\/title","value":"XTMdlDrivingPrivilegeCode","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode~1value\/title","value":"value","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode~1value\/fragments","value":[{"kind":"identifier","text":"value"}],"op":"replace"},{"value":"code","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode~1code\/title"},{"value":[{"kind":"identifier","text":"code"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode~1code\/fragments","op":"replace"}]}]}