{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader"]]},"kind":"symbol","metadata":{"externalID":"c:@M@MdlReader@E@XTMdlGender","navigatorTitle":[{"kind":"identifier","text":"MdlGender"}],"title":"MdlGender","modules":[{"name":"MdlReader"}],"symbolKind":"enum","role":"symbol","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}]},"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/female","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/male","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/notApplicable","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/notKnown"],"title":"Enumeration Cases","generated":true},{"anchor":"Initializers","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/init(rawValue:)"],"title":"Initializers","generated":true},{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/Equatable-Implementations","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH","doc:\/\/com.xinfotech.mdlreader\/SY"],"kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(XTMdlGender) "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlGender"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdlgender"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdlgender"]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlGender/notApplicable":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/notApplicable","title":"MdlGender.notApplicable","url":"\/documentation\/mdlreader\/mdlgender\/notapplicable","kind":"symbol","navigatorTitle":[{"text":"XTMdlGenderNotApplicable","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notApplicable","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlGender/Equatable-Implementations":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/Equatable-Implementations","kind":"article","url":"\/documentation\/mdlreader\/mdlgender\/equatable-implementations","title":"Equatable Implementations","type":"topic","role":"collectionGroup","abstract":[]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlGender/notKnown":{"url":"\/documentation\/mdlreader\/mdlgender\/notknown","title":"MdlGender.notKnown","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/notKnown","navigatorTitle":[{"kind":"identifier","text":"XTMdlGenderNotKnown"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notKnown"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlGender/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/init(rawValue:)","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/mdlreader\/mdlgender\/init(rawvalue:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlGender":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender","kind":"symbol","title":"MdlGender","url":"\/documentation\/mdlreader\/mdlgender","navigatorTitle":[{"kind":"identifier","text":"MdlGender"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlGender"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlGender/female":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/female","title":"MdlGender.female","kind":"symbol","url":"\/documentation\/mdlreader\/mdlgender\/female","navigatorTitle":[{"kind":"identifier","text":"XTMdlGenderFemale"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"female"}],"type":"topic"},"doc://com.xinfotech.mdlreader/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ"},"doc://com.xinfotech.mdlreader/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SH"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlGender/male":{"navigatorTitle":[{"kind":"identifier","text":"XTMdlGenderMale"}],"title":"MdlGender.male","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/male","kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"male"}],"url":"\/documentation\/mdlreader\/mdlgender\/male"},"doc://com.xinfotech.mdlreader/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SY"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlGender/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/mdlreader\/mdlgender\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"XTMdlGender"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"kind":"identifier","text":"XTMdlGender"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"XTMdlGender","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/female","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/male","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/notApplicable","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/notKnown"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XTMdlGender","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender~1notApplicable\/title","value":"XTMdlGenderNotApplicable","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender~1notApplicable\/fragments","value":[{"text":"XTMdlGenderNotApplicable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender~1notKnown\/title","op":"replace","value":"XTMdlGenderNotKnown"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender~1notKnown\/fragments","op":"replace","value":[{"text":"XTMdlGenderNotKnown","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender\/title","op":"replace","value":"XTMdlGender"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender\/fragments","op":"replace","value":[{"text":"XTMdlGender","kind":"identifier"}]},{"value":[{"text":"XTMdlGender","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender\/navigatorTitle","op":"replace"},{"op":"replace","value":"XTMdlGenderFemale","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender~1female\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlGenderFemale"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender~1female\/fragments"},{"op":"replace","value":"XTMdlGenderMale","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender~1male\/title"},{"value":[{"text":"XTMdlGenderMale","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender~1male\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}