{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader"]]},"kind":"symbol","metadata":{"title":"MdlReaderDelegate","externalID":"c:@M@MdlReader@objc(pl)XTMdlReaderDelegate","roleHeading":"Protocol","modules":[{"name":"MdlReader"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"14.0"},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"14.0"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReaderDelegate","kind":"identifier"}],"symbolKind":"protocol","role":"symbol","navigatorTitle":[{"text":"MdlReaderDelegate","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTMdlReaderDelegate) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReaderDelegate","kind":"identifier"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"Methods of this protocol inform your app about connection state changes, data transfer progress, received document fields,","type":"text"},{"text":" ","type":"text"},{"text":"and errors during the reading process.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Provides delegate callbacks for the "},{"type":"codeVoice","code":"MdlReader"},{"type":"text","text":" framework during mDL document retrieval and data exchange."}],"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDidReceiveDocumentFields(_:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDidReceiveError(_:)"],"generated":true,"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdlreaderdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdlreaderdelegate"]}],"seeAlsoSections":[{"anchor":"Main-Classes","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"],"generated":true,"title":"Main Classes"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate"},"sections":[],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate/mdlReaderDataTransferProgress(transfered:total:)":{"title":"mdlReaderDataTransferProgress(transfered:total:)","navigatorTitle":[{"text":"mdlReaderDataTransferProgressWithTransfered:total:","kind":"identifier"}],"required":true,"kind":"symbol","abstract":[{"type":"emphasis","inlineContent":[{"type":"text","text":"(Optional)"}]},{"type":"text","text":" Reports the progress of data transfer from the Holder."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderDataTransferProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"transfered","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"total","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)","role":"symbol","defaultImplementations":1,"url":"\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderdatatransferprogress(transfered:total:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate":{"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","type":"topic","abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"type":"codeVoice","code":"MdlReader"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"url":"\/documentation\/mdlreader\/mdlreaderdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReaderDelegate","kind":"identifier"}],"title":"MdlReaderDelegate","navigatorTitle":[{"text":"MdlReaderDelegate","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlFieldIdentifier":{"url":"\/documentation\/mdlreader\/mdlfieldidentifier","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"abstract":[{"text":"Provides predefined field identifiers used in mDL documents.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","title":"MdlFieldIdentifier","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ReaderErrorCode"}],"url":"\/documentation\/mdlreader\/readererrorcode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReaderErrorCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ReaderErrorCode","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocumentField":{"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField","url":"\/documentation\/mdlreader\/mdldocumentfield","kind":"symbol","title":"MdlDocumentField","type":"topic","abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocumentField","kind":"identifier"}],"navigatorTitle":[{"text":"MdlDocumentField","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate/mdlReaderConnectionStatusChanged(isHolderConnected:)":{"title":"mdlReaderConnectionStatusChanged(isHolderConnected:)","navigatorTitle":[{"text":"mdlReaderConnectionStatusChangedWithIsHolderConnected:","kind":"identifier"}],"required":true,"kind":"symbol","abstract":[{"type":"emphasis","inlineContent":[{"type":"text","text":"(Optional)"}]},{"type":"text","text":" Notifies about a change in connection status with the Holder."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderConnectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isHolderConnected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)","role":"symbol","defaultImplementations":1,"url":"\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderconnectionstatuschanged(isholderconnected:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate/mdlReaderDidReceiveError(_:)":{"title":"mdlReaderDidReceiveError(_:)","navigatorTitle":[{"text":"mdlReaderDidReceiveError:","kind":"identifier"}],"required":true,"kind":"symbol","abstract":[{"type":"text","text":"Called when an error occurs during communication with the mDL Holder."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderDidReceiveError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDidReceiveError(_:)","role":"symbol","url":"\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderdidreceiveerror(_:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate/mdlReaderDidReceiveDocumentFields(_:)":{"title":"mdlReaderDidReceiveDocumentFields(_:)","navigatorTitle":[{"text":"mdlReaderDidReceiveDocumentFields:","kind":"identifier"}],"required":true,"kind":"symbol","abstract":[{"type":"text","text":"Called when the Reader successfully receives document fields from the Holder."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlReaderDidReceiveDocumentFields","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDocumentField","text":"MdlDocumentField","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDidReceiveDocumentFields(_:)","role":"symbol","url":"\/documentation\/mdlreader\/mdlreaderdelegate\/mdlreaderdidreceivedocumentfields(_:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader":{"kind":"symbol","abstract":[{"text":"Main class of the SDK","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader","type":"topic","url":"\/documentation\/mdlreader\/mdlreader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReader","kind":"identifier"}],"title":"MdlReader","navigatorTitle":[{"text":"MdlReader","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"14.0"},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"14.0"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0"}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"XTMdlReaderDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderConnectionStatusChanged(isHolderConnected:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDataTransferProgress(transfered:total:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDidReceiveDocumentFields(_:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate\/mdlReaderDidReceiveError(_:)"],"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Main Classes","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"],"anchor":"Main-Classes"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XTMdlReaderDelegate","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderDataTransferProgress(transfered:total:)\/title","value":"mdlReaderDataTransferProgressWithTransfered:total:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderDataTransferProgress(transfered:total:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlReaderDataTransferProgressWithTransfered:total:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/title","value":"XTMdlReaderDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/fragments","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/fragments","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/title","value":"XTReaderErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"XTReaderErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/title","value":"XTMdlDocumentField","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/fragments","value":[{"kind":"identifier","text":"XTMdlDocumentField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocumentField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderConnectionStatusChanged(isHolderConnected:)\/title","value":"mdlReaderConnectionStatusChangedWithIsHolderConnected:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderConnectionStatusChanged(isHolderConnected:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlReaderConnectionStatusChangedWithIsHolderConnected:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderDidReceiveError(_:)\/title","value":"mdlReaderDidReceiveError:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderDidReceiveError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlReaderDidReceiveError:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderDidReceiveDocumentFields(_:)\/title","value":"mdlReaderDidReceiveDocumentFields:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate~1mdlReaderDidReceiveDocumentFields(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlReaderDidReceiveDocumentFields:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/title","value":"XTMdlReader","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/fragments","value":[{"kind":"identifier","text":"XTMdlReader"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlReader"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}