{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"MdlReader"}],"externalID":"c:@M@MdlReader@objc(cs)MdlReader","title":"MdlReader","role":"symbol","roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlReader"}],"navigatorTitle":[{"kind":"identifier","text":"MdlReader"}]},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/isPersonalized"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/initialize()","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/initialize(completion:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/personalizeWith(token:pin:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/personalizeWith(token:pin:completion:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/removePersonalization()","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/startRequestDocument(fields:isOnline:engagement:pin:delegate:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/stopRequestDocument()","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/updateRootCertificates()","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/updateRootCertificates(completion:)"],"generated":true},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/sdkVersion","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/shared"],"generated":true}],"seeAlsoSections":[{"anchor":"Main-Classes","title":"Main Classes","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"],"generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlReader"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader"]]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH"],"kind":"relationships"}],"abstract":[{"type":"text","text":"Main class of the SDK"}],"variants":[{"paths":["\/documentation\/mdlreader\/mdlreader"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreader\/mdlreader"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/sdkVersion":{"role":"symbol","title":"sdkVersion","navigatorTitle":[{"kind":"identifier","text":"sdkVersion"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkVersion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/sdkVersion","abstract":[{"text":"Framework version","type":"text"}],"url":"\/documentation\/mdlreader\/mdlreader\/sdkversion"},"doc://com.xinfotech.mdlreader/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/startRequestDocument(fields:isOnline:engagement:pin:delegate:)":{"title":"startRequestDocument(fields:isOnline:engagement:pin:delegate:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/startRequestDocument(fields:isOnline:engagement:pin:delegate:)","kind":"symbol","type":"topic","abstract":[{"text":"This method initializes the document request process and sends the request to the holder.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRequestDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"isOnline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"engagement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlReaderDelegate","preciseIdentifier":"c:@M@MdlReader@objc(pl)XTMdlReaderDelegate"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/mdlreader\/mdlreader\/startrequestdocument(fields:isonline:engagement:pin:delegate:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/updateRootCertificates(completion:)":{"role":"symbol","title":"updateRootCertificates(completion:)","navigatorTitle":[{"text":"updateRootCertificatesWithCompletion:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateRootCertificates","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/updateRootCertificates(completion:)","abstract":[{"text":"Downloads CA Root certificates and updates them in the local SDK storage","type":"text"}],"url":"\/documentation\/mdlreader\/mdlreader\/updaterootcertificates(completion:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlFieldIdentifier":{"type":"topic","url":"\/documentation\/mdlreader\/mdlfieldidentifier","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"kind":"symbol","title":"MdlFieldIdentifier","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}]},"doc://com.xinfotech.mdlreader/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/initialize(completion:)":{"navigatorTitle":[{"text":"initializeWithCompletion:","kind":"identifier"}],"title":"initialize(completion:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/initialize(completion:)","kind":"symbol","type":"topic","abstract":[{"text":"SDK initialization","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/mdlreader\/mdlreader\/initialize(completion:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/personalizeWith(token:pin:completion:)":{"navigatorTitle":[{"text":"personalizeWithToken:pin:completion:","kind":"identifier"}],"title":"personalizeWith(token:pin:completion:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/personalizeWith(token:pin:completion:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This method personalizes the Reader App, downloads the necessary certificates and saves them in the secure SDK storage"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalizeWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/mdlreader\/mdlreader\/personalizewith(token:pin:completion:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocumentField":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField","kind":"symbol","url":"\/documentation\/mdlreader\/mdldocumentfield","title":"MdlDocumentField","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocumentField"}],"navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/removePersonalization()":{"role":"symbol","title":"removePersonalization()","navigatorTitle":[{"text":"removePersonalization","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removePersonalization","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/removePersonalization()","abstract":[{"text":"This method deletes all data (keys, certificates, etc.) from the local SDK storage.","type":"text"}],"url":"\/documentation\/mdlreader\/mdlreader\/removepersonalization()"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/shared":{"navigatorTitle":[{"text":"shared","kind":"identifier"}],"title":"shared","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/shared","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The shared framework instance"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)MdlReader","text":"MdlReader","kind":"typeIdentifier"}],"url":"\/documentation\/mdlreader\/mdlreader\/shared"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/personalizeWith(token:pin:)":{"title":"personalizeWith(token:pin:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/personalizeWith(token:pin:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This method personalizes the Reader App, downloads the necessary certificates and saves them in the secure SDK storage"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalizeWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pin"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/mdlreader\/mdlreader\/personalizewith(token:pin:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate":{"navigatorTitle":[{"kind":"identifier","text":"MdlReaderDelegate"}],"title":"MdlReaderDelegate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlReaderDelegate"}],"url":"\/documentation\/mdlreader\/mdlreaderdelegate"},"doc://com.xinfotech.mdlreader/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/stopRequestDocument()":{"role":"symbol","title":"stopRequestDocument()","navigatorTitle":[{"kind":"identifier","text":"stopRequestDocument"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRequestDocument"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/stopRequestDocument()","abstract":[],"url":"\/documentation\/mdlreader\/mdlreader\/stoprequestdocument()"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/isPersonalized":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/isPersonalized","kind":"symbol","url":"\/documentation\/mdlreader\/mdlreader\/ispersonalized","title":"isPersonalized","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPersonalized","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isPersonalized","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns "},{"inlineContent":[{"type":"text","text":"true"}],"type":"strong"},{"type":"text","text":" if the SDK has been personalized (required certificates have been downloaded), otherwise returns "},{"inlineContent":[{"type":"text","text":"false"}],"type":"strong"},{"type":"text","text":"."}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)":{"navigatorTitle":[{"text":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:","kind":"identifier"}],"title":"startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)","kind":"symbol","type":"topic","abstract":[{"text":"This method initializes the document request process and sends the request to the holder.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startRequestDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fields","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"isOnline","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"engagement","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlReader@objc(pl)XTMdlReaderDelegate","text":"MdlReaderDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/mdlreader\/mdlreader\/startrequestdocument(fields:isonline:engagement:pin:delegate:completion:)"},"doc://com.xinfotech.mdlreader/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader":{"url":"\/documentation\/mdlreader\/mdlreader","title":"MdlReader","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader","kind":"symbol","navigatorTitle":[{"text":"MdlReader","kind":"identifier"}],"abstract":[{"text":"Main class of the SDK","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReader","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/SH":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SH","title":"Swift.Hashable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode":{"role":"symbol","title":"ReaderErrorCode","navigatorTitle":[{"text":"ReaderErrorCode","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderErrorCode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode","abstract":[{"type":"text","text":"Possible error codes in SDK"}],"url":"\/documentation\/mdlreader\/readererrorcode"},"doc://com.xinfotech.mdlreader/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/updateRootCertificates()":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/updateRootCertificates()","kind":"symbol","url":"\/documentation\/mdlreader\/mdlreader\/updaterootcertificates()","title":"updateRootCertificates()","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateRootCertificates","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"text":"Downloads CA Root certificates and updates them in the local SDK storage","type":"text"}]},"doc://com.xinfotech.mdlreader/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject","title":"NSObject"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/init":{"role":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/init","abstract":[],"url":"\/documentation\/mdlreader\/mdlreader\/init"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/initialize()":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/initialize()","kind":"symbol","title":"initialize()","url":"\/documentation\/mdlreader\/mdlreader\/initialize()","abstract":[{"type":"text","text":"SDK initialization, async version of method"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MdlReader","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"MdlReader"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MdlReader"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/isPersonalized"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/init","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/initialize(completion:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/personalizeWith(token:pin:completion:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/removePersonalization()","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/stopRequestDocument()","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/updateRootCertificates(completion:)"],"title":"Instance Methods","generated":true},{"anchor":"Type-Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/sdkVersion","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/shared"],"title":"Type Properties","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"],"anchor":"Main-Classes","title":"Main Classes","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReader","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"sdkVersion","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1sdkVersion\/title","op":"replace"},{"value":[{"text":"sdkVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1sdkVersion\/fragments","op":"replace"},{"value":"updateRootCertificatesWithCompletion:","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1updateRootCertificates(completion:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1updateRootCertificates(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateRootCertificatesWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/fragments","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1initialize(completion:)\/title","value":"initializeWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1initialize(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1personalizeWith(token:pin:completion:)\/title","value":"personalizeWithToken:pin:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1personalizeWith(token:pin:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"personalizeWithToken:pin:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/title","value":"XTMdlDocumentField"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/fragments","value":[{"kind":"identifier","text":"XTMdlDocumentField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocumentField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1removePersonalization()\/title","value":"removePersonalization"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1removePersonalization()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removePersonalization"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/title","value":"XTMdlReaderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/fragments","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/navigatorTitle","value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1stopRequestDocument()\/title","value":"stopRequestDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1stopRequestDocument()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopRequestDocument"}]},{"value":"isPersonalized","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1isPersonalized\/title","op":"replace"},{"value":[{"text":"isPersonalized","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1isPersonalized\/fragments","op":"replace"},{"value":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)\/fragments","op":"replace"},{"value":"MdlReader","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/title","op":"replace"},{"value":[{"text":"MdlReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/fragments","op":"replace"},{"value":[{"text":"MdlReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/navigatorTitle","op":"replace"},{"value":"XTReaderErrorCode","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/title","op":"replace"},{"value":[{"text":"XTReaderErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTReaderErrorCode"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/navigatorTitle","op":"replace"}]}]}