{"seeAlsoSections":[{"anchor":"Main-Classes","title":"Main Classes","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/readererrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/readererrorcode"]}],"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleDenied","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleRestricted","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleUnauthorized","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleUnsupported","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/clientCertificateNotFound","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/cryptographicError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/initializationError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/internalError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/issuerDocumentResponseFailed","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/mDocError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/mDocRequestError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/mDocValidationError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/networkError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/notInitialized","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/notPersonalized","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/onlineDocumentResponseError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/pinIsEmpty","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/pinIsWrong","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/sessionDataError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/unknown"]},{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/init(rawValue:)"]},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/Equatable-Implementations","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/RawRepresentable-Implementations"]}],"kind":"symbol","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"},"metadata":{"role":"symbol","symbolKind":"enum","externalID":"c:@M@MdlReader@E@XTReaderErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"ReaderErrorCode","kind":"identifier"}],"title":"ReaderErrorCode","modules":[{"name":"MdlReader"}],"roleHeading":"Enumeration"},"sections":[],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH","doc:\/\/com.xinfotech.mdlreader\/SY"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(XTReaderErrorCode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReaderErrorCode"}],"languages":["swift"]}]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/Equatable-Implementations":{"url":"\/documentation\/mdlreader\/readererrorcode\/equatable-implementations","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/Equatable-Implementations","title":"Equatable Implementations","type":"topic"},"doc://com.xinfotech.mdlreader/SH":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/notPersonalized":{"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/notPersonalized","url":"\/documentation\/mdlreader\/readererrorcode\/notpersonalized","kind":"symbol","title":"ReaderErrorCode.notPersonalized","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notPersonalized"}],"navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeNotPersonalized"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/unknown":{"abstract":[],"url":"\/documentation\/mdlreader\/readererrorcode\/unknown","title":"ReaderErrorCode.unknown","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeUnknown"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/bleUnsupported":{"abstract":[],"url":"\/documentation\/mdlreader\/readererrorcode\/bleunsupported","title":"ReaderErrorCode.bleUnsupported","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleUnsupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleUnsupported"}],"navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnsupported"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/notInitialized":{"url":"\/documentation\/mdlreader\/readererrorcode\/notinitialized","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"XTReaderErrorCodeNotInitialized","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notInitialized","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/notInitialized","title":"ReaderErrorCode.notInitialized","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/issuerDocumentResponseFailed":{"title":"ReaderErrorCode.issuerDocumentResponseFailed","navigatorTitle":[{"text":"XTReaderErrorCodeIssuerDocumentResponseFailed","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuerDocumentResponseFailed","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/issuerDocumentResponseFailed","role":"symbol","url":"\/documentation\/mdlreader\/readererrorcode\/issuerdocumentresponsefailed"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/pinIsEmpty":{"abstract":[],"url":"\/documentation\/mdlreader\/readererrorcode\/pinisempty","title":"ReaderErrorCode.pinIsEmpty","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/pinIsEmpty","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pinIsEmpty","kind":"identifier"}],"navigatorTitle":[{"text":"XTReaderErrorCodePinIsEmpty","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/onlineDocumentResponseError":{"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/onlineDocumentResponseError","url":"\/documentation\/mdlreader\/readererrorcode\/onlinedocumentresponseerror","kind":"symbol","title":"ReaderErrorCode.onlineDocumentResponseError","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onlineDocumentResponseError","kind":"identifier"}],"navigatorTitle":[{"text":"XTReaderErrorCodeOnlineDocumentResponseError","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/mDocError":{"abstract":[],"url":"\/documentation\/mdlreader\/readererrorcode\/mdocerror","title":"ReaderErrorCode.mDocError","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/mDocError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocError","kind":"identifier"}],"navigatorTitle":[{"text":"XTReaderErrorCodeMDocError","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/bleUnauthorized":{"title":"ReaderErrorCode.bleUnauthorized","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnauthorized"}],"kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleUnauthorized"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleUnauthorized","role":"symbol","url":"\/documentation\/mdlreader\/readererrorcode\/bleunauthorized"},"doc://com.xinfotech.mdlreader/SQ":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReaderDelegate":{"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","type":"topic","abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"type":"codeVoice","code":"MdlReader"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"url":"\/documentation\/mdlreader\/mdlreaderdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReaderDelegate","kind":"identifier"}],"title":"MdlReaderDelegate","navigatorTitle":[{"text":"MdlReaderDelegate","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/SY":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/mDocValidationError":{"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/mDocValidationError","abstract":[],"type":"topic","url":"\/documentation\/mdlreader\/readererrorcode\/mdocvalidationerror","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocValidationError","kind":"identifier"}],"title":"ReaderErrorCode.mDocValidationError","navigatorTitle":[{"text":"XTReaderErrorCodeMDocValidationError","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/sessionDataError":{"abstract":[],"url":"\/documentation\/mdlreader\/readererrorcode\/sessiondataerror","title":"ReaderErrorCode.sessionDataError","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/sessionDataError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sessionDataError"}],"navigatorTitle":[{"text":"XTReaderErrorCodeSessionDataError","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/mDocRequestError":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocRequestError","kind":"identifier"}],"title":"ReaderErrorCode.mDocRequestError","navigatorTitle":[{"text":"XTReaderErrorCodeMDocRequestError","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mdlreader\/readererrorcode\/mdocrequesterror","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/mDocRequestError","kind":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/bleRestricted":{"abstract":[],"url":"\/documentation\/mdlreader\/readererrorcode\/blerestricted","title":"ReaderErrorCode.bleRestricted","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleRestricted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleRestricted"}],"navigatorTitle":[{"text":"XTReaderErrorCodeBleRestricted","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlFieldIdentifier":{"url":"\/documentation\/mdlreader\/mdlfieldidentifier","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"abstract":[{"text":"Provides predefined field identifiers used in mDL documents.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","title":"MdlFieldIdentifier","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/pinIsWrong":{"url":"\/documentation\/mdlreader\/readererrorcode\/piniswrong","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"XTReaderErrorCodePinIsWrong","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pinIsWrong","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/pinIsWrong","title":"ReaderErrorCode.pinIsWrong","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/cryptographicError":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cryptographicError","kind":"identifier"}],"title":"ReaderErrorCode.cryptographicError","navigatorTitle":[{"text":"XTReaderErrorCodeCryptographicError","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mdlreader\/readererrorcode\/cryptographicerror","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/cryptographicError","kind":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/init(rawValue:)":{"role":"symbol","url":"\/documentation\/mdlreader\/readererrorcode\/init(rawvalue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/init(rawValue:)","title":"init(rawValue:)","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/clientCertificateNotFound":{"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/clientCertificateNotFound","url":"\/documentation\/mdlreader\/readererrorcode\/clientcertificatenotfound","kind":"symbol","title":"ReaderErrorCode.clientCertificateNotFound","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientCertificateNotFound","kind":"identifier"}],"navigatorTitle":[{"text":"XTReaderErrorCodeClientCertificateNotFound","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDocumentField":{"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField","url":"\/documentation\/mdlreader\/mdldocumentfield","kind":"symbol","title":"MdlDocumentField","type":"topic","abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocumentField","kind":"identifier"}],"navigatorTitle":[{"text":"MdlDocumentField","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ReaderErrorCode"}],"url":"\/documentation\/mdlreader\/readererrorcode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReaderErrorCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ReaderErrorCode","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/bleDenied":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bleDenied","kind":"identifier"}],"title":"ReaderErrorCode.bleDenied","navigatorTitle":[{"text":"XTReaderErrorCodeBleDenied","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mdlreader\/readererrorcode\/bledenied","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleDenied","kind":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/initializationError":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/initializationError","type":"topic","url":"\/documentation\/mdlreader\/readererrorcode\/initializationerror","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initializationError","kind":"identifier"}],"title":"ReaderErrorCode.initializationError","navigatorTitle":[{"text":"XTReaderErrorCodeInitializationError","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/internalError":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"XTReaderErrorCodeInternalError","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/internalError","title":"ReaderErrorCode.internalError","url":"\/documentation\/mdlreader\/readererrorcode\/internalerror"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader":{"kind":"symbol","abstract":[{"text":"Main class of the SDK","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader","type":"topic","url":"\/documentation\/mdlreader\/mdlreader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReader","kind":"identifier"}],"title":"MdlReader","navigatorTitle":[{"text":"MdlReader","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/networkError":{"abstract":[],"url":"\/documentation\/mdlreader\/readererrorcode\/networkerror","title":"ReaderErrorCode.networkError","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/networkError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkError","kind":"identifier"}],"navigatorTitle":[{"text":"XTReaderErrorCodeNetworkError","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/RawRepresentable-Implementations":{"url":"\/documentation\/mdlreader\/readererrorcode\/rawrepresentable-implementations","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"XTReaderErrorCode","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"XTReaderErrorCode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"XTReaderErrorCode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleDenied","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleRestricted","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleUnauthorized","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleUnsupported","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/clientCertificateNotFound","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/cryptographicError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/initializationError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/internalError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/issuerDocumentResponseFailed","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/mDocError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/mDocRequestError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/mDocValidationError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/networkError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/notInitialized","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/notPersonalized","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/onlineDocumentResponseError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/pinIsEmpty","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/pinIsWrong","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/sessionDataError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/unknown"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"Main-Classes","title":"Main Classes","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReaderDelegate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDocumentField"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XTReaderErrorCode","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"XTReaderErrorCodeNotPersonalized","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1notPersonalized\/title"},{"op":"replace","value":[{"text":"XTReaderErrorCodeNotPersonalized","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1notPersonalized\/fragments"},{"op":"replace","value":"XTReaderErrorCodeUnknown","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1unknown\/title"},{"op":"replace","value":[{"text":"XTReaderErrorCodeUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1unknown\/fragments"},{"op":"replace","value":"XTReaderErrorCodeBleUnsupported","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1bleUnsupported\/title"},{"op":"replace","value":[{"text":"XTReaderErrorCodeBleUnsupported","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1bleUnsupported\/fragments"},{"op":"replace","value":"XTReaderErrorCodeNotInitialized","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1notInitialized\/title"},{"op":"replace","value":[{"text":"XTReaderErrorCodeNotInitialized","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1notInitialized\/fragments"},{"op":"replace","value":"XTReaderErrorCodeIssuerDocumentResponseFailed","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1issuerDocumentResponseFailed\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTReaderErrorCodeIssuerDocumentResponseFailed"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1issuerDocumentResponseFailed\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1pinIsEmpty\/title","value":"XTReaderErrorCodePinIsEmpty","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1pinIsEmpty\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodePinIsEmpty"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1onlineDocumentResponseError\/title","value":"XTReaderErrorCodeOnlineDocumentResponseError","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1onlineDocumentResponseError\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeOnlineDocumentResponseError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1mDocError\/title","value":"XTReaderErrorCodeMDocError","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1mDocError\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeMDocError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1bleUnauthorized\/title","value":"XTReaderErrorCodeBleUnauthorized","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1bleUnauthorized\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnauthorized"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/title","value":"XTMdlReaderDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/fragments","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReaderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1mDocValidationError\/title","value":"XTReaderErrorCodeMDocValidationError","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1mDocValidationError\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeMDocValidationError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1sessionDataError\/title","value":"XTReaderErrorCodeSessionDataError","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1sessionDataError\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeSessionDataError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1mDocRequestError\/title","value":"XTReaderErrorCodeMDocRequestError","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1mDocRequestError\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeMDocRequestError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1bleRestricted\/title","value":"XTReaderErrorCodeBleRestricted","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1bleRestricted\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeBleRestricted"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/fragments","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1pinIsWrong\/title","value":"XTReaderErrorCodePinIsWrong","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1pinIsWrong\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodePinIsWrong"}],"op":"replace"},{"op":"replace","value":"XTReaderErrorCodeCryptographicError","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1cryptographicError\/title"},{"op":"replace","value":[{"text":"XTReaderErrorCodeCryptographicError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1cryptographicError\/fragments"},{"op":"replace","value":"XTReaderErrorCodeClientCertificateNotFound","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1clientCertificateNotFound\/title"},{"op":"replace","value":[{"text":"XTReaderErrorCodeClientCertificateNotFound","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1clientCertificateNotFound\/fragments"},{"op":"replace","value":"XTMdlDocumentField","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/title"},{"op":"replace","value":[{"text":"XTMdlDocumentField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/fragments"},{"op":"replace","value":[{"text":"XTMdlDocumentField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDocumentField\/navigatorTitle"},{"op":"replace","value":"XTReaderErrorCode","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/title"},{"op":"replace","value":[{"text":"XTReaderErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/fragments"},{"op":"replace","value":[{"text":"XTReaderErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/navigatorTitle"},{"op":"replace","value":"XTReaderErrorCodeBleDenied","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1bleDenied\/title"},{"op":"replace","value":[{"text":"XTReaderErrorCodeBleDenied","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1bleDenied\/fragments"},{"op":"replace","value":"XTReaderErrorCodeInitializationError","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1initializationError\/title"},{"op":"replace","value":[{"text":"XTReaderErrorCodeInitializationError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1initializationError\/fragments"},{"op":"replace","value":"XTReaderErrorCodeInternalError","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1internalError\/title"},{"op":"replace","value":[{"text":"XTReaderErrorCodeInternalError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1internalError\/fragments"},{"op":"replace","value":"XTMdlReader","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/title"},{"op":"replace","value":[{"text":"XTMdlReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/fragments"},{"op":"replace","value":[{"text":"XTMdlReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/navigatorTitle"},{"op":"replace","value":"XTReaderErrorCodeNetworkError","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1networkError\/title"},{"op":"replace","value":[{"text":"XTReaderErrorCodeNetworkError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1networkError\/fragments"}]}]}