{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/AgeOverNnEntry"]]},"metadata":{"title":"age","externalID":"c:@M@MdlReader@objc(cs)XTAgeOverNnEntry(py)age","modules":[{"name":"MdlReader"}],"roleHeading":"Instance Property","platforms":[{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"Mac Catalyst"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"age","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"age","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/AgeOverNnEntry\/age"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"age","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/ageovernnentry\/age"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/ageovernnentry\/age"]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/AgeOverNnEntry/age":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"age","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"age","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/AgeOverNnEntry\/age","title":"age","url":"\/documentation\/mdlreader\/ageovernnentry\/age"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/AgeOverNnEntry":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgeOverNnEntry","kind":"identifier"}],"title":"AgeOverNnEntry","navigatorTitle":[{"text":"AgeOverNnEntry","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mdlreader\/ageovernnentry","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/AgeOverNnEntry","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"Mac Catalyst"}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"age","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"age"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"age"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"age","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1AgeOverNnEntry~1age\/title"},{"op":"replace","value":[{"kind":"identifier","text":"age"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1AgeOverNnEntry~1age\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1AgeOverNnEntry\/title","op":"replace","value":"XTAgeOverNnEntry"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1AgeOverNnEntry\/fragments","op":"replace","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1AgeOverNnEntry\/navigatorTitle","op":"replace","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}]}]}]}