{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOverAge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/AgeOverNnEntry\/isOverAge"},"kind":"symbol","sections":[],"metadata":{"title":"isOverAge","navigatorTitle":[{"kind":"identifier","text":"isOverAge"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOverAge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Property","externalID":"c:@M@MdlReader@objc(cs)XTAgeOverNnEntry(py)isOverAge","symbolKind":"property","modules":[{"name":"MdlReader"}]},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/AgeOverNnEntry"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/ageovernnentry\/isoverage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/ageovernnentry\/isoverage"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/AgeOverNnEntry":{"role":"symbol","title":"AgeOverNnEntry","navigatorTitle":[{"kind":"identifier","text":"AgeOverNnEntry"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgeOverNnEntry"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/AgeOverNnEntry","abstract":[],"url":"\/documentation\/mdlreader\/ageovernnentry"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/AgeOverNnEntry/isOverAge":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/AgeOverNnEntry\/isOverAge","kind":"symbol","url":"\/documentation\/mdlreader\/ageovernnentry\/isoverage","title":"isOverAge","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOverAge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isOverAge"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isOverAge","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"isOverAge"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOverAge"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"XTAgeOverNnEntry","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1AgeOverNnEntry\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1AgeOverNnEntry\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1AgeOverNnEntry\/navigatorTitle"},{"op":"replace","value":"isOverAge","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1AgeOverNnEntry~1isOverAge\/title"},{"op":"replace","value":[{"text":"isOverAge","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1AgeOverNnEntry~1isOverAge\/fragments"}]}]}