{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(XTMdlBiometricTemplate) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlBiometricTemplate"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdlbiometrictemplate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdlbiometrictemplate"]}],"metadata":{"role":"symbol","externalID":"c:@M@MdlHolder@objc(cs)XTMdlBiometricTemplate","symbolKind":"class","roleHeading":"Class","title":"MdlBiometricTemplate","modules":[{"name":"MdlHolder"}],"navigatorTitle":[{"text":"MdlBiometricTemplate","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlBiometricTemplate"}]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate\/init(templateName:content:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate\/content","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate\/templateName"],"title":"Instance Properties","anchor":"Instance-Properties"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH"]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlBiometricTemplate/content":{"type":"topic","title":"content","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate\/content","role":"symbol","url":"\/documentation\/mdlholder\/mdlbiometrictemplate\/content","kind":"symbol","navigatorTitle":[{"text":"content","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP"},"doc://com.xinfotech.mdlholder/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SH"},"doc://com.xinfotech.mdlholder/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP"},"doc://com.xinfotech.mdlholder/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlBiometricTemplate/init(templateName:content:)":{"type":"topic","title":"init(templateName:content:)","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate\/init(templateName:content:)","role":"symbol","url":"\/documentation\/mdlholder\/mdlbiometrictemplate\/init(templatename:content:)","kind":"symbol","navigatorTitle":[{"text":"initWithTemplateName:content:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"templateName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlBiometricTemplate/templateName":{"type":"topic","title":"templateName","abstract":[{"text":"Template name. It replaces ‘xx’ in ‘biometric_template_xx’.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate\/templateName","role":"symbol","url":"\/documentation\/mdlholder\/mdlbiometrictemplate\/templatename","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"templateName"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlBiometricTemplate":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate","title":"MdlBiometricTemplate","abstract":[],"role":"symbol","url":"\/documentation\/mdlholder\/mdlbiometrictemplate","kind":"symbol","navigatorTitle":[{"text":"MdlBiometricTemplate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlBiometricTemplate"}]},"doc://com.xinfotech.mdlholder/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ"},"doc://com.xinfotech.mdlholder/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP"},"doc://com.xinfotech.mdlholder/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"XTMdlBiometricTemplate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"XTMdlBiometricTemplate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlBiometricTemplate"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate\/content","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate\/templateName"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlBiometricTemplate\/init(templateName:content:)"],"title":"Instance Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlBiometricTemplate"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate~1content\/title","value":"content"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate~1content\/fragments","value":[{"kind":"identifier","text":"content"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate~1init(templateName:content:)\/title","value":"initWithTemplateName:content:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate~1init(templateName:content:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTemplateName:content:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate~1templateName\/title","value":"templateName"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate~1templateName\/fragments","value":[{"kind":"identifier","text":"templateName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate\/title","value":"XTMdlBiometricTemplate"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate\/fragments","value":[{"kind":"identifier","text":"XTMdlBiometricTemplate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlBiometricTemplate\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlBiometricTemplate"}]}]}]}