{"topicSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/administrativeNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/ageBirthYear","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/ageInYears","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/ageOverNn","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/biometricTemplateXx","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/birthDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/birthPlace","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/bloodGroup","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/dlExpiryDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/dlIssueDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/documentNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/drivingPrivileges","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/drivingRestrictions","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/expiryDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/eyeColour","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/familyName","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/familyNameNationalCharacter","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/givenName","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/givenNameNationalCharacter","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/hairColour","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/height","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/holderIdNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issueDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issuingAuthority","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issuingCountry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issuingJurisdiction","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/nationality","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/portrait","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/portraitCaptureDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentAddress","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentCity","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentCountry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentPostalCode","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentState","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/sex","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/signatureUsualMark","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/unDistinguishingSign","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/weight"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH"],"kind":"relationships","type":"conformsTo"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument"},"metadata":{"title":"MdlDocument","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"modules":[{"name":"MdlHolder"}],"externalID":"c:@M@MdlHolder@objc(cs)XTMdlDocument","symbolKind":"class","role":"symbol"},"seeAlsoSections":[{"title":"Main Classes","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"],"generated":true,"anchor":"Main-Classes"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdldocument"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdldocument"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(XTMdlDocument) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Representation of mDL document"}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/signatureUsualMark":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureUsualMark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/signatureUsualMark","type":"topic","url":"\/documentation\/mdlholder\/mdldocument\/signatureusualmark","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"signatureUsualMark"}],"title":"signatureUsualMark","abstract":[{"type":"text","text":"Image of the signature or usual mark of the mDL holder."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/height":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/height","url":"\/documentation\/mdlholder\/mdldocument\/height","role":"symbol","navigatorTitle":[{"text":"height","kind":"identifier"}],"title":"height","abstract":[{"type":"text","text":"mDL holder’s height in centimeters."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"abstract":[{"text":"Main class of the SDK","type":"text"}],"title":"MdlHolder","navigatorTitle":[{"text":"MdlHolder","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolder"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlholder"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/documentNumber":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholder\/mdldocument\/documentnumber","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/documentNumber","role":"symbol","navigatorTitle":[{"text":"documentNumber","kind":"identifier"}],"title":"documentNumber","abstract":[{"text":"The number assigned or calculated by the issuing authority.","type":"text"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/hairColour":{"abstract":[{"type":"text","text":"mDL holder’s hair colour. One of these values: “bald”, “black”, “blond”, “brown”, “grey”, “red”, “auburn”, “sandy”, “white”, “unknown”."}],"title":"hairColour","navigatorTitle":[{"kind":"identifier","text":"hairColour"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hairColour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/hairColour","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdldocument\/haircolour"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/familyName":{"url":"\/documentation\/mdlholder\/mdldocument\/familyname","title":"familyName","navigatorTitle":[{"text":"familyName","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"familyName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/familyName","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Last name, surname or primary identifier, of the mDL holder."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/expiryDate":{"url":"\/documentation\/mdlholder\/mdldocument\/expirydate","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"expiryDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/expiryDate","navigatorTitle":[{"text":"expiryDate","kind":"identifier"}],"title":"expiryDate","abstract":[{"type":"text","text":"Date when mDL expires."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/weight":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"weight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholder\/mdldocument\/weight","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/weight","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"weight"}],"title":"weight","abstract":[{"type":"text","text":"mDL holder’s weigth in kilograms."}]},"doc://com.xinfotech.mdlholder/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)":{"url":"\/documentation\/mdlholder\/mdldocument\/init(familyname:givenname:birthdate:issuedate:expirydate:issuingcountry:issuingauthority:documentnumber:portrait:drivingprivileges:undistinguishingsign:holderidnumber:bloodgroup:dlissuedate:dlexpirydate:drivingrestrictions:administrativenum-1g6bl","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"familyName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"givenName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"birthDate"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":", "},{"text":"issuingCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"issuingAuthority"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"portrait"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingPrivileges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivileges","text":"MdlDrivingPrivileges"},{"kind":"text","text":", "},{"kind":"externalParam","text":"unDistinguishingSign"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"holderIdNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bloodGroup"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"dlIssueDate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlExpiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingRestrictions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"administrativeNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@E@XTMdlGender","text":"MdlGender"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eyeColour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hairColour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"birthPlace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"residentAddress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"portraitCaptureDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"ageInYears","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"ageBirthYear","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"ageOverNn","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AgeOverNnEntry","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTAgeOverNnEntry"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"issuingJurisdiction"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"nationality"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentCity"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"residentState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"residentPostalCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"residentCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"biometricTemplateXx","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlBiometricTemplate","text":"MdlBiometricTemplate"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"familyNameNationalCharacter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"givenNameNationalCharacter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureUsualMark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","navigatorTitle":[{"kind":"identifier","text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"}],"title":"init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","abstract":[],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/portrait":{"url":"\/documentation\/mdlholder\/mdldocument\/portrait","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/portrait","navigatorTitle":[{"kind":"identifier","text":"portrait"}],"title":"portrait","abstract":[{"type":"text","text":"A reproduction of the mDL holder’s portrait."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/residentAddress":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentAddress","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentAddress","url":"\/documentation\/mdlholder\/mdldocument\/residentaddress","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"residentAddress"}],"title":"residentAddress","abstract":[{"type":"text","text":"Permanent place of residence. The place where the mDL holder resides and\/or may be contacted (street\/house number, municipality etc.)."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/holderIdNumber":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"holderIdNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/holderIdNumber","url":"\/documentation\/mdlholder\/mdldocument\/holderidnumber","role":"symbol","navigatorTitle":[{"text":"holderIdNumber","kind":"identifier"}],"title":"holderIdNumber","abstract":[{"type":"text","text":"mDL holder’s national ID or alien ID, or diplomatic ID"}]},"doc://com.xinfotech.mdlholder/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SH"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/administrativeNumber":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"administrativeNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/mdlholder\/mdldocument\/administrativenumber","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/administrativeNumber","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"administrativeNumber"}],"title":"administrativeNumber","abstract":[{"type":"text","text":"An audit control number assignet by the issuing authority."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate":{"url":"\/documentation\/mdlholder\/mdlholderdelegate","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolderDelegate"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"title":"MdlHolderDelegate","abstract":[{"type":"text","text":"Delivers events from the "},{"type":"reference","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","isActive":true},{"type":"text","text":" during the mDL document sharing lifecycle."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/givenNameNationalCharacter":{"url":"\/documentation\/mdlholder\/mdldocument\/givennamenationalcharacter","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenNameNationalCharacter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/givenNameNationalCharacter","navigatorTitle":[{"kind":"identifier","text":"givenNameNationalCharacter"}],"title":"givenNameNationalCharacter","abstract":[{"type":"text","text":"The given name of the mDL holder using full UTF-8 character set."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/portraitCaptureDate":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"portraitCaptureDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/portraitCaptureDate","type":"topic","kind":"symbol","url":"\/documentation\/mdlholder\/mdldocument\/portraitcapturedate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"portraitCaptureDate"}],"title":"portraitCaptureDate","abstract":[{"text":"Date when portrait was taken.","type":"text"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/birthDate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"birthDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/birthDate","url":"\/documentation\/mdlholder\/mdldocument\/birthdate","role":"symbol","navigatorTitle":[{"text":"birthDate","kind":"identifier"}],"title":"birthDate","abstract":[{"type":"text","text":"Day, month and year on which the mDL holder was born. If unknown, approximate date of birth."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/issuingCountry":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issuingCountry","type":"topic","url":"\/documentation\/mdlholder\/mdldocument\/issuingcountry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"issuingCountry"}],"title":"issuingCountry","abstract":[{"type":"text","text":"Alpha-2 country code of the issuing authority’s country or territory."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/issueDate":{"url":"\/documentation\/mdlholder\/mdldocument\/issuedate","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issueDate","navigatorTitle":[{"kind":"identifier","text":"issueDate"}],"title":"issueDate","abstract":[{"type":"text","text":"Date when mDL was issued."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/dlIssueDate":{"url":"\/documentation\/mdlholder\/mdldocument\/dlissuedate","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dlIssueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/dlIssueDate","navigatorTitle":[{"text":"dlIssueDate","kind":"identifier"}],"title":"dlIssueDate","abstract":[{"type":"text","text":"Date of issue of eDL (physical document) issued to mDL holder"}],"role":"symbol"},"doc://com.xinfotech.mdlholder/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/dlExpiryDate":{"abstract":[{"text":"Date of expiry of eDL (physical document) issued to mDL holder","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dlExpiryDate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"navigatorTitle":[{"kind":"identifier","text":"dlExpiryDate"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/dlExpiryDate","title":"dlExpiryDate","type":"topic","url":"\/documentation\/mdlholder\/mdldocument\/dlexpirydate","role":"symbol","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/nationality":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nationality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/nationality","type":"topic","url":"\/documentation\/mdlholder\/mdldocument\/nationality","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nationality"}],"title":"nationality","abstract":[{"type":"text","text":"Nationality of the mDL holder as two letter country code."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/residentPostalCode":{"url":"\/documentation\/mdlholder\/mdldocument\/residentpostalcode","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentPostalCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentPostalCode","navigatorTitle":[{"kind":"identifier","text":"residentPostalCode"}],"title":"residentPostalCode","abstract":[{"type":"text","text":"The postal code of the mDL holder."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/ageInYears":{"url":"\/documentation\/mdlholder\/mdldocument\/ageinyears","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageInYears"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/ageInYears","navigatorTitle":[{"kind":"identifier","text":"ageInYears"}],"title":"ageInYears","abstract":[{"type":"text","text":"The age of the mDL holder.  Age attestation: How old are you (in years)?"}],"role":"symbol"},"doc://com.xinfotech.mdlholder/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/givenName":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"givenName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholder\/mdldocument\/givenname","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/givenName","role":"symbol","navigatorTitle":[{"text":"givenName","kind":"identifier"}],"title":"givenName","abstract":[{"text":"First name(s), other name(s), or secondary identifier, of the mDL holder.","type":"text"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocumentField":{"url":"\/documentation\/mdlholder\/mdldocumentfield","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlDocumentField"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"title":"MdlDocumentField","abstract":[{"type":"text","text":"Represents an mDL document field containing an identifier and a corresponding value."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/ageOverNn":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageOverNn"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgeOverNnEntry","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTAgeOverNnEntry"},{"kind":"text","text":"]?"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/ageOverNn","type":"topic","url":"\/documentation\/mdlholder\/mdldocument\/ageovernn","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ageOverNn"}],"title":"ageOverNn","abstract":[{"type":"text","text":"Age attestation: Nearest “true” attestation above request."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/eyeColour":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeColour"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/eyeColour","type":"topic","url":"\/documentation\/mdlholder\/mdldocument\/eyecolour","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"eyeColour"}],"title":"eyeColour","abstract":[{"type":"text","text":"mDL holder’s eye colour. The value shall be one of the following: “black”, “blue”, “brown”, “dichromatic”, “grey”, “green”, “hazel”, “maroon”, “pink”, “unknown”."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/biometricTemplateXx":{"url":"\/documentation\/mdlholder\/mdldocument\/biometrictemplatexx","title":"biometricTemplateXx","navigatorTitle":[{"text":"biometricTemplateXx","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"biometricTemplateXx","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MdlBiometricTemplate","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlBiometricTemplate","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/biometricTemplateXx","type":"topic","kind":"symbol","role":"symbol","abstract":[]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/issuingAuthority":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingAuthority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholder\/mdldocument\/issuingauthority","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issuingAuthority","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"issuingAuthority"}],"title":"issuingAuthority","abstract":[{"type":"text","text":"Issuing authority name."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/residentCountry":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentCountry","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentCountry","url":"\/documentation\/mdlholder\/mdldocument\/residentcountry","role":"symbol","navigatorTitle":[{"text":"residentCountry","kind":"identifier"}],"title":"residentCountry","abstract":[{"type":"text","text":"The country where the mDL holder lives as the two letter country code."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/ageBirthYear":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ageBirthYear","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/ageBirthYear","url":"\/documentation\/mdlholder\/mdldocument\/agebirthyear","role":"symbol","navigatorTitle":[{"text":"ageBirthYear","kind":"identifier"}],"title":"ageBirthYear","abstract":[{"type":"text","text":"The year when the mDL holder was born.  Age attestation: In what year where you born?"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","title":"MdlHolder","type":"topic","url":"\/documentation\/mdlholder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/residentCity":{"url":"\/documentation\/mdlholder\/mdldocument\/residentcity","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentCity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentCity","navigatorTitle":[{"kind":"identifier","text":"residentCity"}],"title":"residentCity","abstract":[{"type":"text","text":"The city where the mDL holder lives."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/drivingRestrictions":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingRestrictions"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/drivingRestrictions","url":"\/documentation\/mdlholder\/mdldocument\/drivingrestrictions","role":"symbol","navigatorTitle":[{"text":"drivingRestrictions","kind":"identifier"}],"title":"drivingRestrictions","abstract":[{"type":"text","text":"Driver’s restrictions"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/drivingPrivileges":{"url":"\/documentation\/mdlholder\/mdldocument\/drivingprivileges","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingPrivileges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlDrivingPrivileges","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivileges"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/drivingPrivileges","navigatorTitle":[{"kind":"identifier","text":"drivingPrivileges"}],"title":"drivingPrivileges","abstract":[{"type":"text","text":"Driving privileges of the mDL holder. Categories of vehicles\/restrictions\/conditions. (zero or more)"}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/familyNameNationalCharacter":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"familyNameNationalCharacter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/familyNameNationalCharacter","url":"\/documentation\/mdlholder\/mdldocument\/familynamenationalcharacter","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"familyNameNationalCharacter"}],"title":"familyNameNationalCharacter","abstract":[{"type":"text","text":"The family name of the mDL holder using full UTF-8 character set."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/residentState":{"url":"\/documentation\/mdlholder\/mdldocument\/residentstate","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentState","navigatorTitle":[{"kind":"identifier","text":"residentState"}],"title":"residentState","abstract":[{"text":"The state\/province\/district where the mDL holder lives.","type":"text"}],"role":"symbol"},"doc://com.xinfotech.mdlholder/SQ":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/issuingJurisdiction":{"url":"\/documentation\/mdlholder\/mdldocument\/issuingjurisdiction","title":"issuingJurisdiction","navigatorTitle":[{"kind":"identifier","text":"issuingJurisdiction"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingJurisdiction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issuingJurisdiction","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Country subdivision code of the jurisdiction that issued the mDL. The first part of the code shall be the same as the value for issuing country."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","type":"topic","url":"\/documentation\/mdlholder\/mdldocument","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"title":"MdlDocument","abstract":[{"type":"text","text":"Representation of mDL document"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/bloodGroup":{"url":"\/documentation\/mdlholder\/mdldocument\/bloodgroup","title":"bloodGroup","navigatorTitle":[{"kind":"identifier","text":"bloodGroup"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bloodGroup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/bloodGroup","kind":"symbol","role":"symbol","abstract":[{"text":"mDL holder’s blood group","type":"text"}]},"doc://com.xinfotech.mdlholder/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/unDistinguishingSign":{"url":"\/documentation\/mdlholder\/mdldocument\/undistinguishingsign","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unDistinguishingSign"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/unDistinguishingSign","navigatorTitle":[{"kind":"identifier","text":"unDistinguishingSign"}],"title":"unDistinguishingSign","abstract":[{"type":"text","text":"UN Distinguishing sign."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/birthPlace":{"url":"\/documentation\/mdlholder\/mdldocument\/birthplace","title":"birthPlace","navigatorTitle":[{"text":"birthPlace","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"birthPlace","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/birthPlace","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Country and municipality or state\/province where the mDL holder was born."}]},"doc://com.xinfotech.mdlholder/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument/sex":{"url":"\/documentation\/mdlholder\/mdldocument\/sex","title":"sex","navigatorTitle":[{"kind":"identifier","text":"sex"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlGender","preciseIdentifier":"c:@M@MdlHolder@E@XTMdlGender","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/sex","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"mDL holder’s sex."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"XTMdlDocument","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/administrativeNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/ageBirthYear","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/ageInYears","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/ageOverNn","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/biometricTemplateXx","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/birthDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/birthPlace","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/bloodGroup","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/dlExpiryDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/dlIssueDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/documentNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/drivingPrivileges","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/drivingRestrictions","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/expiryDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/eyeColour","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/familyName","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/familyNameNationalCharacter","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/givenName","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/givenNameNationalCharacter","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/hairColour","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/height","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/holderIdNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issueDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issuingAuthority","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issuingCountry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/issuingJurisdiction","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/nationality","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/portrait","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/portraitCaptureDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentAddress","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentCity","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentCountry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentPostalCode","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/residentState","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/sex","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/signatureUsualMark","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/unDistinguishingSign","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/weight"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"],"anchor":"Main-Classes","generated":true,"title":"Main Classes"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlDocument"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"signatureUsualMark","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1signatureUsualMark\/title"},{"op":"replace","value":[{"kind":"identifier","text":"signatureUsualMark"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1signatureUsualMark\/fragments"},{"op":"replace","value":"height","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1height\/title"},{"op":"replace","value":[{"kind":"identifier","text":"height"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1height\/fragments"},{"op":"replace","value":"XTMdlHolder","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlHolder"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlHolder"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle"},{"op":"replace","value":"documentNumber","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1documentNumber\/title"},{"op":"replace","value":[{"kind":"identifier","text":"documentNumber"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1documentNumber\/fragments"},{"op":"replace","value":"hairColour","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1hairColour\/title"},{"op":"replace","value":[{"kind":"identifier","text":"hairColour"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1hairColour\/fragments"},{"op":"replace","value":"familyName","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1familyName\/title"},{"op":"replace","value":[{"kind":"identifier","text":"familyName"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1familyName\/fragments"},{"op":"replace","value":"expiryDate","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1expiryDate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"expiryDate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1expiryDate\/fragments"},{"op":"replace","value":"weight","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1weight\/title"},{"op":"replace","value":[{"kind":"identifier","text":"weight"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1weight\/fragments"},{"op":"replace","value":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/fragments"},{"op":"replace","value":"portrait","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1portrait\/title"},{"op":"replace","value":[{"kind":"identifier","text":"portrait"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1portrait\/fragments"},{"op":"replace","value":"residentAddress","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1residentAddress\/title"},{"op":"replace","value":[{"kind":"identifier","text":"residentAddress"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1residentAddress\/fragments"},{"op":"replace","value":"holderIdNumber","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1holderIdNumber\/title"},{"op":"replace","value":[{"kind":"identifier","text":"holderIdNumber"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1holderIdNumber\/fragments"},{"op":"replace","value":"administrativeNumber","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1administrativeNumber\/title"},{"op":"replace","value":[{"text":"administrativeNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1administrativeNumber\/fragments"},{"op":"replace","value":"XTMdlHolderDelegate","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/title"},{"op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1givenNameNationalCharacter\/title","op":"replace","value":"givenNameNationalCharacter"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1givenNameNationalCharacter\/fragments","value":[{"text":"givenNameNationalCharacter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1portraitCaptureDate\/title","value":"portraitCaptureDate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"portraitCaptureDate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1portraitCaptureDate\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1birthDate\/title","value":"birthDate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"birthDate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1birthDate\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1issuingCountry\/title","value":"issuingCountry","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1issuingCountry\/fragments","value":[{"text":"issuingCountry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1issueDate\/title","value":"issueDate","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1issueDate\/fragments","value":[{"text":"issueDate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1dlIssueDate\/title","value":"dlIssueDate","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1dlIssueDate\/fragments","value":[{"text":"dlIssueDate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1dlExpiryDate\/title","value":"dlExpiryDate","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1dlExpiryDate\/fragments","value":[{"text":"dlExpiryDate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1nationality\/title","value":"nationality","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1nationality\/fragments","value":[{"text":"nationality","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1residentPostalCode\/title","value":"residentPostalCode","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1residentPostalCode\/fragments","value":[{"kind":"identifier","text":"residentPostalCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1ageInYears\/title","value":"ageInYears","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1ageInYears\/fragments","value":[{"kind":"identifier","text":"ageInYears"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1givenName\/title","value":"givenName","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1givenName\/fragments","value":[{"kind":"identifier","text":"givenName"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/title","op":"replace","value":"XTMdlDocumentField"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocumentField"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocumentField"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1ageOverNn\/title","op":"replace","value":"ageOverNn"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1ageOverNn\/fragments","op":"replace","value":[{"kind":"identifier","text":"ageOverNn"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1eyeColour\/title","op":"replace","value":"eyeColour"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1eyeColour\/fragments","op":"replace","value":[{"kind":"identifier","text":"eyeColour"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1biometricTemplateXx\/title","op":"replace","value":"biometricTemplateXx"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1biometricTemplateXx\/fragments","op":"replace","value":[{"kind":"identifier","text":"biometricTemplateXx"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1issuingAuthority\/title","op":"replace","value":"issuingAuthority"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1issuingAuthority\/fragments","op":"replace","value":[{"kind":"identifier","text":"issuingAuthority"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1residentCountry\/title","op":"replace","value":"residentCountry"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1residentCountry\/fragments","op":"replace","value":[{"kind":"identifier","text":"residentCountry"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1ageBirthYear\/title","op":"replace","value":"ageBirthYear"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1ageBirthYear\/fragments","op":"replace","value":[{"kind":"identifier","text":"ageBirthYear"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1residentCity\/title","op":"replace","value":"residentCity"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1residentCity\/fragments","op":"replace","value":[{"kind":"identifier","text":"residentCity"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1drivingRestrictions\/title","op":"replace","value":"drivingRestrictions"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1drivingRestrictions\/fragments","op":"replace","value":[{"kind":"identifier","text":"drivingRestrictions"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1drivingPrivileges\/title","op":"replace","value":"drivingPrivileges"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1drivingPrivileges\/fragments","op":"replace","value":[{"kind":"identifier","text":"drivingPrivileges"}]},{"op":"replace","value":"familyNameNationalCharacter","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1familyNameNationalCharacter\/title"},{"op":"replace","value":[{"kind":"identifier","text":"familyNameNationalCharacter"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1familyNameNationalCharacter\/fragments"},{"op":"replace","value":"residentState","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1residentState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"residentState"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1residentState\/fragments"},{"op":"replace","value":"issuingJurisdiction","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1issuingJurisdiction\/title"},{"op":"replace","value":[{"kind":"identifier","text":"issuingJurisdiction"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1issuingJurisdiction\/fragments"},{"op":"replace","value":"XTMdlDocument","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/navigatorTitle"},{"op":"replace","value":"bloodGroup","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1bloodGroup\/title"},{"op":"replace","value":[{"kind":"identifier","text":"bloodGroup"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1bloodGroup\/fragments"},{"op":"replace","value":"unDistinguishingSign","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1unDistinguishingSign\/title"},{"op":"replace","value":[{"kind":"identifier","text":"unDistinguishingSign"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1unDistinguishingSign\/fragments"},{"op":"replace","value":"birthPlace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1birthPlace\/title"},{"op":"replace","value":[{"text":"birthPlace","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1birthPlace\/fragments"},{"op":"replace","value":"sex","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1sex\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument~1sex\/fragments","value":[{"kind":"identifier","text":"sex"}]}]}]}