{"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTMdlDrivingPrivilegeCodes) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdldrivingprivilegecodes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdldrivingprivilegecodes"]}],"metadata":{"role":"symbol","title":"MdlDrivingPrivilegeCodes","symbolKind":"class","roleHeading":"Class","externalID":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilegeCodes","modules":[{"name":"MdlHolder"}],"navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}]},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes\/init(codes:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes\/codes"],"generated":true}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH"],"kind":"relationships","type":"conformsTo"}],"references":{"doc://com.xinfotech.mdlholder/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilegeCodes/init(codes:)":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes\/init(codes:)","title":"init(codes:)","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdldrivingprivilegecodes\/init(codes:)","navigatorTitle":[{"text":"initWithCodes:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"codes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilegeCode","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilegeCode","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://com.xinfotech.mdlholder/s7CVarArgP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilegeCodes/codes":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes\/codes","title":"codes","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdldrivingprivilegecodes\/codes","navigatorTitle":[{"kind":"identifier","text":"codes"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"codes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilegeCode","kind":"typeIdentifier","text":"MdlDrivingPrivilegeCode"},{"kind":"text","text":"]"}]},"doc://com.xinfotech.mdlholder/objc(cs)NSObject":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.xinfotech.mdlholder/SH":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SH","title":"Swift.Hashable"},"doc://com.xinfotech.mdlholder/objc(pl)NSObject":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilegeCodes":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes","title":"MdlDrivingPrivilegeCodes","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdldrivingprivilegecodes","navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlDrivingPrivilegeCodes"}]},"doc://com.xinfotech.mdlholder/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"XTMdlDrivingPrivilegeCodes"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}]},{"op":"replace","value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes\/codes"],"title":"Instance Properties","anchor":"Instance-Properties"},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCodes\/init(codes:)"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes~1init(codes:)\/title","value":"initWithCodes:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCodes:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes~1init(codes:)\/fragments"},{"value":"codes","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes~1codes\/title","op":"replace"},{"value":[{"text":"codes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes~1codes\/fragments","op":"replace"},{"op":"replace","value":"XTMdlDrivingPrivilegeCodes","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes\/title"},{"value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCodes\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}