{"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges","interfaceLanguage":"swift"},"abstract":[{"text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL).","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(XTMdlDrivingPrivileges) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivileges","kind":"identifier"}]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"text":"Each element in the ","type":"text"},{"code":"drivingPrivileges","type":"codeVoice"},{"text":" array describes a specific privilege the license holder has,","type":"text"},{"text":" ","type":"text"},{"text":"such as vehicle categories or conditions.","type":"text"}],"type":"paragraph"},{"name":"See Also","style":"note","content":[{"inlineContent":[{"text":"","type":"text"},{"code":"MdlDrivingPrivilege","type":"codeVoice"}],"type":"paragraph"}],"type":"aside"}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdldrivingprivileges"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdldrivingprivileges"]}],"metadata":{"role":"symbol","title":"MdlDrivingPrivileges","modules":[{"name":"MdlHolder"}],"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivileges","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivileges"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivileges","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges\/init(drivingPrivileges:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges\/description","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges\/drivingPrivileges"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH"],"type":"conformsTo"}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivileges/drivingPrivileges":{"url":"\/documentation\/mdlholder\/mdldrivingprivileges\/drivingprivileges","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drivingPrivileges","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilege"},{"text":"]","kind":"text"}],"abstract":[{"text":"An array of ","type":"text"},{"code":"MdlDrivingPrivilege","type":"codeVoice"},{"text":" objects representing individual driving privileges.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"drivingPrivileges","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges\/drivingPrivileges","role":"symbol","title":"drivingPrivileges"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivileges/init(drivingPrivileges:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"drivingPrivileges"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilege","text":"MdlDrivingPrivilege"},{"kind":"text","text":"])"}],"kind":"symbol","type":"topic","title":"init(drivingPrivileges:)","url":"\/documentation\/mdlholder\/mdldrivingprivileges\/init(drivingprivileges:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDrivingPrivileges:"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges\/init(drivingPrivileges:)","abstract":[{"text":"Initializes the container with the provided list of driving privileges.","type":"text"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivileges":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges","abstract":[{"type":"text","text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL)."}],"title":"MdlDrivingPrivileges","role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdldrivingprivileges","navigatorTitle":[{"text":"MdlDrivingPrivileges","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivileges"}]},"doc://com.xinfotech.mdlholder/SH":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SH","title":"Swift.Hashable"},"doc://com.xinfotech.mdlholder/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.xinfotech.mdlholder/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject","title":"NSObject"},"doc://com.xinfotech.mdlholder/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.xinfotech.mdlholder/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivileges/description":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges\/description","title":"description","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdldrivingprivileges\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.xinfotech.mdlholder/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ","title":"Swift.Equatable"},"doc://com.xinfotech.mdlholder/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"XTMdlDrivingPrivileges","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges\/description","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges\/drivingPrivileges"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivileges\/init(drivingPrivileges:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlDrivingPrivileges"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges~1drivingPrivileges\/title","value":"drivingPrivileges","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges~1drivingPrivileges\/fragments","value":[{"text":"drivingPrivileges","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges~1init(drivingPrivileges:)\/title","value":"initWithDrivingPrivileges:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges~1init(drivingPrivileges:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDrivingPrivileges:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges\/title","value":"XTMdlDrivingPrivileges","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges\/fragments","value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges~1description\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivileges~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}