{"abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"variants":[{"paths":["\/documentation\/mdlholder\/mdlfieldidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdlfieldidentifier"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder"]]},"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"metadata":{"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlFieldIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlFieldIdentifier"}],"symbolKind":"class","title":"MdlFieldIdentifier","modules":[{"name":"MdlHolder"}],"externalID":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/description","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/value"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/administrativeNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/ageBirthYear","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/ageInYears","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/all","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/birthDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/birthPlace","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/bloodGroup","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/dlExpiryDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/dlIssueDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/documentNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/drivingPrivileges","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/drivingRestrictions","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/expiryDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/eyeColour","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/familyName","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/familyNameNationalCharacter","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/givenName","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/givenNameNationalCharacter","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/hairColour","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/height","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/holderIdNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/issueDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/issuingAuthority","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/issuingCountry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/issuingJurisdiction","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/nationality","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/portrait","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/portraitCaptureDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentAddress","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentCity","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentCountry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentPostalCode","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentState","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/sex","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/signatureUsualMark","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/unDistinguishingSign","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/weight"],"generated":true,"anchor":"Type-Properties"},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/ageOverNn(age:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/biometricTemplate(templateName:)"],"title":"Type Methods"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(XTMdlFieldIdentifier) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlFieldIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"inlineContent":[{"type":"text","text":"Each identifier corresponds to a specific field key that can be used in combination with "},{"type":"codeVoice","code":"MdlDocumentField"},{"text":",","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"where the identifier serves as the field key and the associated value depends on the field’s context."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/ageInYears":{"abstract":[{"type":"text","text":"The age in years of the document holder."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageInYears"},{"kind":"text","text":": "},{"text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/ageInYears","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/ageinyears","title":"ageInYears","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ageInYears"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/sex":{"kind":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/sex","navigatorTitle":[{"text":"sex","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/sex","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"type":"topic","title":"sex","abstract":[{"text":"The sex of the document holder.","type":"text"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/administrativeNumber":{"abstract":[{"type":"text","text":"The administrative number."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"administrativeNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/administrativeNumber","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/administrativenumber","title":"administrativeNumber","kind":"symbol","type":"topic","navigatorTitle":[{"text":"administrativeNumber","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/residentPostalCode":{"abstract":[{"text":"The resident postal code of the document holder.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentPostalCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentPostalCode","title":"residentPostalCode","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/residentpostalcode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"residentPostalCode"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/height":{"abstract":[{"text":"The height of the document holder.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/height","title":"height","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/height","kind":"symbol","type":"topic","navigatorTitle":[{"text":"height","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/unDistinguishingSign":{"abstract":[{"type":"text","text":"The UN distinguishing sign."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unDistinguishingSign","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/unDistinguishingSign","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/undistinguishingsign","title":"unDistinguishingSign","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unDistinguishingSign"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/givenName":{"abstract":[{"type":"text","text":"The given name (first name) of the document holder."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"givenName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/givenName","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/givenname","title":"givenName","kind":"symbol","type":"topic","navigatorTitle":[{"text":"givenName","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/dlIssueDate":{"kind":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/dlissuedate","navigatorTitle":[{"kind":"identifier","text":"dlIssueDate"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/dlIssueDate","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dlIssueDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"}],"type":"topic","title":"dlIssueDate","abstract":[{"type":"text","text":"Date of issue of eDL (physical document) issued to mDL holder"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/portraitCaptureDate":{"abstract":[{"type":"text","text":"The portrait capture date."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"portraitCaptureDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/portraitCaptureDate","title":"portraitCaptureDate","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/portraitcapturedate","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"portraitCaptureDate"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/residentCity":{"abstract":[{"text":"The resident city of the document holder.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentCity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentCity","title":"residentCity","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/residentcity","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"residentCity"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/givenNameNationalCharacter":{"abstract":[{"text":"The given name in national characters.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenNameNationalCharacter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/givenNameNationalCharacter","title":"givenNameNationalCharacter","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/givennamenationalcharacter","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"givenNameNationalCharacter"}]},"doc://com.xinfotech.mdlholder/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/ageBirthYear":{"abstract":[{"text":"The birth year of the document holder.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageBirthYear"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/ageBirthYear","title":"ageBirthYear","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/agebirthyear","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ageBirthYear"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/all":{"abstract":[{"text":"Returns an array of all identifiers","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"},{"kind":"text","text":"]"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/all","title":"all","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/all","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"all"}]},"doc://com.xinfotech.mdlholder/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/residentCountry":{"abstract":[{"text":"The resident country of the document holder.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentCountry"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentCountry","title":"residentCountry","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/residentcountry","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"residentCountry"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/biometricTemplate(templateName:)":{"abstract":[{"text":"A biometric template value with the specified template name.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricTemplate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"templateName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/biometricTemplate(templateName:)","title":"biometricTemplate(templateName:)","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/biometrictemplate(templatename:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"biometricTemplateWithTemplateName:"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/eyeColour":{"abstract":[{"text":"The eye colour of the document holder.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeColour"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/eyeColour","title":"eyeColour","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/eyecolour","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"eyeColour"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/isEqual(_:)":{"url":"\/documentation\/mdlholder\/mdlfieldidentifier\/isequal(_:)","abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual(_:)","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/isEqual(_:)","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/familyName":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"familyName"}],"title":"familyName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"familyName"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/familyName","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The family name of the document holder."}],"url":"\/documentation\/mdlholder\/mdlfieldidentifier\/familyname"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/residentAddress":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"title":"residentAddress","navigatorTitle":[{"kind":"identifier","text":"residentAddress"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentAddress","abstract":[{"text":"The resident address of the document holder.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/residentaddress","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/signatureUsualMark":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureUsualMark"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"title":"signatureUsualMark","navigatorTitle":[{"kind":"identifier","text":"signatureUsualMark"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/signatureUsualMark","abstract":[{"text":"The signature or usual mark of the document holder.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/signatureusualmark","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/value":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"value","navigatorTitle":[{"text":"value","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/value","abstract":[{"type":"text","text":"Identifier value"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/value","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/issuingJurisdiction":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingJurisdiction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier"}],"title":"issuingJurisdiction","navigatorTitle":[{"kind":"identifier","text":"issuingJurisdiction"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/issuingJurisdiction","abstract":[{"type":"text","text":"The issuing jurisdiction of the document."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/issuingjurisdiction","type":"topic"},"doc://com.xinfotech.mdlholder/s7CVarArgP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"kind":"symbol","role":"collection","url":"\/documentation\/mdlholder","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/dlExpiryDate":{"navigatorTitle":[{"text":"dlExpiryDate","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"dlExpiryDate","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/dlexpirydate","abstract":[{"type":"text","text":"Date of expiry of eDL (physical document) issued to mDL holder"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dlExpiryDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/dlExpiryDate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/expiryDate":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiryDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"}],"title":"expiryDate","navigatorTitle":[{"kind":"identifier","text":"expiryDate"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/expiryDate","abstract":[{"type":"text","text":"The expiry date of the document."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/expirydate","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/issuingAuthority":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingAuthority"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"title":"issuingAuthority","navigatorTitle":[{"kind":"identifier","text":"issuingAuthority"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/issuingAuthority","abstract":[{"type":"text","text":"The issuing authority of the document."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/issuingauthority","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier":{"navigatorTitle":[{"kind":"identifier","text":"MdlFieldIdentifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"MdlFieldIdentifier","url":"\/documentation\/mdlholder\/mdlfieldidentifier","abstract":[{"text":"Provides predefined field identifiers used in mDL documents.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlFieldIdentifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/drivingPrivileges":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingPrivileges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"title":"drivingPrivileges","navigatorTitle":[{"kind":"identifier","text":"drivingPrivileges"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/drivingPrivileges","abstract":[{"type":"text","text":"The list of driving privileges of the document holder."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/drivingprivileges","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/bloodGroup":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bloodGroup"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"title":"bloodGroup","navigatorTitle":[{"kind":"identifier","text":"bloodGroup"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/bloodGroup","abstract":[{"text":"mDL holder’s blood group","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/bloodgroup","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/drivingRestrictions":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingRestrictions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"title":"drivingRestrictions","navigatorTitle":[{"kind":"identifier","text":"drivingRestrictions"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/drivingRestrictions","abstract":[{"type":"text","text":"Driver’s restrictions"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/drivingrestrictions","type":"topic"},"doc://com.xinfotech.mdlholder/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ","title":"Swift.Equatable"},"doc://com.xinfotech.mdlholder/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/issueDate":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"title":"issueDate","navigatorTitle":[{"kind":"identifier","text":"issueDate"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/issueDate","abstract":[{"type":"text","text":"The issue date of the document."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/issuedate","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/birthPlace":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthPlace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier"}],"title":"birthPlace","navigatorTitle":[{"kind":"identifier","text":"birthPlace"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/birthPlace","abstract":[{"type":"text","text":"The birth place of the document holder."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/birthplace","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/familyNameNationalCharacter":{"title":"familyNameNationalCharacter","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/familynamenationalcharacter","navigatorTitle":[{"kind":"identifier","text":"familyNameNationalCharacter"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/familyNameNationalCharacter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"familyNameNationalCharacter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The family name in national characters."}]},"doc://com.xinfotech.mdlholder/SH":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SH","title":"Swift.Hashable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/description","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/description","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/documentNumber":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"title":"documentNumber","navigatorTitle":[{"kind":"identifier","text":"documentNumber"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/documentNumber","abstract":[{"type":"text","text":"The document number."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/documentnumber","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/residentState":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"title":"residentState","navigatorTitle":[{"kind":"identifier","text":"residentState"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentState","abstract":[{"type":"text","text":"The resident state of the document holder."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/residentstate","type":"topic"},"doc://com.xinfotech.mdlholder/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/holderIdNumber":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"holderIdNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"title":"holderIdNumber","navigatorTitle":[{"kind":"identifier","text":"holderIdNumber"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/holderIdNumber","abstract":[{"type":"text","text":"mDL holder’s national ID or alien ID, or diplomatic ID"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/holderidnumber","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/birthDate":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"title":"birthDate","navigatorTitle":[{"kind":"identifier","text":"birthDate"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/birthDate","abstract":[{"type":"text","text":"The birth date of the document holder."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/birthdate","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/issuingCountry":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier"}],"title":"issuingCountry","navigatorTitle":[{"kind":"identifier","text":"issuingCountry"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/issuingCountry","abstract":[{"type":"text","text":"The issuing country of the document."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/issuingcountry","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/portrait":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"title":"portrait","navigatorTitle":[{"kind":"identifier","text":"portrait"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/portrait","abstract":[{"type":"text","text":"The portrait image of the document holder."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/portrait","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/hairColour":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"hairColour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"title":"hairColour","navigatorTitle":[{"kind":"identifier","text":"hairColour"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/hairColour","abstract":[{"type":"text","text":"The hair colour of the document holder."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/haircolour","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/ageOverNn(age:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageOverNn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"age"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"title":"ageOverNn(age:)","navigatorTitle":[{"kind":"identifier","text":"ageOverNnWithAge:"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/ageOverNn(age:)","abstract":[{"type":"text","text":"Indicates whether the document holder is over a certain age."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/ageovernn(age:)","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/weight":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"weight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"title":"weight","navigatorTitle":[{"kind":"identifier","text":"weight"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/weight","abstract":[{"type":"text","text":"The weight of the document holder."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/weight","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/nationality":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nationality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"title":"nationality","navigatorTitle":[{"kind":"identifier","text":"nationality"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/nationality","abstract":[{"type":"text","text":"The nationality of the document holder."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/nationality","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"XTMdlFieldIdentifier","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/description","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/value"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/isEqual(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/administrativeNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/ageBirthYear","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/ageInYears","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/all","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/birthDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/birthPlace","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/bloodGroup","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/dlExpiryDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/dlIssueDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/documentNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/drivingPrivileges","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/drivingRestrictions","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/expiryDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/eyeColour","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/familyName","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/familyNameNationalCharacter","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/givenName","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/givenNameNationalCharacter","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/hairColour","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/height","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/holderIdNumber","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/issueDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/issuingAuthority","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/issuingCountry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/issuingJurisdiction","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/nationality","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/portrait","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/portraitCaptureDate","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentAddress","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentCity","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentCountry","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentPostalCode","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentState","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/sex","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/signatureUsualMark","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/unDistinguishingSign","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/weight"],"anchor":"Type-Properties","title":"Type Properties"},{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/ageOverNn(age:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/biometricTemplate(templateName:)"],"anchor":"Type-Methods","title":"Type Methods"}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlFieldIdentifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ageInYears","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1ageInYears\/title"},{"value":[{"text":"ageInYears","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1ageInYears\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1sex\/title","value":"sex","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1sex\/fragments","value":[{"kind":"identifier","text":"sex"}],"op":"replace"},{"op":"replace","value":"administrativeNumber","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1administrativeNumber\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1administrativeNumber\/fragments","op":"replace","value":[{"text":"administrativeNumber","kind":"identifier"}]},{"op":"replace","value":"residentPostalCode","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentPostalCode\/title"},{"value":[{"text":"residentPostalCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentPostalCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1height\/title","value":"height"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1height\/fragments","value":[{"text":"height","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1unDistinguishingSign\/title","value":"unDistinguishingSign"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1unDistinguishingSign\/fragments","op":"replace","value":[{"text":"unDistinguishingSign","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1givenName\/title","op":"replace","value":"givenName"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1givenName\/fragments","op":"replace","value":[{"kind":"identifier","text":"givenName"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1dlIssueDate\/title","op":"replace","value":"dlIssueDate"},{"value":[{"text":"dlIssueDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1dlIssueDate\/fragments"},{"value":"portraitCaptureDate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1portraitCaptureDate\/title"},{"value":[{"kind":"identifier","text":"portraitCaptureDate"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1portraitCaptureDate\/fragments"},{"op":"replace","value":"residentCity","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentCity\/title"},{"op":"replace","value":[{"kind":"identifier","text":"residentCity"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentCity\/fragments"},{"value":"givenNameNationalCharacter","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1givenNameNationalCharacter\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1givenNameNationalCharacter\/fragments","value":[{"text":"givenNameNationalCharacter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1ageBirthYear\/title","value":"ageBirthYear","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1ageBirthYear\/fragments","value":[{"kind":"identifier","text":"ageBirthYear"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1all\/title","value":"all","op":"replace"},{"value":[{"kind":"identifier","text":"all"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1all\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentCountry\/title","value":"residentCountry","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentCountry\/fragments","value":[{"kind":"identifier","text":"residentCountry"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1biometricTemplate(templateName:)\/title","value":"biometricTemplateWithTemplateName:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1biometricTemplate(templateName:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"biometricTemplateWithTemplateName:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1eyeColour\/title","value":"eyeColour","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1eyeColour\/fragments","value":[{"kind":"identifier","text":"eyeColour"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1familyName\/title","value":"familyName","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1familyName\/fragments","value":[{"kind":"identifier","text":"familyName"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentAddress\/title","value":"residentAddress","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentAddress\/fragments","value":[{"kind":"identifier","text":"residentAddress"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1signatureUsualMark\/title","value":"signatureUsualMark"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1signatureUsualMark\/fragments","value":[{"kind":"identifier","text":"signatureUsualMark"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1value\/title","value":"value","op":"replace"},{"value":[{"kind":"identifier","text":"value"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1value\/fragments","op":"replace"},{"value":"issuingJurisdiction","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1issuingJurisdiction\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1issuingJurisdiction\/fragments","value":[{"kind":"identifier","text":"issuingJurisdiction"}]},{"value":"dlExpiryDate","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1dlExpiryDate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1dlExpiryDate\/fragments","value":[{"kind":"identifier","text":"dlExpiryDate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1expiryDate\/title","value":"expiryDate","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1expiryDate\/fragments","value":[{"kind":"identifier","text":"expiryDate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1issuingAuthority\/title","op":"replace","value":"issuingAuthority"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1issuingAuthority\/fragments","op":"replace","value":[{"kind":"identifier","text":"issuingAuthority"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/title","op":"replace","value":"XTMdlFieldIdentifier"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/fragments","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}],"op":"replace"},{"value":"drivingPrivileges","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1drivingPrivileges\/title"},{"value":[{"kind":"identifier","text":"drivingPrivileges"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1drivingPrivileges\/fragments"},{"value":"bloodGroup","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1bloodGroup\/title"},{"value":[{"kind":"identifier","text":"bloodGroup"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1bloodGroup\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1drivingRestrictions\/title","value":"drivingRestrictions","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1drivingRestrictions\/fragments","value":[{"kind":"identifier","text":"drivingRestrictions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1issueDate\/title","value":"issueDate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1issueDate\/fragments","value":[{"kind":"identifier","text":"issueDate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1birthPlace\/title","value":"birthPlace"},{"value":[{"kind":"identifier","text":"birthPlace"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1birthPlace\/fragments"},{"value":"familyNameNationalCharacter","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1familyNameNationalCharacter\/title"},{"value":[{"kind":"identifier","text":"familyNameNationalCharacter"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1familyNameNationalCharacter\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1description\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1documentNumber\/title","value":"documentNumber","op":"replace"},{"value":[{"kind":"identifier","text":"documentNumber"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1documentNumber\/fragments"},{"value":"residentState","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentState\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentState\/fragments","value":[{"kind":"identifier","text":"residentState"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1holderIdNumber\/title","value":"holderIdNumber","op":"replace"},{"value":[{"text":"holderIdNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1holderIdNumber\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1birthDate\/title","value":"birthDate"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1birthDate\/fragments","value":[{"kind":"identifier","text":"birthDate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1issuingCountry\/title","value":"issuingCountry","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1issuingCountry\/fragments","value":[{"kind":"identifier","text":"issuingCountry"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1portrait\/title","value":"portrait","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1portrait\/fragments","value":[{"kind":"identifier","text":"portrait"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1hairColour\/title","value":"hairColour","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1hairColour\/fragments","value":[{"kind":"identifier","text":"hairColour"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1ageOverNn(age:)\/title","value":"ageOverNnWithAge:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1ageOverNn(age:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"ageOverNnWithAge:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1weight\/title","value":"weight","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1weight\/fragments","value":[{"kind":"identifier","text":"weight"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1nationality\/title","value":"nationality","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1nationality\/fragments","value":[{"kind":"identifier","text":"nationality"}],"op":"replace"}]}]}