{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTMdlGender) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdlgender"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdlgender"]}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}],"symbolKind":"enum","roleHeading":"Enumeration","title":"MdlGender","role":"symbol","navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"modules":[{"name":"MdlHolder"}],"externalID":"c:@M@MdlHolder@E@XTMdlGender"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/female","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/male","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/notApplicable","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/notKnown"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/Equatable-Implementations","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH","doc:\/\/com.xinfotech.mdlholder\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender","title":"MdlGender","abstract":[],"role":"symbol","url":"\/documentation\/mdlholder\/mdlgender","kind":"symbol","navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender/notApplicable":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/notApplicable","title":"MdlGender.notApplicable","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdlgender\/notapplicable","navigatorTitle":[{"text":"XTMdlGenderNotApplicable","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notApplicable","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender/init(rawValue:)":{"url":"\/documentation\/mdlholder\/mdlgender\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/init(rawValue:)","role":"symbol","title":"init(rawValue:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender/RawRepresentable-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/mdlholder\/mdlgender\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/RawRepresentable-Implementations","abstract":[]},"doc://com.xinfotech.mdlholder/SH":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.xinfotech.mdlholder/SY":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender/notKnown":{"type":"topic","title":"MdlGender.notKnown","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/notKnown","role":"symbol","url":"\/documentation\/mdlholder\/mdlgender\/notknown","kind":"symbol","navigatorTitle":[{"text":"XTMdlGenderNotKnown","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notKnown","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/mdlholder\/mdlgender\/equatable-implementations"},"doc://com.xinfotech.mdlholder/SQ":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender/male":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/male","abstract":[],"title":"MdlGender.male","role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdlgender\/male","navigatorTitle":[{"kind":"identifier","text":"XTMdlGenderMale"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"male","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender/female":{"title":"MdlGender.female","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTMdlGenderFemale"}],"url":"\/documentation\/mdlholder\/mdlgender\/female","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"female"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/female","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"XTMdlGender"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"XTMdlGender","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlGender"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/female","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/male","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/notApplicable","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/notKnown"],"title":"Enumeration Cases","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XTMdlGender","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/title","value":"XTMdlGender"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/fragments","value":[{"kind":"identifier","text":"XTMdlGender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlGender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1notApplicable\/title","value":"XTMdlGenderNotApplicable"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1notApplicable\/fragments","value":[{"kind":"identifier","text":"XTMdlGenderNotApplicable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1notKnown\/title","value":"XTMdlGenderNotKnown"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1notKnown\/fragments","value":[{"kind":"identifier","text":"XTMdlGenderNotKnown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1male\/title","value":"XTMdlGenderMale"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1male\/fragments","value":[{"kind":"identifier","text":"XTMdlGenderMale"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1female\/title","value":"XTMdlGenderFemale"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1female\/fragments","value":[{"kind":"identifier","text":"XTMdlGenderFemale"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}