{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(XTMdlHolderDelegate) "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MdlHolderDelegate","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Methods in this protocol notify your app about incoming field requests, errors, connection status changes,"},{"text":" ","type":"text"},{"type":"text","text":"transfer progress, and completion of document transmission."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Delivers events from the "},{"type":"reference","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","isActive":true},{"type":"text","text":" during the mDL document sharing lifecycle."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdlholderdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdlholderdelegate"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MdlHolderDelegate","kind":"identifier"}],"role":"symbol","modules":[{"name":"MdlHolder"}],"navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"title":"MdlHolderDelegate","externalID":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate","symbolKind":"protocol","roleHeading":"Protocol"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"},"topicSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDataTransferProgress(transfered:total:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveError(_:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDocumentDidSent()"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"seeAlsoSections":[{"anchor":"Main-Classes","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField"],"title":"Main Classes"}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocumentField":{"abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}],"url":"\/documentation\/mdlholder\/mdldocumentfield","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MdlDocumentField","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"title":"MdlDocumentField","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate":{"abstract":[{"type":"text","text":"Delivers events from the "},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","isActive":true,"type":"reference"},{"type":"text","text":" during the mDL document sharing lifecycle."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlHolderDelegate"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","url":"\/documentation\/mdlholder\/mdlholderdelegate","title":"MdlHolderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MdlHolderDelegate"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderDataTransferProgress(transfered:total:)":{"abstract":[{"type":"emphasis","inlineContent":[{"text":"(Optional)","type":"text"}]},{"type":"text","text":" Reports the progress of data transfer to the Reader."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderDataTransferProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transfered"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"total"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","required":true,"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDataTransferProgress(transfered:total:)","title":"mdlHolderDataTransferProgress(transfered:total:)","url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdatatransferprogress(transfered:total:)","type":"topic","kind":"symbol","defaultImplementations":1,"navigatorTitle":[{"text":"mdlHolderDataTransferProgressWithTransfered:total:","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderDocumentDidSent()":{"required":true,"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mdlHolderDocumentDidSent"}],"defaultImplementations":1,"kind":"symbol","title":"mdlHolderDocumentDidSent()","url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdocumentdidsent()","abstract":[{"inlineContent":[{"type":"text","text":"(Optional)"}],"type":"emphasis"},{"type":"text","text":" Indicates that the document has been fully sent to the Reader."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderDocumentDidSent"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDocumentDidSent()"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderConnectionStatusChanged(isReaderConnected:)":{"required":true,"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:"}],"defaultImplementations":1,"kind":"symbol","title":"mdlHolderConnectionStatusChanged(isReaderConnected:)","url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderconnectionstatuschanged(isreaderconnected:)","abstract":[{"inlineContent":[{"type":"text","text":"(Optional)"}],"type":"emphasis"},{"type":"text","text":" Notifies about a change in the connection status to the Reader."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderConnectionStatusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isReaderConnected"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlholder","type":"topic","kind":"symbol","title":"MdlHolder","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderDidReceiveRequestedFields(_:)":{"role":"symbol","navigatorTitle":[{"text":"mdlHolderDidReceiveRequestedFields:","kind":"identifier"}],"required":true,"title":"mdlHolderDidReceiveRequestedFields(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","type":"topic","abstract":[{"type":"text","text":"Called when the Reader requests specific document fields."}],"url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdidreceiverequestedfields(_:)","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"abstract":[{"text":"Main class of the SDK","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolder"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","title":"MdlHolder","url":"\/documentation\/mdlholder\/mdlholder","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlHolder"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderDidReceiveError(_:)":{"role":"symbol","navigatorTitle":[{"text":"mdlHolderDidReceiveError:","kind":"identifier"}],"required":true,"title":"mdlHolderDidReceiveError(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDidReceiveError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveError(_:)","type":"topic","url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdidreceiveerror(_:)","kind":"symbol","abstract":[{"type":"text","text":"Called when an error occurs in the sharing workflow."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument":{"url":"\/documentation\/mdlholder\/mdldocument","abstract":[{"type":"text","text":"Representation of mDL document"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"title":"MdlDocument","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"XTMdlHolderDelegate","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderConnectionStatusChanged(isReaderConnected:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDataTransferProgress(transfered:total:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveError(_:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDocumentDidSent()"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"Main Classes","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField"],"generated":true,"anchor":"Main-Classes"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlHolderDelegate"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"XTMdlDocumentField","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocumentField"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocumentField"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/navigatorTitle"},{"op":"replace","value":"XTMdlHolderDelegate","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/navigatorTitle"},{"op":"replace","value":"mdlHolderDataTransferProgressWithTransfered:total:","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDataTransferProgress(transfered:total:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlHolderDataTransferProgressWithTransfered:total:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDataTransferProgress(transfered:total:)\/fragments"},{"op":"replace","value":"mdlHolderDocumentDidSent","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDocumentDidSent()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlHolderDocumentDidSent"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDocumentDidSent()\/fragments"},{"op":"replace","value":"mdlHolderConnectionStatusChangedWithIsReaderConnected:","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderConnectionStatusChanged(isReaderConnected:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlHolderConnectionStatusChangedWithIsReaderConnected:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderConnectionStatusChanged(isReaderConnected:)\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/title","value":"mdlHolderDidReceiveRequestedFields:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/fragments"},{"op":"replace","value":"XTMdlHolder","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlHolder"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlHolder"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle"},{"op":"replace","value":"mdlHolderDidReceiveError:","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveError(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlHolderDidReceiveError:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveError(_:)\/fragments"},{"op":"replace","value":"XTMdlDocument","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/navigatorTitle"}]}]}