{"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Main class of the SDK"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTMdlHolder) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolder","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder"]]},"variants":[{"paths":["\/documentation\/mdlholder\/mdlholder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdlholder"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@MdlHolder@objc(cs)XTMdlHolder","title":"MdlHolder","navigatorTitle":[{"kind":"identifier","text":"MdlHolder"}],"symbolKind":"class","roleHeading":"Class","modules":[{"name":"MdlHolder"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolder"}],"role":"symbol"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/mdlDocument"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/approveDocumentSharing(completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/initialize()","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/initialize(completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/loadDocumentWith(token:pin:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/loadDocumentWith(token:pin:completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/rejectDocumentSharing(completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/removeDocument()","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/startDocumentSharing(withPin:delegate:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/startDocumentSharing(withPin:delegate:completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/updateRootCertificates()","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/updateRootCertificates(completion:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/sdkVersion","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/shared"],"generated":true,"anchor":"Type-Properties"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"],"generated":true,"anchor":"Main-Classes","title":"Main Classes"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlholder\/SQ","doc:\/\/com.xinfotech.mdlholder\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"references":{"doc://com.xinfotech.mdlholder/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SQ"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/sdkVersion":{"title":"sdkVersion","kind":"symbol","navigatorTitle":[{"text":"sdkVersion","kind":"identifier"}],"url":"\/documentation\/mdlholder\/mdlholder\/sdkversion","abstract":[{"type":"text","text":"Framework version"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkVersion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/sdkVersion","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/startDocumentSharing(withPin:delegate:)":{"type":"topic","title":"startDocumentSharing(withPin:delegate:)","abstract":[{"type":"text","text":"This method initializes the document sharing process"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/startDocumentSharing(withPin:delegate:)","role":"symbol","url":"\/documentation\/mdlholder\/mdlholder\/startdocumentsharing(withpin:delegate:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDocumentSharing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPin"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate","kind":"typeIdentifier","text":"MdlHolderDelegate"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.xinfotech.mdlholder/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.xinfotech.mdlholder\/SH","type":"unresolvable"},"doc://com.xinfotech.mdlholder/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/loadDocumentWith(token:pin:completion:)":{"type":"topic","abstract":[{"type":"text","text":"The asynchronous method that loads a document into the SDK"}],"title":"loadDocumentWith(token:pin:completion:)","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/loadDocumentWith(token:pin:completion:)","role":"symbol","url":"\/documentation\/mdlholder\/mdlholder\/loaddocumentwith(token:pin:completion:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadDocumentWithToken:pin:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadDocumentWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/mdlDocument":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlDocument"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlDocument","kind":"typeIdentifier","text":"MdlDocument"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholder\/mdlholder\/mdldocument","title":"mdlDocument","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mdlDocument"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/mdlDocument","abstract":[{"text":"Returns the entire mDL document from the local  SDK storage or nil if document missing","type":"text"}]},"doc://com.xinfotech.mdlholder/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.xinfotech.mdlholder\/objc(pl)NSObject","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/removeDocument()":{"type":"topic","title":"removeDocument()","abstract":[{"type":"text","text":"Deletes a document and all associated data from the local SDK storage."}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/removeDocument()","role":"symbol","url":"\/documentation\/mdlholder\/mdlholder\/removedocument()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"removeDocument"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDocument"},{"kind":"text","text":"()"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/startDocumentSharing(withPin:delegate:completion:)":{"type":"topic","title":"startDocumentSharing(withPin:delegate:completion:)","abstract":[{"text":"Starts the mDL document sharing session initiated via QR engagement.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/startDocumentSharing(withPin:delegate:completion:)","role":"symbol","url":"\/documentation\/mdlholder\/mdlholder\/startdocumentsharing(withpin:delegate:completion:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"startDocumentSharingWithPin:delegate:completion:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDocumentSharing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlHolderDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, ("},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/initialize()":{"type":"topic","title":"initialize()","abstract":[{"type":"text","text":"SDK initialization, async version of method"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/initialize()","role":"symbol","url":"\/documentation\/mdlholder\/mdlholder\/initialize()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}]},"doc://com.xinfotech.mdlholder/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.xinfotech.mdlholder\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate":{"url":"\/documentation\/mdlholder\/mdlholderdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlHolderDelegate"}],"abstract":[{"text":"Delivers events from the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","type":"reference"},{"type":"text","text":" during the mDL document sharing lifecycle."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlHolderDelegate"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","role":"symbol","title":"MdlHolderDelegate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/approveDocumentSharing(completion:)":{"type":"topic","title":"approveDocumentSharing(completion:)","abstract":[{"type":"text","text":"This method sends the requested document fields to the reader."}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/approveDocumentSharing(completion:)","role":"symbol","url":"\/documentation\/mdlholder\/mdlholder\/approvedocumentsharing(completion:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"approveDocumentSharingWithCompletion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"approveDocumentSharing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]},"doc://com.xinfotech.mdlholder/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlholder\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocumentField":{"type":"topic","abstract":[{"type":"text","text":"Represents an mDL document field containing an identifier and a corresponding value."}],"title":"MdlDocumentField","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","role":"symbol","url":"\/documentation\/mdlholder\/mdldocumentfield","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocumentField"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/loadDocumentWith(token:pin:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadDocumentWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","type":"topic","title":"loadDocumentWith(token:pin:)","url":"\/documentation\/mdlholder\/mdlholder\/loaddocumentwith(token:pin:)","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/loadDocumentWith(token:pin:)","abstract":[{"type":"text","text":"The async version of method that loads a document into the SDK"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/shared":{"type":"topic","abstract":[{"type":"text","text":"The shared framework instance"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/shared","title":"shared","role":"symbol","url":"\/documentation\/mdlholder\/mdlholder\/shared","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"shared"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlHolder","text":"MdlHolder"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/rejectDocumentSharing(completion:)":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/rejectDocumentSharing(completion:)","title":"rejectDocumentSharing(completion:)","abstract":[{"text":"This method rejects the document request.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdlholder\/rejectdocumentsharing(completion:)","navigatorTitle":[{"kind":"identifier","text":"rejectDocumentSharingWithCompletion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rejectDocumentSharing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"url":"\/documentation\/mdlholder\/mdlholder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolder","kind":"identifier"}],"abstract":[{"text":"Main class of the SDK","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MdlHolder","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","role":"symbol","title":"MdlHolder"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/updateRootCertificates(completion:)":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/updateRootCertificates(completion:)","title":"updateRootCertificates(completion:)","abstract":[{"text":"Downloads CA Root certificates and updates them in the local SDK storage","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdlholder\/updaterootcertificates(completion:)","navigatorTitle":[{"kind":"identifier","text":"updateRootCertificatesWithCompletion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRootCertificates"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/initialize(completion:)":{"url":"\/documentation\/mdlholder\/mdlholder\/initialize(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"text":"SDK initialization","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initializeWithCompletion:"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/initialize(completion:)","role":"symbol","title":"initialize(completion:)"},"doc://com.xinfotech.mdlholder/s7CVarArgP":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDocument":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","title":"MdlDocument","abstract":[{"text":"Representation of mDL document","type":"text"}],"role":"symbol","url":"\/documentation\/mdlholder\/mdldocument","kind":"symbol","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MdlDocument","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/updateRootCertificates()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRootCertificates"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholder\/mdlholder\/updaterootcertificates()","title":"updateRootCertificates()","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/updateRootCertificates()","abstract":[{"text":"Downloads CA Root certificates and updates them in the local SDK storage","type":"text"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/XTMdlHolder/init":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/XTMdlHolder\/init","title":"init","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/xtmdlholder\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"XTMdlHolder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/mdlDocument"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/approveDocumentSharing(completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/initialize(completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/loadDocumentWith(token:pin:completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/rejectDocumentSharing(completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/removeDocument()","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/startDocumentSharing(withPin:delegate:completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/updateRootCertificates(completion:)","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/XTMdlHolder\/init"]},{"anchor":"Type-Properties","generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/sdkVersion","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/shared"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.xinfotech.mdlholder\/objc(cs)NSObject"],"title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Main-Classes","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocument","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDocumentField","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate"],"title":"Main Classes","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlHolder"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1sdkVersion\/title","value":"sdkVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1sdkVersion\/fragments","value":[{"text":"sdkVersion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1loadDocumentWith(token:pin:completion:)\/title","value":"loadDocumentWithToken:pin:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1loadDocumentWith(token:pin:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadDocumentWithToken:pin:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1mdlDocument\/title","value":"mdlDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1mdlDocument\/fragments","value":[{"text":"mdlDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1removeDocument()\/title","value":"removeDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1removeDocument()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1startDocumentSharing(withPin:delegate:completion:)\/title","value":"startDocumentSharingWithPin:delegate:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1startDocumentSharing(withPin:delegate:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startDocumentSharingWithPin:delegate:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/title","value":"XTMdlHolderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/fragments","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/navigatorTitle","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1approveDocumentSharing(completion:)\/title","value":"approveDocumentSharingWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1approveDocumentSharing(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"approveDocumentSharingWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/title","value":"XTMdlDocumentField"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/fragments","value":[{"text":"XTMdlDocumentField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocumentField\/navigatorTitle","value":[{"text":"XTMdlDocumentField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1rejectDocumentSharing(completion:)\/title","value":"rejectDocumentSharingWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1rejectDocumentSharing(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rejectDocumentSharingWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title","value":"XTMdlHolder"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle","value":[{"text":"XTMdlHolder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1updateRootCertificates(completion:)\/title","value":"updateRootCertificatesWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1updateRootCertificates(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateRootCertificatesWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1initialize(completion:)\/title","value":"initializeWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1initialize(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initializeWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/title","value":"XTMdlDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/fragments","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDocument\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocument"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}