{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleUnauthorized"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"case","title":"ReaderErrorCode.bleUnauthorized","modules":[{"name":"MdlReaderSdk"}],"externalID":"c:@M@MdlReaderSdk@E@XTReaderErrorCode@XTReaderErrorCodeBleUnauthorized","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bleUnauthorized","kind":"identifier"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnauthorized"}]},"variants":[{"paths":["\/documentation\/mdlreadersdk\/readererrorcode\/bleunauthorized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/readererrorcode\/bleunauthorized"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode"]]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleUnauthorized","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/bleUnauthorized":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleUnauthorized","abstract":[],"role":"symbol","navigatorTitle":[{"text":"XTReaderErrorCodeBleUnauthorized","kind":"identifier"}],"title":"ReaderErrorCode.bleUnauthorized","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bleUnauthorized","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/readererrorcode\/bleunauthorized","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/readererrorcode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReaderErrorCode"}],"title":"ReaderErrorCode","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode","navigatorTitle":[{"kind":"identifier","text":"ReaderErrorCode"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"XTReaderErrorCodeBleUnauthorized","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnauthorized"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnauthorized"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"XTReaderErrorCodeBleUnauthorized","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1bleUnauthorized\/title"},{"value":[{"text":"XTReaderErrorCodeBleUnauthorized","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1bleUnauthorized\/fragments"},{"value":"XTReaderErrorCode","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"XTReaderErrorCode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}