{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/readererrorcode\/bleunsupported"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/readererrorcode\/bleunsupported"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bleUnsupported","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleUnsupported","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MdlReaderSdk"}],"title":"ReaderErrorCode.bleUnsupported","navigatorTitle":[{"text":"XTReaderErrorCodeBleUnsupported","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@E@XTReaderErrorCode@XTReaderErrorCodeBleUnsupported","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bleUnsupported"}],"symbolKind":"case","roleHeading":"Case"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode":{"navigatorTitle":[{"text":"ReaderErrorCode","kind":"identifier"}],"kind":"symbol","title":"ReaderErrorCode","url":"\/documentation\/mdlreadersdk\/readererrorcode","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderErrorCode","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/bleUnsupported":{"kind":"symbol","title":"ReaderErrorCode.bleUnsupported","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnsupported"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleUnsupported"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleUnsupported","url":"\/documentation\/mdlreadersdk\/readererrorcode\/bleunsupported"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"XTReaderErrorCodeBleUnsupported"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"XTReaderErrorCodeBleUnsupported","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnsupported"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/title","value":"XTReaderErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/fragments","value":[{"text":"XTReaderErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"XTReaderErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1bleUnsupported\/title","value":"XTReaderErrorCodeBleUnsupported"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1bleUnsupported\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnsupported"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}