{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientCertificateNotFound","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/readererrorcode\/clientcertificatenotfound"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/readererrorcode\/clientcertificatenotfound"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode"]]},"metadata":{"symbolKind":"case","title":"ReaderErrorCode.clientCertificateNotFound","modules":[{"name":"MdlReaderSdk"}],"externalID":"c:@M@MdlReaderSdk@E@XTReaderErrorCode@XTReaderErrorCodeClientCertificateNotFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"clientCertificateNotFound","kind":"identifier"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"XTReaderErrorCodeClientCertificateNotFound","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/clientCertificateNotFound","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/readererrorcode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReaderErrorCode"}],"title":"ReaderErrorCode","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode","navigatorTitle":[{"kind":"identifier","text":"ReaderErrorCode"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/clientCertificateNotFound":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"clientCertificateNotFound","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"XTReaderErrorCodeClientCertificateNotFound","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/readererrorcode\/clientcertificatenotfound","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/clientCertificateNotFound","title":"ReaderErrorCode.clientCertificateNotFound","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"XTReaderErrorCodeClientCertificateNotFound"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"XTReaderErrorCodeClientCertificateNotFound","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"XTReaderErrorCodeClientCertificateNotFound","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/title","value":"XTReaderErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/fragments","value":[{"text":"XTReaderErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"XTReaderErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1clientCertificateNotFound\/title","value":"XTReaderErrorCodeClientCertificateNotFound","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1clientCertificateNotFound\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeClientCertificateNotFound"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}