{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cryptographicError","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/cryptographicError"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/readererrorcode\/cryptographicerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/readererrorcode\/cryptographicerror"]}],"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeCryptographicError"}],"modules":[{"name":"MdlReaderSdk"}],"symbolKind":"case","title":"ReaderErrorCode.cryptographicError","roleHeading":"Case","externalID":"c:@M@MdlReaderSdk@E@XTReaderErrorCode@XTReaderErrorCodeCryptographicError","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cryptographicError"}]},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/readererrorcode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReaderErrorCode"}],"title":"ReaderErrorCode","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode","navigatorTitle":[{"kind":"identifier","text":"ReaderErrorCode"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection","title":"MdlReaderSdk","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/cryptographicError":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/readererrorcode\/cryptographicerror","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cryptographicError","kind":"identifier"}],"title":"ReaderErrorCode.cryptographicError","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/cryptographicError","navigatorTitle":[{"text":"XTReaderErrorCodeCryptographicError","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"XTReaderErrorCodeCryptographicError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeCryptographicError"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"XTReaderErrorCodeCryptographicError","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"XTReaderErrorCode","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTReaderErrorCode"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/navigatorTitle","value":[{"text":"XTReaderErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1cryptographicError\/title","value":"XTReaderErrorCodeCryptographicError"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1cryptographicError\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeCryptographicError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}