{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/notInitialized","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"notInitialized","kind":"identifier"}]}]}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeNotInitialized"}],"symbolKind":"case","modules":[{"name":"MdlReaderSdk"}],"title":"ReaderErrorCode.notInitialized","roleHeading":"Case","externalID":"c:@M@MdlReaderSdk@E@XTReaderErrorCode@XTReaderErrorCodeNotInitialized","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notInitialized"}]},"variants":[{"paths":["\/documentation\/mdlreadersdk\/readererrorcode\/notinitialized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/readererrorcode\/notinitialized"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode"]]},"sections":[],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/readererrorcode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReaderErrorCode"}],"title":"ReaderErrorCode","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode","navigatorTitle":[{"kind":"identifier","text":"ReaderErrorCode"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/notInitialized":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeNotInitialized"}],"title":"ReaderErrorCode.notInitialized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notInitialized"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/readererrorcode\/notinitialized","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/notInitialized"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"XTReaderErrorCodeNotInitialized"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTReaderErrorCodeNotInitialized"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"XTReaderErrorCodeNotInitialized","kind":"identifier"}],"languages":["occ"]}]}},{"value":"XTReaderErrorCode","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/navigatorTitle","op":"replace","value":[{"text":"XTReaderErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1notInitialized\/title","op":"replace","value":"XTReaderErrorCodeNotInitialized"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1notInitialized\/fragments","op":"replace","value":[{"text":"XTReaderErrorCodeNotInitialized","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}