{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/readererrorcode\/pinisempty"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/readererrorcode\/pinisempty"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pinIsEmpty","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/pinIsEmpty","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MdlReaderSdk"}],"title":"ReaderErrorCode.pinIsEmpty","navigatorTitle":[{"text":"XTReaderErrorCodePinIsEmpty","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@E@XTReaderErrorCode@XTReaderErrorCodePinIsEmpty","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pinIsEmpty","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/pinIsEmpty":{"kind":"symbol","title":"ReaderErrorCode.pinIsEmpty","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodePinIsEmpty"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinIsEmpty"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/pinIsEmpty","url":"\/documentation\/mdlreadersdk\/readererrorcode\/pinisempty"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode":{"navigatorTitle":[{"text":"ReaderErrorCode","kind":"identifier"}],"kind":"symbol","title":"ReaderErrorCode","url":"\/documentation\/mdlreadersdk\/readererrorcode","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderErrorCode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"XTReaderErrorCodePinIsEmpty","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"XTReaderErrorCodePinIsEmpty"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"XTReaderErrorCodePinIsEmpty"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1pinIsEmpty\/title","value":"XTReaderErrorCodePinIsEmpty"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1pinIsEmpty\/fragments","value":[{"text":"XTReaderErrorCodePinIsEmpty","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/title","value":"XTReaderErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/fragments","value":[{"text":"XTReaderErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/navigatorTitle","value":[{"text":"XTReaderErrorCode","kind":"identifier"}]}]}]}