{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader"]]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/mdlreader\/mdlreader\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@MdlReader@objc(cs)MdlReader(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","modules":[{"name":"MdlReader"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/init":{"role":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/init","abstract":[],"url":"\/documentation\/mdlreader\/mdlreader\/init"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader":{"url":"\/documentation\/mdlreader\/mdlreader","title":"MdlReader","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader","kind":"symbol","navigatorTitle":[{"text":"MdlReader","kind":"identifier"}],"abstract":[{"text":"Main class of the SDK","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReader","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MdlReader","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MdlReader"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/fragments"},{"op":"replace","value":[{"text":"MdlReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}