{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"MdlReader"}],"externalID":"c:@M@MdlReader@objc(cs)MdlReader(im)stopRequestDocument","title":"stopRequestDocument()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRequestDocument"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"stopRequestDocument","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/stopRequestDocument()"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRequestDocument"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdlreader\/stoprequestdocument()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdlreader\/stoprequestdocument()"]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader/stopRequestDocument()":{"role":"symbol","title":"stopRequestDocument()","navigatorTitle":[{"kind":"identifier","text":"stopRequestDocument"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRequestDocument"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader\/stopRequestDocument()","abstract":[],"url":"\/documentation\/mdlreader\/mdlreader\/stoprequestdocument()"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlReader":{"url":"\/documentation\/mdlreader\/mdlreader","title":"MdlReader","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlReader","kind":"symbol","navigatorTitle":[{"text":"MdlReader","kind":"identifier"}],"abstract":[{"text":"Main class of the SDK","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReader","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"stopRequestDocument","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopRequestDocument"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopRequestDocument"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1stopRequestDocument()\/title","value":"stopRequestDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader~1stopRequestDocument()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stopRequestDocument"}],"op":"replace"},{"op":"replace","value":"MdlReader","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/fragments","op":"replace","value":[{"text":"MdlReader","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MdlReader"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlReader\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}