{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes"]]},"metadata":{"symbolKind":"init","platforms":[{"beta":false,"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0"}],"roleHeading":"Initializer","modules":[{"name":"MdlReaderSdk"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilegeCodes(im)initWithCodes:","navigatorTitle":[{"kind":"identifier","text":"initWithCodes:"}],"title":"init(codes:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"codes","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilegeCode","text":"MdlDrivingPrivilegeCode"},{"text":"])","kind":"text"}]},"sections":[],"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdldrivingprivilegecodes\/init(codes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdldrivingprivilegecodes\/init(codes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes\/init(codes:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codes"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilegeCode","kind":"typeIdentifier","text":"MdlDrivingPrivilegeCode"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCodes/init(codes:)":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes\/init(codes:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"codes","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"MdlDrivingPrivilegeCode","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilegeCode","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"navigatorTitle":[{"text":"initWithCodes:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecodes\/init(codes:)","title":"init(codes:)","abstract":[]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection","title":"MdlReaderSdk","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCodes":{"navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecodes","title":"MdlDrivingPrivilegeCodes","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes","kind":"symbol","abstract":[]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCode":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilegeCode"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecode","title":"MdlDrivingPrivilegeCode","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false,"beta":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithCodes:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCodes:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCodes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<XTMdlDrivingPrivilegeCode *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"codes"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithCodes:","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes~1init(codes:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCodes:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes~1init(codes:)\/fragments","op":"replace"},{"value":"XTMdlDrivingPrivilegeCodes","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes\/title","op":"replace"},{"value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes\/fragments","op":"replace"},{"value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes\/navigatorTitle","op":"replace"},{"value":"XTMdlDrivingPrivilegeCode","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode\/title","op":"replace"},{"value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode\/fragments","op":"replace"},{"value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}