{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleUnauthorized"},"kind":"symbol","metadata":{"externalID":"c:@M@MdlHolder@E@XTHolderErrorCode@XTHolderErrorCodeBleUnauthorized","roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeBleUnauthorized"}],"title":"HolderErrorCode.bleUnauthorized","symbolKind":"case","modules":[{"name":"MdlHolder"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleUnauthorized"}]},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleUnauthorized"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/mdlholder\/holdererrorcode\/bleunauthorized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/holdererrorcode\/bleunauthorized"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/bleUnauthorized":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bleUnauthorized","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholder\/holdererrorcode\/bleunauthorized","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/bleUnauthorized","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeBleUnauthorized"}],"title":"HolderErrorCode.bleUnauthorized","abstract":[]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","title":"MdlHolder","type":"topic","url":"\/documentation\/mdlholder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode":{"url":"\/documentation\/mdlholder\/holdererrorcode","title":"HolderErrorCode","navigatorTitle":[{"kind":"identifier","text":"HolderErrorCode"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HolderErrorCode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Possible error codes in SDK"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"XTHolderErrorCodeBleUnauthorized","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCodeBleUnauthorized"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"XTHolderErrorCodeBleUnauthorized","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1bleUnauthorized\/title","value":"XTHolderErrorCodeBleUnauthorized","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1bleUnauthorized\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCodeBleUnauthorized"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/title","value":"XTHolderErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"XTHolderErrorCode"}],"op":"replace"}]}]}