{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/holdererrorcode\/mdocerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/holdererrorcode\/mdocerror"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mDocError","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocError","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocError","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","title":"HolderErrorCode.mDocError","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeMDocError","kind":"identifier"}],"modules":[{"name":"MdlHolder"}],"externalID":"c:@M@MdlHolder@E@XTHolderErrorCode@XTHolderErrorCodeMDocError"},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HolderErrorCode"}],"kind":"symbol","type":"topic","title":"HolderErrorCode","url":"\/documentation\/mdlholder\/holdererrorcode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HolderErrorCode"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/mDocError":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocError"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholder\/holdererrorcode\/mdocerror","title":"HolderErrorCode.mDocError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeMDocError"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocError","abstract":[]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"XTHolderErrorCodeMDocError","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"XTHolderErrorCodeMDocError","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"XTHolderErrorCodeMDocError","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"XTHolderErrorCode","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTHolderErrorCode"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTHolderErrorCode"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/navigatorTitle"},{"op":"replace","value":"XTHolderErrorCodeMDocError","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocError\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTHolderErrorCodeMDocError"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocError\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}