{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"MdlHolder"}],"roleHeading":"Case","externalID":"c:@M@MdlHolder@E@XTHolderErrorCode@XTHolderErrorCodeMDocRequestError","navigatorTitle":[{"text":"XTHolderErrorCodeMDocRequestError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocRequestError"}],"title":"HolderErrorCode.mDocRequestError","symbolKind":"case","role":"symbol"},"variants":[{"paths":["\/documentation\/mdlholder\/holdererrorcode\/mdocrequesterror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/holdererrorcode\/mdocrequesterror"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocRequestError","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode"]]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocRequestError","interfaceLanguage":"swift"},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/mDocRequestError":{"kind":"symbol","url":"\/documentation\/mdlholder\/holdererrorcode\/mdocrequesterror","type":"topic","navigatorTitle":[{"text":"XTHolderErrorCodeMDocRequestError","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocRequestError","kind":"identifier"}],"abstract":[],"title":"HolderErrorCode.mDocRequestError","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocRequestError","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlholder\/holdererrorcode","navigatorTitle":[{"text":"HolderErrorCode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HolderErrorCode","kind":"identifier"}],"title":"HolderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"XTHolderErrorCodeMDocRequestError","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCodeMDocRequestError"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"XTHolderErrorCodeMDocRequestError"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocRequestError\/title","value":"XTHolderErrorCodeMDocRequestError","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocRequestError\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCodeMDocRequestError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/title","value":"XTHolderErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/fragments","value":[{"text":"XTHolderErrorCode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/navigatorTitle","value":[{"text":"XTHolderErrorCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}