{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode"]]},"metadata":{"symbolKind":"case","role":"symbol","roleHeading":"Case","externalID":"c:@M@MdlHolder@E@XTHolderErrorCode@XTHolderErrorCodeNotInitialized","title":"HolderErrorCode.notInitialized","modules":[{"name":"MdlHolder"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notInitialized"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeNotInitialized"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/mdlholder\/holdererrorcode\/notinitialized"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/holdererrorcode\/notinitialized"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notInitialized"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/notInitialized"},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HolderErrorCode"}],"title":"HolderErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"HolderErrorCode","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode","type":"topic","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"kind":"symbol","url":"\/documentation\/mdlholder\/holdererrorcode"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/notInitialized":{"navigatorTitle":[{"text":"XTHolderErrorCodeNotInitialized","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"HolderErrorCode.notInitialized","url":"\/documentation\/mdlholder\/holdererrorcode\/notinitialized","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notInitialized"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/notInitialized"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"kind":"symbol","role":"collection","url":"\/documentation\/mdlholder","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"XTHolderErrorCodeNotInitialized","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"XTHolderErrorCodeNotInitialized"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"XTHolderErrorCodeNotInitialized"}],"languages":["occ"]}]}},{"value":"XTHolderErrorCode","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCode"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTHolderErrorCode"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1notInitialized\/title","op":"replace","value":"XTHolderErrorCodeNotInitialized"},{"op":"replace","value":[{"kind":"identifier","text":"XTHolderErrorCodeNotInitialized"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1notInitialized\/fragments"}]}]}