{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootCaCertificateMissing"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/holdererrorcode\/rootcacertificatemissing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/holdererrorcode\/rootcacertificatemissing"]}],"metadata":{"title":"HolderErrorCode.rootCaCertificateMissing","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeRootCaCertificateMissing"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootCaCertificateMissing"}],"externalID":"c:@M@MdlHolder@E@XTHolderErrorCode@XTHolderErrorCodeRootCaCertificateMissing","modules":[{"name":"MdlHolder"}],"symbolKind":"case","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/rootCaCertificateMissing"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/rootCaCertificateMissing":{"url":"\/documentation\/mdlholder\/holdererrorcode\/rootcacertificatemissing","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootCaCertificateMissing"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/rootCaCertificateMissing","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeRootCaCertificateMissing"}],"title":"HolderErrorCode.rootCaCertificateMissing","abstract":[],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode":{"url":"\/documentation\/mdlholder\/holdererrorcode","title":"HolderErrorCode","navigatorTitle":[{"kind":"identifier","text":"HolderErrorCode"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HolderErrorCode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Possible error codes in SDK"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","title":"MdlHolder","type":"topic","url":"\/documentation\/mdlholder","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"XTHolderErrorCodeRootCaCertificateMissing","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"XTHolderErrorCodeRootCaCertificateMissing"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"XTHolderErrorCodeRootCaCertificateMissing"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"XTHolderErrorCodeRootCaCertificateMissing","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1rootCaCertificateMissing\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTHolderErrorCodeRootCaCertificateMissing"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1rootCaCertificateMissing\/fragments","op":"replace"},{"value":"XTHolderErrorCode","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTHolderErrorCode"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTHolderErrorCode"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/navigatorTitle","op":"replace"}]}]}