{"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"modules":[{"name":"MdlHolderSdk"}],"role":"symbol","title":"value","externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlDrivingPrivilegeCode(py)value","navigatorTitle":[{"text":"value","kind":"identifier"}],"platforms":[{"deprecated":false,"introducedAt":"14.0","unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"name":"Mac Catalyst","beta":false}],"symbolKind":"property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode"]]},"abstract":[{"text":"Value as per ISO\/IEC 18013-2 Annex A","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdldrivingprivilegecode\/value"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdldrivingprivilegecode\/value"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/value"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivilegeCode/value":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"Value as per ISO\/IEC 18013-2 Annex A","type":"text"}],"title":"value","role":"symbol","navigatorTitle":[{"text":"value","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode\/value","url":"\/documentation\/mdlholdersdk\/mdldrivingprivilegecode\/value"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlDrivingPrivilegeCode":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlDrivingPrivilegeCode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/mdldrivingprivilegecode","role":"symbol","navigatorTitle":[{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"abstract":[],"title":"MdlDrivingPrivilegeCode"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"14.0","deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"14.0","deprecated":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"14.0","deprecated":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"value"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"value"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"value","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode~1value\/title","op":"replace","value":"value"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode~1value\/fragments","op":"replace","value":[{"text":"value","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode\/title","op":"replace","value":"XTMdlDrivingPrivilegeCode"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode\/fragments","op":"replace","value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlDrivingPrivilegeCode\/navigatorTitle","op":"replace","value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}