{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initializationError","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/initializationError"},"metadata":{"title":"HolderErrorCode.initializationError","modules":[{"name":"MdlHolder"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initializationError","kind":"identifier"}],"navigatorTitle":[{"text":"XTHolderErrorCodeInitializationError","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@MdlHolder@E@XTHolderErrorCode@XTHolderErrorCodeInitializationError"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode"]]},"variants":[{"paths":["\/documentation\/mdlholder\/holdererrorcode\/initializationerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/holdererrorcode\/initializationerror"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/initializationError":{"kind":"symbol","title":"HolderErrorCode.initializationError","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/initializationerror","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/initializationError","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializationError"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeInitializationError"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode","navigatorTitle":[{"text":"HolderErrorCode","kind":"identifier"}],"url":"\/documentation\/mdlholder\/holdererrorcode","type":"topic","title":"HolderErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HolderErrorCode","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"XTHolderErrorCodeInitializationError","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"XTHolderErrorCodeInitializationError"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"XTHolderErrorCodeInitializationError","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1initializationError\/title","op":"replace","value":"XTHolderErrorCodeInitializationError"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1initializationError\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeInitializationError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/title","op":"replace","value":"XTHolderErrorCode"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/fragments","op":"replace","value":[{"text":"XTHolderErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/navigatorTitle","op":"replace","value":[{"text":"XTHolderErrorCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}