{"sections":[],"metadata":{"title":"HolderErrorCode.mDocExpired","modules":[{"name":"MdlHolder"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocExpired","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeMDocExpired"}],"symbolKind":"case","externalID":"c:@M@MdlHolder@E@XTHolderErrorCode@XTHolderErrorCodeMDocExpired"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocExpired","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode"]]},"variants":[{"paths":["\/documentation\/mdlholder\/holdererrorcode\/mdocexpired"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/holdererrorcode\/mdocexpired"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocExpired"},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode","navigatorTitle":[{"text":"HolderErrorCode","kind":"identifier"}],"url":"\/documentation\/mdlholder\/holdererrorcode","type":"topic","title":"HolderErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HolderErrorCode","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/mDocExpired":{"title":"HolderErrorCode.mDocExpired","kind":"symbol","abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/mdocexpired","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocExpired","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mDocExpired"}],"navigatorTitle":[{"text":"XTHolderErrorCodeMDocExpired","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"XTHolderErrorCodeMDocExpired","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"XTHolderErrorCodeMDocExpired","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"XTHolderErrorCodeMDocExpired","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"XTHolderErrorCode","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/title"},{"value":[{"text":"XTHolderErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/fragments"},{"value":[{"text":"XTHolderErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/navigatorTitle"},{"value":"XTHolderErrorCodeMDocExpired","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocExpired\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocExpired\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeMDocExpired","kind":"identifier"}]}]}]}