{"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocValidationError","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"HolderErrorCode.mDocValidationError","navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeMDocValidationError"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mDocValidationError","kind":"identifier"}],"externalID":"c:@M@MdlHolder@E@XTHolderErrorCode@XTHolderErrorCodeMDocValidationError","modules":[{"name":"MdlHolder"}],"symbolKind":"case","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mDocValidationError"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/holdererrorcode\/mdocvalidationerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/holdererrorcode\/mdocvalidationerror"]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","title":"MdlHolder","type":"topic","url":"\/documentation\/mdlholder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode":{"url":"\/documentation\/mdlholder\/holdererrorcode","title":"HolderErrorCode","navigatorTitle":[{"kind":"identifier","text":"HolderErrorCode"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HolderErrorCode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Possible error codes in SDK"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/mDocValidationError":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocValidationError"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/mDocValidationError","type":"topic","url":"\/documentation\/mdlholder\/holdererrorcode\/mdocvalidationerror","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeMDocValidationError","kind":"identifier"}],"title":"HolderErrorCode.mDocValidationError","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"XTHolderErrorCodeMDocValidationError","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"XTHolderErrorCodeMDocValidationError","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"XTHolderErrorCodeMDocValidationError"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"XTHolderErrorCode","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/navigatorTitle","value":[{"text":"XTHolderErrorCode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"XTHolderErrorCodeMDocValidationError","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocValidationError\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTHolderErrorCodeMDocValidationError"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1mDocValidationError\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}