{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/holdererrorcode\/sessiondataerror"]},{"paths":["\/documentation\/mdlholder\/holdererrorcode\/sessiondataerror"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDataError"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionDataError","kind":"identifier"}],"roleHeading":"Case","title":"HolderErrorCode.sessionDataError","modules":[{"name":"MdlHolder"}],"navigatorTitle":[{"text":"XTHolderErrorCodeSessionDataError","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MdlHolder@E@XTHolderErrorCode@XTHolderErrorCodeSessionDataError"},"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/sessionDataError","interfaceLanguage":"swift"},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode/sessionDataError":{"abstract":[],"url":"\/documentation\/mdlholder\/holdererrorcode\/sessiondataerror","kind":"symbol","title":"HolderErrorCode.sessionDataError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionDataError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"XTHolderErrorCodeSessionDataError","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode\/sessionDataError","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/HolderErrorCode":{"abstract":[{"type":"text","text":"Possible error codes in SDK"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/HolderErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HolderErrorCode"}],"url":"\/documentation\/mdlholder\/holdererrorcode","title":"HolderErrorCode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HolderErrorCode"}],"type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","type":"topic","title":"MdlHolder","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"XTHolderErrorCodeSessionDataError"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeSessionDataError","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"XTHolderErrorCodeSessionDataError"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1sessionDataError\/title","op":"replace","value":"XTHolderErrorCodeSessionDataError"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode~1sessionDataError\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeSessionDataError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/title","op":"replace","value":"XTHolderErrorCode"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/fragments","op":"replace","value":[{"text":"XTHolderErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1HolderErrorCode\/navigatorTitle","op":"replace","value":[{"text":"XTHolderErrorCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}