{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilege"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdldrivingprivilege\/codes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/mdldrivingprivilege\/codes"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Array of code info. (one or more)","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlDrivingPrivilegeCodes","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilegeCodes"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilege\/codes"},"metadata":{"platforms":[{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false}],"modules":[{"name":"MdlReaderSdk"}],"title":"codes","navigatorTitle":[{"text":"codes","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilege(py)codes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilegeCodes"},{"text":"?","kind":"text"}],"symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilege/codes":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilege\/codes","kind":"symbol","type":"topic","title":"codes","navigatorTitle":[{"text":"codes","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilegeCodes"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Array of code info. (one or more)"}],"url":"\/documentation\/mdlreadersdk\/mdldrivingprivilege\/codes","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilege":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilege","title":"MdlDrivingPrivilege","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilege"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"identifier"}],"abstract":[{"type":"text","text":"A data model representing a single driving privilege entry from a Mobile Driving Licence (mDL)."}],"url":"\/documentation\/mdlreadersdk\/mdldrivingprivilege","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCodes":{"kind":"symbol","title":"MdlDrivingPrivilegeCodes","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilegeCodes"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivilegeCodes"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes","url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecodes"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"codes"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"codes"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilegeCodes","text":"XTMdlDrivingPrivilegeCodes"},{"kind":"text","text":" * "},{"kind":"identifier","text":"codes"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege~1codes\/title","op":"replace","value":"codes"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege~1codes\/fragments","op":"replace","value":[{"kind":"identifier","text":"codes"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege\/title","op":"replace","value":"XTMdlDrivingPrivilege"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes\/title","op":"replace","value":"XTMdlDrivingPrivilegeCodes"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}]}]}]}