{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilege"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/mdlreadersdk\/mdldrivingprivilege\/vehiclecategorycode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdldrivingprivilege\/vehiclecategorycode"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The category of the vehicle that the holder is permitted to drive (ISO\/IEC 18013-1)."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleCategoryCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilege\/vehicleCategoryCode"},"metadata":{"modules":[{"name":"MdlReaderSdk"}],"platforms":[{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false}],"title":"vehicleCategoryCode","navigatorTitle":[{"kind":"identifier","text":"vehicleCategoryCode"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilege(py)vehicleCategoryCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleCategoryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilege/vehicleCategoryCode":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilege\/vehicleCategoryCode","kind":"symbol","type":"topic","title":"vehicleCategoryCode","navigatorTitle":[{"text":"vehicleCategoryCode","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vehicleCategoryCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The category of the vehicle that the holder is permitted to drive (ISO\/IEC 18013-1)."}],"url":"\/documentation\/mdlreadersdk\/mdldrivingprivilege\/vehiclecategorycode","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilege":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilege","title":"MdlDrivingPrivilege","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilege"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"identifier"}],"abstract":[{"type":"text","text":"A data model representing a single driving privilege entry from a Mobile Driving Licence (mDL)."}],"url":"\/documentation\/mdlreadersdk\/mdldrivingprivilege","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/platforms","value":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"14.0","unavailable":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"vehicleCategoryCode","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"vehicleCategoryCode"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"vehicleCategoryCode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"vehicleCategoryCode","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege~1vehicleCategoryCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege~1vehicleCategoryCode\/fragments","value":[{"kind":"identifier","text":"vehicleCategoryCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege\/title","value":"XTMdlDrivingPrivilege"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege\/fragments","op":"replace","value":[{"text":"XTMdlDrivingPrivilege","kind":"identifier"}]},{"op":"replace","value":[{"text":"XTMdlDrivingPrivilege","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilege\/navigatorTitle"}]}]}