{"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlGender\/Equatable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlGender"]]},"topicSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlGender\/!=(_:_:)"],"generated":true,"anchor":"Operators","title":"Operators"}],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdlgender\/equatable-implementations"]}],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"MdlHolderSdk"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlGender/!=(_:_:)":{"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlGender\/!=(_:_:)","title":"!=(_:_:)","url":"\/documentation\/mdlholdersdk\/mdlgender\/!=(_:_:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlGender":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}],"abstract":[],"title":"MdlGender","role":"symbol","navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlGender","url":"\/documentation\/mdlholdersdk\/mdlgender"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlGender\/title","op":"replace","value":"XTMdlGender"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlGender\/fragments","value":[{"text":"XTMdlGender","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlGender\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlGender"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}