{"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"male","kind":"identifier"}],"modules":[{"name":"MdlHolderSdk"}],"role":"symbol","title":"MdlGender.male","externalID":"c:@M@MdlHolderSdk@E@XTMdlGender@XTMdlGenderMale","navigatorTitle":[{"text":"XTMdlGenderMale","kind":"identifier"}],"platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","beta":false}],"symbolKind":"case"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlGender"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdlgender\/male"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdlgender\/male"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlGender\/male"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"male"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlGender/male":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"male","kind":"identifier"}],"abstract":[],"title":"MdlGender.male","role":"symbol","navigatorTitle":[{"text":"XTMdlGenderMale","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlGender\/male","url":"\/documentation\/mdlholdersdk\/mdlgender\/male"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlGender":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}],"abstract":[],"title":"MdlGender","role":"symbol","navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlGender","url":"\/documentation\/mdlholdersdk\/mdlgender"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"XTMdlGenderMale"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"XTMdlGenderMale","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"XTMdlGenderMale","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlGender~1male\/title","op":"replace","value":"XTMdlGenderMale"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlGender~1male\/fragments","op":"replace","value":[{"text":"XTMdlGenderMale","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlGender\/title","op":"replace","value":"XTMdlGender"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlGender\/fragments","op":"replace","value":[{"text":"XTMdlGender","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlGender\/navigatorTitle","op":"replace","value":[{"text":"XTMdlGender","kind":"identifier"}]}]}]}