{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdlfieldidentifier\/administrativenumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdlfieldidentifier\/administrativenumber"]}],"metadata":{"title":"administrativeNumber","externalID":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier(cpy)administrativeNumber","symbolKind":"property","role":"symbol","roleHeading":"Type Property","navigatorTitle":[{"text":"administrativeNumber","kind":"identifier"}],"modules":[{"name":"MdlHolder"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"administrativeNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"administrativeNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Value type: "},{"type":"codeVoice","code":"String"}]}]}],"type":"unorderedList"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier"]]},"abstract":[{"type":"text","text":"The administrative number."}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/administrativeNumber","interfaceLanguage":"swift"},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/administrativeNumber":{"title":"administrativeNumber","navigatorTitle":[{"text":"administrativeNumber","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mdlholder\/mdlfieldidentifier\/administrativenumber","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"administrativeNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The administrative number."}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/administrativeNumber"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"url":"\/documentation\/mdlholder\/mdlfieldidentifier","type":"topic","title":"MdlFieldIdentifier","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"administrativeNumber","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"administrativeNumber","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"XTMdlFieldIdentifier","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"},{"text":" * ","kind":"text"},{"text":"administrativeNumber","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"administrativeNumber","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1administrativeNumber\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1administrativeNumber\/fragments","op":"replace","value":[{"text":"administrativeNumber","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier"},{"value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/navigatorTitle","op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]}]}]}