{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"}]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Value type: ","type":"text"},{"type":"codeVoice","code":"String"}],"type":"paragraph"}]}]}],"kind":"content"}],"abstract":[{"type":"text","text":"The document number."}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/documentNumber","interfaceLanguage":"swift"},"metadata":{"title":"documentNumber","externalID":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier(cpy)documentNumber","symbolKind":"property","role":"symbol","roleHeading":"Type Property","navigatorTitle":[{"text":"documentNumber","kind":"identifier"}],"modules":[{"name":"MdlHolder"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier"]]},"sections":[],"variants":[{"paths":["\/documentation\/mdlholder\/mdlfieldidentifier\/documentnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdlfieldidentifier\/documentnumber"]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/documentNumber":{"kind":"symbol","title":"documentNumber","abstract":[{"text":"The document number.","type":"text"}],"url":"\/documentation\/mdlholder\/mdlfieldidentifier\/documentnumber","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/documentNumber","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"navigatorTitle":[{"text":"documentNumber","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"url":"\/documentation\/mdlholder\/mdlfieldidentifier","type":"topic","title":"MdlFieldIdentifier","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"documentNumber"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"documentNumber"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","text":"XTMdlFieldIdentifier","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"documentNumber","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1documentNumber\/title"},{"value":[{"text":"documentNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1documentNumber\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/title","op":"replace","value":"XTMdlFieldIdentifier"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/fragments","op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/navigatorTitle","op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]}]}]}