{"sections":[],"variants":[{"paths":["\/documentation\/mdlholder\/mdlfieldidentifier\/residentpostalcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdlfieldidentifier\/residentpostalcode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","externalID":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier(cpy)residentPostalCode","title":"residentPostalCode","roleHeading":"Type Property","role":"symbol","navigatorTitle":[{"text":"residentPostalCode","kind":"identifier"}],"modules":[{"name":"MdlHolder"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"residentPostalCode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentPostalCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Value type: "},{"type":"codeVoice","code":"String"}]}]}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier"]]},"abstract":[{"type":"text","text":"The resident postal code of the document holder."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentPostalCode"},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/residentPostalCode":{"title":"residentPostalCode","kind":"symbol","abstract":[{"text":"The resident postal code of the document holder.","type":"text"}],"url":"\/documentation\/mdlholder\/mdlfieldidentifier\/residentpostalcode","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentPostalCode","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentPostalCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"residentPostalCode","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"url":"\/documentation\/mdlholder\/mdlfieldidentifier","type":"topic","title":"MdlFieldIdentifier","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"op":"replace","value":"residentPostalCode","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"residentPostalCode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"XTMdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier"},{"text":" * ","kind":"text"},{"text":"residentPostalCode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentPostalCode\/title","op":"replace","value":"residentPostalCode"},{"op":"replace","value":[{"text":"residentPostalCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentPostalCode\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/title","op":"replace","value":"XTMdlFieldIdentifier"},{"op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/navigatorTitle"}]}]}