{"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentAddress","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Value type: "},{"code":"String","type":"codeVoice"}],"type":"paragraph"}]}]}]}],"variants":[{"paths":["\/documentation\/mdlholder\/mdlfieldidentifier\/residentaddress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdlfieldidentifier\/residentaddress"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"roleHeading":"Type Property","externalID":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier(cpy)residentAddress","symbolKind":"property","title":"residentAddress","modules":[{"name":"MdlHolder"}],"platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"14.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"14.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"14.0"}],"role":"symbol","navigatorTitle":[{"text":"residentAddress","kind":"identifier"}]},"abstract":[{"type":"text","text":"The resident address of the document holder."}],"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/residentAddress":{"abstract":[{"type":"text","text":"The resident address of the document holder."}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/residentAddress","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"url":"\/documentation\/mdlholder\/mdlfieldidentifier\/residentaddress","title":"residentAddress","kind":"symbol","navigatorTitle":[{"text":"residentAddress","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier":{"abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"title":"MdlFieldIdentifier","role":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","url":"\/documentation\/mdlholder\/mdlfieldidentifier","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlFieldIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"MdlFieldIdentifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","type":"topic","title":"MdlHolder","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"14.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"14.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"14.0"}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"residentAddress","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"residentAddress"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","text":"XTMdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"residentAddress"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentAddress\/title","value":"residentAddress","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1residentAddress\/fragments","value":[{"text":"residentAddress","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier","op":"replace"},{"op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/fragments"},{"op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}