{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/init(rawValue:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","externalID":"s:12MdlHolderSdk0B9ErrorCodeO8rawValueACSgSi_tcfc","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"MdlHolderSdk"}]},"variants":[{"paths":["\/documentation\/mdlholdersdk\/holdererrorcode\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HolderErrorCode","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/holdererrorcode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HolderErrorCode"}],"abstract":[{"type":"text","text":"Possible error codes in SDK"}],"title":"HolderErrorCode"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/init(rawValue:)":{"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/init(rawValue:)","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/init(rawvalue:)","title":"init(rawValue:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/title","value":"XTHolderErrorCode"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/fragments","op":"replace","value":[{"text":"XTHolderErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTHolderErrorCode"}]}]}]}