{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocError"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocError","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/mdlholdersdk\/holdererrorcode\/mdocerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholdersdk\/holdererrorcode\/mdocerror"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"XTHolderErrorCodeMDocError","kind":"identifier"}],"externalID":"c:@M@MdlHolderSdk@E@XTHolderErrorCode@XTHolderErrorCodeMDocError","symbolKind":"case","roleHeading":"Case","title":"HolderErrorCode.mDocError","modules":[{"name":"MdlHolderSdk"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocError"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HolderErrorCode","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/holdererrorcode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HolderErrorCode"}],"abstract":[{"type":"text","text":"Possible error codes in SDK"}],"title":"HolderErrorCode"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/mDocError":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocError","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/mdocerror","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeMDocError","kind":"identifier"}],"abstract":[],"title":"HolderErrorCode.mDocError"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"XTHolderErrorCodeMDocError","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"XTHolderErrorCodeMDocError"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"XTHolderErrorCodeMDocError","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"XTHolderErrorCode","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/title"},{"value":[{"kind":"identifier","text":"XTHolderErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/fragments"},{"value":[{"kind":"identifier","text":"XTHolderErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocError\/title","op":"replace","value":"XTHolderErrorCodeMDocError"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocError\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeMDocError","kind":"identifier"}]}]}]}