{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocExpired"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeMDocExpired"}],"role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mDocExpired","kind":"identifier"}],"externalID":"c:@M@MdlHolderSdk@E@XTHolderErrorCode@XTHolderErrorCodeMDocExpired","title":"HolderErrorCode.mDocExpired","symbolKind":"case","modules":[{"name":"MdlHolderSdk"}]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocExpired","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/holdererrorcode\/mdocexpired"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/holdererrorcode\/mdocexpired"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode"]]},"sections":[],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/mDocExpired":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mDocExpired","kind":"identifier"}],"abstract":[],"title":"HolderErrorCode.mDocExpired","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeMDocExpired","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/mDocExpired","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/mdocexpired"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HolderErrorCode","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/holdererrorcode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HolderErrorCode"}],"abstract":[{"type":"text","text":"Possible error codes in SDK"}],"title":"HolderErrorCode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"XTHolderErrorCodeMDocExpired"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"XTHolderErrorCodeMDocExpired","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"XTHolderErrorCodeMDocExpired"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocExpired\/title","op":"replace","value":"XTHolderErrorCodeMDocExpired"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1mDocExpired\/fragments","op":"replace","value":[{"text":"XTHolderErrorCodeMDocExpired","kind":"identifier"}]},{"op":"replace","value":"XTHolderErrorCode","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/title"},{"op":"replace","value":[{"text":"XTHolderErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/navigatorTitle","value":[{"text":"XTHolderErrorCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}