{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/hashValue"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/hash(into:)"],"generated":true,"anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/RawRepresentable-Implementations"},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"RawRepresentable Implementations","modules":[{"name":"MdlHolderSdk"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/holdererrorcode\/rawrepresentable-implementations"]}],"kind":"article","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/hashValue":{"abstract":[],"type":"topic","role":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/hashValue","title":"hashValue","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/hashvalue"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/hash(into:)":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/hash(into:)","role":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"abstract":[],"title":"hash(into:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HolderErrorCode","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/holdererrorcode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HolderErrorCode"}],"abstract":[{"type":"text","text":"Possible error codes in SDK"}],"title":"HolderErrorCode"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/title","value":"XTHolderErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"XTHolderErrorCode"}]}]}]}