{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/success"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/holdererrorcode\/success"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/holdererrorcode\/success"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"XTHolderErrorCodeSuccess"}],"roleHeading":"Case","externalID":"c:@M@MdlHolderSdk@E@XTHolderErrorCode@XTHolderErrorCodeSuccess","symbolKind":"case","title":"HolderErrorCode.success","modules":[{"name":"MdlHolderSdk"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode/success":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"XTHolderErrorCodeSuccess","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode\/success","url":"\/documentation\/mdlholdersdk\/holdererrorcode\/success","title":"HolderErrorCode.success"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/HolderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/HolderErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HolderErrorCode","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mdlholdersdk\/holdererrorcode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HolderErrorCode"}],"abstract":[{"type":"text","text":"Possible error codes in SDK"}],"title":"HolderErrorCode"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"XTHolderErrorCodeSuccess","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"XTHolderErrorCodeSuccess"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"XTHolderErrorCodeSuccess"}],"languages":["occ"]}]},"op":"replace"},{"value":"XTHolderErrorCodeSuccess","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1success\/title"},{"value":[{"kind":"identifier","text":"XTHolderErrorCodeSuccess"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode~1success\/fragments"},{"value":"XTHolderErrorCode","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/title"},{"value":[{"kind":"identifier","text":"XTHolderErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/fragments"},{"value":[{"kind":"identifier","text":"XTHolderErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1HolderErrorCode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}