{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges\/drivingPrivileges","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges"]]},"abstract":[{"type":"text","text":"An array of "},{"type":"codeVoice","code":"MdlDrivingPrivilege"},{"type":"text","text":" objects representing individual driving privileges."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdldrivingprivileges\/drivingprivileges"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdldrivingprivileges\/drivingprivileges"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drivingPrivileges","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilege"},{"text":"]","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"14.0","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingPrivileges"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilege","text":"MdlDrivingPrivilege"},{"kind":"text","text":"]"}],"modules":[{"name":"MdlReader"}],"navigatorTitle":[{"kind":"identifier","text":"drivingPrivileges"}],"title":"drivingPrivileges","externalID":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivileges(py)drivingPrivileges"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivileges/drivingPrivileges":{"title":"drivingPrivileges","navigatorTitle":[{"text":"drivingPrivileges","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"An array of "},{"code":"MdlDrivingPrivilege","type":"codeVoice"},{"type":"text","text":" objects representing individual driving privileges."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drivingPrivileges","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilege"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges\/drivingPrivileges","role":"symbol","url":"\/documentation\/mdlreader\/mdldrivingprivileges\/drivingprivileges"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilege":{"abstract":[{"type":"text","text":"A data model representing a single driving privilege entry from a Mobile Driving Licence (mDL)."}],"url":"\/documentation\/mdlreader\/mdldrivingprivilege","title":"MdlDrivingPrivilege","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"identifier"}],"navigatorTitle":[{"text":"MdlDrivingPrivilege","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivileges":{"abstract":[{"type":"text","text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL)."}],"url":"\/documentation\/mdlreader\/mdldrivingprivileges","title":"MdlDrivingPrivileges","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivileges","kind":"identifier"}],"navigatorTitle":[{"text":"MdlDrivingPrivileges","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"Mac Catalyst"}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"drivingPrivileges"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"drivingPrivileges"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<XTMdlDrivingPrivilege *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"drivingPrivileges","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges~1drivingPrivileges\/title","op":"replace","value":"drivingPrivileges"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges~1drivingPrivileges\/fragments","op":"replace","value":[{"kind":"identifier","text":"drivingPrivileges"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/title","op":"replace","value":"XTMdlDrivingPrivilege"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges\/title","op":"replace","value":"XTMdlDrivingPrivileges"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}