{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges\/init(drivingPrivileges:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"drivingPrivileges"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilege","text":"MdlDrivingPrivilege"},{"kind":"text","text":"])"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"type":"codeVoice","code":"MdlDrivingPrivilege"},{"type":"text","text":" instances."}]}],"name":"drivingPrivileges"}],"kind":"parameters"}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Initializes the container with the provided list of driving privileges."}],"variants":[{"paths":["\/documentation\/mdlreader\/mdldrivingprivileges\/init(drivingprivileges:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreader\/mdldrivingprivileges\/init(drivingprivileges:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivileges(im)initWithDrivingPrivileges:","navigatorTitle":[{"text":"initWithDrivingPrivileges:","kind":"identifier"}],"title":"init(drivingPrivileges:)","modules":[{"name":"MdlReader"}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"drivingPrivileges","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilege","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilege"},{"text":"])","kind":"text"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilege":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilege","kind":"symbol","url":"\/documentation\/mdlreader\/mdldrivingprivilege","title":"MdlDrivingPrivilege","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivilege"}],"navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilege"}],"abstract":[{"type":"text","text":"A data model representing a single driving privilege entry from a Mobile Driving Licence (mDL)."}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivileges/init(drivingPrivileges:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithDrivingPrivileges:"}],"title":"init(drivingPrivileges:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges\/init(drivingPrivileges:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Initializes the container with the provided list of driving privileges."}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"drivingPrivileges"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilege","kind":"typeIdentifier","text":"MdlDrivingPrivilege"},{"text":"])","kind":"text"}],"url":"\/documentation\/mdlreader\/mdldrivingprivileges\/init(drivingprivileges:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivileges":{"abstract":[{"text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL).","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivileges"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivileges","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivileges","kind":"identifier"}],"url":"\/documentation\/mdlreader\/mdldrivingprivileges","title":"MdlDrivingPrivileges","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithDrivingPrivileges:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDrivingPrivileges:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDrivingPrivileges:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<XTMdlDrivingPrivilege *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"drivingPrivileges","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"drivingPrivileges","content":[{"type":"paragraph","inlineContent":[{"text":"An array of ","type":"text"},{"type":"codeVoice","code":"MdlDrivingPrivilege"},{"text":" instances.","type":"text"}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/title","value":"XTMdlDrivingPrivilege"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/fragments","value":[{"text":"XTMdlDrivingPrivilege","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilege\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilege"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges~1init(drivingPrivileges:)\/title","value":"initWithDrivingPrivileges:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges~1init(drivingPrivileges:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDrivingPrivileges:"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges\/title","op":"replace","value":"XTMdlDrivingPrivileges"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivileges\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}]}]}]}