{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder"]]},"sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDocumentSharing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlHolderDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolderSdk@objc(pl)XTMdlHolderDelegate"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"qrString","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"modules":[{"name":"MdlHolderSdk"}],"role":"symbol","title":"startDocumentSharing(withPin:delegate:completion:)","externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlHolder(im)startDocumentSharingWithPin:delegate:completion:","navigatorTitle":[{"text":"startDocumentSharingWithPin:delegate:completion:","kind":"identifier"}],"platforms":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}],"symbolKind":"method"},"abstract":[{"text":"Starts the mDL document sharing session initiated via QR engagement.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdlholder\/startdocumentsharing(withpin:delegate:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholdersdk\/mdlholder\/startdocumentsharing(withpin:delegate:completion:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/startDocumentSharing(withPin:delegate:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(startDocumentSharingWithPin:delegate:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDocumentSharing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPin","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pin","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(pl)XTMdlHolderDelegate","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate","text":"MdlHolderDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"qrString","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Authorization PIN code.","type":"text"}],"type":"paragraph"}],"name":"pin"},{"content":[{"inlineContent":[{"text":"The delegate object specified to receive SDK events.","type":"text"}],"type":"paragraph"}],"name":"delegate"},{"content":[{"inlineContent":[{"text":"A block of code that runs on the main thread and is called after a sharing has been successfully initialized or an error has occurred. The block has no return value and has the following parameters:","type":"text"}],"type":"paragraph"},{"items":[{"term":{"inlineContent":[{"type":"text","text":"qrString"}]},"definition":{"content":[{"inlineContent":[{"text":"A string for QR code generation or nil if error occurs.","type":"text"}],"type":"paragraph"}]}},{"term":{"inlineContent":[{"type":"text","text":"error"}]},"definition":{"content":[{"inlineContent":[{"text":"An object containing error information or nil if no error occurs.","type":"text"}],"type":"paragraph"}]}}],"type":"termList"}],"name":"completion"}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"After successful initialization of document sharing, subsequent events will be delivered via the "},{"isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate","type":"reference"},{"type":"text","text":" delegate methods."},{"type":"text","text":" "},{"type":"text","text":"In particular, a request to view document fields will be received through the "},{"isActive":true,"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","type":"reference"},{"type":"text","text":" delegate method."},{"type":"text","text":" "},{"type":"text","text":"This request must be either approved or rejected by calling the corresponding "},{"code":"approveDocumentSharing(completion:)","type":"codeVoice"},{"type":"text","text":" or "},{"code":"rejectDocumentSharing(completion:)","type":"codeVoice"},{"type":"text","text":" methods."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate/mdlHolderDidReceiveRequestedFields(_:)":{"abstract":[{"type":"text","text":"Called when the Reader requests specific document fields."}],"type":"topic","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mdlHolderDidReceiveRequestedFields","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"},{"kind":"text","text":"])"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate\/mdlholderdidreceiverequestedfields(_:)","title":"mdlHolderDidReceiveRequestedFields(_:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/startDocumentSharing(withPin:delegate:completion:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDocumentSharing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPin"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlHolderSdk@objc(pl)XTMdlHolderDelegate","kind":"typeIdentifier","text":"MdlHolderDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"qrString"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Starts the mDL document sharing session initiated via QR engagement."}],"title":"startDocumentSharing(withPin:delegate:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startDocumentSharingWithPin:delegate:completion:"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/startDocumentSharing(withPin:delegate:completion:)","url":"\/documentation\/mdlholdersdk\/mdlholder\/startdocumentsharing(withpin:delegate:completion:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolderDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolderDelegate"}],"abstract":[{"text":"Delivers events from the ","type":"text"},{"type":"codeVoice","code":"MdlHolder"},{"type":"text","text":" during the mDL document sharing lifecycle."}],"title":"MdlHolderDelegate","role":"symbol","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolderDelegate","url":"\/documentation\/mdlholdersdk\/mdlholderdelegate"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder":{"abstract":[{"type":"text","text":"Main class of the SDK"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlHolder"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolder"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder","url":"\/documentation\/mdlholdersdk\/mdlholder","title":"MdlHolder"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"startDocumentSharingWithPin:delegate:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"startDocumentSharingWithPin:delegate:completion:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"startDocumentSharingWithPin:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pin","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<XTMdlHolderDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MdlHolderSdk@objc(pl)XTMdlHolderDelegate"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":", ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Authorization PIN code."}]}],"name":"pin"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate object specified to receive SDK events.","type":"text"}]}],"name":"delegate"},{"name":"completion","content":[{"inlineContent":[{"text":"A block of code that runs on the main thread and is called after a sharing has been successfully initialized or an error has occurred. The block has no return value and has the following parameters:","type":"text"}],"type":"paragraph"},{"items":[{"definition":{"content":[{"inlineContent":[{"type":"text","text":"A string for QR code generation or nil if error occurs."}],"type":"paragraph"}]},"term":{"inlineContent":[{"type":"text","text":"qrString"}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing error information or nil if no error occurs."}]}]},"term":{"inlineContent":[{"type":"text","text":"error"}]}}],"type":"termList"}]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/title","op":"replace","value":"mdlHolderDidReceiveRequestedFields:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mdlHolderDidReceiveRequestedFields:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/fragments"},{"op":"replace","value":"startDocumentSharingWithPin:delegate:completion:","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1startDocumentSharing(withPin:delegate:completion:)\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1startDocumentSharing(withPin:delegate:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startDocumentSharingWithPin:delegate:completion:"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/title","op":"replace","value":"XTMdlHolderDelegate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/fragments","op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolderDelegate\/navigatorTitle","op":"replace","value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/title","value":"XTMdlHolder"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlHolder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlHolder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}