{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder"]]},"sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRootCertificates"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"modules":[{"name":"MdlHolderSdk"}],"role":"symbol","externalID":"c:@M@MdlHolderSdk@objc(cs)XTMdlHolder(im)updateRootCertificatesWithCompletion:","title":"updateRootCertificates(completion:)","navigatorTitle":[{"kind":"identifier","text":"updateRootCertificatesWithCompletion:"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"14.0","deprecated":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}],"symbolKind":"method"},"abstract":[{"text":"Downloads CA Root certificates and updates them in the local SDK storage","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholdersdk\/mdlholder\/updaterootcertificates(completion:)"]},{"paths":["\/documentation\/mdlholdersdk\/mdlholder\/updaterootcertificates(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/updateRootCertificates(completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(updateRootCertificatesWithCompletion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateRootCertificates","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The block to execute asynchronously after the certificates has been received or an error has occurred. The block has no return value and has the following parameters:"}],"type":"paragraph"},{"items":[{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing error information or nil if no error occurs."}]}]},"term":{"inlineContent":[{"text":"error","type":"text"}]}}],"type":"termList"}],"name":"completion"}]},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Also, CA root certificates are updated with each "},{"type":"reference","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/initialize(completion:)","isActive":true},{"type":"text","text":" call."}]}],"kind":"content"}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/initialize(completion:)":{"abstract":[{"type":"text","text":"SDK initialization"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"initializeWithCompletion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/initialize(completion:)","url":"\/documentation\/mdlholdersdk\/mdlholder\/initialize(completion:)","title":"initialize(completion:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder":{"abstract":[{"type":"text","text":"Main class of the SDK"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlHolder"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolder"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder","url":"\/documentation\/mdlholdersdk\/mdlholder","title":"MdlHolder"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk/MdlHolder/updateRootCertificates(completion:)":{"abstract":[{"type":"text","text":"Downloads CA Root certificates and updates them in the local SDK storage"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"updateRootCertificatesWithCompletion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateRootCertificates","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk\/MdlHolder\/updateRootCertificates(completion:)","title":"updateRootCertificates(completion:)","url":"\/documentation\/mdlholdersdk\/mdlholder\/updaterootcertificates(completion:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolderSdk":{"type":"topic","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"title":"MdlHolderSdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolderSdk","url":"\/documentation\/mdlholdersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","beta":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"updateRootCertificatesWithCompletion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateRootCertificatesWithCompletion:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"updateRootCertificatesWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The block to execute asynchronously after the certificates has been received or an error has occurred. The block has no return value and has the following parameters:"}]},{"type":"termList","items":[{"definition":{"content":[{"type":"paragraph","inlineContent":[{"text":"An object containing error information or nil if no error occurs.","type":"text"}]}]},"term":{"inlineContent":[{"type":"text","text":"error"}]}}]}],"name":"completion"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1initialize(completion:)\/title","value":"initializeWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1initialize(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initializeWithCompletion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/title","value":"XTMdlHolder","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/fragments","value":[{"text":"XTMdlHolder","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder\/navigatorTitle","value":[{"text":"XTMdlHolder","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1updateRootCertificates(completion:)\/title","value":"updateRootCertificatesWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolderSdk~1MdlHolder~1updateRootCertificates(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateRootCertificatesWithCompletion:","kind":"identifier"}],"op":"replace"}]}]}