{"abstract":[{"type":"text","text":"Code as per ISO\/IEC 18013-2 Annex A."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCode\/code","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","externalID":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilegeCode(py)code","modules":[{"name":"MdlHolder"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"code"}],"title":"code","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdldrivingprivilegecode\/code"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdldrivingprivilegecode\/code"]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilegeCode":{"title":"MdlDrivingPrivilegeCode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilegeCode"}],"url":"\/documentation\/mdlholder\/mdldrivingprivilegecode","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCode","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilegeCode/code":{"url":"\/documentation\/mdlholder\/mdldrivingprivilegecode\/code","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"Code as per ISO\/IEC 18013-2 Annex A.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"code","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCode\/code","role":"symbol","title":"code"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"code"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"code"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"code","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode\/title","op":"replace","value":"XTMdlDrivingPrivilegeCode"},{"value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode\/fragments","op":"replace"},{"value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode\/navigatorTitle","op":"replace"},{"value":"code","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode~1code\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode~1code\/fragments","op":"replace","value":[{"kind":"identifier","text":"code"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}