{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCode"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCode\/value"},"variants":[{"paths":["\/documentation\/mdlholder\/mdldrivingprivilegecode\/value"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdldrivingprivilegecode\/value"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"MdlHolder"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","deprecated":false},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0"},{"introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"}],"symbolKind":"property","externalID":"c:@M@MdlHolder@objc(cs)XTMdlDrivingPrivilegeCode(py)value","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","title":"value","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"value"}]},"abstract":[{"type":"text","text":"Value as per ISO\/IEC 18013-2 Annex A"}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilegeCode/value":{"abstract":[{"text":"Value as per ISO\/IEC 18013-2 Annex A","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCode\/value","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/mdlholder\/mdldrivingprivilegecode\/value","title":"value","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"value"}],"type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","type":"topic","title":"MdlHolder","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlDrivingPrivilegeCode":{"abstract":[],"title":"MdlDrivingPrivilegeCode","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlDrivingPrivilegeCode","type":"topic","role":"symbol","url":"\/documentation\/mdlholder\/mdldrivingprivilegecode","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilegeCode"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlDrivingPrivilegeCode"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"}]},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"value","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"value"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"value"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode~1value\/title","op":"replace","value":"value"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode~1value\/fragments","value":[{"kind":"identifier","text":"value"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode\/title","value":"XTMdlDrivingPrivilegeCode","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode\/fragments","value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlDrivingPrivilegeCode\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}