{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"birthPlace","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdldocument\/birthplace"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/mdldocument\/birthplace"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument"]]},"abstract":[{"type":"text","text":"Country and municipality or state\/province where the mDL holder was born."}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocument(py)birthPlace","platforms":[{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"iOS"},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst"}],"modules":[{"name":"MdlReaderSdk"}],"navigatorTitle":[{"kind":"identifier","text":"birthPlace"}],"title":"birthPlace","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthPlace"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","role":"symbol"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/birthPlace"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/mdldocument","navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"abstract":[{"text":"Representation of mDL document","type":"text"}],"title":"MdlDocument"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/birthPlace":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthPlace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"birthPlace","kind":"identifier"}],"abstract":[{"type":"text","text":"Country and municipality or state\/province where the mDL holder was born."}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/birthplace","title":"birthPlace","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/birthPlace","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"beta":false,"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"birthPlace","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"birthPlace","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"birthPlace","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"XTMdlDocument","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/fragments"},{"value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/navigatorTitle"},{"value":"birthPlace","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1birthPlace\/title"},{"value":[{"kind":"identifier","text":"birthPlace"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1birthPlace\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}