{"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/bloodGroup","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bloodGroup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument"]]},"sections":[],"metadata":{"title":"bloodGroup","navigatorTitle":[{"text":"bloodGroup","kind":"identifier"}],"modules":[{"name":"MdlReaderSdk"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bloodGroup","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":[{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocument(py)bloodGroup","roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"mDL holder’s blood group","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdldocument\/bloodgroup"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/mdldocument\/bloodgroup"]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/bloodGroup":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/bloodGroup","kind":"symbol","type":"topic","title":"bloodGroup","navigatorTitle":[{"text":"bloodGroup","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bloodGroup","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"mDL holder’s blood group","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/bloodgroup","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"title":"MdlDocument","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","url":"\/documentation\/mdlreadersdk\/mdldocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"introducedAt":"14.0","unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"introducedAt":"14.0","unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"introducedAt":"14.0","unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"bloodGroup","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"bloodGroup"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"bloodGroup","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"bloodGroup","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1bloodGroup\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1bloodGroup\/fragments","op":"replace","value":[{"kind":"identifier","text":"bloodGroup"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/title","value":"XTMdlDocument","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/fragments","value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}]}]}]}