{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingPrivileges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivileges","text":"MdlDrivingPrivileges","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivileges"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdldocument\/drivingprivileges"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdldocument\/drivingprivileges"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument"]]},"abstract":[{"type":"text","text":"Driving privileges of the mDL holder. Categories of vehicles\/restrictions\/conditions. (zero or more)"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"drivingPrivileges"}],"platforms":[{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst"}],"modules":[{"name":"MdlReaderSdk"}],"symbolKind":"property","title":"drivingPrivileges","roleHeading":"Instance Property","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocument(py)drivingPrivileges","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingPrivileges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivileges","text":"MdlDrivingPrivileges"}]},"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/drivingPrivileges","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/mdldocument","navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"abstract":[{"text":"Representation of mDL document","type":"text"}],"title":"MdlDocument"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/drivingPrivileges":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingPrivileges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlDrivingPrivileges","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivileges"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"drivingPrivileges"}],"abstract":[{"type":"text","text":"Driving privileges of the mDL holder. Categories of vehicles\/restrictions\/conditions. (zero or more)"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/drivingprivileges","title":"drivingPrivileges","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/drivingPrivileges","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivileges":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivileges"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivileges"}],"abstract":[{"type":"text","text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL)."}],"url":"\/documentation\/mdlreadersdk\/mdldrivingprivileges","title":"MdlDrivingPrivileges","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivileges","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst"}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"drivingPrivileges"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"drivingPrivileges"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivileges","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivileges","text":"XTMdlDrivingPrivileges","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"drivingPrivileges","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/title","value":"XTMdlDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/fragments","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1drivingPrivileges\/title","value":"drivingPrivileges"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1drivingPrivileges\/fragments","value":[{"kind":"identifier","text":"drivingPrivileges"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges\/title","value":"XTMdlDrivingPrivileges"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivileges"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}