{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/familyName"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"familyName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument"]]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"familyName","navigatorTitle":[{"kind":"identifier","text":"familyName"}],"modules":[{"name":"MdlReaderSdk"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"familyName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":[{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocument(py)familyName","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Last name, surname or primary identifier, of the mDL holder."}],"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdldocument\/familyname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdldocument\/familyname"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"title":"MdlDocument","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","url":"\/documentation\/mdlreadersdk\/mdldocument"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/familyName":{"kind":"symbol","title":"familyName","navigatorTitle":[{"kind":"identifier","text":"familyName"}],"abstract":[{"text":"Last name, surname or primary identifier, of the mDL holder.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"familyName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/familyName","url":"\/documentation\/mdlreadersdk\/mdldocument\/familyname"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"familyName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"familyName"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"familyName","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/title","value":"XTMdlDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/fragments","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1familyName\/title","value":"familyName"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1familyName\/fragments","value":[{"kind":"identifier","text":"familyName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}