{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/givenName","interfaceLanguage":"swift"},"abstract":[{"text":"First name(s), other name(s), or secondary identifier, of the mDL holder.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocument(py)givenName","platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"14.0","beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"14.0","beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"14.0","beta":false}],"modules":[{"name":"MdlReaderSdk"}],"navigatorTitle":[{"kind":"identifier","text":"givenName"}],"title":"givenName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"symbolKind":"property","role":"symbol"},"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdldocument\/givenname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdldocument\/givenname"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument"]]},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/mdldocument","navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"abstract":[{"text":"Representation of mDL document","type":"text"}],"title":"MdlDocument"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/givenName":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"givenName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"givenName","kind":"identifier"}],"abstract":[{"text":"First name(s), other name(s), or secondary identifier, of the mDL holder.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/givenname","title":"givenName","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/givenName","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"introducedAt":"14.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"beta":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"givenName","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"givenName"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"givenName"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"XTMdlDocument","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/title"},{"value":[{"text":"XTMdlDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1givenName\/title","value":"givenName","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1givenName\/fragments","value":[{"text":"givenName","kind":"identifier"}],"op":"replace"}]}]}