{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"holderIdNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdldocument\/holderidnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdldocument\/holderidnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument"]]},"abstract":[{"text":"mDL holder’s national ID or alien ID, or diplomatic ID","type":"text"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"holderIdNumber"}],"modules":[{"name":"MdlReaderSdk"}],"platforms":[{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false}],"symbolKind":"property","title":"holderIdNumber","roleHeading":"Instance Property","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocument(py)holderIdNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"holderIdNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/holderIdNumber"},"kind":"symbol","references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/mdldocument","navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"abstract":[{"text":"Representation of mDL document","type":"text"}],"title":"MdlDocument"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/holderIdNumber":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"holderIdNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"holderIdNumber","kind":"identifier"}],"abstract":[{"text":"mDL holder’s national ID or alien ID, or diplomatic ID","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/holderidnumber","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/holderIdNumber","title":"holderIdNumber","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"holderIdNumber"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"holderIdNumber","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"holderIdNumber","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/title","value":"XTMdlDocument"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/fragments","op":"replace","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}]},{"value":"holderIdNumber","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1holderIdNumber\/title","op":"replace"},{"value":[{"kind":"identifier","text":"holderIdNumber"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1holderIdNumber\/fragments","op":"replace"}]}]}