{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/mdlreadersdk\/mdldocument\/init(familyname:givenname:birthdate:issuedate:expirydate:issuingcountry:issuingauthority:documentnumber:portrait:drivingprivileges:undistinguishingsign:holderidnumber:bloodgroup:dlissuedate:dlexpirydate:drivingrestrictions:administrativenum-1g6bl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdldocument\/init(familyname:givenname:birthdate:issuedate:expirydate:issuingcountry:issuingauthority:documentnumber:portrait:drivingprivileges:undistinguishingsign:holderidnumber:bloodgroup:dlissuedate:dlexpirydate:drivingrestrictions:administrativenum-1g6bl"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"familyName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"givenName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"birthDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"issueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"issuingCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"issuingAuthority","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"portrait","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"drivingPrivileges","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlDrivingPrivileges","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivileges","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivileges"},{"text":", ","kind":"text"},{"text":"unDistinguishingSign","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"holderIdNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"bloodGroup","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"dlIssueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"dlExpiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"drivingRestrictions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"administrativeNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"sex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlGender","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@E@XTMdlGender"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"? = nil, ","kind":"text"},{"text":"weight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"? = nil, ","kind":"text"},{"text":"eyeColour","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"hairColour","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"birthPlace","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"residentAddress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"portraitCaptureDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"? = nil, ","kind":"text"},{"text":"ageInYears","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"? = nil, ","kind":"text"},{"text":"ageBirthYear","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"? = nil, ","kind":"text"},{"text":"ageOverNn","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AgeOverNnEntry","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTAgeOverNnEntry"},{"text":"]? = nil, ","kind":"text"},{"text":"issuingJurisdiction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"nationality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"residentCity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"residentState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"residentPostalCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"residentCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"biometricTemplateXx","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MdlBiometricTemplate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlBiometricTemplate"},{"text":"]? = nil, ","kind":"text"},{"text":"familyNameNationalCharacter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"givenNameNationalCharacter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"signatureUsualMark","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)"},"metadata":{"platforms":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"14.0","unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"14.0","unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"14.0","unavailable":false}],"modules":[{"name":"MdlReaderSdk"}],"title":"init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","navigatorTitle":[{"kind":"identifier","text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocument(im)initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"familyName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"givenName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"birthDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issueDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingCountry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingAuthority"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"portrait"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingPrivileges"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivileges","kind":"typeIdentifier","text":"MdlDrivingPrivileges"},{"kind":"text","text":", "},{"kind":"externalParam","text":"unDistinguishingSign"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"holderIdNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bloodGroup"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlIssueDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlExpiryDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingRestrictions"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"administrativeNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlReaderSdk@E@XTMdlGender","kind":"typeIdentifier","text":"MdlGender"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eyeColour"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hairColour"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"birthPlace"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"portraitCaptureDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageInYears"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageBirthYear"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageOverNn"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTAgeOverNnEntry","kind":"typeIdentifier","text":"AgeOverNnEntry"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"issuingJurisdiction"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nationality"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentCity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentState"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentPostalCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentCountry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlBiometricTemplate","kind":"typeIdentifier","text":"MdlBiometricTemplate"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"familyNameNationalCharacter"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"givenNameNationalCharacter"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signatureUsualMark"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"?)"}],"symbolKind":"init","roleHeading":"Initializer"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlGender":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender","kind":"symbol","type":"topic","title":"MdlGender","navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/mdlgender","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/AgeOverNnEntry":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry","kind":"symbol","type":"topic","title":"AgeOverNnEntry","navigatorTitle":[{"text":"AgeOverNnEntry","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgeOverNnEntry","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/ageovernnentry","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"title":"MdlDocument","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","url":"\/documentation\/mdlreadersdk\/mdldocument"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlBiometricTemplate":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate","title":"MdlBiometricTemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MdlBiometricTemplate"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlBiometricTemplate"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/mdlbiometrictemplate","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivileges":{"kind":"symbol","title":"MdlDrivingPrivileges","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivileges"}],"abstract":[{"type":"text","text":"A container class representing a collection of driving privileges extracted from a Mobile Driving Licence (mDL)."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivileges","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivileges","url":"\/documentation\/mdlreadersdk\/mdldrivingprivileges"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","kind":"symbol","type":"topic","title":"init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","navigatorTitle":[{"text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"familyName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"givenName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"birthDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"issueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"issuingCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"issuingAuthority","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"portrait","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"drivingPrivileges","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlDrivingPrivileges","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivileges"},{"text":", ","kind":"text"},{"text":"unDistinguishingSign","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"holderIdNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"bloodGroup","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"dlIssueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"dlExpiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"drivingRestrictions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"administrativeNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"sex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlGender","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@E@XTMdlGender"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"weight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"eyeColour","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"hairColour","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"birthPlace"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"residentAddress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"portraitCaptureDate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageInYears"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageBirthYear"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ageOverNn"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTAgeOverNnEntry","kind":"typeIdentifier","text":"AgeOverNnEntry"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"issuingJurisdiction"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"nationality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"residentCity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"residentState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"residentPostalCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"residentCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"biometricTemplateXx"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MdlBiometricTemplate","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlBiometricTemplate"},{"text":"]?, ","kind":"text"},{"text":"familyNameNationalCharacter","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"givenNameNationalCharacter"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureUsualMark"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?)","kind":"text"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/mdldocument\/init(familyname:givenname:birthdate:issuedate:expirydate:issuingcountry:issuingauthority:documentnumber:portrait:drivingprivileges:undistinguishingsign:holderidnumber:bloodgroup:dlissuedate:dlexpirydate:drivingrestrictions:administrativenum-1g6bl","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"deprecated":false,"introducedAt":"14.0","beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFamilyName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"familyName"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"givenName"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"birthDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"issueDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiryDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"expiryDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingCountry:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"issuingCountry"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingAuthority:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"issuingAuthority"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentNumber"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"portrait"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingPrivileges:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivileges","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivileges","text":"XTMdlDrivingPrivileges"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"drivingPrivileges"},{"kind":"text","text":" "},{"kind":"identifier","text":"unDistinguishingSign:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"unDistinguishingSign"},{"kind":"text","text":" "},{"kind":"identifier","text":"holderIdNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"holderIdNumber"},{"kind":"text","text":" "},{"kind":"identifier","text":"bloodGroup:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bloodGroup"},{"kind":"text","text":" "},{"kind":"identifier","text":"dlIssueDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dlIssueDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"dlExpiryDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dlExpiryDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingRestrictions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"drivingRestrictions"},{"kind":"text","text":" "},{"kind":"identifier","text":"administrativeNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"administrativeNumber"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender","kind":"typeIdentifier","text":"XTMdlGender","preciseIdentifier":"c:@M@MdlReaderSdk@E@XTMdlGender"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sex"},{"kind":"text","text":" "},{"kind":"identifier","text":"height:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" *) "},{"text":"height","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"weight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"weight"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeColour:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"eyeColour"},{"kind":"text","text":" "},{"kind":"identifier","text":"hairColour:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"hairColour"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthPlace:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"birthPlace"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentAddress:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"residentAddress"},{"kind":"text","text":" "},{"kind":"identifier","text":"portraitCaptureDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"portraitCaptureDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageInYears:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ageInYears"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageBirthYear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"ageBirthYear"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageOverNn:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<XTAgeOverNnEntry *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ageOverNn"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingJurisdiction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"issuingJurisdiction"},{"kind":"text","text":" "},{"kind":"identifier","text":"nationality:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nationality"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentCity:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"residentCity"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"residentState"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentPostalCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"residentPostalCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentCountry:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"residentCountry"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricTemplateXx:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<XTMdlBiometricTemplate *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"biometricTemplateXx"},{"kind":"text","text":" "},{"text":"familyNameNationalCharacter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"familyNameNationalCharacter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"givenNameNationalCharacter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"givenNameNationalCharacter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"signatureUsualMark:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"signatureUsualMark","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/title","value":"XTMdlGender","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/fragments","value":[{"kind":"identifier","text":"XTMdlGender"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/navigatorTitle","value":[{"text":"XTMdlGender","kind":"identifier"}]},{"value":"XTAgeOverNnEntry","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/title"},{"value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/navigatorTitle","value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/title","value":"XTMdlDocument"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/fragments"},{"value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/navigatorTitle"},{"op":"replace","value":"XTMdlBiometricTemplate","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate\/title"},{"op":"replace","value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTMdlBiometricTemplate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate\/navigatorTitle"},{"op":"replace","value":"XTMdlDrivingPrivileges","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges\/title"},{"op":"replace","value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivileges\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivileges","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/title","value":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/fragments"}]}]}