{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdldocument\/issuingjurisdiction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/mdldocument\/issuingjurisdiction"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Country subdivision code of the jurisdiction that issued the mDL. The first part of the code shall be the same as the value for issuing country."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingJurisdiction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issuingJurisdiction"},"metadata":{"platforms":[{"deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"14.0","beta":false,"name":"Mac Catalyst","unavailable":false}],"modules":[{"name":"MdlReaderSdk"}],"title":"issuingJurisdiction","navigatorTitle":[{"text":"issuingJurisdiction","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocument(py)issuingJurisdiction","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingJurisdiction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument":{"abstract":[{"text":"Representation of mDL document","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"title":"MdlDocument","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","url":"\/documentation\/mdlreadersdk\/mdldocument"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/issuingJurisdiction":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issuingJurisdiction","title":"issuingJurisdiction","kind":"symbol","type":"topic","navigatorTitle":[{"text":"issuingJurisdiction","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingJurisdiction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"abstract":[{"text":"Country subdivision code of the jurisdiction that issued the mDL. The first part of the code shall be the same as the value for issuing country.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/issuingjurisdiction","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"deprecated":false,"name":"iOS","introducedAt":"14.0","unavailable":false},{"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"14.0","unavailable":false},{"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"issuingJurisdiction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"issuingJurisdiction","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"issuingJurisdiction"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/title","value":"XTMdlDocument","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/fragments","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/navigatorTitle","value":[{"text":"XTMdlDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1issuingJurisdiction\/title","value":"issuingJurisdiction"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1issuingJurisdiction\/fragments","value":[{"text":"issuingJurisdiction","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}