{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"mDL holder’s sex."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sex"},{"kind":"text","text":": "},{"text":"MdlGender","preciseIdentifier":"c:@M@MdlReaderSdk@E@XTMdlGender","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocument(py)sex","modules":[{"name":"MdlReaderSdk"}],"platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"14.0","beta":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}],"navigatorTitle":[{"kind":"identifier","text":"sex"}],"title":"sex","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlGender","preciseIdentifier":"c:@M@MdlReaderSdk@E@XTMdlGender","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol"},"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdldocument\/sex"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdldocument\/sex"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument"]]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/sex","interfaceLanguage":"swift"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/mdldocument","navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"abstract":[{"text":"Representation of mDL document","type":"text"}],"title":"MdlDocument"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/sex":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlGender","preciseIdentifier":"c:@M@MdlReaderSdk@E@XTMdlGender","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"sex","kind":"identifier"}],"abstract":[{"type":"text","text":"mDL holder’s sex."}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/sex","title":"sex","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/sex","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlGender":{"navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"url":"\/documentation\/mdlreadersdk\/mdlgender","title":"MdlGender","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"beta":false,"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"sex"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"sex"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@E@XTMdlGender","text":"XTMdlGender","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/title","op":"replace","value":"XTMdlDocument"},{"value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/fragments"},{"value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/navigatorTitle"},{"value":"sex","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1sex\/title"},{"value":[{"kind":"identifier","text":"sex"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1sex\/fragments"},{"value":"XTMdlGender","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/fragments","value":[{"kind":"identifier","text":"XTMdlGender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlGender"}]}]}]}