{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdlfieldidentifier\/agebirthyear"]},{"paths":["\/documentation\/mdlreadersdk\/mdlfieldidentifier\/agebirthyear"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The birth year of the document holder."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageBirthYear"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier"}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Value type: "},{"type":"codeVoice","code":"Int"}]}]}],"type":"unorderedList"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier\/ageBirthYear"},"metadata":{"platforms":[{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"name":"iPadOS","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false}],"modules":[{"name":"MdlReaderSdk"}],"title":"ageBirthYear","navigatorTitle":[{"kind":"identifier","text":"ageBirthYear"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier(cpy)ageBirthYear","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageBirthYear"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"symbolKind":"property","roleHeading":"Type Property"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier/ageBirthYear":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier\/ageBirthYear","kind":"symbol","type":"topic","title":"ageBirthYear","navigatorTitle":[{"kind":"identifier","text":"ageBirthYear"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ageBirthYear","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier"}],"abstract":[{"type":"text","text":"The birth year of the document holder."}],"url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier\/agebirthyear","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlFieldIdentifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlFieldIdentifier"}],"abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"name":"iPadOS","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","value":"ageBirthYear","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ageBirthYear","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"ageBirthYear"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ageBirthYear","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier~1ageBirthYear\/title"},{"op":"replace","value":[{"text":"ageBirthYear","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier~1ageBirthYear\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/fragments","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/navigatorTitle","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}],"op":"replace"}]}]}