{"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier\/birthDate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"birthDate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Value type: "},{"code":"Date","type":"codeVoice"}]}]}],"type":"unorderedList"}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"birthDate","navigatorTitle":[{"kind":"identifier","text":"birthDate"}],"modules":[{"name":"MdlReaderSdk"}],"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"birthDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier"}],"platforms":[{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false,"name":"Mac Catalyst"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier(cpy)birthDate","roleHeading":"Type Property"},"abstract":[{"type":"text","text":"The birth date of the document holder."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdlfieldidentifier\/birthdate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/mdlfieldidentifier\/birthdate"]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier/birthDate":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier\/birthDate","title":"birthDate","type":"topic","kind":"symbol","navigatorTitle":[{"text":"birthDate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate"},{"kind":"text","text":": "},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier"}],"abstract":[{"type":"text","text":"The birth date of the document holder."}],"url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier\/birthdate","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlFieldIdentifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlFieldIdentifier"}],"abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":[{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"deprecated":false,"introducedAt":"14.0","beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false,"name":"Mac Catalyst"}],"op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"birthDate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"birthDate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","kind":"typeIdentifier","text":"XTMdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"birthDate"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier~1birthDate\/title","value":"birthDate","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier~1birthDate\/fragments","op":"replace","value":[{"text":"birthDate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/title","op":"replace","value":"XTMdlFieldIdentifier"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/fragments","op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/navigatorTitle","op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}