{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/mdlreadersdk\/mdlfieldidentifier\/documentnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdlfieldidentifier\/documentnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The document number.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Value type: ","type":"text"},{"code":"String","type":"codeVoice"}],"type":"paragraph"}]}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier\/documentNumber"},"metadata":{"title":"documentNumber","navigatorTitle":[{"text":"documentNumber","kind":"identifier"}],"modules":[{"name":"MdlReaderSdk"}],"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"}],"platforms":[{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier(cpy)documentNumber","roleHeading":"Type Property"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlFieldIdentifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlFieldIdentifier"}],"abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier/documentNumber":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier\/documentNumber","kind":"symbol","type":"topic","title":"documentNumber","navigatorTitle":[{"kind":"identifier","text":"documentNumber"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"abstract":[{"type":"text","text":"The document number."}],"url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier\/documentnumber","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"documentNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"documentNumber"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"XTMdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier"},{"text":" * ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/fragments","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier~1documentNumber\/title","value":"documentNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier~1documentNumber\/fragments","value":[{"text":"documentNumber","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}