{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The hair colour of the document holder.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hairColour","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"items":[{"content":[{"inlineContent":[{"text":"Value type: ","type":"text"},{"code":"String","type":"codeVoice"}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"metadata":{"roleHeading":"Type Property","modules":[{"name":"MdlReaderSdk"}],"platforms":[{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false}],"externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier(cpy)hairColour","navigatorTitle":[{"text":"hairColour","kind":"identifier"}],"title":"hairColour","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hairColour","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol"},"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdlfieldidentifier\/haircolour"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdlfieldidentifier\/haircolour"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier\/hairColour","interfaceLanguage":"swift"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlFieldIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"abstract":[{"text":"Provides predefined field identifiers used in mDL documents.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier/hairColour":{"abstract":[{"text":"The hair colour of the document holder.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier\/hairColour","role":"symbol","navigatorTitle":[{"text":"hairColour","kind":"identifier"}],"title":"hairColour","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hairColour","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier\/haircolour","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"hairColour"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"hairColour","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","text":"XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"hairColour"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/navigatorTitle","op":"replace"},{"value":"hairColour","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier~1hairColour\/title","op":"replace"},{"value":[{"text":"hairColour","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier~1hairColour\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}