{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier"]]},"abstract":[{"text":"The issuing country of the document.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingCountry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Value type: ","type":"text"},{"type":"codeVoice","code":"String"}]}]}],"type":"unorderedList"}],"kind":"content"}],"metadata":{"roleHeading":"Type Property","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier(cpy)issuingCountry","modules":[{"name":"MdlReaderSdk"}],"platforms":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"14.0"},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"14.0"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"14.0"}],"navigatorTitle":[{"text":"issuingCountry","kind":"identifier"}],"title":"issuingCountry","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingCountry","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdlfieldidentifier\/issuingcountry"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/mdlfieldidentifier\/issuingcountry"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier\/issuingCountry","interfaceLanguage":"swift"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlFieldIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"abstract":[{"text":"Provides predefined field identifiers used in mDL documents.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier/issuingCountry":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"issuingCountry"}],"abstract":[{"text":"The issuing country of the document.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier\/issuingcountry","title":"issuingCountry","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier\/issuingCountry","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"issuingCountry","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"issuingCountry","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"issuingCountry","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"XTMdlFieldIdentifier","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier~1issuingCountry\/title","op":"replace","value":"issuingCountry"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier~1issuingCountry\/fragments","op":"replace","value":[{"kind":"identifier","text":"issuingCountry"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}