{"kind":"symbol","abstract":[{"text":"The birth place of the document holder.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier"]]},"metadata":{"role":"symbol","externalID":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier(cpy)birthPlace","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"birthPlace","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier"}],"navigatorTitle":[{"text":"birthPlace","kind":"identifier"}],"title":"birthPlace","platforms":[{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"Mac Catalyst"}],"modules":[{"name":"MdlReader"}],"roleHeading":"Type Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier\/birthPlace"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthPlace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"items":[{"content":[{"inlineContent":[{"text":"Value type: ","type":"text"},{"type":"codeVoice","code":"String"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"variants":[{"paths":["\/documentation\/mdlreader\/mdlfieldidentifier\/birthplace"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreader\/mdlfieldidentifier\/birthplace"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlFieldIdentifier/birthPlace":{"abstract":[{"text":"The birth place of the document holder.","type":"text"}],"url":"\/documentation\/mdlreader\/mdlfieldidentifier\/birthplace","title":"birthPlace","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier\/birthPlace","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"birthPlace","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier"}],"navigatorTitle":[{"text":"birthPlace","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlFieldIdentifier":{"url":"\/documentation\/mdlreader\/mdlfieldidentifier","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"abstract":[{"text":"Provides predefined field identifiers used in mDL documents.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","title":"MdlFieldIdentifier","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"Mac Catalyst"}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"birthPlace","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"birthPlace"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"XTMdlFieldIdentifier","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier"},{"text":" * ","kind":"text"},{"text":"birthPlace","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier~1birthPlace\/title","value":"birthPlace","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier~1birthPlace\/fragments","value":[{"kind":"identifier","text":"birthPlace"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/fragments","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}],"op":"replace"}]}]}