{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier\/dlExpiryDate","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MdlReader"}],"externalID":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier(cpy)dlExpiryDate","title":"dlExpiryDate","roleHeading":"Type Property","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dlExpiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"dlExpiryDate"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dlExpiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Value type: "},{"type":"codeVoice","code":"String"}]}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier"]]},"abstract":[{"text":"Date of expiry of eDL (physical document) issued to mDL holder","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdlfieldidentifier\/dlexpirydate"]},{"paths":["\/documentation\/mdlreader\/mdlfieldidentifier\/dlexpirydate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlFieldIdentifier":{"type":"topic","url":"\/documentation\/mdlreader\/mdlfieldidentifier","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"kind":"symbol","title":"MdlFieldIdentifier","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlFieldIdentifier/dlExpiryDate":{"abstract":[{"type":"text","text":"Date of expiry of eDL (physical document) issued to mDL holder"}],"navigatorTitle":[{"text":"dlExpiryDate","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier\/dlExpiryDate","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dlExpiryDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier"}],"title":"dlExpiryDate","url":"\/documentation\/mdlreader\/mdlfieldidentifier\/dlexpirydate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"dlExpiryDate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dlExpiryDate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","text":"XTMdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier"},{"text":" * ","kind":"text"},{"text":"dlExpiryDate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"XTMdlFieldIdentifier","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/fragments","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]},{"value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/navigatorTitle","op":"replace"},{"value":"dlExpiryDate","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier~1dlExpiryDate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"dlExpiryDate"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier~1dlExpiryDate\/fragments","op":"replace"}]}]}