{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier\/eyeColour"},"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"MdlReader"}],"externalID":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier(cpy)eyeColour","title":"eyeColour","roleHeading":"Type Property","role":"symbol","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeColour","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"eyeColour"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeColour","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Value type: ","type":"text"},{"type":"codeVoice","code":"String"}],"type":"paragraph"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier"]]},"abstract":[{"type":"text","text":"The eye colour of the document holder."}],"variants":[{"paths":["\/documentation\/mdlreader\/mdlfieldidentifier\/eyecolour"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreader\/mdlfieldidentifier\/eyecolour"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlFieldIdentifier":{"type":"topic","url":"\/documentation\/mdlreader\/mdlfieldidentifier","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"kind":"symbol","title":"MdlFieldIdentifier","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlFieldIdentifier/eyeColour":{"abstract":[{"text":"The eye colour of the document holder.","type":"text"}],"navigatorTitle":[{"text":"eyeColour","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier\/eyeColour","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeColour","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier"}],"title":"eyeColour","url":"\/documentation\/mdlreader\/mdlfieldidentifier\/eyecolour","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"eyeColour","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"eyeColour","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"eyeColour"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"XTMdlFieldIdentifier","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/title"},{"op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/navigatorTitle","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier~1eyeColour\/title","value":"eyeColour","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier~1eyeColour\/fragments","value":[{"text":"eyeColour","kind":"identifier"}],"op":"replace"}]}]}