{"abstract":[{"text":"The resident city of the document holder.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentCity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Value type: ","type":"text"},{"type":"codeVoice","code":"String"}]}]}],"type":"unorderedList"}]}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier\/residentCity","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"residentCity"}],"symbolKind":"property","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentCity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier"}],"modules":[{"name":"MdlReader"}],"externalID":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier(cpy)residentCity","title":"residentCity","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdlfieldidentifier\/residentcity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdlfieldidentifier\/residentcity"]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlFieldIdentifier":{"type":"topic","url":"\/documentation\/mdlreader\/mdlfieldidentifier","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"kind":"symbol","title":"MdlFieldIdentifier","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlFieldIdentifier","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlFieldIdentifier/residentCity":{"navigatorTitle":[{"kind":"identifier","text":"residentCity"}],"title":"residentCity","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier\/residentCity","kind":"symbol","abstract":[{"type":"text","text":"The resident city of the document holder."}],"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentCity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","text":"MdlFieldIdentifier"}],"url":"\/documentation\/mdlreader\/mdlfieldidentifier\/residentcity"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"residentCity","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"residentCity"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"XTMdlFieldIdentifier","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlFieldIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"residentCity"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/title","op":"replace","value":"XTMdlFieldIdentifier"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier\/navigatorTitle","op":"replace","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]},{"value":"residentCity","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier~1residentCity\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlFieldIdentifier~1residentCity\/fragments","value":[{"text":"residentCity","kind":"identifier"}],"op":"replace"}]}]}