{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry\/init(age:isOverAge:)"},"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithAge:isOverAge:","kind":"identifier"}],"externalID":"c:@M@MdlHolder@objc(cs)XTAgeOverNnEntry(im)initWithAge:isOverAge:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"age"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isOverAge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"symbolKind":"init","title":"init(age:isOverAge:)","role":"symbol","modules":[{"name":"MdlHolder"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"age","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"isOverAge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/ageovernnentry\/init(age:isoverage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/ageovernnentry\/init(age:isoverage:)"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry"]]},"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/AgeOverNnEntry/init(age:isOverAge:)":{"type":"topic","title":"init(age:isOverAge:)","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry\/init(age:isOverAge:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"age","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isOverAge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithAge:isOverAge:","kind":"identifier"}],"url":"\/documentation\/mdlholder\/ageovernnentry\/init(age:isoverage:)","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/AgeOverNnEntry":{"type":"topic","title":"AgeOverNnEntry","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgeOverNnEntry","kind":"identifier"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"AgeOverNnEntry","kind":"identifier"}],"url":"\/documentation\/mdlholder\/ageovernnentry","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAge:isOverAge:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAge:isOverAge:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithAge:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"age"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOverAge:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isOverAge"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry~1init(age:isOverAge:)\/title","op":"replace","value":"initWithAge:isOverAge:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry~1init(age:isOverAge:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAge:isOverAge:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/title","value":"XTAgeOverNnEntry"},{"op":"replace","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/navigatorTitle","value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}]}]}]}