{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry\/isOverAge"},"metadata":{"role":"symbol","navigatorTitle":[{"text":"isOverAge","kind":"identifier"}],"modules":[{"name":"MdlHolder"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isOverAge","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@MdlHolder@objc(cs)XTAgeOverNnEntry(py)isOverAge","roleHeading":"Instance Property","title":"isOverAge"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOverAge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mdlholder\/ageovernnentry\/isoverage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/ageovernnentry\/isoverage"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry"]]},"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/AgeOverNnEntry/isOverAge":{"type":"topic","title":"isOverAge","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry\/isOverAge","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isOverAge","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"isOverAge","kind":"identifier"}],"url":"\/documentation\/mdlholder\/ageovernnentry\/isoverage","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/AgeOverNnEntry":{"type":"topic","title":"AgeOverNnEntry","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/AgeOverNnEntry","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgeOverNnEntry","kind":"identifier"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"AgeOverNnEntry","kind":"identifier"}],"url":"\/documentation\/mdlholder\/ageovernnentry","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isOverAge"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isOverAge"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOverAge"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry~1isOverAge\/title","value":"isOverAge"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry~1isOverAge\/fragments","value":[{"kind":"identifier","text":"isOverAge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/title","value":"XTAgeOverNnEntry"},{"op":"replace","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/fragments"},{"op":"replace","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1AgeOverNnEntry\/navigatorTitle"}]}]}