{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"female","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/female","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"XTMdlGenderFemale","kind":"identifier"}],"title":"MdlGender.female","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"female","kind":"identifier"}],"modules":[{"name":"MdlHolder"}],"externalID":"c:@M@MdlHolder@E@XTMdlGender@XTMdlGenderFemale","roleHeading":"Case","role":"symbol"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender"]]},"variants":[{"paths":["\/documentation\/mdlholder\/mdlgender\/female"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdlgender\/female"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender":{"kind":"symbol","title":"MdlGender","abstract":[],"url":"\/documentation\/mdlholder\/mdlgender","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}],"navigatorTitle":[{"text":"MdlGender","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender/female":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/female","navigatorTitle":[{"text":"XTMdlGenderFemale","kind":"identifier"}],"url":"\/documentation\/mdlholder\/mdlgender\/female","type":"topic","title":"MdlGender.female","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"female"}],"kind":"symbol","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"XTMdlGenderFemale","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"XTMdlGenderFemale","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"XTMdlGenderFemale","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"XTMdlGender","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/title"},{"value":[{"text":"XTMdlGender","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/fragments"},{"value":[{"kind":"identifier","text":"XTMdlGender"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/navigatorTitle"},{"value":"XTMdlGenderFemale","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1female\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1female\/fragments","value":[{"kind":"identifier","text":"XTMdlGenderFemale"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}