{"kind":"symbol","identifier":{"url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/notKnown","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@MdlHolder@E@XTMdlGender@XTMdlGenderNotKnown","roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"XTMdlGenderNotKnown","kind":"identifier"}],"title":"MdlGender.notKnown","symbolKind":"case","modules":[{"name":"MdlHolder"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notKnown"}]},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notKnown","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdlgender\/notknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdlgender\/notknown"]}],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","title":"MdlHolder","type":"topic","url":"\/documentation\/mdlholder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender/notKnown":{"abstract":[],"title":"MdlGender.notKnown","navigatorTitle":[{"kind":"identifier","text":"XTMdlGenderNotKnown"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notKnown"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/notKnown","kind":"symbol","role":"symbol","url":"\/documentation\/mdlholder\/mdlgender\/notknown"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender":{"url":"\/documentation\/mdlholder\/mdlgender","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlGender"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender","navigatorTitle":[{"kind":"identifier","text":"MdlGender"}],"title":"MdlGender","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"XTMdlGenderNotKnown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"XTMdlGenderNotKnown"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"XTMdlGenderNotKnown","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"XTMdlGenderNotKnown","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1notKnown\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlGenderNotKnown"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1notKnown\/fragments","op":"replace"},{"value":"XTMdlGender","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlGender"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlGender"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/navigatorTitle","op":"replace"}]}]}