{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/unDistinguishingSign"},"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"unDistinguishingSign"}],"externalID":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier(cpy)unDistinguishingSign","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"unDistinguishingSign","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"symbolKind":"property","role":"symbol","title":"unDistinguishingSign","modules":[{"name":"MdlHolder"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"unDistinguishingSign"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Value type: ","type":"text"},{"code":"String","type":"codeVoice"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdlfieldidentifier\/undistinguishingsign"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdlfieldidentifier\/undistinguishingsign"]}],"abstract":[{"type":"text","text":"The UN distinguishing sign."}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier"]]},"sections":[],"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier/unDistinguishingSign":{"url":"\/documentation\/mdlholder\/mdlfieldidentifier\/undistinguishingsign","type":"topic","title":"unDistinguishingSign","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unDistinguishingSign","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"}],"abstract":[{"text":"The UN distinguishing sign.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier\/unDistinguishingSign","navigatorTitle":[{"kind":"identifier","text":"unDistinguishingSign"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlFieldIdentifier":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlFieldIdentifier"}],"title":"MdlFieldIdentifier","role":"symbol","abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"type":"topic","url":"\/documentation\/mdlholder\/mdlfieldidentifier","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"unDistinguishingSign","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"unDistinguishingSign"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"XTMdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlFieldIdentifier"},{"text":" * ","kind":"text"},{"text":"unDistinguishingSign","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1unDistinguishingSign\/title","value":"unDistinguishingSign"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier~1unDistinguishingSign\/fragments","value":[{"kind":"identifier","text":"unDistinguishingSign"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/fragments","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlFieldIdentifier\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]}]}]}