{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/notApplicable"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notApplicable","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdlgender\/notapplicable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdlgender\/notapplicable"]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notApplicable"}],"roleHeading":"Case","symbolKind":"case","title":"MdlGender.notApplicable","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTMdlGenderNotApplicable"}],"modules":[{"name":"MdlHolder"}],"externalID":"c:@M@MdlHolder@E@XTMdlGender@XTMdlGenderNotApplicable"},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender","title":"MdlGender","abstract":[],"role":"symbol","url":"\/documentation\/mdlholder\/mdlgender","kind":"symbol","navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlGender/notApplicable":{"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlGender\/notApplicable","title":"MdlGender.notApplicable","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/mdlholder\/mdlgender\/notapplicable","navigatorTitle":[{"text":"XTMdlGenderNotApplicable","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notApplicable","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"XTMdlGenderNotApplicable"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"XTMdlGenderNotApplicable","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"XTMdlGenderNotApplicable"}]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/title","value":"XTMdlGender","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/fragments","value":[{"text":"XTMdlGender","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlGender"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1notApplicable\/title","value":"XTMdlGenderNotApplicable","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlGender~1notApplicable\/fragments","value":[{"kind":"identifier","text":"XTMdlGenderNotApplicable"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}