{"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes\/codes","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilegeCode","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCode","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mdlreader\/mdldrivingprivilegecodes\/codes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreader\/mdldrivingprivilegecodes\/codes"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes"]]},"metadata":{"modules":[{"name":"MdlReader"}],"platforms":[{"beta":false,"name":"iOS","unavailable":false,"introducedAt":"14.0","deprecated":false},{"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"14.0","deprecated":false},{"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"14.0","deprecated":false}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilegeCode","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCode","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"codes","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCodes(py)codes","title":"codes"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCodes":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes","abstract":[],"navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"url":"\/documentation\/mdlreader\/mdldrivingprivilegecodes","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"type":"topic","kind":"symbol","title":"MdlDrivingPrivilegeCodes","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCodes/codes":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes\/codes","abstract":[],"navigatorTitle":[{"text":"codes","kind":"identifier"}],"url":"\/documentation\/mdlreader\/mdldrivingprivilegecodes\/codes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codes","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCode","text":"MdlDrivingPrivilegeCode","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic","kind":"symbol","title":"codes","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCode":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode","abstract":[],"navigatorTitle":[{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"url":"\/documentation\/mdlreader\/mdldrivingprivilegecode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"MdlDrivingPrivilegeCode","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"name":"iOS","introducedAt":"14.0","unavailable":false,"beta":false},{"deprecated":false,"name":"iPadOS","introducedAt":"14.0","unavailable":false,"beta":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"beta":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"codes","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"codes","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<XTMdlDrivingPrivilegeCode *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"codes","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"XTMdlDrivingPrivilegeCodes","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/title","op":"replace"},{"value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/fragments","op":"replace"},{"value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/navigatorTitle","op":"replace"},{"value":"codes","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes~1codes\/title","op":"replace"},{"value":[{"text":"codes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes~1codes\/fragments","op":"replace"},{"value":"XTMdlDrivingPrivilegeCode","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode\/title","op":"replace"},{"value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode\/fragments","op":"replace"},{"value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}