{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/mdlreader\/mdldrivingprivilegecodes\/init(codes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/mdldrivingprivilegecodes\/init(codes:)"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes\/init(codes:)"},"sections":[],"metadata":{"title":"init(codes:)","navigatorTitle":[{"text":"initWithCodes:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCode","kind":"typeIdentifier","text":"MdlDrivingPrivilegeCode"},{"kind":"text","text":"])"}],"roleHeading":"Initializer","externalID":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCodes(im)initWithCodes:","symbolKind":"init","modules":[{"name":"MdlReader"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"codes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode","preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCode"},{"text":"])","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCodes/init(codes:)":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes\/init(codes:)","kind":"symbol","title":"init(codes:)","url":"\/documentation\/mdlreader\/mdldrivingprivilegecodes\/init(codes:)","navigatorTitle":[{"kind":"identifier","text":"initWithCodes:"}],"abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MdlReader@objc(cs)XTMdlDrivingPrivilegeCode","kind":"typeIdentifier","text":"MdlDrivingPrivilegeCode"},{"kind":"text","text":"])"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCodes":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCodes","url":"\/documentation\/mdlreader\/mdldrivingprivilegecodes","title":"MdlDrivingPrivilegeCodes","kind":"symbol","navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlDrivingPrivilegeCode":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreader\/mdldrivingprivilegecode","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilegeCode"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivilegeCode"}],"title":"MdlDrivingPrivilegeCode","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlDrivingPrivilegeCode"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithCodes:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCodes:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCodes:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<XTMdlDrivingPrivilegeCode *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"codes"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithCodes:","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes~1init(codes:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCodes:"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes~1init(codes:)\/fragments"},{"value":"XTMdlDrivingPrivilegeCodes","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/title"},{"value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/fragments"},{"value":[{"text":"XTMdlDrivingPrivilegeCodes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCodes\/navigatorTitle"},{"value":"XTMdlDrivingPrivilegeCode","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode\/title"},{"value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode\/fragments"},{"value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlDrivingPrivilegeCode\/navigatorTitle"}]}]}