{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"age","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mdlreadersdk\/ageovernnentry\/age"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/ageovernnentry\/age"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"age","kind":"identifier"}],"modules":[{"name":"MdlReaderSdk"}],"platforms":[{"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false,"beta":false}],"symbolKind":"property","title":"age","roleHeading":"Instance Property","externalID":"c:@M@MdlReaderSdk@objc(cs)XTAgeOverNnEntry(py)age","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"age","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry\/age"},"kind":"symbol","references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/AgeOverNnEntry/age":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/ageovernnentry\/age","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"age"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"age","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry\/age","navigatorTitle":[{"kind":"identifier","text":"age"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/AgeOverNnEntry":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/ageovernnentry","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgeOverNnEntry","kind":"identifier"}],"title":"AgeOverNnEntry","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry","navigatorTitle":[{"text":"AgeOverNnEntry","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false,"beta":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"age","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"age","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"age"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry~1age\/title","value":"age","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry~1age\/fragments","value":[{"text":"age","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/title","value":"XTAgeOverNnEntry","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/fragments","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/navigatorTitle","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}