{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"age","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isOverAge","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Initializer","externalID":"c:@M@MdlReaderSdk@objc(cs)XTAgeOverNnEntry(im)initWithAge:isOverAge:","platforms":[{"beta":false,"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false}],"modules":[{"name":"MdlReaderSdk"}],"navigatorTitle":[{"text":"initWithAge:isOverAge:","kind":"identifier"}],"title":"init(age:isOverAge:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"age","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isOverAge","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/ageovernnentry\/init(age:isoverage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/ageovernnentry\/init(age:isoverage:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry"]]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry\/init(age:isOverAge:)","interfaceLanguage":"swift"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/AgeOverNnEntry/init(age:isOverAge:)":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/ageovernnentry\/init(age:isoverage:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"age","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"isOverAge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"init(age:isOverAge:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry\/init(age:isOverAge:)","navigatorTitle":[{"kind":"identifier","text":"initWithAge:isOverAge:"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/AgeOverNnEntry":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/ageovernnentry","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgeOverNnEntry","kind":"identifier"}],"title":"AgeOverNnEntry","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry","navigatorTitle":[{"text":"AgeOverNnEntry","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"14.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0"}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithAge:isOverAge:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAge:isOverAge:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithAge:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"age","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isOverAge:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isOverAge","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry~1init(age:isOverAge:)\/title","op":"replace","value":"initWithAge:isOverAge:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry~1init(age:isOverAge:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAge:isOverAge:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/title","op":"replace","value":"XTAgeOverNnEntry"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/fragments","op":"replace","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/navigatorTitle","op":"replace","value":[{"text":"XTAgeOverNnEntry","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}