{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"]]},"kind":"symbol","metadata":{"title":"ReaderErrorCode.bleUnauthorized","externalID":"c:@M@MdlReader@E@XTReaderErrorCode@XTReaderErrorCodeBleUnauthorized","roleHeading":"Case","modules":[{"name":"MdlReader"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bleUnauthorized","kind":"identifier"}],"symbolKind":"case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnauthorized"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bleUnauthorized","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/readererrorcode\/bleunauthorized"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/readererrorcode\/bleunauthorized"]}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleUnauthorized","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/bleUnauthorized":{"title":"ReaderErrorCode.bleUnauthorized","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnauthorized"}],"kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleUnauthorized"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleUnauthorized","role":"symbol","url":"\/documentation\/mdlreader\/readererrorcode\/bleunauthorized"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ReaderErrorCode"}],"url":"\/documentation\/mdlreader\/readererrorcode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReaderErrorCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ReaderErrorCode","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"XTReaderErrorCodeBleUnauthorized","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"XTReaderErrorCodeBleUnauthorized","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"XTReaderErrorCodeBleUnauthorized","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1bleUnauthorized\/title","value":"XTReaderErrorCodeBleUnauthorized","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1bleUnauthorized\/fragments","value":[{"text":"XTReaderErrorCodeBleUnauthorized","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/title","op":"replace","value":"XTReaderErrorCode"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/fragments","op":"replace","value":[{"text":"XTReaderErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTReaderErrorCode"}]}]}]}