{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bleUnsupported","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleUnsupported"},"sections":[],"kind":"symbol","metadata":{"title":"ReaderErrorCode.bleUnsupported","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnsupported"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bleUnsupported","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@MdlReader@E@XTReaderErrorCode@XTReaderErrorCodeBleUnsupported","symbolKind":"case","modules":[{"name":"MdlReader"}]},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"]]},"variants":[{"paths":["\/documentation\/mdlreader\/readererrorcode\/bleunsupported"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreader\/readererrorcode\/bleunsupported"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode":{"role":"symbol","title":"ReaderErrorCode","navigatorTitle":[{"text":"ReaderErrorCode","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderErrorCode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode","abstract":[{"type":"text","text":"Possible error codes in SDK"}],"url":"\/documentation\/mdlreader\/readererrorcode"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/bleUnsupported":{"navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnsupported"}],"title":"ReaderErrorCode.bleUnsupported","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/bleUnsupported","kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleUnsupported"}],"url":"\/documentation\/mdlreader\/readererrorcode\/bleunsupported"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"role":"collection","title":"MdlReader","kind":"symbol","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"XTReaderErrorCodeBleUnsupported","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnsupported"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnsupported"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"XTReaderErrorCode","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/title"},{"value":[{"text":"XTReaderErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/fragments"},{"value":[{"kind":"identifier","text":"XTReaderErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/navigatorTitle"},{"value":"XTReaderErrorCodeBleUnsupported","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1bleUnsupported\/title"},{"value":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnsupported"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1bleUnsupported\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}