{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/clientCertificateNotFound","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Case","externalID":"c:@M@MdlReader@E@XTReaderErrorCode@XTReaderErrorCodeClientCertificateNotFound","modules":[{"name":"MdlReader"}],"symbolKind":"case","title":"ReaderErrorCode.clientCertificateNotFound","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientCertificateNotFound","kind":"identifier"}],"navigatorTitle":[{"text":"XTReaderErrorCodeClientCertificateNotFound","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/readererrorcode\/clientcertificatenotfound"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/readererrorcode\/clientcertificatenotfound"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientCertificateNotFound","kind":"identifier"}]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"]]},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/clientCertificateNotFound":{"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/clientCertificateNotFound","url":"\/documentation\/mdlreader\/readererrorcode\/clientcertificatenotfound","kind":"symbol","title":"ReaderErrorCode.clientCertificateNotFound","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientCertificateNotFound","kind":"identifier"}],"navigatorTitle":[{"text":"XTReaderErrorCodeClientCertificateNotFound","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ReaderErrorCode"}],"url":"\/documentation\/mdlreader\/readererrorcode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReaderErrorCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ReaderErrorCode","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"XTReaderErrorCodeClientCertificateNotFound","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"XTReaderErrorCodeClientCertificateNotFound","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"XTReaderErrorCodeClientCertificateNotFound"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"XTReaderErrorCodeClientCertificateNotFound","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1clientCertificateNotFound\/title","op":"replace"},{"value":[{"text":"XTReaderErrorCodeClientCertificateNotFound","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1clientCertificateNotFound\/fragments","op":"replace"},{"value":"XTReaderErrorCode","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/title","op":"replace"},{"value":[{"text":"XTReaderErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/fragments","op":"replace"},{"value":[{"text":"XTReaderErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/navigatorTitle","op":"replace"}]}]}