{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/hashValue"},"metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@MdlReader@E@XTReaderErrorCode","modules":[{"name":"MdlReader","relatedModules":["Swift"]}],"extendedModule":"Swift","symbolKind":"property","title":"hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]}},"variants":[{"paths":["\/documentation\/mdlreader\/readererrorcode\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/hashValue":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/hashValue","type":"topic","url":"\/documentation\/mdlreader\/readererrorcode\/hashvalue","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"hashValue","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]}},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ReaderErrorCode"}],"url":"\/documentation\/mdlreader\/readererrorcode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReaderErrorCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ReaderErrorCode","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/title","value":"XTReaderErrorCode","op":"replace"},{"value":[{"text":"XTReaderErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"XTReaderErrorCode"}]}]}]}