{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/mDocRequestError"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/readererrorcode\/mdocrequesterror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreader\/readererrorcode\/mdocrequesterror"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocRequestError","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocRequestError","kind":"identifier"}],"modules":[{"name":"MdlReader"}],"navigatorTitle":[{"text":"XTReaderErrorCodeMDocRequestError","kind":"identifier"}],"title":"ReaderErrorCode.mDocRequestError","externalID":"c:@M@MdlReader@E@XTReaderErrorCode@XTReaderErrorCodeMDocRequestError"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode/mDocRequestError":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocRequestError","kind":"identifier"}],"title":"ReaderErrorCode.mDocRequestError","navigatorTitle":[{"text":"XTReaderErrorCodeMDocRequestError","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mdlreader\/readererrorcode\/mdocrequesterror","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode\/mDocRequestError","kind":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/ReaderErrorCode":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/ReaderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ReaderErrorCode"}],"url":"\/documentation\/mdlreader\/readererrorcode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReaderErrorCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ReaderErrorCode","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"XTReaderErrorCodeMDocRequestError","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"XTReaderErrorCodeMDocRequestError","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"XTReaderErrorCodeMDocRequestError","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"XTReaderErrorCodeMDocRequestError","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1mDocRequestError\/title"},{"value":[{"text":"XTReaderErrorCodeMDocRequestError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode~1mDocRequestError\/fragments"},{"value":"XTReaderErrorCode","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/title","op":"replace"},{"value":[{"text":"XTReaderErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTReaderErrorCode"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1ReaderErrorCode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}