{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/ageovernnentry"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/ageovernnentry"]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTAgeOverNnEntry) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgeOverNnEntry","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry\/init(age:isOverAge:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry\/age","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry\/isOverAge"],"generated":true}],"metadata":{"title":"AgeOverNnEntry","navigatorTitle":[{"kind":"identifier","text":"AgeOverNnEntry"}],"modules":[{"name":"MdlReaderSdk"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AgeOverNnEntry","kind":"identifier"}],"platforms":[{"name":"iOS","deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"14.0","name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTAgeOverNnEntry","roleHeading":"Class"},"references":{"doc://com.xinfotech.mdlreader/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ"},"doc://com.xinfotech.mdlreader/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/AgeOverNnEntry":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry","kind":"symbol","type":"topic","title":"AgeOverNnEntry","navigatorTitle":[{"text":"AgeOverNnEntry","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgeOverNnEntry","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/ageovernnentry","role":"symbol"},"doc://com.xinfotech.mdlreader/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP"},"doc://com.xinfotech.mdlreader/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject"},"doc://com.xinfotech.mdlreader/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/AgeOverNnEntry/init(age:isOverAge:)":{"kind":"symbol","title":"init(age:isOverAge:)","navigatorTitle":[{"kind":"identifier","text":"initWithAge:isOverAge:"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"age"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isOverAge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry\/init(age:isOverAge:)","url":"\/documentation\/mdlreadersdk\/ageovernnentry\/init(age:isoverage:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/AgeOverNnEntry/age":{"kind":"symbol","title":"age","navigatorTitle":[{"kind":"identifier","text":"age"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"age"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry\/age","url":"\/documentation\/mdlreadersdk\/ageovernnentry\/age"},"doc://com.xinfotech.mdlreader/SH":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SH","title":"Swift.Hashable"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/AgeOverNnEntry/isOverAge":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry\/isOverAge","title":"isOverAge","kind":"symbol","type":"topic","navigatorTitle":[{"text":"isOverAge","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isOverAge","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/ageovernnentry\/isoverage","role":"symbol"},"doc://com.xinfotech.mdlreader/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"XTAgeOverNnEntry","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry\/age","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry\/isOverAge"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/AgeOverNnEntry\/init(age:isOverAge:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTAgeOverNnEntry"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"XTAgeOverNnEntry","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/title"},{"value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/fragments"},{"value":[{"kind":"identifier","text":"XTAgeOverNnEntry"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry\/navigatorTitle"},{"value":"initWithAge:isOverAge:","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry~1init(age:isOverAge:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAge:isOverAge:"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry~1init(age:isOverAge:)\/fragments"},{"value":"age","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry~1age\/title"},{"value":[{"kind":"identifier","text":"age"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry~1age\/fragments"},{"value":"isOverAge","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry~1isOverAge\/title"},{"value":[{"kind":"identifier","text":"isOverAge"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1AgeOverNnEntry~1isOverAge\/fragments"}]}]}