{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(XTMdlBiometricTemplate) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlBiometricTemplate"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk"]]},"kind":"symbol","sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate\/init(templateName:content:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate\/content","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate\/templateName"],"generated":true,"anchor":"Instance-Properties"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"MdlBiometricTemplate","navigatorTitle":[{"kind":"identifier","text":"MdlBiometricTemplate"}],"modules":[{"name":"MdlReaderSdk"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlBiometricTemplate"}],"platforms":[{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlBiometricTemplate","roleHeading":"Class"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH"],"kind":"relationships","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdlbiometrictemplate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdlbiometrictemplate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.xinfotech.mdlreader/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP"},"doc://com.xinfotech.mdlreader/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP"},"doc://com.xinfotech.mdlreader/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlBiometricTemplate":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate","title":"MdlBiometricTemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MdlBiometricTemplate"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlBiometricTemplate"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/mdlbiometrictemplate","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlBiometricTemplate/init(templateName:content:)":{"navigatorTitle":[{"text":"initWithTemplateName:content:","kind":"identifier"}],"kind":"symbol","title":"init(templateName:content:)","url":"\/documentation\/mdlreadersdk\/mdlbiometrictemplate\/init(templatename:content:)","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate\/init(templateName:content:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"templateName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}]},"doc://com.xinfotech.mdlreader/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ"},"doc://com.xinfotech.mdlreader/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SH"},"doc://com.xinfotech.mdlreader/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlBiometricTemplate/templateName":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate\/templateName","title":"templateName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"templateName"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"text":"Template name. It replaces ‘xx’ in ‘biometric_template_xx’.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdlbiometrictemplate\/templatename","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlBiometricTemplate/content":{"kind":"symbol","title":"content","navigatorTitle":[{"kind":"identifier","text":"content"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate\/content","url":"\/documentation\/mdlreadersdk\/mdlbiometrictemplate\/content"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":[{"name":"iOS","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false},{"deprecated":false,"introducedAt":"14.0","beta":false,"name":"iPadOS","unavailable":false},{"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"XTMdlBiometricTemplate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlBiometricTemplate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"XTMdlBiometricTemplate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate\/content","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate\/templateName"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlBiometricTemplate\/init(templateName:content:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlBiometricTemplate"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"XTMdlBiometricTemplate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate\/title"},{"value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate\/fragments"},{"value":[{"text":"XTMdlBiometricTemplate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate\/navigatorTitle"},{"value":"initWithTemplateName:content:","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate~1init(templateName:content:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTemplateName:content:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate~1init(templateName:content:)\/fragments"},{"value":"templateName","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate~1templateName\/title"},{"value":[{"text":"templateName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate~1templateName\/fragments"},{"value":"content","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate~1content\/title"},{"value":[{"text":"content","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlBiometricTemplate~1content\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}