{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTMdlDrivingPrivilegeCode) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk"]]},"sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode\/init(code:sign:value:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode\/code","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode\/sign","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode\/value"],"anchor":"Instance-Properties","title":"Instance Properties"}],"metadata":{"title":"MdlDrivingPrivilegeCode","navigatorTitle":[{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"modules":[{"name":"MdlReaderSdk"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"platforms":[{"name":"iOS","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilegeCode","roleHeading":"Class"},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdldrivingprivilegecode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/mdldrivingprivilegecode"]}],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCode/value":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode\/value","title":"value","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"value"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"abstract":[{"text":"Value as per ISO\/IEC 18013-2 Annex A","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecode\/value","role":"symbol"},"doc://com.xinfotech.mdlreader/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.xinfotech.mdlreader/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.xinfotech.mdlreader/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ","title":"Swift.Equatable"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCode/sign":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode\/sign","kind":"symbol","type":"topic","title":"sign","navigatorTitle":[{"kind":"identifier","text":"sign"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sign","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Sign as per ISO\/IEC 18013-2 Annex A"}],"url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecode\/sign","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCode/code":{"kind":"symbol","title":"code","navigatorTitle":[{"text":"code","kind":"identifier"}],"abstract":[{"text":"Code as per ISO\/IEC 18013-2 Annex A.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode\/code","url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecode\/code"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCode/init(code:sign:value:)":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode\/init(code:sign:value:)","title":"init(code:sign:value:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"initWithCode:sign:value:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"code"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sign"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecode\/init(code:sign:value:)","role":"symbol"},"doc://com.xinfotech.mdlreader/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SH"},"doc://com.xinfotech.mdlreader/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCode":{"kind":"symbol","title":"MdlDrivingPrivilegeCode","navigatorTitle":[{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode","url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecode"},"doc://com.xinfotech.mdlreader/objc(cs)NSObject":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.xinfotech.mdlreader/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"XTMdlDrivingPrivilegeCode","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"XTMdlDrivingPrivilegeCode","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode\/code","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode\/sign","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode\/value"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCode\/init(code:sign:value:)"],"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"value":"value","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode~1value\/title"},{"value":[{"kind":"identifier","text":"value"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode~1value\/fragments"},{"value":"sign","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode~1sign\/title"},{"value":[{"kind":"identifier","text":"sign"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode~1sign\/fragments"},{"value":"code","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode~1code\/title"},{"value":[{"kind":"identifier","text":"code"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode~1code\/fragments"},{"value":"initWithCode:sign:value:","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode~1init(code:sign:value:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCode:sign:value:"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode~1init(code:sign:value:)\/fragments"},{"value":"XTMdlDrivingPrivilegeCode","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode\/title"},{"value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode\/fragments"},{"value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCode"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}