{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdldrivingprivilegecodes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/mdldrivingprivilegecodes"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH"],"kind":"relationships","type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(XTMdlDrivingPrivilegeCodes) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivilegeCodes"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes\/init(codes:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes\/codes"],"generated":true,"anchor":"Instance-Properties"}],"metadata":{"platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false}],"modules":[{"name":"MdlReaderSdk"}],"title":"MdlDrivingPrivilegeCodes","navigatorTitle":[{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilegeCodes","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDrivingPrivilegeCodes","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class"},"references":{"doc://com.xinfotech.mdlreader/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCodes/codes":{"kind":"symbol","title":"codes","navigatorTitle":[{"text":"codes","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MdlDrivingPrivilegeCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilegeCode"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes\/codes","url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecodes\/codes"},"doc://com.xinfotech.mdlreader/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","type":"unresolvable"},"doc://com.xinfotech.mdlreader/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCodes":{"kind":"symbol","title":"MdlDrivingPrivilegeCodes","navigatorTitle":[{"kind":"identifier","text":"MdlDrivingPrivilegeCodes"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDrivingPrivilegeCodes"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes","url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecodes"},"doc://com.xinfotech.mdlreader/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SH","type":"unresolvable"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDrivingPrivilegeCodes/init(codes:)":{"kind":"symbol","title":"init(codes:)","navigatorTitle":[{"kind":"identifier","text":"initWithCodes:"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivilegeCode","text":"MdlDrivingPrivilegeCode"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes\/init(codes:)","url":"\/documentation\/mdlreadersdk\/mdldrivingprivilegecodes\/init(codes:)"},"doc://com.xinfotech.mdlreader/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.xinfotech.mdlreader/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"XTMdlDrivingPrivilegeCodes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes\/codes"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDrivingPrivilegeCodes\/init(codes:)"],"generated":true,"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes~1codes\/title","value":"codes"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes~1codes\/fragments","value":[{"kind":"identifier","text":"codes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes\/title","value":"XTMdlDrivingPrivilegeCodes"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes\/fragments","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDrivingPrivilegeCodes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes~1init(codes:)\/title","value":"initWithCodes:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDrivingPrivilegeCodes~1init(codes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCodes:"}]}]}]}