{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(XTMdlDocument) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlDocument","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdldocument"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/mdldocument"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP","doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP","doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"abstract":[{"text":"Representation of mDL document","type":"text"}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"MdlDocument","kind":"identifier"}],"platforms":[{"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"beta":false},{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst"}],"modules":[{"name":"MdlReaderSdk"}],"symbolKind":"class","title":"MdlDocument","roleHeading":"Class","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlDocument","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlDocument"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/administrativeNumber","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/ageBirthYear","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/ageInYears","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/ageOverNn","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/biometricTemplateXx","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/birthDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/birthPlace","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/bloodGroup","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/dlExpiryDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/dlIssueDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/documentNumber","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/drivingPrivileges","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/drivingRestrictions","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/expiryDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/eyeColour","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/familyName","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/familyNameNationalCharacter","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/givenName","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/givenNameNationalCharacter","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/hairColour","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/height","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/holderIdNumber","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issueDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issuingAuthority","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issuingCountry","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issuingJurisdiction","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/nationality","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/portrait","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/portraitCaptureDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentAddress","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentCity","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentCountry","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentPostalCode","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentState","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/sex","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/signatureUsualMark","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/unDistinguishingSign","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/weight"]}],"kind":"symbol","references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/familyName":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"familyName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"familyName","kind":"identifier"}],"abstract":[{"type":"text","text":"Last name, surname or primary identifier, of the mDL holder."}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/familyname","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/familyName","title":"familyName","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject","title":"NSObject"},"doc://com.xinfotech.mdlreader/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/birthDate":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"birthDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"birthDate"}],"abstract":[{"text":"Day, month and year on which the mDL holder was born. If unknown, approximate date of birth.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/birthdate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/birthDate","title":"birthDate","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s7CVarArgP"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/height":{"abstract":[{"text":"mDL holder’s height in centimeters.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"height"}],"title":"height","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/mdldocument\/height","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/height"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/residentState":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentState","abstract":[{"text":"The state\/province\/district where the mDL holder lives.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"residentState","kind":"identifier"}],"title":"residentState","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentState","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/mdldocument\/residentstate","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/holderIdNumber":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"holderIdNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"holderIdNumber","kind":"identifier"}],"abstract":[{"text":"mDL holder’s national ID or alien ID, or diplomatic ID","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/holderidnumber","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/holderIdNumber","title":"holderIdNumber","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/residentCountry":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentCountry"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"residentCountry","kind":"identifier"}],"abstract":[{"text":"The country where the mDL holder lives as the two letter country code.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/residentcountry","title":"residentCountry","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentCountry","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/documentNumber":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"text":"documentNumber","kind":"identifier"}],"abstract":[{"type":"text","text":"The number assigned or calculated by the issuing authority."}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/documentnumber","title":"documentNumber","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/documentNumber","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ","title":"Swift.Equatable"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/birthPlace":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthPlace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"birthPlace","kind":"identifier"}],"abstract":[{"type":"text","text":"Country and municipality or state\/province where the mDL holder was born."}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/birthplace","title":"birthPlace","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/birthPlace","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/drivingRestrictions":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drivingRestrictions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"drivingRestrictions","kind":"identifier"}],"abstract":[{"text":"Driver’s restrictions","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/drivingrestrictions","title":"drivingRestrictions","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/drivingRestrictions","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/ageInYears":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ageInYears","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ageInYears"}],"abstract":[{"text":"The age of the mDL holder.  Age attestation: How old are you (in years)?","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/ageinyears","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/ageInYears","title":"ageInYears","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/givenNameNationalCharacter":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"givenNameNationalCharacter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"givenNameNationalCharacter","kind":"identifier"}],"abstract":[{"text":"The given name of the mDL holder using full UTF-8 character set.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/givennamenationalcharacter","title":"givenNameNationalCharacter","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/givenNameNationalCharacter","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/dlIssueDate":{"abstract":[{"type":"text","text":"Date of issue of eDL (physical document) issued to mDL holder"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"dlIssueDate","kind":"identifier"}],"title":"dlIssueDate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dlIssueDate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/mdldocument\/dlissuedate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/dlIssueDate"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/signatureUsualMark":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"signatureUsualMark","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"signatureUsualMark","kind":"identifier"}],"abstract":[{"text":"Image of the signature or usual mark of the mDL holder.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/signatureusualmark","title":"signatureUsualMark","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/signatureUsualMark","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.xinfotech.mdlreader\/s23CustomStringConvertibleP"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/nationality":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nationality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"nationality","kind":"identifier"}],"abstract":[{"text":"Nationality of the mDL holder as two letter country code.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/nationality","title":"nationality","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/nationality","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/givenName":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"givenName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"givenName","kind":"identifier"}],"abstract":[{"text":"First name(s), other name(s), or secondary identifier, of the mDL holder.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/givenname","title":"givenName","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/givenName","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/residentAddress":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"residentAddress","kind":"identifier"}],"abstract":[{"type":"text","text":"Permanent place of residence. The place where the mDL holder resides and\/or may be contacted (street\/house number, municipality etc.)."}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/residentaddress","title":"residentAddress","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentAddress","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/eyeColour":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeColour","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"eyeColour","kind":"identifier"}],"abstract":[{"type":"text","text":"mDL holder’s eye colour. The value shall be one of the following: “black”, “blue”, “brown”, “dichromatic”, “grey”, “green”, “hazel”, “maroon”, “pink”, “unknown”."}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/eyecolour","title":"eyeColour","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/eyeColour","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/sex":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MdlGender","preciseIdentifier":"c:@M@MdlReaderSdk@E@XTMdlGender","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"sex","kind":"identifier"}],"abstract":[{"type":"text","text":"mDL holder’s sex."}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/sex","title":"sex","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/sex","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/hairColour":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hairColour","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"hairColour","kind":"identifier"}],"abstract":[{"type":"text","text":"mDL holder’s hair colour. One of these values: “bald”, “black”, “blond”, “brown”, “grey”, “red”, “auburn”, “sandy”, “white”, “unknown”."}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/haircolour","title":"hairColour","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/hairColour","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/ageBirthYear":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ageBirthYear","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"ageBirthYear","kind":"identifier"}],"abstract":[{"type":"text","text":"The year when the mDL holder was born.  Age attestation: In what year where you born?"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/agebirthyear","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/ageBirthYear","title":"ageBirthYear","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/issuingJurisdiction":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"issuingJurisdiction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"issuingJurisdiction","kind":"identifier"}],"abstract":[{"text":"Country subdivision code of the jurisdiction that issued the mDL. The first part of the code shall be the same as the value for issuing country.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/issuingjurisdiction","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issuingJurisdiction","title":"issuingJurisdiction","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/mdldocument","navigatorTitle":[{"kind":"identifier","text":"MdlDocument"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocument"}],"abstract":[{"text":"Representation of mDL document","type":"text"}],"title":"MdlDocument"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/weight":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/weight","abstract":[{"text":"mDL holder’s weigth in kilograms.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"weight"}],"title":"weight","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"weight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/mdldocument\/weight","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"familyName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"givenName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"birthDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issueDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issuingCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issuingAuthority","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"portrait","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"drivingPrivileges","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MdlDrivingPrivileges","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivileges"},{"kind":"text","text":", "},{"kind":"externalParam","text":"unDistinguishingSign"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"holderIdNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"bloodGroup","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dlIssueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":", ","kind":"text"},{"text":"dlExpiryDate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drivingRestrictions"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"administrativeNumber"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"text":"MdlGender","preciseIdentifier":"c:@M@MdlReaderSdk@E@XTMdlGender","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"height"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eyeColour"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"hairColour","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"birthPlace","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"residentAddress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"portraitCaptureDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"ageInYears","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"ageBirthYear","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"ageOverNn","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AgeOverNnEntry","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTAgeOverNnEntry","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"issuingJurisdiction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"nationality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"residentCity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"residentState"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"residentPostalCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"residentCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"biometricTemplateXx","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlBiometricTemplate","text":"MdlBiometricTemplate","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"familyNameNationalCharacter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"givenNameNationalCharacter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"signatureUsualMark","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mdlreadersdk\/mdldocument\/init(familyname:givenname:birthdate:issuedate:expirydate:issuingcountry:issuingauthority:documentnumber:portrait:drivingprivileges:undistinguishingsign:holderidnumber:bloodgroup:dlissuedate:dlexpirydate:drivingrestrictions:administrativenum-1g6bl","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","title":"init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/SH":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.xinfotech.mdlreader/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/s28CustomDebugStringConvertibleP"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/expiryDate":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/expiryDate","abstract":[{"text":"Date when mDL expires.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"expiryDate","kind":"identifier"}],"title":"expiryDate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiryDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/mdldocument\/expirydate","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/residentPostalCode":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentPostalCode","abstract":[{"text":"The postal code of the mDL holder.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"residentPostalCode"}],"title":"residentPostalCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentPostalCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/mdldocument\/residentpostalcode","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/biometricTemplateXx":{"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/biometricTemplateXx","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"biometricTemplateXx"}],"title":"biometricTemplateXx","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricTemplateXx"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlBiometricTemplate","text":"MdlBiometricTemplate"},{"kind":"text","text":"]?"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/mdldocument\/biometrictemplatexx","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/portraitCaptureDate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portraitCaptureDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"portraitCaptureDate","kind":"identifier"}],"abstract":[{"text":"Date when portrait was taken.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/portraitcapturedate","title":"portraitCaptureDate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/portraitCaptureDate","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/issuingCountry":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingCountry","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"issuingCountry","kind":"identifier"}],"abstract":[{"type":"text","text":"Alpha-2 country code of the issuing authority’s country or territory."}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/issuingcountry","title":"issuingCountry","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issuingCountry","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/dlExpiryDate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dlExpiryDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"dlExpiryDate","kind":"identifier"}],"abstract":[{"text":"Date of expiry of eDL (physical document) issued to mDL holder","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/dlexpirydate","title":"dlExpiryDate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/dlExpiryDate","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/ageOverNn":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageOverNn"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTAgeOverNnEntry","text":"AgeOverNnEntry"},{"kind":"text","text":"]?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ageOverNn"}],"abstract":[{"text":"Age attestation: Nearest “true” attestation above request.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/ageovernn","title":"ageOverNn","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/ageOverNn","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/administrativeNumber":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"administrativeNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"administrativeNumber"}],"abstract":[{"text":"An audit control number assignet by the issuing authority.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/administrativenumber","title":"administrativeNumber","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/administrativeNumber","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/unDistinguishingSign":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unDistinguishingSign","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"unDistinguishingSign","kind":"identifier"}],"abstract":[{"type":"text","text":"UN Distinguishing sign."}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/undistinguishingsign","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/unDistinguishingSign","title":"unDistinguishingSign","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/bloodGroup":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bloodGroup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bloodGroup"}],"abstract":[{"type":"text","text":"mDL holder’s blood group"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/bloodgroup","title":"bloodGroup","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/bloodGroup","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/portrait":{"abstract":[{"text":"A reproduction of the mDL holder’s portrait.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"portrait","kind":"identifier"}],"title":"portrait","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portrait","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/mdldocument\/portrait","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/portrait"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/issuingAuthority":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingAuthority","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"issuingAuthority","kind":"identifier"}],"abstract":[{"text":"Issuing authority name.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/issuingauthority","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issuingAuthority","title":"issuingAuthority","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/issueDate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issueDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"issueDate","kind":"identifier"}],"abstract":[{"text":"Date when mDL was issued.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/issuedate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issueDate","title":"issueDate","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/residentCity":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residentCity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"residentCity","kind":"identifier"}],"abstract":[{"text":"The city where the mDL holder lives.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/residentcity","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentCity","title":"residentCity","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/drivingPrivileges":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"drivingPrivileges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlDrivingPrivileges","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlDrivingPrivileges"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"drivingPrivileges"}],"abstract":[{"type":"text","text":"Driving privileges of the mDL holder. Categories of vehicles\/restrictions\/conditions. (zero or more)"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/drivingprivileges","title":"drivingPrivileges","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/drivingPrivileges","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocument/familyNameNationalCharacter":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"familyNameNationalCharacter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"familyNameNationalCharacter","kind":"identifier"}],"abstract":[{"text":"The family name of the mDL holder using full UTF-8 character set.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdldocument\/familynamenationalcharacter","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/familyNameNationalCharacter","title":"familyNameNationalCharacter","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst"}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"XTMdlDocument","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlDocument"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/administrativeNumber","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/ageBirthYear","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/ageInYears","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/ageOverNn","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/biometricTemplateXx","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/birthDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/birthPlace","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/bloodGroup","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/dlExpiryDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/dlIssueDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/documentNumber","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/drivingPrivileges","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/drivingRestrictions","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/expiryDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/eyeColour","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/familyName","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/familyNameNationalCharacter","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/givenName","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/givenNameNationalCharacter","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/hairColour","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/height","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/holderIdNumber","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issueDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issuingAuthority","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issuingCountry","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/issuingJurisdiction","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/nationality","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/portrait","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/portraitCaptureDate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentAddress","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentCity","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentCountry","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentPostalCode","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/residentState","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/sex","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/signatureUsualMark","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/unDistinguishingSign","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/weight"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocument\/init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.xinfotech.mdlreader\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTMdlDocument"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"familyName","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1familyName\/title","op":"replace"},{"value":[{"text":"familyName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1familyName\/fragments","op":"replace"},{"value":"birthDate","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1birthDate\/title","op":"replace"},{"value":[{"text":"birthDate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1birthDate\/fragments","op":"replace"},{"value":"height","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1height\/title","op":"replace"},{"value":[{"text":"height","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1height\/fragments","op":"replace"},{"value":"residentState","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1residentState\/title","op":"replace"},{"value":[{"kind":"identifier","text":"residentState"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1residentState\/fragments","op":"replace"},{"value":"holderIdNumber","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1holderIdNumber\/title","op":"replace"},{"value":[{"text":"holderIdNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1holderIdNumber\/fragments","op":"replace"},{"value":"residentCountry","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1residentCountry\/title","op":"replace"},{"value":[{"text":"residentCountry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1residentCountry\/fragments","op":"replace"},{"value":"documentNumber","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1documentNumber\/title","op":"replace"},{"value":[{"text":"documentNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1documentNumber\/fragments","op":"replace"},{"value":"birthPlace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1birthPlace\/title","op":"replace"},{"value":[{"text":"birthPlace","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1birthPlace\/fragments","op":"replace"},{"value":"drivingRestrictions","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1drivingRestrictions\/title","op":"replace"},{"value":[{"text":"drivingRestrictions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1drivingRestrictions\/fragments","op":"replace"},{"value":"ageInYears","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1ageInYears\/title","op":"replace"},{"value":[{"text":"ageInYears","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1ageInYears\/fragments","op":"replace"},{"value":"givenNameNationalCharacter","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1givenNameNationalCharacter\/title","op":"replace"},{"value":[{"text":"givenNameNationalCharacter","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1givenNameNationalCharacter\/fragments","op":"replace"},{"value":"dlIssueDate","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1dlIssueDate\/title","op":"replace"},{"value":[{"text":"dlIssueDate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1dlIssueDate\/fragments","op":"replace"},{"value":"signatureUsualMark","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1signatureUsualMark\/title","op":"replace"},{"value":[{"kind":"identifier","text":"signatureUsualMark"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1signatureUsualMark\/fragments","op":"replace"},{"value":"nationality","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1nationality\/title","op":"replace"},{"value":[{"kind":"identifier","text":"nationality"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1nationality\/fragments","op":"replace"},{"value":"givenName","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1givenName\/title","op":"replace"},{"value":[{"kind":"identifier","text":"givenName"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1givenName\/fragments"},{"value":"residentAddress","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1residentAddress\/title"},{"value":[{"kind":"identifier","text":"residentAddress"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1residentAddress\/fragments"},{"value":"eyeColour","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1eyeColour\/title"},{"value":[{"kind":"identifier","text":"eyeColour"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1eyeColour\/fragments"},{"value":"sex","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1sex\/title"},{"value":[{"kind":"identifier","text":"sex"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1sex\/fragments"},{"value":"hairColour","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1hairColour\/title"},{"value":[{"kind":"identifier","text":"hairColour"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1hairColour\/fragments"},{"value":"ageBirthYear","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1ageBirthYear\/title"},{"value":[{"kind":"identifier","text":"ageBirthYear"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1ageBirthYear\/fragments"},{"value":"issuingJurisdiction","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1issuingJurisdiction\/title"},{"value":[{"kind":"identifier","text":"issuingJurisdiction"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1issuingJurisdiction\/fragments"},{"value":"XTMdlDocument","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/title"},{"value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/fragments"},{"value":[{"kind":"identifier","text":"XTMdlDocument"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument\/navigatorTitle"},{"value":"weight","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1weight\/title"},{"value":[{"kind":"identifier","text":"weight"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1weight\/fragments"},{"value":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFamilyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1init(familyName:givenName:birthDate:issueDate:expiryDate:issuingCountry:issuingAuthority:documentNumber:portrait:drivingPrivileges:unDistinguishingSign:holderIdNumber:bloodGroup:dlIssueDate:dlExpiryDate:drivingRestrictions:administrativeNumber:sex:height:weight:eyeColour:hairColour:birthPlace:residentAddress:portraitCaptureDate:ageInYears:ageBirthYear:ageOverNn:issuingJurisdiction:nationality:residentCity:residentState:residentPostalCode:residentCountry:biometricTemplateXx:familyNameNationalCharacter:givenNameNationalCharacter:signatureUsualMark:)\/fragments"},{"value":"expiryDate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1expiryDate\/title"},{"value":[{"text":"expiryDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1expiryDate\/fragments"},{"value":"residentPostalCode","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1residentPostalCode\/title"},{"value":[{"text":"residentPostalCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1residentPostalCode\/fragments"},{"value":"biometricTemplateXx","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1biometricTemplateXx\/title"},{"value":[{"text":"biometricTemplateXx","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1biometricTemplateXx\/fragments"},{"value":"portraitCaptureDate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1portraitCaptureDate\/title"},{"value":[{"text":"portraitCaptureDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1portraitCaptureDate\/fragments"},{"value":"issuingCountry","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1issuingCountry\/title"},{"value":[{"text":"issuingCountry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1issuingCountry\/fragments"},{"value":"dlExpiryDate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1dlExpiryDate\/title"},{"value":[{"text":"dlExpiryDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1dlExpiryDate\/fragments"},{"value":"ageOverNn","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1ageOverNn\/title"},{"value":[{"text":"ageOverNn","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1ageOverNn\/fragments"},{"value":"administrativeNumber","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1administrativeNumber\/title"},{"value":[{"text":"administrativeNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1administrativeNumber\/fragments"},{"value":"unDistinguishingSign","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1unDistinguishingSign\/title"},{"value":[{"kind":"identifier","text":"unDistinguishingSign"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1unDistinguishingSign\/fragments"},{"value":"bloodGroup","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1bloodGroup\/title","op":"replace"},{"value":[{"kind":"identifier","text":"bloodGroup"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1bloodGroup\/fragments","op":"replace"},{"value":"portrait","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1portrait\/title"},{"value":[{"kind":"identifier","text":"portrait"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1portrait\/fragments","op":"replace"},{"value":"issuingAuthority","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1issuingAuthority\/title","op":"replace"},{"value":[{"kind":"identifier","text":"issuingAuthority"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1issuingAuthority\/fragments","op":"replace"},{"value":"issueDate","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1issueDate\/title","op":"replace"},{"value":[{"text":"issueDate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1issueDate\/fragments","op":"replace"},{"value":"residentCity","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1residentCity\/title","op":"replace"},{"value":[{"kind":"identifier","text":"residentCity"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1residentCity\/fragments"},{"value":"drivingPrivileges","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1drivingPrivileges\/title","op":"replace"},{"value":[{"kind":"identifier","text":"drivingPrivileges"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1drivingPrivileges\/fragments"},{"value":"familyNameNationalCharacter","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1familyNameNationalCharacter\/title"},{"value":[{"kind":"identifier","text":"familyNameNationalCharacter"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocument~1familyNameNationalCharacter\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}