{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(XTMdlGender) ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MdlGender","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/female","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/male","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/notApplicable","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/notKnown"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/Equatable-Implementations","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/RawRepresentable-Implementations"]}],"metadata":{"roleHeading":"Enumeration","externalID":"c:@M@MdlReaderSdk@E@XTMdlGender","modules":[{"name":"MdlReaderSdk"}],"platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"14.0","beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"14.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"14.0"}],"navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"title":"MdlGender","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MdlGender","kind":"identifier"}],"symbolKind":"enum","role":"symbol"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH","doc:\/\/com.xinfotech.mdlreader\/SY"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdlgender"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdlgender"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk"]]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender","interfaceLanguage":"swift"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlGender/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/mdlreadersdk\/mdlgender\/rawrepresentable-implementations","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlGender/init(rawValue:)":{"url":"\/documentation\/mdlreadersdk\/mdlgender\/init(rawvalue:)","title":"init(rawValue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/init(rawValue:)","kind":"symbol","abstract":[]},"doc://com.xinfotech.mdlreader/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ","title":"Swift.Equatable"},"doc://com.xinfotech.mdlreader/SY":{"type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SY","title":"Swift.RawRepresentable"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlGender/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","kind":"article","url":"\/documentation\/mdlreadersdk\/mdlgender\/equatable-implementations","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlGender/notKnown":{"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/notKnown","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTMdlGenderNotKnown"}],"title":"MdlGender.notKnown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notKnown"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/mdlgender\/notknown","type":"topic"},"doc://com.xinfotech.mdlreader/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SH"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlGender/female":{"abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/female","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTMdlGenderFemale"}],"title":"MdlGender.female","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"female"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/mdlgender\/female","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlGender":{"navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"url":"\/documentation\/mdlreadersdk\/mdlgender","title":"MdlGender","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlGender","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender","kind":"symbol","abstract":[]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlGender/notApplicable":{"type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"XTMdlGenderNotApplicable"}],"title":"MdlGender.notApplicable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notApplicable"}],"kind":"symbol","url":"\/documentation\/mdlreadersdk\/mdlgender\/notapplicable","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/notApplicable"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlGender/male":{"navigatorTitle":[{"text":"XTMdlGenderMale","kind":"identifier"}],"url":"\/documentation\/mdlreadersdk\/mdlgender\/male","title":"MdlGender.male","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"male"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/male","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"XTMdlGender","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlGender"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlGender"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/female","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/male","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/notApplicable","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlGender\/notKnown"],"generated":true,"anchor":"Enumeration-Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XTMdlGender","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"XTMdlGenderNotKnown","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender~1notKnown\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlGenderNotKnown"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender~1notKnown\/fragments","op":"replace"},{"value":"XTMdlGenderFemale","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender~1female\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlGenderFemale"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender~1female\/fragments","op":"replace"},{"value":"XTMdlGender","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlGender"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlGender"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender\/navigatorTitle","op":"replace"},{"value":"XTMdlGenderNotApplicable","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender~1notApplicable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlGenderNotApplicable"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender~1notApplicable\/fragments","op":"replace"},{"value":"XTMdlGenderMale","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender~1male\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlGenderMale"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlGender~1male\/fragments","op":"replace"}]}]}