{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/readererrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/readererrorcode"]}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.xinfotech.mdlreader\/SQ","doc:\/\/com.xinfotech.mdlreader\/SH","doc:\/\/com.xinfotech.mdlreader\/SY"],"title":"Conforms To"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Possible error codes in SDK","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(XTReaderErrorCode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReaderErrorCode"}]}]}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleDenied","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleRestricted","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleUnauthorized","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleUnsupported","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/clientCertificateNotFound","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/cryptographicError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/initializationError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/internalError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/issuerDocumentResponseFailed","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocReaderExpired","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocReaderRevoked","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocRequestError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocValidationError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/networkError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/notInitialized","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/notPersonalized","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/onlineDocumentResponseError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/pinIsEmpty","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/pinIsWrong","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/sessionDataError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/success","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/unknown"],"title":"Enumeration Cases"},{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/init(rawValue:)"],"title":"Initializers"},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/Equatable-Implementations","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"seeAlsoSections":[{"anchor":"Main-Classes","generated":true,"identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocumentField"],"title":"Main Classes"}],"metadata":{"modules":[{"name":"MdlReaderSdk"}],"title":"ReaderErrorCode","navigatorTitle":[{"text":"ReaderErrorCode","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MdlReaderSdk@E@XTReaderErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReaderErrorCode"}],"symbolKind":"enum","roleHeading":"Enumeration"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode":{"navigatorTitle":[{"text":"ReaderErrorCode","kind":"identifier"}],"kind":"symbol","title":"ReaderErrorCode","url":"\/documentation\/mdlreadersdk\/readererrorcode","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode","abstract":[{"text":"Possible error codes in SDK","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderErrorCode","kind":"identifier"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlDocumentField":{"kind":"symbol","title":"MdlDocumentField","navigatorTitle":[{"kind":"identifier","text":"MdlDocumentField"}],"abstract":[{"text":"Represents an mDL document field containing an identifier and a corresponding value.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlDocumentField"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocumentField","url":"\/documentation\/mdlreadersdk\/mdldocumentfield"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/pinIsEmpty":{"kind":"symbol","title":"ReaderErrorCode.pinIsEmpty","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodePinIsEmpty"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinIsEmpty"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/pinIsEmpty","url":"\/documentation\/mdlreadersdk\/readererrorcode\/pinisempty"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/bleUnsupported":{"kind":"symbol","title":"ReaderErrorCode.bleUnsupported","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnsupported"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleUnsupported"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleUnsupported","url":"\/documentation\/mdlreadersdk\/readererrorcode\/bleunsupported"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/mDocError":{"kind":"symbol","title":"ReaderErrorCode.mDocError","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeMDocError"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocError"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocError","url":"\/documentation\/mdlreadersdk\/readererrorcode\/mdocerror"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader","title":"MdlReader","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MdlReader","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlReader"}],"abstract":[{"type":"text","text":"Main class of the SDK"}],"url":"\/documentation\/mdlreadersdk\/mdlreader","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/networkError":{"kind":"symbol","title":"ReaderErrorCode.networkError","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeNetworkError"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkError"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/networkError","url":"\/documentation\/mdlreadersdk\/readererrorcode\/networkerror"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/mDocRequestError":{"kind":"symbol","title":"ReaderErrorCode.mDocRequestError","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeMDocRequestError"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocRequestError"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocRequestError","url":"\/documentation\/mdlreadersdk\/readererrorcode\/mdocrequesterror"},"doc://com.xinfotech.mdlreader/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SY"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/RawRepresentable-Implementations":{"kind":"article","title":"RawRepresentable Implementations","abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/RawRepresentable-Implementations","url":"\/documentation\/mdlreadersdk\/readererrorcode\/rawrepresentable-implementations"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/notInitialized":{"kind":"symbol","title":"ReaderErrorCode.notInitialized","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeNotInitialized"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notInitialized"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/notInitialized","url":"\/documentation\/mdlreadersdk\/readererrorcode\/notinitialized"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/sessionDataError":{"kind":"symbol","title":"ReaderErrorCode.sessionDataError","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeSessionDataError"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDataError"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/sessionDataError","url":"\/documentation\/mdlreadersdk\/readererrorcode\/sessiondataerror"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/issuerDocumentResponseFailed":{"kind":"symbol","title":"ReaderErrorCode.issuerDocumentResponseFailed","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeIssuerDocumentResponseFailed"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuerDocumentResponseFailed"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/issuerDocumentResponseFailed","url":"\/documentation\/mdlreadersdk\/readererrorcode\/issuerdocumentresponsefailed"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/notPersonalized":{"kind":"symbol","title":"ReaderErrorCode.notPersonalized","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeNotPersonalized"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notPersonalized"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/notPersonalized","url":"\/documentation\/mdlreadersdk\/readererrorcode\/notpersonalized"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/onlineDocumentResponseError":{"kind":"symbol","title":"ReaderErrorCode.onlineDocumentResponseError","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeOnlineDocumentResponseError"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlineDocumentResponseError"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/onlineDocumentResponseError","url":"\/documentation\/mdlreadersdk\/readererrorcode\/onlinedocumentresponseerror"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/internalError":{"kind":"symbol","title":"ReaderErrorCode.internalError","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeInternalError"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/internalError","url":"\/documentation\/mdlreadersdk\/readererrorcode\/internalerror"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/initializationError":{"kind":"symbol","title":"ReaderErrorCode.initializationError","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeInitializationError"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializationError"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/initializationError","url":"\/documentation\/mdlreadersdk\/readererrorcode\/initializationerror"},"doc://com.xinfotech.mdlreader/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SQ"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/success":{"kind":"symbol","title":"ReaderErrorCode.success","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeSuccess"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/success","url":"\/documentation\/mdlreadersdk\/readererrorcode\/success"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/pinIsWrong":{"kind":"symbol","title":"ReaderErrorCode.pinIsWrong","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodePinIsWrong"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinIsWrong"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/pinIsWrong","url":"\/documentation\/mdlreadersdk\/readererrorcode\/piniswrong"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlFieldIdentifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlFieldIdentifier"}],"abstract":[{"type":"text","text":"Provides predefined field identifiers used in mDL documents."}],"url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/mDocReaderRevoked":{"kind":"symbol","title":"ReaderErrorCode.mDocReaderRevoked","navigatorTitle":[{"text":"XTReaderErrorCodeMDocReaderRevoked","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mDocReaderRevoked","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocReaderRevoked","url":"\/documentation\/mdlreadersdk\/readererrorcode\/mdocreaderrevoked"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/clientCertificateNotFound":{"kind":"symbol","title":"ReaderErrorCode.clientCertificateNotFound","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeClientCertificateNotFound"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientCertificateNotFound"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/clientCertificateNotFound","url":"\/documentation\/mdlreadersdk\/readererrorcode\/clientcertificatenotfound"},"doc://com.xinfotech.mdlreader/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.xinfotech.mdlreader\/SH"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/mDocReaderExpired":{"kind":"symbol","title":"ReaderErrorCode.mDocReaderExpired","navigatorTitle":[{"text":"XTReaderErrorCodeMDocReaderExpired","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocReaderExpired"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocReaderExpired","url":"\/documentation\/mdlreadersdk\/readererrorcode\/mdocreaderexpired"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate":{"kind":"symbol","title":"MdlReaderDelegate","navigatorTitle":[{"kind":"identifier","text":"MdlReaderDelegate"}],"abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"code":"MdlReader","type":"codeVoice"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlReaderDelegate"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/init(rawValue:)","url":"\/documentation\/mdlreadersdk\/readererrorcode\/init(rawvalue:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/mDocValidationError":{"kind":"symbol","title":"ReaderErrorCode.mDocValidationError","navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeMDocValidationError"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocValidationError"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocValidationError","url":"\/documentation\/mdlreadersdk\/readererrorcode\/mdocvalidationerror"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/bleDenied":{"kind":"symbol","title":"ReaderErrorCode.bleDenied","navigatorTitle":[{"text":"XTReaderErrorCodeBleDenied","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bleDenied","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleDenied","url":"\/documentation\/mdlreadersdk\/readererrorcode\/bledenied"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/bleUnauthorized":{"kind":"symbol","title":"ReaderErrorCode.bleUnauthorized","navigatorTitle":[{"text":"XTReaderErrorCodeBleUnauthorized","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bleUnauthorized","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleUnauthorized","url":"\/documentation\/mdlreadersdk\/readererrorcode\/bleunauthorized"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","url":"\/documentation\/mdlreadersdk\/readererrorcode\/equatable-implementations","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/Equatable-Implementations","abstract":[],"role":"collectionGroup"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/cryptographicError":{"navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeCryptographicError"}],"kind":"symbol","title":"ReaderErrorCode.cryptographicError","url":"\/documentation\/mdlreadersdk\/readererrorcode\/cryptographicerror","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/cryptographicError","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cryptographicError"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/unknown":{"navigatorTitle":[{"kind":"identifier","text":"XTReaderErrorCodeUnknown"}],"kind":"symbol","title":"ReaderErrorCode.unknown","url":"\/documentation\/mdlreadersdk\/readererrorcode\/unknown","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/unknown","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/ReaderErrorCode/bleRestricted":{"kind":"symbol","title":"ReaderErrorCode.bleRestricted","navigatorTitle":[{"text":"XTReaderErrorCodeBleRestricted","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bleRestricted"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleRestricted","url":"\/documentation\/mdlreadersdk\/readererrorcode\/blerestricted"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"XTReaderErrorCode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"kind":"identifier","text":"XTReaderErrorCode"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"XTReaderErrorCode"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleDenied","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleRestricted","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleUnauthorized","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/bleUnsupported","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/clientCertificateNotFound","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/cryptographicError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/initializationError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/internalError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/issuerDocumentResponseFailed","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocReaderExpired","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocReaderRevoked","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocRequestError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/mDocValidationError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/networkError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/notInitialized","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/notPersonalized","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/onlineDocumentResponseError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/pinIsEmpty","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/pinIsWrong","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/sessionDataError","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/success","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/ReaderErrorCode\/unknown"],"generated":true,"anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Main-Classes","title":"Main Classes","identifiers":["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlDocumentField"]}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"XTReaderErrorCode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/title","value":"XTReaderErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/fragments","value":[{"text":"XTReaderErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode\/navigatorTitle","value":[{"text":"XTReaderErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField\/title","value":"XTMdlDocumentField","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField\/fragments","value":[{"kind":"identifier","text":"XTMdlDocumentField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlDocumentField\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlDocumentField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1pinIsEmpty\/title","value":"XTReaderErrorCodePinIsEmpty","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1pinIsEmpty\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodePinIsEmpty"}],"op":"replace"},{"op":"replace","value":"XTReaderErrorCodeBleUnsupported","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1bleUnsupported\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTReaderErrorCodeBleUnsupported"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1bleUnsupported\/fragments"},{"op":"replace","value":"XTReaderErrorCodeMDocError","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1mDocError\/title"},{"op":"replace","value":[{"kind":"identifier","text":"XTReaderErrorCodeMDocError"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1mDocError\/fragments"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/title","value":"XTMdlReader","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/fragments","value":[{"kind":"identifier","text":"XTMdlReader"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlReader"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1networkError\/title","value":"XTReaderErrorCodeNetworkError","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1networkError\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeNetworkError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1mDocRequestError\/title","value":"XTReaderErrorCodeMDocRequestError","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1mDocRequestError\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeMDocRequestError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1notInitialized\/title","value":"XTReaderErrorCodeNotInitialized","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1notInitialized\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeNotInitialized"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1sessionDataError\/title","value":"XTReaderErrorCodeSessionDataError","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1sessionDataError\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeSessionDataError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1issuerDocumentResponseFailed\/title","value":"XTReaderErrorCodeIssuerDocumentResponseFailed","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1issuerDocumentResponseFailed\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeIssuerDocumentResponseFailed"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1notPersonalized\/title","value":"XTReaderErrorCodeNotPersonalized","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1notPersonalized\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeNotPersonalized"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1onlineDocumentResponseError\/title","value":"XTReaderErrorCodeOnlineDocumentResponseError","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1onlineDocumentResponseError\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeOnlineDocumentResponseError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1internalError\/title","value":"XTReaderErrorCodeInternalError","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1internalError\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeInternalError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1initializationError\/title","value":"XTReaderErrorCodeInitializationError","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1initializationError\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeInitializationError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1success\/title","value":"XTReaderErrorCodeSuccess","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1success\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeSuccess"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1pinIsWrong\/title","value":"XTReaderErrorCodePinIsWrong","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1pinIsWrong\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodePinIsWrong"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/fragments","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1mDocReaderRevoked\/title","value":"XTReaderErrorCodeMDocReaderRevoked","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1mDocReaderRevoked\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeMDocReaderRevoked"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1clientCertificateNotFound\/title","value":"XTReaderErrorCodeClientCertificateNotFound","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1clientCertificateNotFound\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeClientCertificateNotFound"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1mDocReaderExpired\/title","value":"XTReaderErrorCodeMDocReaderExpired","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1mDocReaderExpired\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeMDocReaderExpired"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/title","value":"XTMdlReaderDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/fragments","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/navigatorTitle","value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1mDocValidationError\/title","value":"XTReaderErrorCodeMDocValidationError","op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1mDocValidationError\/fragments","value":[{"text":"XTReaderErrorCodeMDocValidationError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1bleDenied\/title","value":"XTReaderErrorCodeBleDenied","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1bleDenied\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeBleDenied"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1bleUnauthorized\/title","value":"XTReaderErrorCodeBleUnauthorized"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1bleUnauthorized\/fragments","value":[{"text":"XTReaderErrorCodeBleUnauthorized","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1cryptographicError\/title","value":"XTReaderErrorCodeCryptographicError"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1cryptographicError\/fragments","value":[{"text":"XTReaderErrorCodeCryptographicError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1unknown\/title","value":"XTReaderErrorCodeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1unknown\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1bleRestricted\/title","value":"XTReaderErrorCodeBleRestricted"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1ReaderErrorCode~1bleRestricted\/fragments","value":[{"kind":"identifier","text":"XTReaderErrorCodeBleRestricted"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}