{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/approveDocumentSharing(completion:)"},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"approveDocumentSharingWithCompletion:","kind":"identifier"}],"externalID":"c:@M@MdlHolder@objc(cs)XTMdlHolder(im)approveDocumentSharingWithCompletion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"approveDocumentSharing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","title":"approveDocumentSharing(completion:)","role":"symbol","modules":[{"name":"MdlHolder"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"approveDocumentSharing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdlholder\/approvedocumentsharing(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdlholder\/approvedocumentsharing(completion:)"]}],"abstract":[{"type":"text","text":"This method sends the requested document fields to the reader."}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder"]]},"sections":[],"kind":"symbol","references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/approveDocumentSharing(completion:)":{"abstract":[{"text":"This method sends the requested document fields to the reader.","type":"text"}],"title":"approveDocumentSharing(completion:)","type":"topic","url":"\/documentation\/mdlholder\/mdlholder\/approvedocumentsharing(completion:)","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/approveDocumentSharing(completion:)","role":"symbol","navigatorTitle":[{"text":"approveDocumentSharingWithCompletion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"approveDocumentSharing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection","kind":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","navigatorTitle":[{"text":"MdlHolder","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolder"}],"title":"MdlHolder","role":"symbol","abstract":[{"type":"text","text":"Main class of the SDK"}],"type":"topic","url":"\/documentation\/mdlholder\/mdlholder","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"approveDocumentSharingWithCompletion:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"approveDocumentSharingWithCompletion:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"approveDocumentSharingWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"approveDocumentSharingWithCompletion:","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1approveDocumentSharing(completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"approveDocumentSharingWithCompletion:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1approveDocumentSharing(completion:)\/fragments","op":"replace"},{"value":"XTMdlHolder","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlHolder"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlHolder"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle","op":"replace"}]}]}