{"sections":[],"metadata":{"modules":[{"name":"MdlHolder"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"title":"initialize()","externalID":"s:9MdlHolderAAC10initializeyyYaKF","roleHeading":"Instance Method","role":"symbol"},"abstract":[{"type":"text","text":"SDK initialization, async version of method"}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/mdlholder\/mdlholder\/initialize()"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/initialize()"},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/initialize()":{"abstract":[{"text":"SDK initialization, async version of method","type":"text"}],"url":"\/documentation\/mdlholder\/mdlholder\/initialize()","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"title":"initialize()","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/initialize()","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"kind":"symbol","role":"collection","url":"\/documentation\/mdlholder","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"abstract":[{"text":"Main class of the SDK","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolder"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","title":"MdlHolder","url":"\/documentation\/mdlholder\/mdlholder","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlHolder"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title","value":"XTMdlHolder"},{"value":[{"kind":"identifier","text":"XTMdlHolder"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments"},{"value":[{"text":"XTMdlHolder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle"}]}]}