{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rejectDocumentSharing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/rejectDocumentSharing(completion:)"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder"]]},"abstract":[{"text":"This method rejects the document request.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/mdlholder\/mdlholder\/rejectdocumentsharing(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdlholder\/rejectdocumentsharing(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rejectDocumentSharing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"symbolKind":"method","roleHeading":"Instance Method","title":"rejectDocumentSharing(completion:)","modules":[{"name":"MdlHolder"}],"role":"symbol","externalID":"c:@M@MdlHolder@objc(cs)XTMdlHolder(im)rejectDocumentSharingWithCompletion:","navigatorTitle":[{"kind":"identifier","text":"rejectDocumentSharingWithCompletion:"}]},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}],"kind":"symbol","role":"collection","url":"\/documentation\/mdlholder","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/rejectDocumentSharing(completion:)":{"type":"topic","abstract":[{"type":"text","text":"This method rejects the document request."}],"navigatorTitle":[{"kind":"identifier","text":"rejectDocumentSharingWithCompletion:"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/rejectDocumentSharing(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rejectDocumentSharing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"kind":"symbol","title":"rejectDocumentSharing(completion:)","url":"\/documentation\/mdlholder\/mdlholder\/rejectdocumentsharing(completion:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"abstract":[{"text":"Main class of the SDK","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolder"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","title":"MdlHolder","url":"\/documentation\/mdlholder\/mdlholder","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlHolder"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"rejectDocumentSharingWithCompletion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rejectDocumentSharingWithCompletion:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rejectDocumentSharingWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1rejectDocumentSharing(completion:)\/title","op":"replace","value":"rejectDocumentSharingWithCompletion:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1rejectDocumentSharing(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rejectDocumentSharingWithCompletion:"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title","op":"replace","value":"XTMdlHolder"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlHolder"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlHolder"}]}]}]}