{"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/init(rawValue:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreader\/mdlgender\/init(rawvalue:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(rawValue:)","platforms":[{"beta":false,"unavailable":false,"introducedAt":"14.0","deprecated":false,"name":"iOS"},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer","externalID":"s:9MdlReader0A6GenderO8rawValueACSgSi_tcfc","modules":[{"name":"MdlReader"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender"]]},"kind":"symbol","sections":[],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlGender":{"url":"\/documentation\/mdlreader\/mdlgender","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender","role":"symbol","navigatorTitle":[{"text":"MdlGender","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MdlGender","kind":"identifier"}],"title":"MdlGender"},"doc://com.xinfotech.mdlreader/documentation/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlreader","type":"topic","kind":"symbol","title":"MdlReader","role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReader/MdlGender/init(rawValue:)":{"role":"symbol","url":"\/documentation\/mdlreader\/mdlgender\/init(rawvalue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReader\/MdlGender\/init(rawValue:)","title":"init(rawValue:)","type":"topic"}},"variantOverrides":[{"patch":[{"value":"XTMdlGender","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender\/title","op":"replace"},{"value":[{"text":"XTMdlGender","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender\/fragments","op":"replace"},{"value":[{"text":"XTMdlGender","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReader~1MdlGender\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}