{"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdlreader\/personalizewith(token:pin:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/mdlreader\/personalizewith(token:pin:completion:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"This method personalizes the Reader App, downloads the necessary certificates and saves them in the secure SDK storage","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(personalizeWithToken:pin:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"personalizeWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"token","content":[{"type":"paragraph","inlineContent":[{"text":"Personalization token.","type":"text"}]}]},{"name":"pin","content":[{"type":"paragraph","inlineContent":[{"text":"Authorization PIN code.","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"The block to execute asynchronously after personalization has been completed or an error has occurred.  The block has no return value and has the following parameters:","type":"text"}]},{"type":"termList","items":[{"term":{"inlineContent":[{"type":"text","text":"error"}]},"definition":{"content":[{"inlineContent":[{"type":"text","text":"An object containing error information or nil if no error occurs."}],"type":"paragraph"}]}}]}]}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/personalizeWith(token:pin:completion:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlReader(im)personalizeWithToken:pin:completion:","navigatorTitle":[{"kind":"identifier","text":"personalizeWithToken:pin:completion:"}],"symbolKind":"method","platforms":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false}],"title":"personalizeWith(token:pin:completion:)","modules":[{"name":"MdlReaderSdk"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"personalizeWith","kind":"identifier"},{"kind":"text","text":"("},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"roleHeading":"Instance Method"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader/personalizeWith(token:pin:completion:)":{"kind":"symbol","title":"personalizeWith(token:pin:completion:)","navigatorTitle":[{"kind":"identifier","text":"personalizeWithToken:pin:completion:"}],"abstract":[{"type":"text","text":"This method personalizes the Reader App, downloads the necessary certificates and saves them in the secure SDK storage"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"personalizeWith","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pin"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/personalizeWith(token:pin:completion:)","url":"\/documentation\/mdlreadersdk\/mdlreader\/personalizewith(token:pin:completion:)"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader","title":"MdlReader","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MdlReader","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlReader"}],"abstract":[{"type":"text","text":"Main class of the SDK"}],"url":"\/documentation\/mdlreadersdk\/mdlreader","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"14.0","unavailable":false}],"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"personalizeWithToken:pin:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"personalizeWithToken:pin:completion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"personalizeWithToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"token"},{"kind":"text","text":" "},{"kind":"identifier","text":"pin:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pin"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^)(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Personalization token.","type":"text"}]}],"name":"token"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Authorization PIN code."}]}],"name":"pin"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The block to execute asynchronously after personalization has been completed or an error has occurred.  The block has no return value and has the following parameters:"}]},{"type":"termList","items":[{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing error information or nil if no error occurs."}]}]},"term":{"inlineContent":[{"text":"error","type":"text"}]}}]}],"name":"completion"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1personalizeWith(token:pin:completion:)\/title","value":"personalizeWithToken:pin:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1personalizeWith(token:pin:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"personalizeWithToken:pin:completion:"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/title","op":"replace","value":"XTMdlReader"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/fragments","value":[{"kind":"identifier","text":"XTMdlReader"}]},{"op":"replace","value":[{"text":"XTMdlReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/navigatorTitle"}]}]}