{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdlreader\/sdkversion"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlreadersdk\/mdlreader\/sdkversion"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader"]]},"abstract":[{"type":"text","text":"Framework version"}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"sdkVersion","kind":"identifier"}],"platforms":[{"beta":false,"unavailable":false,"introducedAt":"14.0","deprecated":false,"name":"iOS"},{"beta":false,"unavailable":false,"introducedAt":"14.0","deprecated":false,"name":"iPadOS"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"14.0"}],"modules":[{"name":"MdlReaderSdk"}],"symbolKind":"property","title":"sdkVersion","roleHeading":"Type Property","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlReader(cpy)sdkVersion","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/sdkVersion","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader/sdkVersion":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"sdkVersion","kind":"identifier"}],"abstract":[{"type":"text","text":"Framework version"}],"url":"\/documentation\/mdlreadersdk\/mdlreader\/sdkversion","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/sdkVersion","title":"sdkVersion","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader":{"navigatorTitle":[{"text":"MdlReader","kind":"identifier"}],"url":"\/documentation\/mdlreadersdk\/mdlreader","title":"MdlReader","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReader","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader","kind":"symbol","abstract":[{"type":"text","text":"Main class of the SDK"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"sdkVersion"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"sdkVersion","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"sdkVersion","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1sdkVersion\/title","value":"sdkVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1sdkVersion\/fragments","value":[{"text":"sdkVersion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/title","value":"XTMdlReader"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/fragments","value":[{"text":"XTMdlReader","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/navigatorTitle","value":[{"text":"XTMdlReader","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}