{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startRequestDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fields","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","text":"MdlFieldIdentifier","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"isOnline","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"engagement","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlReaderDelegate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","preciseIdentifier":"c:@M@MdlReaderSdk@objc(pl)XTMdlReaderDelegate","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Requested document fields.","type":"text"}]}],"name":"fields"},{"name":"isOnline","content":[{"inlineContent":[{"type":"text","text":"A Boolean value indicating the communication mode. If "},{"code":"true","type":"codeVoice"},{"text":", the document will be transferred from the Issue Authority via cloud; if ","type":"text"},{"type":"codeVoice","code":"false"},{"text":", the document will be transferred from the holder via BLE.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Engagement string obtained from QR code."}],"type":"paragraph"}],"name":"engagement"},{"name":"pin","content":[{"inlineContent":[{"text":"Authorization PIN.","type":"text"}],"type":"paragraph"}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate object specified to receive SDK events.","type":"text"}]}]}]}],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/startRequestDocument(fields:isOnline:engagement:pin:delegate:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"This method initializes the document request process and sends the request to the holder.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlreadersdk\/mdlreader\/startrequestdocument(fields:isonline:engagement:pin:delegate:)"]}],"metadata":{"roleHeading":"Instance Method","externalID":"s:12MdlReaderSdk0aB0C20startRequestDocument6fields8isOnline10engagement3pin8delegateySayAA0A15FieldIdentifierCG_SbS2SAA0aB8Delegate_ptYaKF","modules":[{"name":"MdlReaderSdk"}],"platforms":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"14.0"},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"14.0"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"14.0"}],"title":"startRequestDocument(fields:isOnline:engagement:pin:delegate:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRequestDocument"},{"kind":"text","text":"("},{"text":"fields","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"MdlFieldIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier"},{"text":"], ","kind":"text"},{"text":"isOnline","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"engagement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pin"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MdlReaderDelegate","preciseIdentifier":"c:@M@MdlReaderSdk@objc(pl)XTMdlReaderDelegate"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"symbolKind":"method","role":"symbol"},"kind":"symbol","sections":[],"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader":{"navigatorTitle":[{"text":"MdlReader","kind":"identifier"}],"url":"\/documentation\/mdlreadersdk\/mdlreader","title":"MdlReader","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReader","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader","kind":"symbol","abstract":[{"type":"text","text":"Main class of the SDK"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader/startRequestDocument(fields:isOnline:engagement:pin:delegate:)":{"url":"\/documentation\/mdlreadersdk\/mdlreader\/startrequestdocument(fields:isonline:engagement:pin:delegate:)","title":"startRequestDocument(fields:isOnline:engagement:pin:delegate:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRequestDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"isOnline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"engagement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pin"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlReaderDelegate","preciseIdentifier":"c:@M@MdlReaderSdk@objc(pl)XTMdlReaderDelegate","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/startRequestDocument(fields:isOnline:engagement:pin:delegate:)","kind":"symbol","abstract":[{"text":"This method initializes the document request process and sends the request to the holder.","type":"text"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlFieldIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"abstract":[{"text":"Provides predefined field identifiers used in mDL documents.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate","abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"type":"codeVoice","code":"MdlReader"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReaderDelegate","kind":"identifier"}],"title":"MdlReaderDelegate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","navigatorTitle":[{"text":"MdlReaderDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"XTMdlReader","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/title","op":"replace"},{"value":[{"text":"XTMdlReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlReader"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/title","value":"XTMdlFieldIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/fragments","value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlFieldIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/title","value":"XTMdlReaderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/fragments","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}