{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"This method initializes the document request process and sends the request to the holder."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startRequestDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fields","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier"},{"text":"], ","kind":"text"},{"text":"isOnline","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"engagement","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlReaderDelegate","preciseIdentifier":"c:@M@MdlReaderSdk@objc(pl)XTMdlReaderDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"fields","content":[{"inlineContent":[{"text":"Requested document fields.","type":"text"}],"type":"paragraph"}]},{"name":"isOnline","content":[{"inlineContent":[{"text":"A Boolean value indicating the communication mode. If ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", the document will be transferred from the Issue Authority via cloud; if ","type":"text"},{"type":"codeVoice","code":"false"},{"text":", the document will be transferred from the holder via BLE.","type":"text"}],"type":"paragraph"}]},{"name":"engagement","content":[{"inlineContent":[{"text":"Engagement string obtained from QR code.","type":"text"}],"type":"paragraph"}]},{"name":"pin","content":[{"inlineContent":[{"text":"Authorization PIN.","type":"text"}],"type":"paragraph"}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate object specified to receive SDK events."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The block to execute asynchronously after the method completes or an error has occurred.  The block has no return value and has the following parameters:"}]},{"items":[{"term":{"inlineContent":[{"text":"error","type":"text"}]},"definition":{"content":[{"inlineContent":[{"text":"An object containing error information or nil if no error occurs. that will be executed .","type":"text"}],"type":"paragraph"}]}}],"type":"termList"}]}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"MdlReaderSdk"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"14.0"},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"14.0"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0"}],"externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlReader(im)startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:","navigatorTitle":[{"kind":"identifier","text":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:"}],"title":"startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRequestDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","text":"MdlFieldIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"isOnline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"engagement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(pl)XTMdlReaderDelegate","text":"MdlReaderDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol"},"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdlreader\/startrequestdocument(fields:isonline:engagement:pin:delegate:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdlreader\/startrequestdocument(fields:isonline:engagement:pin:delegate:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader"]]},"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)","interfaceLanguage":"swift"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader":{"navigatorTitle":[{"text":"MdlReader","kind":"identifier"}],"url":"\/documentation\/mdlreadersdk\/mdlreader","title":"MdlReader","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReader","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader","kind":"symbol","abstract":[{"type":"text","text":"Main class of the SDK"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlFieldIdentifier":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlFieldIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"MdlFieldIdentifier","kind":"identifier"}],"abstract":[{"text":"Provides predefined field identifiers used in mDL documents.","type":"text"}],"url":"\/documentation\/mdlreadersdk\/mdlfieldidentifier","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlFieldIdentifier","title":"MdlFieldIdentifier","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader/startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startRequestDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fields","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlReaderSdk@objc(cs)XTMdlFieldIdentifier","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"isOnline","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"engagement","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlReaderDelegate","preciseIdentifier":"c:@M@MdlReaderSdk@objc(pl)XTMdlReaderDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:"}],"abstract":[{"type":"text","text":"This method initializes the document request process and sends the request to the holder."}],"url":"\/documentation\/mdlreadersdk\/mdlreader\/startrequestdocument(fields:isonline:engagement:pin:delegate:completion:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)","title":"startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReaderDelegate":{"kind":"symbol","type":"topic","url":"\/documentation\/mdlreadersdk\/mdlreaderdelegate","abstract":[{"text":"Provides delegate callbacks for the ","type":"text"},{"type":"codeVoice","code":"MdlReader"},{"text":" framework during mDL document retrieval and data exchange.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReaderDelegate","kind":"identifier"}],"title":"MdlReaderDelegate","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReaderDelegate","navigatorTitle":[{"text":"MdlReaderDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"14.0"},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"14.0"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0"}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"startRequestDocumentFields:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<XTMdlFieldIdentifier *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fields","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isOnline:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isOnline","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"engagement:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"engagement","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pin:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pin","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@MdlReaderSdk@objc(pl)XTMdlReaderDelegate","text":"id<XTMdlReaderDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Requested document fields.","type":"text"}]}],"name":"fields"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A Boolean value indicating the communication mode. If ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", the document will be transferred from the Issue Authority via cloud; if ","type":"text"},{"code":"false","type":"codeVoice"},{"text":", the document will be transferred from the holder via BLE.","type":"text"}]}],"name":"isOnline"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Engagement string obtained from QR code.","type":"text"}]}],"name":"engagement"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Authorization PIN.","type":"text"}]}],"name":"pin"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate object specified to receive SDK events.","type":"text"}]}],"name":"delegate"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The block to execute asynchronously after the method completes or an error has occurred.  The block has no return value and has the following parameters:","type":"text"}]},{"type":"termList","items":[{"term":{"inlineContent":[{"text":"error","type":"text"}]},"definition":{"content":[{"inlineContent":[{"type":"text","text":"An object containing error information or nil if no error occurs. that will be executed ."}],"type":"paragraph"}]}}]}],"name":"completion"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"XTMdlReader","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/title"},{"value":[{"kind":"identifier","text":"XTMdlReader"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/fragments"},{"value":[{"kind":"identifier","text":"XTMdlReader"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/navigatorTitle"},{"value":"XTMdlFieldIdentifier","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/title"},{"value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/fragments"},{"value":[{"text":"XTMdlFieldIdentifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlFieldIdentifier\/navigatorTitle"},{"value":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRequestDocumentFields:isOnline:engagement:pin:delegate:completion:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1startRequestDocument(fields:isOnline:engagement:pin:delegate:completion:)\/fragments","op":"replace"},{"value":"XTMdlReaderDelegate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/title"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/fragments","op":"replace","value":[{"text":"XTMdlReaderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReaderDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlReaderDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}