{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader"]]},"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdlreader\/updaterootcertificates()"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Downloads CA Root certificates and updates them in the local SDK storage.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateRootCertificates","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"Also, CA root certificates are updated with each ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/initialize()"},{"text":" call.","type":"text"}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/updateRootCertificates()"},"metadata":{"modules":[{"name":"MdlReaderSdk"}],"platforms":[{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"14.0","beta":false,"name":"Mac Catalyst","unavailable":false}],"title":"updateRootCertificates()","role":"symbol","externalID":"s:12MdlReaderSdk0aB0C22updateRootCertificatesyyYaKF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRootCertificates"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"}],"symbolKind":"method","roleHeading":"Instance Method"},"references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader","title":"MdlReader","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MdlReader","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MdlReader"}],"abstract":[{"type":"text","text":"Main class of the SDK"}],"url":"\/documentation\/mdlreadersdk\/mdlreader","role":"symbol"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader/initialize()":{"kind":"symbol","title":"initialize()","abstract":[{"type":"text","text":"SDK initialization."}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/initialize()","url":"\/documentation\/mdlreadersdk\/mdlreader\/initialize()"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"kind":"symbol","title":"MdlReaderSdk","url":"\/documentation\/mdlreadersdk","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5.","type":"text"}],"role":"collection"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader/updateRootCertificates()":{"kind":"symbol","title":"updateRootCertificates()","abstract":[{"type":"text","text":"Downloads CA Root certificates and updates them in the local SDK storage."}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateRootCertificates","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/updateRootCertificates()","url":"\/documentation\/mdlreadersdk\/mdlreader\/updaterootcertificates()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/title","value":"XTMdlReader"},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/fragments","value":[{"text":"XTMdlReader","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/navigatorTitle","value":[{"text":"XTMdlReader","kind":"identifier"}]}]}]}