{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(updateRootCertificatesWithCompletion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateRootCertificates","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The block to execute asynchronously after the certificates has been received or an error has occurred. The block has no return value and has the following parameters:","type":"text"}],"type":"paragraph"},{"items":[{"definition":{"content":[{"type":"paragraph","inlineContent":[{"text":"An object containing error information or nil if no error occurs.","type":"text"}]}]},"term":{"inlineContent":[{"text":"error","type":"text"}]}}],"type":"termList"}],"name":"completion"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Also, CA root certificates are updated with each ","type":"text"},{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/initialize(completion:)","isActive":true,"type":"reference"},{"text":" call.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/mdlreadersdk\/mdlreader\/updaterootcertificates(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlreadersdk\/mdlreader\/updaterootcertificates(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader"]]},"abstract":[{"type":"text","text":"Downloads CA Root certificates and updates them in the local SDK storage"}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"updateRootCertificatesWithCompletion:","kind":"identifier"}],"modules":[{"name":"MdlReaderSdk"}],"platforms":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}],"symbolKind":"method","title":"updateRootCertificates(completion:)","roleHeading":"Instance Method","externalID":"c:@M@MdlReaderSdk@objc(cs)XTMdlReader(im)updateRootCertificatesWithCompletion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateRootCertificates","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"sections":[],"identifier":{"url":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/updateRootCertificates(completion:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader":{"navigatorTitle":[{"text":"MdlReader","kind":"identifier"}],"url":"\/documentation\/mdlreadersdk\/mdlreader","title":"MdlReader","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlReader","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader","kind":"symbol","abstract":[{"type":"text","text":"Main class of the SDK"}]},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk":{"identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk","abstract":[{"type":"text","text":"The framework for acting as a Mobile Driving Licence (mDL) Reader compliant with ISO\/IEC 18013-5."}],"role":"collection","title":"MdlReaderSdk","kind":"symbol","url":"\/documentation\/mdlreadersdk","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader/updateRootCertificates(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateRootCertificates","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"updateRootCertificatesWithCompletion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Downloads CA Root certificates and updates them in the local SDK storage"}],"url":"\/documentation\/mdlreadersdk\/mdlreader\/updaterootcertificates(completion:)","title":"updateRootCertificates(completion:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/updateRootCertificates(completion:)","kind":"symbol","type":"topic"},"doc://com.xinfotech.mdlreader/documentation/MdlReaderSdk/MdlReader/initialize(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initializeWithCompletion:","kind":"identifier"}],"abstract":[{"type":"text","text":"SDK initialization"}],"url":"\/documentation\/mdlreadersdk\/mdlreader\/initialize(completion:)","identifier":"doc:\/\/com.xinfotech.mdlreader\/documentation\/MdlReaderSdk\/MdlReader\/initialize(completion:)","title":"initialize(completion:)","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"updateRootCertificatesWithCompletion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateRootCertificatesWithCompletion:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateRootCertificatesWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"completion","content":[{"inlineContent":[{"text":"The block to execute asynchronously after the certificates has been received or an error has occurred. The block has no return value and has the following parameters:","type":"text"}],"type":"paragraph"},{"items":[{"term":{"inlineContent":[{"text":"error","type":"text"}]},"definition":{"content":[{"type":"paragraph","inlineContent":[{"text":"An object containing error information or nil if no error occurs.","type":"text"}]}]}}],"type":"termList"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/title","op":"replace","value":"XTMdlReader"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/fragments","op":"replace","value":[{"text":"XTMdlReader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader\/navigatorTitle","op":"replace","value":[{"text":"XTMdlReader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1updateRootCertificates(completion:)\/title","op":"replace","value":"updateRootCertificatesWithCompletion:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1updateRootCertificates(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateRootCertificatesWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1initialize(completion:)\/title","op":"replace","value":"initializeWithCompletion:"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlreader~1documentation~1MdlReaderSdk~1MdlReader~1initialize(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initializeWithCompletion:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}