{"abstract":[{"text":"This method sends the requested document fields to the reader.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/approveDocumentSharing()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdlholder\/approvedocumentsharing()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/mdlholder\/approvedocumentsharing()"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"approveDocumentSharing","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An object containing error information or nil if no error occurs.","type":"text"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"When a reader requests to read some fields of a document from a holder, the holder receives an event ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","isActive":true},{"text":" using the ","type":"text"},{"type":"codeVoice","code":"MdlHolderDelegate"},{"text":" protocol. The holder can then decide to allow reading of document fields using this method.","type":"text"}]},{"type":"aside","style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Errors that may occur while sending the document to the reader will be received in the delegate method: "},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveError(_:)","isActive":true,"type":"reference"}]}]}]}],"metadata":{"externalID":"c:@M@MdlHolder@objc(cs)XTMdlHolder(im)approveDocumentSharing","symbolKind":"method","navigatorTitle":[{"text":"approveDocumentSharing","kind":"identifier"}],"title":"approveDocumentSharing()","platforms":[{"introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"approveDocumentSharing","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"MdlHolder"}],"roleHeading":"Instance Method"},"sections":[],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderDidReceiveRequestedFields(_:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields:"}],"type":"topic","title":"mdlHolderDidReceiveRequestedFields(_:)","abstract":[{"type":"text","text":"Called when the Reader requests specific document fields."}],"required":true,"url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdidreceiverequestedfields(_:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","type":"topic","title":"MdlHolder","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/approveDocumentSharing()":{"abstract":[{"type":"text","text":"This method sends the requested document fields to the reader."}],"title":"approveDocumentSharing()","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/approveDocumentSharing()","type":"topic","role":"symbol","url":"\/documentation\/mdlholder\/mdlholder\/approvedocumentsharing()","navigatorTitle":[{"kind":"identifier","text":"approveDocumentSharing"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"approveDocumentSharing"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolder","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","navigatorTitle":[{"kind":"identifier","text":"MdlHolder"}],"type":"topic","title":"MdlHolder","abstract":[{"type":"text","text":"Main class of the SDK"}],"role":"symbol","url":"\/documentation\/mdlholder\/mdlholder"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderDidReceiveError(_:)":{"abstract":[{"text":"Called when an error occurs in the sharing workflow.","type":"text"}],"title":"mdlHolderDidReceiveError(_:)","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveError(_:)","type":"topic","role":"symbol","url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdidreceiveerror(_:)","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"mdlHolderDidReceiveError:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderDidReceiveError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","deprecated":false},{"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"approveDocumentSharing","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"approveDocumentSharing"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"approveDocumentSharing"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"An object containing error information or nil if no error occurs.","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"mdlHolderDidReceiveRequestedFields:","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/fragments","op":"replace"},{"value":"approveDocumentSharing","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1approveDocumentSharing()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"approveDocumentSharing"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1approveDocumentSharing()\/fragments","op":"replace"},{"value":"XTMdlHolder","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlHolder"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlHolder"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle","op":"replace"},{"value":"mdlHolderDidReceiveError:","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveError(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlHolderDidReceiveError:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveError(_:)\/fragments","op":"replace"}]}]}