{"abstract":[{"type":"text","text":"This method rejects the document request."}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/rejectDocumentSharing()"},"variants":[{"paths":["\/documentation\/mdlholder\/mdlholder\/rejectdocumentsharing()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdlholder\/rejectdocumentsharing()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rejectDocumentSharing"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"text":"An object containing error information or nil if no error occurs.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"text":"When a reader requests to read some fields of a document from a holder, the holder receives an event ","type":"text"},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","isActive":true,"type":"reference"},{"text":" using the ","type":"text"},{"code":"MdlHolderDelegate","type":"codeVoice"},{"text":" protocol. The holder can then decide to reject reading of document fields using this method.","type":"text"}],"type":"paragraph"}]}],"metadata":{"externalID":"c:@M@MdlHolder@objc(cs)XTMdlHolder(im)rejectDocumentSharing","symbolKind":"method","navigatorTitle":[{"text":"rejectDocumentSharing","kind":"identifier"}],"title":"rejectDocumentSharing()","platforms":[{"unavailable":false,"introducedAt":"14.0","name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"14.0","name":"iPadOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"beta":false}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rejectDocumentSharing","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"MdlHolder"}],"roleHeading":"Instance Method"},"sections":[],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/rejectDocumentSharing()":{"kind":"symbol","abstract":[{"type":"text","text":"This method rejects the document request."}],"url":"\/documentation\/mdlholder\/mdlholder\/rejectdocumentsharing()","title":"rejectDocumentSharing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rejectDocumentSharing"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"rejectDocumentSharing"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/rejectDocumentSharing()","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderDidReceiveRequestedFields(_:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields:"}],"type":"topic","title":"mdlHolderDidReceiveRequestedFields(_:)","abstract":[{"type":"text","text":"Called when the Reader requests specific document fields."}],"required":true,"url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdidreceiverequestedfields(_:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","type":"topic","title":"MdlHolder","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolder","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","navigatorTitle":[{"kind":"identifier","text":"MdlHolder"}],"type":"topic","title":"MdlHolder","abstract":[{"type":"text","text":"Main class of the SDK"}],"role":"symbol","url":"\/documentation\/mdlholder\/mdlholder"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"introducedAt":"14.0","name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"14.0","name":"iPadOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"beta":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"rejectDocumentSharing","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rejectDocumentSharing"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"rejectDocumentSharing"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"An object containing error information or nil if no error occurs."}],"type":"paragraph"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"rejectDocumentSharing","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1rejectDocumentSharing()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rejectDocumentSharing"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1rejectDocumentSharing()\/fragments","op":"replace"},{"value":"mdlHolderDidReceiveRequestedFields:","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/fragments","op":"replace"},{"value":"XTMdlHolder","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlHolder"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"XTMdlHolder"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}