{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdlholder\/mdlholder\/startdocumentsharing(withpin:delegate:)"]}],"metadata":{"title":"startDocumentSharing(withPin:delegate:)","externalID":"s:9MdlHolderAAC20startDocumentSharing7withPin8delegateS2S_AA0aB8Delegate_ptYaKF","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"MdlHolder"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDocumentSharing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPin","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate","text":"MdlHolderDelegate","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDocumentSharing"},{"text":"(","kind":"text"},{"text":"withPin","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pin","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","text":"MdlHolderDelegate"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]},{"parameters":[{"name":"pin","content":[{"inlineContent":[{"text":"PIN code that protects private keys","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate object specified to receive SDK events.","type":"text"}]}],"name":"delegate"}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"qrString - the string for QR code generation","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder"]]},"abstract":[{"text":"This method initializes the document sharing process","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/startDocumentSharing(withPin:delegate:)"},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/startDocumentSharing(withPin:delegate:)":{"title":"startDocumentSharing(withPin:delegate:)","role":"symbol","url":"\/documentation\/mdlholder\/mdlholder\/startdocumentsharing(withpin:delegate:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDocumentSharing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MdlHolderDelegate","preciseIdentifier":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"This method initializes the document sharing process"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/startDocumentSharing(withPin:delegate:)"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","abstract":[{"text":"Delivers events from the ","type":"text"},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","type":"reference","isActive":true},{"text":" during the mDL document sharing lifecycle.","type":"text"}],"kind":"symbol","url":"\/documentation\/mdlholder\/mdlholderdelegate","navigatorTitle":[{"text":"MdlHolderDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolderDelegate","kind":"identifier"}],"role":"symbol","title":"MdlHolderDelegate","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","abstract":[{"text":"Main class of the SDK","type":"text"}],"kind":"symbol","url":"\/documentation\/mdlholder\/mdlholder","navigatorTitle":[{"text":"MdlHolder","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolder","kind":"identifier"}],"role":"symbol","title":"MdlHolder","type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"title":"MdlHolder","kind":"symbol","abstract":[{"text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5.","type":"text"}],"url":"\/documentation\/mdlholder","type":"topic","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/title","op":"replace","value":"XTMdlHolderDelegate"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlHolderDelegate"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title","op":"replace","value":"XTMdlHolder"},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments","op":"replace","value":[{"kind":"identifier","text":"XTMdlHolder"}]},{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"XTMdlHolder"}]}]}]}