{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Starts the mDL document sharing session initiated via QR engagement.","type":"text"}],"variants":[{"paths":["\/documentation\/mdlholder\/mdlholder\/startdocumentsharing(withpin:delegate:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdlholder\/mdlholder\/startdocumentsharing(withpin:delegate:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(startDocumentSharingWithPin:delegate:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDocumentSharing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPin","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pin","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","preciseIdentifier":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate","text":"MdlHolderDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"qrString","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Authorization PIN code."}],"type":"paragraph"}],"name":"pin"},{"content":[{"inlineContent":[{"type":"text","text":"The delegate object specified to receive SDK events."}],"type":"paragraph"}],"name":"delegate"},{"content":[{"inlineContent":[{"type":"text","text":"A block of code that runs on the main thread and is called after a sharing has been successfully initialized or an error has occurred. The block has no return value and has the following parameters:"}],"type":"paragraph"},{"items":[{"term":{"inlineContent":[{"type":"text","text":"qrString"}]},"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A string for QR code generation or nil if error occurs."}]}]}},{"term":{"inlineContent":[{"type":"text","text":"error"}]},"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing error information or nil if no error occurs."}]}]}}],"type":"termList"}],"name":"completion"}]},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"After successful initialization of document sharing, subsequent events will be delivered via the "},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","isActive":true,"type":"reference"},{"type":"text","text":" delegate methods."},{"type":"text","text":" "},{"type":"text","text":"In particular, a request to view document fields will be received through the "},{"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","isActive":true,"type":"reference"},{"text":" delegate method.","type":"text"},{"text":" ","type":"text"},{"text":"This request must be either approved or rejected by calling the corresponding ","type":"text"},{"code":"approveDocumentSharing(completion:)","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"rejectDocumentSharing(completion:)","type":"codeVoice"},{"text":" methods.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"metadata":{"symbolKind":"method","title":"startDocumentSharing(withPin:delegate:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDocumentSharing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPin","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate","text":"MdlHolderDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"qrString","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"startDocumentSharingWithPin:delegate:completion:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MdlHolder@objc(cs)XTMdlHolder(im)startDocumentSharingWithPin:delegate:completion:","platforms":[{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"iOS"},{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"Mac Catalyst"}],"modules":[{"name":"MdlHolder"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/startDocumentSharing(withPin:delegate:completion:)"},"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","type":"topic","title":"MdlHolder","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolder","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","navigatorTitle":[{"kind":"identifier","text":"MdlHolder"}],"type":"topic","title":"MdlHolder","abstract":[{"type":"text","text":"Main class of the SDK"}],"role":"symbol","url":"\/documentation\/mdlholder\/mdlholder"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate":{"abstract":[{"type":"text","text":"Delivers events from the "},{"type":"codeVoice","code":"MdlHolder"},{"type":"text","text":" during the mDL document sharing lifecycle."}],"role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MdlHolderDelegate"}],"url":"\/documentation\/mdlholder\/mdlholderdelegate","title":"MdlHolderDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MdlHolderDelegate"}],"type":"topic"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder/startDocumentSharing(withPin:delegate:completion:)":{"kind":"symbol","abstract":[{"type":"text","text":"Starts the mDL document sharing session initiated via QR engagement."}],"url":"\/documentation\/mdlholder\/mdlholder\/startdocumentsharing(withpin:delegate:completion:)","title":"startDocumentSharing(withPin:delegate:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDocumentSharing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(pl)XTMdlHolderDelegate","text":"MdlHolderDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"qrString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDocumentSharingWithPin:delegate:completion:"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder\/startDocumentSharing(withPin:delegate:completion:)","role":"symbol"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolderDelegate/mdlHolderDidReceiveRequestedFields(_:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolderDelegate\/mdlHolderDidReceiveRequestedFields(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"MdlFieldIdentifier","preciseIdentifier":"c:@M@MdlHolder@objc(cs)XTMdlFieldIdentifier"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields:"}],"type":"topic","title":"mdlHolderDidReceiveRequestedFields(_:)","abstract":[{"type":"text","text":"Called when the Reader requests specific document fields."}],"required":true,"url":"\/documentation\/mdlholder\/mdlholderdelegate\/mdlholderdidreceiverequestedfields(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"unavailable":false,"introducedAt":"14.0","deprecated":false,"name":"iOS","beta":false},{"introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"startDocumentSharingWithPin:delegate:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"startDocumentSharingWithPin:delegate:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"startDocumentSharingWithPin:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"pin","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@MdlHolder@objc(pl)XTMdlHolderDelegate","text":"id<XTMdlHolderDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"pin","content":[{"inlineContent":[{"type":"text","text":"Authorization PIN code."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The delegate object specified to receive SDK events."}],"type":"paragraph"}],"name":"delegate"},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"A block of code that runs on the main thread and is called after a sharing has been successfully initialized or an error has occurred. The block has no return value and has the following parameters:"}],"type":"paragraph"},{"items":[{"term":{"inlineContent":[{"text":"qrString","type":"text"}]},"definition":{"content":[{"inlineContent":[{"text":"A string for QR code generation or nil if error occurs.","type":"text"}],"type":"paragraph"}]}},{"term":{"inlineContent":[{"text":"error","type":"text"}]},"definition":{"content":[{"inlineContent":[{"type":"text","text":"An object containing error information or nil if no error occurs."}],"type":"paragraph"}]}}],"type":"termList"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"XTMdlHolder","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title"},{"value":[{"text":"XTMdlHolder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments"},{"value":[{"text":"XTMdlHolder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle"},{"value":"XTMdlHolderDelegate","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/title"},{"value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/fragments"},{"value":[{"text":"XTMdlHolderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate\/navigatorTitle"},{"value":"startDocumentSharingWithPin:delegate:completion:","op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1startDocumentSharing(withPin:delegate:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"startDocumentSharingWithPin:delegate:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder~1startDocumentSharing(withPin:delegate:completion:)\/fragments"},{"value":"mdlHolderDidReceiveRequestedFields:","path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mdlHolderDidReceiveRequestedFields:"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolderDelegate~1mdlHolderDidReceiveRequestedFields(_:)\/fragments","op":"replace"}]}]}