{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdlholder\/xtmdlholder\/init"]}],"hierarchy":{"paths":[["doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/XTMdlHolder\/init"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@MdlHolder@objc(cs)XTMdlHolder(im)init","symbolKind":"method","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","platforms":[{"unavailable":false,"introducedAt":"14.0","name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"14.0","name":"iPadOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"beta":false}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"modules":[{"name":"MdlHolder"}],"roleHeading":"Instance Method"},"sections":[],"references":{"doc://com.xinfotech.mdlholder/documentation/MdlHolder":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder","type":"topic","title":"MdlHolder","url":"\/documentation\/mdlholder","abstract":[{"type":"text","text":"The framework for acting as a mobile Driving Licence (mDL) holder compliant with ISO\/IEC 18013-5."}]},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/MdlHolder":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MdlHolder","kind":"identifier"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/MdlHolder","navigatorTitle":[{"kind":"identifier","text":"MdlHolder"}],"type":"topic","title":"MdlHolder","abstract":[{"type":"text","text":"Main class of the SDK"}],"role":"symbol","url":"\/documentation\/mdlholder\/mdlholder"},"doc://com.xinfotech.mdlholder/documentation/MdlHolder/XTMdlHolder/init":{"kind":"symbol","abstract":[],"url":"\/documentation\/mdlholder\/xtmdlholder\/init","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.xinfotech.mdlholder\/documentation\/MdlHolder\/XTMdlHolder\/init","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/title","op":"replace","value":"XTMdlHolder"},{"value":[{"text":"XTMdlHolder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/fragments","op":"replace"},{"value":[{"text":"XTMdlHolder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.xinfotech.mdlholder~1documentation~1MdlHolder~1MdlHolder\/navigatorTitle","op":"replace"}]}]}